# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentLineage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_id", models.CharField(max_length=255, unique=True)),
                ("parent_id", models.CharField(blank=True, max_length=255, null=True)),
                ("root_id", models.CharField(max_length=255)),
                ("generation", models.IntegerField(default=0)),
                ("branch_name", models.CharField(blank=True, max_length=100)),
                ("variation_type", models.CharField(blank=True, max_length=50)),
                ("variation_params", models.JSONField(blank=True, default=dict)),
                ("total_interactions", models.IntegerField(default=0)),
                ("positive_interactions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["root_id", "generation", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_id"], name="style_memor_content_aaa11f_idx"
                    ),
                    models.Index(
                        fields=["parent_id"], name="style_memor_parent__8b1905_idx"
                    ),
                    models.Index(
                        fields=["root_id"], name="style_memor_root_id_b4161c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StyleMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_id", models.CharField(db_index=True, max_length=255)),
                (
                    "parent_content_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("love", "Love"),
                            ("like", "Like"),
                            ("dislike", "Dislike"),
                            ("save", "Save"),
                            ("share", "Share"),
                            ("download", "Download"),
                            ("remix", "Remix"),
                            ("delete", "Delete"),
                            ("rate_1", "Rate 1 Star"),
                            ("rate_2", "Rate 2 Stars"),
                            ("rate_3", "Rate 3 Stars"),
                            ("rate_4", "Rate 4 Stars"),
                            ("rate_5", "Rate 5 Stars"),
                            ("generate_similar", "Generate Similar"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipe", models.JSONField(blank=True, default=dict)),
                (
                    "style_elements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "color_palette",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=7),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("prompt", models.TextField(blank=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StylePattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern_type", models.CharField(max_length=50)),
                ("pattern_value", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.5)),
                ("frequency", models.IntegerField(default=1)),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "related_memories",
                    models.ManyToManyField(blank=True, to="style_memory.stylememory"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-frequency"],
            },
        ),
        migrations.CreateModel(
            name="StyleSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("prompt_template", models.TextField()),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("used", "Used"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_content_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "based_on_patterns",
                    models.ManyToManyField(to="style_memory.stylepattern"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="style_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="stylememory",
            index=models.Index(
                fields=["user", "-created_at"], name="style_memor_user_id_c09f70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stylememory",
            index=models.Index(
                fields=["content_id"], name="style_memor_content_122784_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stylememory",
            index=models.Index(
                fields=["interaction_type"], name="style_memor_interac_6ecb61_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stylepattern",
            unique_together={("user", "pattern_type", "pattern_value")},
        ),
    ]
