# Generated by Django 5.0.6 on 2025-11-23 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("style_memory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stylememory",
            name="project_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True),
        ),
        migrations.AddIndex(
            model_name="stylememory",
            index=models.Index(
                fields=["user", "project_id", "-created_at"],
                name="style_memor_user_id_c804cc_idx",
            ),
        ),
    ]
