# Generated by Django 5.0.6 on 2025-09-17 16:41

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique channel name (e.g., 'general', 'orchestration-123')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-friendly display name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Channel description and purpose"
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Channel"),
                            ("topic", "Topic Channel"),
                            ("team", "Team Channel"),
                            ("general", "General Channel"),
                            ("system", "System Channel"),
                            ("orchestration", "Orchestration Channel"),
                        ],
                        default="project",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether channel is visible to all users",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Whether channel is archived"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional channel metadata (orchestration_id, etc.)",
                    ),
                ),
                (
                    "active_agents",
                    models.JSONField(
                        default=list,
                        help_text="List of currently active agent IDs in this channel",
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of messages in channel"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Channel",
                "verbose_name_plural": "Agent Channels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentChannelMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                            ("observer", "Observer"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "notification_level",
                    models.CharField(
                        choices=[
                            ("all", "All Messages"),
                            ("mentions", "Mentions Only"),
                            ("none", "No Notifications"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time member read messages in this channel",
                        null=True,
                    ),
                ),
                (
                    "is_watching",
                    models.BooleanField(
                        default=True,
                        help_text="Whether member is actively watching this channel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Channel Membership",
                "verbose_name_plural": "Agent Channel Memberships",
            },
        ),
        migrations.CreateModel(
            name="AgentChannelMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("agent_message", "Agent Message"),
                            ("system_message", "System Message"),
                            ("user_message", "User Message"),
                            ("status_update", "Status Update"),
                            ("task_update", "Task Update"),
                            ("tool_usage", "Tool Usage"),
                            ("collaboration_request", "Collaboration Request"),
                            ("result_share", "Result Share"),
                            ("error_report", "Error Report"),
                        ],
                        default="agent_message",
                        max_length=30,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "rich_content",
                    models.JSONField(
                        default=dict,
                        help_text="Rich content (code blocks, attachments, etc.)",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        blank=True,
                        help_text="Thread ID for message threading",
                        max_length=100,
                    ),
                ),
                (
                    "reactions",
                    models.JSONField(
                        default=dict, help_text="Emoji reactions to this message"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Whether message is pinned in channel"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Message timestamp"
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, help_text="Last edit timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Channel Message",
                "verbose_name_plural": "Agent Channel Messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        help_text="Human-readable execution identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        help_text="Description of the task to be performed"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        help_text="Categorization of task type",
                        max_length=100,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context and parameters for execution",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input data provided to the agent"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initializing", "Initializing"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent Priority"),
                            ("critical", "Critical Priority"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="Completion progress (0-100)"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True,
                        help_text="Description of current execution step",
                        max_length=500,
                    ),
                ),
                (
                    "steps_completed",
                    models.JSONField(default=list, help_text="List of completed steps"),
                ),
                (
                    "estimated_completion_time",
                    models.DateTimeField(
                        blank=True, help_text="Estimated completion time", null=True
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Execution result data", null=True
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured output data from agent execution",
                    ),
                ),
                (
                    "llm_response",
                    models.TextField(blank=True, help_text="Raw response from the LLM"),
                ),
                (
                    "output_files",
                    models.JSONField(
                        default=list, help_text="List of generated output files"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if execution failed"
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True, help_text="Detailed error information", null=True
                    ),
                ),
                (
                    "warnings",
                    models.JSONField(
                        default=list, help_text="Non-critical warnings during execution"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Total execution time in seconds",
                        null=True,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(
                        default=dict,
                        help_text="Token usage statistics (input, output, total)",
                    ),
                ),
                (
                    "cost_breakdown",
                    models.JSONField(default=dict, help_text="Detailed cost breakdown"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=10
                    ),
                ),
                (
                    "memory_usage_mb",
                    models.FloatField(
                        blank=True, help_text="Peak memory usage in MB", null=True
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True, help_text="User rating (1-5)", null=True
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True, help_text="User feedback on execution quality"
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Automated quality assessment score",
                        null=True,
                    ),
                ),
                (
                    "collaboration_context",
                    models.JSONField(
                        default=dict, help_text="Context for multi-agent collaboration"
                    ),
                ),
                (
                    "websocket_channel",
                    models.CharField(
                        blank=True,
                        help_text="WebSocket channel for real-time updates",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Execution",
                "verbose_name_plural": "Agent Executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentOrchestration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable orchestration name", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the orchestration workflow"
                    ),
                ),
                (
                    "workflow_definition",
                    models.JSONField(
                        help_text="Complete workflow definition with steps and dependencies"
                    ),
                ),
                (
                    "agent_sequence",
                    models.JSONField(
                        default=list, help_text="Ordered sequence of agents to execute"
                    ),
                ),
                (
                    "execution_strategy",
                    models.CharField(
                        choices=[
                            ("sequential", "Sequential Execution"),
                            ("parallel", "Parallel Execution"),
                            ("conditional", "Conditional Execution"),
                            ("adaptive", "Adaptive Execution"),
                        ],
                        default="sequential",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("initializing", "Initializing"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_agent_index",
                    models.IntegerField(
                        default=0, help_text="Index of currently executing agent"
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                (
                    "intermediate_results",
                    models.JSONField(
                        default=list,
                        help_text="Results from each agent in the orchestration",
                    ),
                ),
                (
                    "final_result",
                    models.JSONField(
                        blank=True, help_text="Aggregated final result", null=True
                    ),
                ),
                (
                    "total_execution_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Total orchestration time in seconds",
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "websocket_channel",
                    models.CharField(
                        blank=True,
                        help_text="WebSocket channel for orchestration updates",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Orchestration",
                "verbose_name_plural": "Agent Orchestrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "registry_name",
                    models.CharField(
                        default="unified_agent_registry", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Central registry for the Unified Donkey Betz Platform agents"
                    ),
                ),
                ("total_agents", models.PositiveIntegerField(default=0)),
                ("active_agents", models.PositiveIntegerField(default=0)),
                ("total_executions", models.PositiveIntegerField(default=0)),
                (
                    "capability_index",
                    models.JSONField(
                        default=dict,
                        help_text="Index mapping capabilities to agent lists",
                    ),
                ),
                (
                    "specialization_index",
                    models.JSONField(
                        default=dict,
                        help_text="Index mapping specializations to agent lists",
                    ),
                ),
                (
                    "keyword_index",
                    models.JSONField(
                        default=dict, help_text="Index mapping keywords to agent lists"
                    ),
                ),
                ("avg_success_rate", models.FloatField(default=0.0)),
                ("avg_execution_time", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Registry",
                "verbose_name_plural": "Agent Registries",
            },
        ),
        migrations.CreateModel(
            name="AgentTool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique tool name", max_length=100, unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-friendly display name", max_length=150
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Tool description and capabilities"),
                ),
                (
                    "tool_type",
                    models.CharField(
                        choices=[
                            ("api", "API Integration"),
                            ("computation", "Computation Tool"),
                            ("data_processing", "Data Processing"),
                            ("communication", "Communication Tool"),
                            ("content_generation", "Content Generation"),
                            ("analysis", "Analysis Tool"),
                            ("monitoring", "Monitoring Tool"),
                            ("integration", "System Integration"),
                        ],
                        help_text="Category of tool",
                        max_length=50,
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        blank=True, help_text="Primary endpoint URL if applicable"
                    ),
                ),
                (
                    "authentication_config",
                    models.JSONField(
                        default=dict, help_text="Authentication configuration"
                    ),
                ),
                (
                    "tool_config",
                    models.JSONField(
                        default=dict, help_text="Tool-specific configuration parameters"
                    ),
                ),
                (
                    "supported_operations",
                    models.JSONField(
                        default=list, help_text="List of operations this tool supports"
                    ),
                ),
                (
                    "required_permissions",
                    models.JSONField(
                        default=list, help_text="Required permissions to use this tool"
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_response_time_ms",
                    models.FloatField(
                        default=0.0, help_text="Average response time in milliseconds"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(default=1.0, help_text="Success rate (0-1)"),
                ),
                ("tool_version", models.CharField(default="1.0.0", max_length=20)),
            ],
            options={
                "verbose_name": "Agent Tool",
                "verbose_name_plural": "Agent Tools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedAgentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique agent name", max_length=200, unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-friendly display name",
                        max_length=250,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed agent description and purpose"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("research", "Research & Analysis"),
                            ("content", "Content Creation"),
                            ("business", "Business Development"),
                            ("career", "Career Development"),
                            ("technical", "Technical Analysis"),
                            ("creative", "Creative Design"),
                            ("marketing", "Marketing & Growth"),
                            ("financial", "Financial Analysis"),
                            ("legal", "Legal & Compliance"),
                            ("communication", "Communication & Outreach"),
                            (
                                "sports-analytics",
                                "Sports Analytics & Betting Intelligence",
                            ),
                            (
                                "odds-calculation",
                                "Odds Calculation & Betting Mathematics",
                            ),
                            ("risk-assessment", "Risk Assessment & Management"),
                            ("implementation", "Implementation & Deployment"),
                            ("token-budget", "Token Budget & Context Optimization"),
                            (
                                "rag-diagnostics",
                                "RAG Diagnostics & Grounding Optimization",
                            ),
                            (
                                "glossary-anchor-curator",
                                "Glossary Anchor Curation & RAG Optimization",
                            ),
                            (
                                "memory-bridge-coordinator",
                                "Memory Bridge Coordination & Context Management",
                            ),
                            (
                                "core-agents-enablement-coordinator",
                                "Core Agents Enablement Coordinator",
                            ),
                            ("narrative-predictor-agent", "Narrative Predictor Agent"),
                            (
                                "empire-builder-orchestrator",
                                "Empire Builder Orchestrator",
                            ),
                            ("correlation-hunter", "Correlation Hunter"),
                            ("shit-talker", "Shit Talker & Motivational Combat Agent"),
                            (
                                "autonomous-knowledge-evolution-engine",
                                "Autonomous Knowledge Evolution Engine",
                            ),
                            ("orchestration", "Multi-Agent Orchestration"),
                            ("self-awareness", "Self-Awareness & Introspection"),
                        ],
                        help_text="Primary specialization area",
                        max_length=100,
                    ),
                ),
                (
                    "capabilities",
                    models.JSONField(
                        default=list,
                        help_text="List of specific capabilities this agent provides",
                    ),
                ),
                (
                    "required_tools",
                    models.JSONField(
                        default=list,
                        help_text="Tools required for this agent to function",
                    ),
                ),
                (
                    "optional_tools",
                    models.JSONField(
                        default=list,
                        help_text="Optional tools that enhance agent performance",
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System prompt that defines agent behavior and personality"
                    ),
                ),
                (
                    "personality_traits",
                    models.JSONField(
                        default=dict,
                        help_text="Personality configuration (style, tone, detail_level, etc.)",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google AI"),
                            ("azure", "Azure OpenAI"),
                            ("local", "Local Model"),
                        ],
                        default="openai",
                        help_text="Primary LLM provider",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="gpt-5-mini",
                        help_text="Specific model name",
                        max_length=100,
                    ),
                ),
                (
                    "llm_config",
                    models.JSONField(
                        default=dict,
                        help_text="LLM configuration (temperature, max_tokens, etc.)",
                    ),
                ),
                (
                    "fallback_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google AI"),
                            ("azure", "Azure OpenAI"),
                            ("local", "Local Model"),
                        ],
                        help_text="Fallback LLM provider if primary fails",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fallback_model",
                    models.CharField(
                        blank=True, help_text="Fallback model name", max_length=100
                    ),
                ),
                (
                    "routing_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords used for intelligent agent routing",
                    ),
                ),
                (
                    "routing_patterns",
                    models.JSONField(
                        default=list, help_text="Regex patterns for advanced routing"
                    ),
                ),
                (
                    "domain_tags",
                    models.JSONField(
                        default=list,
                        help_text="Domain tags (sports, content, orchestration, etc.)",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Base confidence score for routing decisions",
                    ),
                ),
                (
                    "avg_completion_time",
                    models.IntegerField(
                        default=300, help_text="Average completion time in seconds"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.95, help_text="Success rate percentage (0-1)"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of times agent has been used"
                    ),
                ),
                (
                    "avg_user_rating",
                    models.FloatField(
                        default=0.0, help_text="Average user rating (0-5)"
                    ),
                ),
                (
                    "estimated_cost_per_execution",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Estimated cost per execution in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_token_usage",
                    models.JSONField(
                        default=dict, help_text="Average token usage statistics"
                    ),
                ),
                (
                    "resource_requirements",
                    models.JSONField(
                        default=dict, help_text="Compute and memory requirements"
                    ),
                ),
                (
                    "agent_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Semantic version number",
                        max_length=20,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=True, help_text="Whether this is a template or instance"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this agent is available in the marketplace",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this agent has been verified/approved",
                    ),
                ),
                (
                    "supports_streaming",
                    models.BooleanField(
                        default=False,
                        help_text="Whether agent supports streaming responses",
                    ),
                ),
                (
                    "supports_interruption",
                    models.BooleanField(
                        default=False,
                        help_text="Whether agent execution can be interrupted",
                    ),
                ),
                (
                    "supports_collaboration",
                    models.BooleanField(
                        default=False,
                        help_text="Whether agent can work with other agents",
                    ),
                ),
                (
                    "max_concurrent_executions",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum concurrent executions allowed"
                    ),
                ),
                (
                    "learning_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether agent can learn from executions",
                    ),
                ),
                (
                    "self_improvement_enabled",
                    models.BooleanField(
                        default=False, help_text="Whether agent can modify itself"
                    ),
                ),
                (
                    "collaboration_history",
                    models.JSONField(
                        default=list,
                        help_text="History of successful collaborations with other agents",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization that owns this agent",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified Agent Template",
                "verbose_name_plural": "Unified Agent Templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
    ]
