# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentchannel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_channels",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmembership",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="agents.agentchannel",
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmembership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmessage",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="agents.agentchannel",
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmessage",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="agents.agentchannelmessage",
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmessage",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User that sent this message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmessage",
            name="agent_instance",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent execution that sent this message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_messages",
                to="agents.agentexecution",
            ),
        ),
        migrations.AddField(
            model_name="agentorchestration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orchestrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="parent_orchestration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_executions",
                to="agents.agentorchestration",
            ),
        ),
        migrations.AddField(
            model_name="agentchannel",
            name="orchestration",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated orchestration if this is an orchestration channel",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="agents.agentorchestration",
            ),
        ),
        migrations.AddField(
            model_name="unifiedagenttemplate",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_agent_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unifiedagenttemplate",
            name="parent_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent template if this is a derived agent",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_templates",
                to="agents.unifiedagenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="agenttool",
            name="compatible_agents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Agents compatible with this tool",
                related_name="compatible_tools",
                to="agents.unifiedagenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="agents.unifiedagenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="agentchannelmembership",
            name="agent_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channel_memberships",
                to="agents.unifiedagenttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannelmessage",
            index=models.Index(
                fields=["channel", "timestamp"], name="agents_agen_channel_0b85a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannelmessage",
            index=models.Index(
                fields=["message_type"], name="agents_agen_message_4dd428_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannelmessage",
            index=models.Index(
                fields=["thread_id"], name="agents_agen_thread__b2cce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannel",
            index=models.Index(
                fields=["channel_type"], name="agents_agen_channel_ebad93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannel",
            index=models.Index(
                fields=["is_active"], name="agents_agen_is_acti_4da781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannel",
            index=models.Index(
                fields=["created_at"], name="agents_agen_created_ad8557_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedagenttemplate",
            index=models.Index(
                fields=["specialization"], name="agents_unif_special_1a67b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedagenttemplate",
            index=models.Index(
                fields=["llm_provider"], name="agents_unif_llm_pro_86553c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedagenttemplate",
            index=models.Index(
                fields=["is_active"], name="agents_unif_is_acti_3521a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedagenttemplate",
            index=models.Index(
                fields=["usage_count"], name="agents_unif_usage_c_8da1c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedagenttemplate",
            index=models.Index(
                fields=["success_rate"], name="agents_unif_success_0e72aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["status"], name="agents_agen_status_fc4569_idx"),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["priority"], name="agents_agen_priorit_b20ae9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(
                fields=["started_at"], name="agents_agen_started_6cdf12_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecution",
            index=models.Index(fields=["user"], name="agents_agen_user_id_d8fb16_idx"),
        ),
        migrations.AddIndex(
            model_name="agentchannelmembership",
            index=models.Index(
                fields=["channel", "is_active"], name="agents_agen_channel_72464d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentchannelmembership",
            index=models.Index(
                fields=["last_read_at"], name="agents_agen_last_re_4e1a11_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentchannelmembership",
            unique_together={("channel", "agent_template"), ("channel", "user")},
        ),
    ]
