# Generated by Django 5.0.6 on 2025-09-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0002_initial"),
    ]

    operations = [
        # Index for agent execution queries by status and created time
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(
                fields=['status', '-created_at'],
                name='agent_exec_status_time_idx'
            ),
        ),
        # Index for agent execution queries by template and status
        migrations.AddIndex(
            model_name='agentexecution',
            index=models.Index(
                fields=['template', 'status'],
                name='agent_exec_template_status_idx'
            ),
        ),
        # Index for agent template queries by specialization and active status
        migrations.AddIndex(
            model_name='unifiedagenttemplate',
            index=models.Index(
                fields=['specialization', 'is_active'],
                name='agent_tmpl_spec_active_idx'
            ),
        ),
        # Index for agent template queries by active status and usage count
        migrations.AddIndex(
            model_name='unifiedagenttemplate',
            index=models.Index(
                fields=['is_active', '-usage_count'],
                name='agent_tmpl_active_usage_idx'
            ),
        ),
        # Index for agent orchestration queries
        migrations.AddIndex(
            model_name='agentorchestration',
            index=models.Index(
                fields=['user', 'status', '-created_at'],
                name='agent_orch_user_status_idx'
            ),
        ),
    ]
