# Generated by Django 5.0.6 on 2025-09-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agentexecution",
            name="agent_exec_status_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="agentexecution",
            name="agent_exec_template_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="agentorchestration",
            name="agent_orch_user_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="unifiedagenttemplate",
            name="agent_tmpl_spec_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="unifiedagenttemplate",
            name="agent_tmpl_active_usage_idx",
        ),
    ]
