# Generated by Django 5.0.6 on 2025-09-30 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_remove_agentexecution_agent_exec_status_time_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "total_predictions",
                    models.IntegerField(
                        default=0, help_text="Total predictions made by this agent"
                    ),
                ),
                (
                    "correct_predictions",
                    models.IntegerField(
                        default=0, help_text="Number of correct predictions"
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        default=0.0, help_text="Overall accuracy (0.0-1.0)"
                    ),
                ),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("nfl", "NFL"),
                            ("nba", "NBA"),
                            ("mlb", "MLB"),
                            ("nhl", "NHL"),
                        ],
                        help_text="Sport type for these metrics",
                        max_length=10,
                    ),
                ),
                (
                    "sport_predictions",
                    models.IntegerField(
                        default=0, help_text="Predictions made for this sport"
                    ),
                ),
                (
                    "sport_correct",
                    models.IntegerField(
                        default=0, help_text="Correct predictions for this sport"
                    ),
                ),
                (
                    "sport_accuracy",
                    models.FloatField(
                        default=0.0, help_text="Accuracy for this sport (0.0-1.0)"
                    ),
                ),
                (
                    "avg_confidence_when_correct",
                    models.FloatField(
                        default=0.0,
                        help_text="Average confidence when prediction was correct",
                    ),
                ),
                (
                    "avg_confidence_when_wrong",
                    models.FloatField(
                        default=0.0,
                        help_text="Average confidence when prediction was wrong",
                    ),
                ),
                (
                    "confidence_calibration_score",
                    models.FloatField(
                        default=0.0,
                        help_text="How well-calibrated confidence is (-1.0 to 1.0)",
                    ),
                ),
                (
                    "last_10_predictions_accuracy",
                    models.FloatField(
                        default=0.0, help_text="Accuracy of last 10 predictions"
                    ),
                ),
                (
                    "last_30_predictions_accuracy",
                    models.FloatField(
                        default=0.0, help_text="Accuracy of last 30 predictions"
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        default="stable",
                        help_text="Performance trend",
                        max_length=20,
                    ),
                ),
                (
                    "best_sport",
                    models.CharField(
                        blank=True,
                        help_text="Sport agent performs best in",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "worst_sport",
                    models.CharField(
                        blank=True,
                        help_text="Sport agent performs worst in",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("overconfident", "Overconfident"),
                            ("well_calibrated", "Well Calibrated"),
                            ("underconfident", "Underconfident"),
                        ],
                        default="well_calibrated",
                        help_text="Confidence calibration assessment",
                        max_length=20,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="agents.unifiedagenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Performance Metrics",
                "verbose_name_plural": "Agent Performance Metrics",
                "indexes": [
                    models.Index(
                        fields=["agent", "sport_type"],
                        name="agents_agen_agent_i_e7237b_idx",
                    ),
                    models.Index(
                        fields=["accuracy"], name="agents_agen_accurac_d0d3f9_idx"
                    ),
                    models.Index(
                        fields=["sport_accuracy"], name="agents_agen_sport_a_235706_idx"
                    ),
                ],
                "unique_together": {("agent", "sport_type")},
            },
        ),
    ]
