# Generated by Django 5.2 on 2025-10-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agentperformancemetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifiedagenttemplate",
            name="tool_integrations",
            field=models.JSONField(
                default=dict,
                help_text='Tool integration configuration:\n        {\n            "web_search": {"enabled": true, "provider": "serper", "max_results": 10},\n            "api_calls": {"enabled": true, "allowed_apis": ["openai", "serper"]},\n            "data_access": {"spider_data": true, "learning_context": true},\n            "content_generation": {"types": ["blog", "social"], "max_length": 5000}\n        }',
            ),
        ),
    ]
