# Generated by Django 5.0.6 on 2025-11-17 03:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_add_tool_integrations"),
        ("content", "0019_minifig_asset_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "contribution_type",
                    models.CharField(
                        choices=[
                            ("generation", "Content Generation"),
                            ("editing", "Editing/Enhancement"),
                            ("orchestration", "Workflow Orchestration"),
                            ("analysis", "Analysis/Planning"),
                            ("recommendation", "Recommendation"),
                            ("iteration", "Iterative Improvement"),
                        ],
                        default="generation",
                        help_text="Type of contribution",
                        max_length=50,
                    ),
                ),
                (
                    "contribution_role",
                    models.CharField(
                        default="Primary Creator",
                        help_text="Role in creation process",
                        max_length=100,
                    ),
                ),
                (
                    "contribution_percentage",
                    models.IntegerField(
                        default=100,
                        help_text="Contribution percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        blank=True, help_text="Description of what agent did"
                    ),
                ),
                (
                    "execution_time_seconds",
                    models.FloatField(
                        blank=True, help_text="Execution time in seconds", null=True
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True, help_text="AI tokens consumed", null=True
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_selected",
                    models.BooleanField(
                        default=False,
                        help_text="True if user selected this agent's output as favorite",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent that made this contribution",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="agents.unifiedagenttemplate",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to agent execution record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_contributions",
                        to="agents.agentexecution",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image created/edited by agent",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_contributions",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this contribution belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_contributions",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        help_text="Video created/edited by agent",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_contributions",
                        to="content.videohistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Contribution",
                "verbose_name_plural": "Agent Contributions",
                "db_table": "agent_contributions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="agent_contr_project_73eef1_idx",
                    ),
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="agent_contr_agent_i_8262dc_idx",
                    ),
                    models.Index(
                        fields=["contribution_type"],
                        name="agent_contr_contrib_7c56a7_idx",
                    ),
                ],
            },
        ),
    ]
