# Generated by Django 5.0.6 on 2025-11-21 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_agentcontribution"),
        ("content", "0028_alter_imagehistory_seed_projectshare"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentcontribution",
            name="minifig_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="3D model created by agent",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_contributions",
                to="content.minifigasset",
            ),
        ),
    ]
