# Generated by Django 5.0.6 on 2025-12-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_agentcontribution_minifig_asset"),
        ("core", "0064_alter_businessresearchresult_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcontribution",
            name="project",
            field=models.ForeignKey(
                help_text="Project this contribution belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_contributions",
                to="core.partnershipproject",
            ),
        ),
    ]
