# Generated by Django 5.0.6 on 2026-01-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_alter_agentcontribution_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcontribution",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this contribution belongs to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_contributions",
                to="core.partnershipproject",
            ),
        ),
    ]
