#!/usr/bin/env python3
"""
Demo Real Agent Execution
Shows real projects with correctly assigned agents
"""
import os
import sys
import django
import redis
import json
import uuid
from datetime import datetime

# Setup Django environment
sys.path.append('/Users/donkeyking/development/unified-donkey-betz')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

import openai

def create_blog_post():
    """Create a real blog post using AI"""
    print("📝 Creating real blog post with AI agent...")

    # Initialize OpenAI client
    client = openai.OpenAI(api_key=os.getenv('OPENAI_API_KEY'))

    # Create a real blog post
    prompt = """
    Write a professional 500-word blog post about "5 Essential AI Productivity Tools for Remote Workers".

    Include:
    - Engaging introduction
    - 5 specific tools with descriptions
    - Benefits for remote workers
    - Strong conclusion
    - SEO-friendly structure

    Write in a professional, helpful tone.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are a professional content writer specializing in AI and productivity tools."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=1000,
            temperature=0.7
        )

        blog_content = response.choices[0].message.content

        # Save to file
        filename = f"real_job_deliverables/blog_post_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        os.makedirs('real_job_deliverables', exist_ok=True)

        with open(filename, 'w') as f:
            f.write(f"# AI Productivity Tools Blog Post\n\n")
            f.write(f"**Generated by AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}**\n\n")
            f.write(blog_content)

        print(f"✅ Blog post created: {filename}")
        print(f"📄 Content length: {len(blog_content)} characters")
        print(f"📝 First 150 characters: {blog_content[:150]}...")

        return filename, blog_content

    except Exception as e:
        print(f"❌ Error creating blog post: {e}")
        return None, None

def create_python_script():
    """Create a real Python data analysis script"""
    print("\n🐍 Creating real Python script with AI agent...")

    # Initialize OpenAI client
    client = openai.OpenAI(api_key=os.getenv('OPENAI_API_KEY'))

    prompt = """
    Create a Python script that analyzes sales data from a CSV file.

    Requirements:
    - Read CSV with columns: date, product, sales_amount, region
    - Calculate total sales by product and region
    - Generate a simple visualization (bar chart)
    - Export results to a new CSV file
    - Include proper error handling and documentation

    Write clean, professional code with comments.
    """

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are an expert Python developer specializing in data analysis."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=1000,
            temperature=0.3
        )

        script_content = response.choices[0].message.content

        # Clean up code (remove markdown formatting if present)
        if "```python" in script_content:
            script_content = script_content.split("```python")[1].split("```")[0].strip()
        elif "```" in script_content:
            script_content = script_content.split("```")[1].strip()

        # Save to file
        filename = f"real_job_deliverables/sales_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py"

        with open(filename, 'w') as f:
            f.write(f"#!/usr/bin/env python\n")
            f.write(f'"""\nSales Data Analysis Script\n')
            f.write(f"Generated by AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f'"""\n\n')
            f.write(script_content)

        print(f"✅ Python script created: {filename}")
        print(f"📄 Script length: {len(script_content)} characters")
        print(f"🐍 First 100 characters: {script_content[:100]}...")

        return filename, script_content

    except Exception as e:
        print(f"❌ Error creating Python script: {e}")
        return None, None

def create_projects_in_redis():
    """Create real projects with correct agent assignments"""
    print("📦 Creating projects with proper agent assignments...")

    r = redis.Redis(host='localhost', port=6379, decode_responses=True)

    # Create Node.js API project (should use Code Generator)
    api_project_id = f"proj_{uuid.uuid4().hex[:8]}"
    api_project = {
        'id': api_project_id,
        'opportunity': {
            'job_id': f'demo_{uuid.uuid4().hex[:6]}',
            'title': 'Build REST API with Node.js',
            'platform': 'Upwork',
            'budget': 1200,
            'skills_required': ['Node.js', 'REST API', 'Express']
        },
        'status': 'active',
        'created_at': datetime.now().isoformat(),
        'analysis': {
            'agent_team': {
                'lead_agent': 'Code Generator',
                'supporting_agents': ['API Builder', 'Backend Developer']
            }
        }
    }
    r.set(f"freelance:project:{api_project_id}", json.dumps(api_project))
    print(f"✅ Project 1: Node.js API → Code Generator")

    # Create Blog Writing project (should use Content Creator)
    blog_project_id = f"proj_{uuid.uuid4().hex[:8]}"
    blog_project = {
        'id': blog_project_id,
        'opportunity': {
            'job_id': f'demo_{uuid.uuid4().hex[:6]}',
            'title': 'Write 10 SEO Blog Posts',
            'platform': 'Fiverr',
            'budget': 500,
            'skills_required': ['Content Writing', 'SEO', 'Blog']
        },
        'status': 'active',
        'created_at': datetime.now().isoformat(),
        'analysis': {
            'agent_team': {
                'lead_agent': 'Content Creator',
                'supporting_agents': ['SEO Optimizer', 'Copywriter']
            }
        }
    }
    r.set(f"freelance:project:{blog_project_id}", json.dumps(blog_project))
    print(f"✅ Project 2: SEO Blog Posts → Content Creator")

    # Create Data Analysis project (should use Data Analyst)
    data_project_id = f"proj_{uuid.uuid4().hex[:8]}"
    data_project = {
        'id': data_project_id,
        'opportunity': {
            'job_id': f'demo_{uuid.uuid4().hex[:6]}',
            'title': 'Python Data Analysis Dashboard',
            'platform': 'Upwork',
            'budget': 600,
            'skills_required': ['Python', 'Pandas', 'Data Analysis']
        },
        'status': 'active',
        'created_at': datetime.now().isoformat(),
        'analysis': {
            'agent_team': {
                'lead_agent': 'Data Analyst',
                'supporting_agents': ['Code Generator', 'Script Writer']
            }
        }
    }
    r.set(f"freelance:project:{data_project_id}", json.dumps(data_project))
    print(f"✅ Project 3: Python Dashboard → Data Analyst")

    return [api_project_id, blog_project_id, data_project_id]

def demo_freelance_deliverables():
    """Demo creating real freelance deliverables"""
    print("🚀 REAL AGENT EXECUTION DEMO")
    print("="*50)
    print("This shows agents creating actual deliverables for freelance jobs")
    print()

    # First create projects in Redis
    project_ids = create_projects_in_redis()
    print(f"\n✅ Created {len(project_ids)} projects with correct agent assignments")

    # Create blog post
    blog_file, blog_content = create_blog_post()

    # Create Python script
    script_file, script_content = create_python_script()

    print("\n" + "="*50)
    print("📊 EXECUTION SUMMARY")
    print("="*50)

    deliverables = []
    if blog_file:
        deliverables.append(("Blog Post", blog_file, len(blog_content)))
    if script_file:
        deliverables.append(("Python Script", script_file, len(script_content)))

    print(f"✅ Created {len(deliverables)} real deliverables:")
    for i, (type_name, filename, size) in enumerate(deliverables, 1):
        print(f"   {i}. {type_name}: {filename} ({size} chars)")

    if deliverables:
        print(f"\n💰 Total value created: ~${len(deliverables) * 200}")
        print("🎯 These are REAL files that could be delivered to clients!")
        print("📁 Check the 'real_job_deliverables' folder")

    print("\n🤖 Agent assignments in UI should show:")
    print("   • Code Generator → Working on Node.js API")
    print("   • Content Creator → Working on SEO Blog Posts")
    print("   • Data Analyst → Working on Python Dashboard")
    print("\n🎨 Check the '152 Agent Army' monitor in UI!")

    return deliverables

if __name__ == '__main__':
    demo_freelance_deliverables()