#!/bin/bash
# Quick Reference Commands for Unified Donkey Betz

echo "🎯 UNIFIED DONKEY BETZ - QUICK COMMANDS"
echo "========================================"
echo ""
echo "📋 Main Commands:"
echo "  Start Everything:    ./start_ws_quick.sh"
echo "  Verify Platform:     python verify_platform.py"
echo "  Test API:           python quick-api-test.py"
echo "  Test Connectivity:   python test_frontend_connectivity.py"
echo ""
echo "📍 Key URLs:"
echo "  Command Center:      http://localhost:3000/control-center"
echo "  Backend API:         http://localhost:8000/api/v1/"
echo "  Admin Panel:         http://localhost:8000/admin/"
echo ""
echo "🔑 Authentication:"
echo "  API Token:          0fb2390dedd5cc47ec7e6a320e1477b31b7c0a97"
echo "  Admin Username:     command_center"
echo "  Admin Password:     donkeybetz123"
echo ""
echo "📊 View Logs:"
echo "  Backend:            tail -f backend.log"
echo "  Frontend:           tail -f frontend.log"
echo "  Both:               tail -f *.log"
echo ""
echo "🛑 Stop Everything:   Press Ctrl+C in the terminal running start_ws_quick.sh"
echo ""
echo "✅ Your platform has 150 AI agents ready to execute!"