#!/bin/bash
# Secure local development setup

echo "🔒 Setting up secure local development environment"
echo ""
echo "Option 1: Use environment variables (recommended)"
echo "-------------------------------------------------"
echo "Add to your ~/.zshrc or ~/.bashrc:"
echo ""
echo "# Development API Keys (keep these secret!)"
echo "export OPENAI_API_KEY='your-key-here'"
echo "export ANTHROPIC_API_KEY='your-key-here'"
echo "export GOOGLE_API_KEY='your-key-here'"
echo "export GROQ_API_KEY='your-key-here'"
echo ""
echo "Then run: source ~/.zshrc"
echo ""
echo "Option 2: Use macOS Keychain"
echo "-----------------------------"
echo "Store keys in Keychain:"
echo "  security add-generic-password -a $USER -s OPENAI_API_KEY -w 'your-key'"
echo ""
echo "Retrieve in Python:"
echo "  import subprocess"
echo "  result = subprocess.run(['security', 'find-generic-password', '-s', 'OPENAI_API_KEY', '-w'], capture_output=True, text=True)"
echo "  api_key = result.stdout.strip()"
echo ""
echo "Option 3: Use a .env.local file (git-ignored)"
echo "-----------------------------------------------"
echo "Create .env.local with your keys and add to .gitignore"
echo "Never commit this file!"