# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External API identifier",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "scheduled_start",
                    models.DateTimeField(help_text="Scheduled game start time"),
                ),
                (
                    "actual_start",
                    models.DateTimeField(
                        blank=True, help_text="Actual game start time", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("halftime", "Halftime"),
                            ("final", "Final"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True, help_text="Venue name", max_length=200
                    ),
                ),
                (
                    "venue_city",
                    models.CharField(
                        blank=True, help_text="Venue city", max_length=100
                    ),
                ),
                (
                    "season",
                    models.CharField(help_text="Season identifier", max_length=20),
                ),
                (
                    "week",
                    models.IntegerField(
                        blank=True,
                        help_text="Week number (for sports with weeks)",
                        null=True,
                    ),
                ),
                (
                    "is_playoff",
                    models.BooleanField(
                        default=False, help_text="Whether this is a playoff game"
                    ),
                ),
                (
                    "weather_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Weather conditions (temperature, wind, etc.)",
                    ),
                ),
                (
                    "home_score",
                    models.IntegerField(
                        blank=True, help_text="Home team final score", null=True
                    ),
                ),
                (
                    "away_score",
                    models.IntegerField(
                        blank=True, help_text="Away team final score", null=True
                    ),
                ),
                (
                    "current_period",
                    models.CharField(
                        blank=True, help_text="Current period/quarter", max_length=20
                    ),
                ),
                (
                    "time_remaining",
                    models.CharField(
                        blank=True,
                        help_text="Time remaining in current period",
                        max_length=20,
                    ),
                ),
                (
                    "live_stats",
                    models.JSONField(default=dict, help_text="Live game statistics"),
                ),
                (
                    "total_handle",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total betting handle for this game",
                        max_digits=15,
                    ),
                ),
                (
                    "sharp_action",
                    models.JSONField(
                        default=dict, help_text="Sharp betting action indicators"
                    ),
                ),
                (
                    "public_betting",
                    models.JSONField(
                        default=dict, help_text="Public betting percentages"
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="Sportsbook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Sportsbook name", max_length=200, unique=True
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Short abbreviation", max_length=20, unique=True
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(blank=True, help_text="API endpoint for odds data"),
                ),
                (
                    "api_key_config",
                    models.JSONField(
                        default=dict, help_text="API authentication configuration"
                    ),
                ),
                (
                    "is_sharp",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is considered a sharp book",
                    ),
                ),
                (
                    "betting_limits",
                    models.JSONField(
                        default=dict, help_text="Betting limits by market type"
                    ),
                ),
                (
                    "supported_markets",
                    models.JSONField(
                        default=list, help_text="List of supported market types"
                    ),
                ),
                (
                    "line_speed",
                    models.FloatField(
                        default=0.0, help_text="How quickly lines move (seconds)"
                    ),
                ),
                (
                    "accuracy_score",
                    models.FloatField(
                        default=0.0, help_text="Historical accuracy of closing lines"
                    ),
                ),
                (
                    "legal_states",
                    models.JSONField(
                        default=list,
                        help_text="States/regions where this book is legal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sportsbook",
                "verbose_name_plural": "Sportsbooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankrollManagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1000.00"),
                        help_text="Current bankroll balance",
                        max_digits=15,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting bankroll amount",
                        max_digits=15,
                    ),
                ),
                (
                    "max_bet_percentage",
                    models.FloatField(
                        default=0.05,
                        help_text="Maximum bet size as percentage of bankroll",
                        validators=[
                            django.core.validators.MinValueValidator(0.001),
                            django.core.validators.MaxValueValidator(0.25),
                        ],
                    ),
                ),
                (
                    "kelly_multiplier",
                    models.FloatField(
                        default=0.25,
                        help_text="Kelly Criterion multiplier (fractional Kelly)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low Risk"),
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("very_high", "Very High Risk"),
                            ("extreme", "Extreme Risk"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "total_wagered",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total amount wagered",
                        max_digits=15,
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total profit/loss",
                        max_digits=15,
                    ),
                ),
                (
                    "win_rate",
                    models.FloatField(
                        default=0.0, help_text="Overall win rate percentage"
                    ),
                ),
                (
                    "roi_percentage",
                    models.FloatField(
                        default=0.0, help_text="Return on investment percentage"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Current winning/losing streak (positive = wins)",
                    ),
                ),
                ("longest_winning_streak", models.IntegerField(default=0)),
                ("longest_losing_streak", models.IntegerField(default=0)),
                (
                    "volatility_score",
                    models.FloatField(
                        default=0.0, help_text="Bankroll volatility measure"
                    ),
                ),
                (
                    "daily_loss_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum daily loss limit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "monthly_loss_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum monthly loss limit",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bankroll",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bankroll Management",
                "verbose_name_plural": "Bankroll Management",
            },
        ),
        migrations.CreateModel(
            name="BettingMarket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("moneyline", "Moneyline"),
                            ("spread", "Point Spread"),
                            ("total", "Over/Under Total"),
                            ("prop", "Player/Team Prop"),
                            ("futures", "Futures"),
                            ("parlay", "Parlay"),
                            ("teaser", "Teaser"),
                            ("live", "Live Bet"),
                        ],
                        help_text="Type of betting market",
                        max_length=20,
                    ),
                ),
                (
                    "market_name",
                    models.CharField(
                        help_text="Descriptive market name", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open for Betting"),
                            ("closed", "Closed"),
                            ("suspended", "Suspended"),
                            ("resulted", "Resulted"),
                            ("voided", "Voided"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "market_params",
                    models.JSONField(
                        default=dict,
                        help_text="Market-specific parameters (spread value, total, etc.)",
                    ),
                ),
                (
                    "settlement_value",
                    models.JSONField(
                        blank=True,
                        help_text="Settlement value when market is resulted",
                        null=True,
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, help_text="When market was settled", null=True
                    ),
                ),
                (
                    "total_volume",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total betting volume",
                        max_digits=15,
                    ),
                ),
                (
                    "sharp_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage of sharp money"
                    ),
                ),
                (
                    "public_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage of public money"
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markets",
                        to="sports.game",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betting Market",
                "verbose_name_plural": "Betting Markets",
                "ordering": ["game", "market_type"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="League/conference name", max_length=200, unique=True
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="League abbreviation (e.g., NFL, NBA)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("nfl", "National Football League"),
                            ("ncaaf", "NCAA Football"),
                            ("nba", "National Basketball Association"),
                            ("ncaab", "NCAA Basketball"),
                            ("mlb", "Major League Baseball"),
                            ("nhl", "National Hockey League"),
                            ("soccer", "Soccer"),
                            ("mma", "Mixed Martial Arts"),
                            ("tennis", "Tennis"),
                            ("golf", "Golf"),
                            ("boxing", "Boxing"),
                            ("esports", "E-Sports"),
                        ],
                        help_text="Type of sport",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="USA", help_text="Primary country", max_length=100
                    ),
                ),
                (
                    "current_season",
                    models.CharField(
                        help_text="Current season (e.g., '2023-2024')", max_length=20
                    ),
                ),
                (
                    "season_start_date",
                    models.DateField(
                        blank=True, help_text="Season start date", null=True
                    ),
                ),
                (
                    "season_end_date",
                    models.DateField(
                        blank=True, help_text="Season end date", null=True
                    ),
                ),
                (
                    "api_provider",
                    models.CharField(
                        blank=True, help_text="Primary data provider", max_length=100
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        default=dict, help_text="API configuration and endpoints"
                    ),
                ),
                (
                    "betting_rules",
                    models.JSONField(
                        default=dict,
                        help_text="League-specific betting rules and limits",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "ordering": ["sport_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["sport_type"], name="sports_leag_sport_t_c023bd_idx"
                    ),
                    models.Index(
                        fields=["abbreviation"], name="sports_leag_abbrevi_c09e22_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="sports.league",
            ),
        ),
        migrations.CreateModel(
            name="OddsLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "home_odds",
                    models.IntegerField(
                        blank=True,
                        help_text="Home team odds (American format)",
                        null=True,
                    ),
                ),
                (
                    "away_odds",
                    models.IntegerField(
                        blank=True,
                        help_text="Away team odds (American format)",
                        null=True,
                    ),
                ),
                (
                    "home_spread",
                    models.FloatField(
                        blank=True, help_text="Home team spread", null=True
                    ),
                ),
                (
                    "away_spread",
                    models.FloatField(
                        blank=True, help_text="Away team spread", null=True
                    ),
                ),
                (
                    "total_line",
                    models.FloatField(
                        blank=True, help_text="Over/Under total", null=True
                    ),
                ),
                (
                    "over_odds",
                    models.IntegerField(blank=True, help_text="Over odds", null=True),
                ),
                (
                    "under_odds",
                    models.IntegerField(blank=True, help_text="Under odds", null=True),
                ),
                (
                    "line_sequence",
                    models.PositiveIntegerField(
                        default=1, help_text="Sequence number for this line"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Whether this is the current line"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this line was first posted"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this line was taken down", null=True
                    ),
                ),
                (
                    "decimal_odds",
                    models.JSONField(default=dict, help_text="Decimal format odds"),
                ),
                (
                    "implied_probabilities",
                    models.JSONField(
                        default=dict, help_text="Calculated implied probabilities"
                    ),
                ),
                (
                    "movement_reason",
                    models.CharField(
                        blank=True, help_text="Reason for line movement", max_length=200
                    ),
                ),
                (
                    "sharp_move",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this movement was due to sharp action",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds_lines",
                        to="sports.bettingmarket",
                    ),
                ),
                (
                    "sportsbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds_lines",
                        to="sports.sportsbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odds Line",
                "verbose_name_plural": "Odds Lines",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "bet_type",
                    models.CharField(
                        choices=[
                            ("moneyline", "Moneyline"),
                            ("spread", "Point Spread"),
                            ("total", "Over/Under Total"),
                            ("prop", "Player/Team Prop"),
                            ("futures", "Futures"),
                            ("parlay", "Parlay"),
                            ("teaser", "Teaser"),
                            ("live", "Live Bet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "selection",
                    models.CharField(
                        help_text="What was bet on (team, over, under, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "odds_taken",
                    models.IntegerField(
                        help_text="Odds when bet was placed (American format)"
                    ),
                ),
                (
                    "stake",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount wagered",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "potential_payout",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potential payout including stake",
                        max_digits=12,
                    ),
                ),
                (
                    "potential_profit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potential profit (payout - stake)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("push", "Push"),
                            ("voided", "Voided"),
                            ("partial", "Partial Win/Loss"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual result amount (profit/loss)",
                        max_digits=12,
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(
                        blank=True, help_text="When bet was settled", null=True
                    ),
                ),
                (
                    "kelly_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Kelly Criterion recommended bet size percentage",
                        null=True,
                    ),
                ),
                (
                    "edge_percentage",
                    models.FloatField(
                        blank=True, help_text="Calculated edge percentage", null=True
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low Risk"),
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("very_high", "Very High Risk"),
                            ("extreme", "Extreme Risk"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Expected value of this bet",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence_level",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence in this bet (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "bet_reason",
                    models.TextField(
                        blank=True, help_text="Reason for placing this bet"
                    ),
                ),
                (
                    "agent_recommendation",
                    models.JSONField(
                        default=dict,
                        help_text="Agent recommendation that led to this bet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="sports.bettingmarket",
                    ),
                ),
                (
                    "odds_line",
                    models.ForeignKey(
                        help_text="The specific odds line when bet was placed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="sports.oddsline",
                    ),
                ),
                (
                    "sportsbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="sports.sportsbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bet",
                "verbose_name_plural": "Bets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SportsAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("game", "Individual Game"),
                            ("team", "Team Analysis"),
                            ("league", "League Analysis"),
                            ("player", "Player Analysis"),
                            ("market", "Market Analysis"),
                            ("user", "User Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(
                        help_text="ID of the entity being analyzed", max_length=100
                    ),
                ),
                (
                    "analysis_period",
                    models.CharField(
                        choices=[
                            ("game", "Single Game"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("season", "Season"),
                            ("historical", "Historical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(help_text="Start of analysis period"),
                ),
                (
                    "period_end",
                    models.DateTimeField(help_text="End of analysis period"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict, help_text="Calculated metrics and KPIs"
                    ),
                ),
                (
                    "trends",
                    models.JSONField(default=dict, help_text="Trend analysis data"),
                ),
                (
                    "predictions",
                    models.JSONField(
                        default=dict, help_text="Predictive analytics results"
                    ),
                ),
                (
                    "comparative_analysis",
                    models.JSONField(
                        default=dict, help_text="Comparisons with benchmarks"
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        help_text="Agent or system that generated analytics",
                        max_length=200,
                    ),
                ),
                (
                    "computation_time_seconds",
                    models.FloatField(
                        default=0.0, help_text="Time taken to compute analytics"
                    ),
                ),
                (
                    "data_quality_score",
                    models.FloatField(
                        default=1.0, help_text="Quality score of underlying data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sports Analytics",
                "verbose_name_plural": "Sports Analytics",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope_type", "scope_id"],
                        name="sports_spor_scope_t_7c5b2c_idx",
                    ),
                    models.Index(
                        fields=["analysis_period", "-created_at"],
                        name="sports_spor_analysi_8d5bdf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LineMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "movement_size",
                    models.FloatField(
                        help_text="Size of the movement (in odds or spread points)"
                    ),
                ),
                (
                    "movement_direction",
                    models.CharField(
                        choices=[("up", "Line Moved Up"), ("down", "Line Moved Down")],
                        max_length=10,
                    ),
                ),
                (
                    "is_significant",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a significant movement",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        blank=True,
                        help_text="Event that triggered the movement",
                        max_length=200,
                    ),
                ),
                (
                    "betting_volume_factor",
                    models.FloatField(
                        default=0.0,
                        help_text="How much betting volume influenced this move",
                    ),
                ),
                (
                    "news_factor",
                    models.FloatField(
                        default=0.0,
                        help_text="How much news/information influenced this move",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_movements",
                        to="sports.bettingmarket",
                    ),
                ),
                (
                    "new_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements_to",
                        to="sports.oddsline",
                    ),
                ),
                (
                    "old_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements_from",
                        to="sports.oddsline",
                    ),
                ),
                (
                    "sportsbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_movements",
                        to="sports.sportsbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Movement",
                "verbose_name_plural": "Line Movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BettingRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "recommended_selection",
                    models.CharField(
                        help_text="Recommended bet selection", max_length=200
                    ),
                ),
                (
                    "recommended_odds",
                    models.IntegerField(help_text="Recommended odds to take"),
                ),
                (
                    "recommended_stake",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Recommended stake amount",
                        max_digits=10,
                    ),
                ),
                (
                    "expected_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Expected value of recommendation",
                        max_digits=10,
                    ),
                ),
                (
                    "win_probability",
                    models.FloatField(help_text="Estimated win probability"),
                ),
                (
                    "confidence_level",
                    models.FloatField(
                        help_text="AI confidence in recommendation",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "edge_percentage",
                    models.FloatField(help_text="Calculated edge percentage"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low Risk"),
                            ("low", "Low Risk"),
                            ("moderate", "Moderate Risk"),
                            ("high", "High Risk"),
                            ("very_high", "Very High Risk"),
                            ("extreme", "Extreme Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "kelly_percentage",
                    models.FloatField(help_text="Kelly Criterion recommended size"),
                ),
                (
                    "generating_agent",
                    models.CharField(
                        help_text="Agent that generated this recommendation",
                        max_length=200,
                    ),
                ),
                (
                    "analysis_factors",
                    models.JSONField(
                        default=dict, help_text="Factors considered in analysis"
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(help_text="Detailed reasoning for recommendation"),
                ),
                (
                    "model_predictions",
                    models.JSONField(
                        default=dict,
                        help_text="Raw model predictions and probabilities",
                    ),
                ),
                (
                    "historical_performance",
                    models.JSONField(
                        default=dict,
                        help_text="Historical performance of similar recommendations",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When recommendation expires"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether recommendation is still active"
                    ),
                ),
                (
                    "user_action",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "actual_result",
                    models.CharField(
                        blank=True,
                        help_text="Actual outcome for performance tracking",
                        max_length=20,
                    ),
                ),
                (
                    "bet_placed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation",
                        to="sports.bet",
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="sports.bettingmarket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betting_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="sports.game",
                    ),
                ),
                (
                    "recommended_sportsbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="sports.sportsbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Betting Recommendation",
                "verbose_name_plural": "Betting Recommendations",
                "ordering": ["-confidence_level", "-expected_value", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("moneyline", "Moneyline"),
                            ("spread", "Point Spread"),
                            ("total", "Over/Under Total"),
                            ("prop", "Player/Team Prop"),
                            ("futures", "Futures"),
                            ("parlay", "Parlay"),
                            ("teaser", "Teaser"),
                            ("live", "Live Bet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("odds_1", models.IntegerField(help_text="Odds at sportsbook 1")),
                ("odds_2", models.IntegerField(help_text="Odds at sportsbook 2")),
                (
                    "selection_1",
                    models.CharField(
                        help_text="What to bet on at sportsbook 1", max_length=200
                    ),
                ),
                (
                    "selection_2",
                    models.CharField(
                        help_text="What to bet on at sportsbook 2", max_length=200
                    ),
                ),
                (
                    "arbitrage_percentage",
                    models.FloatField(help_text="Arbitrage profit percentage"),
                ),
                (
                    "stake_1_percentage",
                    models.FloatField(help_text="Percentage of total stake for bet 1"),
                ),
                (
                    "stake_2_percentage",
                    models.FloatField(help_text="Percentage of total stake for bet 2"),
                ),
                (
                    "minimum_profit",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Minimum guaranteed profit percentage",
                        max_digits=10,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this opportunity expires"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether opportunity is still available"
                    ),
                ),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why opportunity was closed",
                        max_length=200,
                    ),
                ),
                (
                    "risk_factors",
                    models.JSONField(default=list, help_text="Identified risk factors"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence in this arbitrage opportunity",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arbitrage_opportunities",
                        to="sports.game",
                    ),
                ),
                (
                    "sportsbook_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arb_opportunities_1",
                        to="sports.sportsbook",
                    ),
                ),
                (
                    "sportsbook_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arb_opportunities_2",
                        to="sports.sportsbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arbitrage Opportunity",
                "verbose_name_plural": "Arbitrage Opportunities",
                "ordering": ["-arbitrage_percentage", "-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("name", models.CharField(help_text="Team name", max_length=200)),
                (
                    "abbreviation",
                    models.CharField(help_text="Team abbreviation", max_length=10),
                ),
                ("city", models.CharField(help_text="Team city", max_length=100)),
                (
                    "conference",
                    models.CharField(
                        blank=True, help_text="Conference/division", max_length=100
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        blank=True,
                        help_text="Division within conference",
                        max_length=100,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="External API identifier", max_length=100
                    ),
                ),
                ("logo_url", models.URLField(blank=True, help_text="Team logo URL")),
                (
                    "current_record",
                    models.JSONField(
                        default=dict,
                        help_text="Current season record (wins, losses, etc.)",
                    ),
                ),
                (
                    "season_stats",
                    models.JSONField(default=dict, help_text="Season statistics"),
                ),
                (
                    "ats_record",
                    models.JSONField(
                        default=dict, help_text="Against The Spread record"
                    ),
                ),
                (
                    "ou_record",
                    models.JSONField(default=dict, help_text="Over/Under record"),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="sports.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["league", "name"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away_games",
                to="sports.team",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_games",
                to="sports.team",
            ),
        ),
        migrations.AddIndex(
            model_name="bettingmarket",
            index=models.Index(
                fields=["game", "market_type"], name="sports_bett_game_id_f7fdc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bettingmarket",
            index=models.Index(fields=["status"], name="sports_bett_status_b0e8ed_idx"),
        ),
        migrations.AddIndex(
            model_name="oddsline",
            index=models.Index(
                fields=["market", "sportsbook"], name="sports_odds_market__08f85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oddsline",
            index=models.Index(
                fields=["is_current"], name="sports_odds_is_curr_6771b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oddsline",
            index=models.Index(
                fields=["created_at"], name="sports_odds_created_544d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linemovement",
            index=models.Index(
                fields=["market", "-created_at"], name="sports_line_market__ce4971_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="linemovement",
            index=models.Index(
                fields=["is_significant"], name="sports_line_is_sign_89ba71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bettingrecommendation",
            index=models.Index(
                fields=["user", "is_active"], name="sports_bett_user_id_5c3eab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bettingrecommendation",
            index=models.Index(
                fields=["game", "-confidence_level"],
                name="sports_bett_game_id_9e9228_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(
                fields=["user", "-created_at"], name="sports_bet_user_id_75887c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(fields=["status"], name="sports_bet_status_c32c9c_idx"),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(fields=["market"], name="sports_bet_market__2a4911_idx"),
        ),
        migrations.AddIndex(
            model_name="arbitrageopportunity",
            index=models.Index(
                fields=["is_active", "-arbitrage_percentage"],
                name="sports_arbi_is_acti_1412eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="arbitrageopportunity",
            index=models.Index(fields=["game"], name="sports_arbi_game_id_dd011d_idx"),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["league"], name="sports_team_league__bbeee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["external_id"], name="sports_team_externa_68d763_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("league", "abbreviation")},
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["league", "-scheduled_start"],
                name="sports_game_league__16d7c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(fields=["status"], name="sports_game_status_2e4360_idx"),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["external_id"], name="sports_game_externa_d2d48c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["scheduled_start"], name="sports_game_schedul_a69373_idx"
            ),
        ),
    ]
