# Generated by Django 5.0.6 on 2026-03-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_mlprediction_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlprediction",
            name="bookmaker_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of bookmakers in consensus at prediction time",
            ),
        ),
        migrations.AddField(
            model_name="mlprediction",
            name="closing_odds",
            field=models.IntegerField(
                blank=True,
                help_text="Closing odds on predicted winner (captured when game goes FINAL)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mlprediction",
            name="odds_at_prediction",
            field=models.IntegerField(
                blank=True,
                help_text="American odds on predicted winner at time of prediction (e.g. -110, +150)",
                null=True,
            ),
        ),
    ]
