# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key (e.g., 'max_concurrent_agents')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        help_text="Configuration value (can be any JSON-serializable type)"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of this configuration",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("agents", "Agent Orchestration"),
                            ("sports", "Sports Analytics"),
                            ("content", "Content Generation"),
                            ("ai_services", "AI Services"),
                            ("system", "System Settings"),
                            ("security", "Security Settings"),
                            ("performance", "Performance Tuning"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this configuration contains sensitive data",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="UnifiedUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform_role",
                    models.CharField(
                        choices=[
                            ("admin", "Platform Administrator"),
                            ("sports_analyst", "Sports Analytics User"),
                            ("content_creator", "Content Generation User"),
                            ("agent_manager", "Agent Orchestration Manager"),
                            ("unified_user", "Full Platform Access"),
                        ],
                        default="unified_user",
                        help_text="Primary role/access level on the platform",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for programmatic access",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "monthly_api_calls",
                    models.PositiveIntegerField(
                        default=0, help_text="API calls made this month"
                    ),
                ),
                (
                    "api_call_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Monthly API call limit"
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences across all platform systems",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PlatformMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(
                        help_text="Name of the metric (e.g., 'active_agents', 'api_calls_per_hour')",
                        max_length=100,
                    ),
                ),
                (
                    "metric_value",
                    models.FloatField(help_text="Numeric value of the metric"),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter (cumulative)"),
                            ("gauge", "Gauge (point-in-time)"),
                            ("histogram", "Histogram (distribution)"),
                            ("timer", "Timer (duration)"),
                        ],
                        default="gauge",
                        max_length=20,
                    ),
                ),
                (
                    "subsystem",
                    models.CharField(
                        choices=[
                            ("agents", "Agent Orchestration"),
                            ("sports", "Sports Analytics"),
                            ("content", "Content Generation"),
                            ("ai_services", "AI Services"),
                            ("gateway", "API Gateway"),
                            ("realtime", "Real-time Systems"),
                            ("system", "System-wide"),
                        ],
                        default="system",
                        max_length=50,
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional labels/dimensions for the metric",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this metric was recorded"
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Metric",
                "verbose_name_plural": "Platform Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-timestamp"],
                        name="core_platfo_metric__59ae20_idx",
                    ),
                    models.Index(
                        fields=["subsystem", "-timestamp"],
                        name="core_platfo_subsyst_ae1d73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "avatar_file",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "occupation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "preferred_ai_model",
                    models.CharField(default="gpt-5-mini", max_length=20),
                ),
                (
                    "default_content_tone",
                    models.CharField(default="professional", max_length=20),
                ),
                ("auto_save", models.BooleanField(default=True)),
                ("dark_mode", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                (
                    "default_citation_style",
                    models.CharField(default="APA", max_length=10),
                ),
                (
                    "preferred_book_length",
                    models.CharField(default="medium", max_length=10),
                ),
                (
                    "research_topics",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("pro", "Professional"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="premium",
                        max_length=20,
                    ),
                ),
                ("credits_remaining", models.IntegerField(default=10000)),
                ("storage_used_mb", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "db_table": "core_userprofile",
            },
        ),
        migrations.CreateModel(
            name="UserStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_contents", models.IntegerField(default=0)),
                ("total_images", models.IntegerField(default=0)),
                ("total_videos", models.IntegerField(default=0)),
                ("total_blogs", models.IntegerField(default=0)),
                ("total_social_posts", models.IntegerField(default=0)),
                ("total_ebooks", models.IntegerField(default=0)),
                ("total_research_docs", models.IntegerField(default=0)),
                ("total_campaigns", models.IntegerField(default=0)),
                ("total_ai_requests", models.IntegerField(default=0)),
                ("total_tokens_used", models.BigIntegerField(default=0)),
                ("total_exports", models.IntegerField(default=0)),
                (
                    "favorite_style",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("last_7_days_activity", models.IntegerField(default=0)),
                ("last_30_days_activity", models.IntegerField(default=0)),
                ("images_storage_mb", models.FloatField(default=0)),
                ("videos_storage_mb", models.FloatField(default=0)),
                ("documents_storage_mb", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userstatistics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Statistics",
                "verbose_name_plural": "User Statistics",
                "db_table": "core_userstatistics",
            },
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=255)),
                ("user_message", models.TextField()),
                ("assistant_response", models.TextField()),
                ("context_used", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                ("provider_used", models.CharField(blank=True, max_length=50)),
                ("agents_used", models.JSONField(default=list)),
                ("agent_results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Conversation",
                "verbose_name_plural": "Chat Conversations",
                "db_table": "chat_conversations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="chat_conver_user_id_394262_idx",
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="chat_conver_convers_a5bd2d_idx",
                    ),
                ],
            },
        ),
    ]
