# Generated by Django for System Completion Orchestrator

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for extensibility')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active/enabled')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('current_title', models.CharField(blank=True, max_length=200)),
                ('years_experience', models.IntegerField(default=0)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (0-2 years)'), ('junior', 'Junior (2-4 years)'), ('mid', 'Mid Level (4-7 years)'), ('senior', 'Senior (7-10 years)'), ('lead', 'Lead/Principal (10+ years)'), ('executive', 'Executive (C-Level)')], default='entry', max_length=20)),
                ('desired_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desired_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.JSONField(default=list, help_text="List of skills with proficiency levels: [{'name': 'Python', 'proficiency': 'Expert', 'years': 5}]")),
                ('certifications', models.JSONField(default=list, help_text="List of certifications: [{'name': 'AWS Certified', 'issued_by': 'Amazon', 'date': '2023-01-01'}]")),
                ('work_history', models.JSONField(default=list, help_text='Work experience entries with company, role, dates, responsibilities')),
                ('education', models.JSONField(default=list, help_text='Education entries with degree, institution, graduation year')),
                ('resume', models.FileField(blank=True, help_text='Primary resume file', null=True, upload_to='resumes/')),
                ('portfolio_url', models.URLField(blank=True)),
                ('cover_letters', models.JSONField(default=dict, help_text='Cover letter templates by industry/role type')),
                ('linkedin_url', models.URLField(blank=True)),
                ('indeed_profile', models.CharField(blank=True, max_length=200)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('job_preferences', models.JSONField(default=dict, help_text='Job search preferences including industries, role types, company sizes')),
                ('remote_preference', models.CharField(choices=[('remote', 'Remote Only'), ('hybrid', 'Hybrid (Remote + Office)'), ('onsite', 'On-site Only'), ('no_preference', 'No Preference')], default='no_preference', max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('profile_completeness', models.FloatField(default=0.0, help_text='Percentage of profile completion (0-100)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extended User Profile',
                'verbose_name_plural': 'Extended User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for extensibility')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active/enabled')),
                ('version_name', models.CharField(help_text="Name for this resume version (e.g., 'Software Engineer', 'Data Scientist')", max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary/default resume')),
                ('resume_file', models.FileField(upload_to='resumes/versions/')),
                ('resume_text', models.TextField(blank=True, help_text='Extracted text content of the resume')),
                ('target_industries', models.JSONField(default=list, help_text='Industries this resume is optimized for')),
                ('target_roles', models.JSONField(default=list, help_text='Role types this resume is optimized for')),
                ('keywords', models.JSONField(default=list, help_text='Keywords included in this resume version')),
                ('times_used', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Success rate when using this resume (0-100)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume Version',
                'verbose_name_plural': 'Resume Versions',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for extensibility')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active/enabled')),
                ('job_id', models.CharField(help_text='External job posting ID', max_length=200)),
                ('platform', models.CharField(help_text='Job platform (LinkedIn, Indeed, etc.)', max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('job_url', models.URLField(blank=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('application_method', models.CharField(choices=[('quick_apply', 'Quick Apply (AI-Generated)'), ('manual', 'Manual Application'), ('agent_automated', 'Agent Automated'), ('bulk_apply', 'Bulk Application')], default='quick_apply', max_length=20)),
                ('resume_version', models.CharField(blank=True, help_text='Which resume version was used', max_length=100)),
                ('cover_letter_used', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('viewed', 'Application Viewed'), ('screening', 'Initial Screening'), ('phone_interview', 'Phone Interview'), ('technical_interview', 'Technical Interview'), ('final_interview', 'Final Interview'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('employer_response', models.TextField(blank=True)),
                ('interview_dates', models.JSONField(default=list, help_text='List of interview dates and types')),
                ('notes', models.TextField(blank=True)),
                ('response_time_days', models.IntegerField(blank=True, help_text='Days from application to first response', null=True)),
                ('match_score', models.FloatField(default=0.0, help_text='AI-calculated fit score (0-100)')),
                ('salary_offered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_negotiated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Universal unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible metadata storage for extensibility')),
                ('version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this record is active/enabled')),
                ('embedding_vector', models.JSONField(help_text='Vector representation for similarity search')),
                ('content', models.TextField(help_text='Original content that was embedded')),
                ('content_type', models.CharField(choices=[('successful_application', 'Successful Application Pattern'), ('rejected_application', 'Rejected Application Analysis'), ('interview_notes', 'Interview Experience'), ('skill_validation', 'Skill Validation Data'), ('preference_update', 'User Preference Change'), ('success_pattern', 'General Success Pattern'), ('failure_pattern', 'Failure Pattern Analysis')], max_length=30)),
                ('confidence_score', models.FloatField(default=0.5, help_text='Confidence in this embedding (0-1)')),
                ('usage_count', models.IntegerField(default=0, help_text='How many times this embedding has been used')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('source_metadata', models.JSONField(default=dict, help_text='Additional source information')),
                ('source_application', models.ForeignKey(blank=True, help_text='Associated job application if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Embedding',
                'verbose_name_plural': 'User Embeddings',
            },
        ),
        migrations.AddIndex(
            model_name='userembedding',
            index=models.Index(fields=['user', 'content_type'], name='core_useren_user_id_e1f59e_idx'),
        ),
        migrations.AddIndex(
            model_name='userembedding',
            index=models.Index(fields=['confidence_score'], name='core_useren_confide_c46fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='userembedding',
            index=models.Index(fields=['-last_used'], name='core_useren_last_us_d68c54_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', '-applied_date'], name='core_jobapp_user_id_1a1e72_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status', '-applied_date'], name='core_jobapp_status_fbf8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['platform', '-applied_date'], name='core_jobapp_platfor_45a2b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumeversion',
            unique_together={('user', 'version_name')},
        ),
    ]