# Generated by Django 5.0.6 on 2025-09-17 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_system_completion_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnhancedUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_role",
                    models.CharField(
                        blank=True,
                        help_text="Primary professional role (e.g., CEO, Software Engineer, PhD Student)",
                        max_length=200,
                    ),
                ),
                (
                    "secondary_roles",
                    models.JSONField(
                        default=list, help_text="Additional roles and responsibilities"
                    ),
                ),
                (
                    "long_term_goals",
                    models.JSONField(
                        default=list,
                        help_text="Major life/career goals with target dates",
                    ),
                ),
                (
                    "current_projects",
                    models.JSONField(
                        default=list,
                        help_text="Active projects with priority levels and deadlines",
                    ),
                ),
                (
                    "quarterly_objectives",
                    models.JSONField(default=dict, help_text="OKRs or quarterly goals"),
                ),
                (
                    "communication_style",
                    models.CharField(
                        choices=[
                            ("concise", "Concise - Brief and to the point"),
                            ("detailed", "Detailed - Comprehensive information"),
                            ("balanced", "Balanced - Mix based on context"),
                            ("visual", "Visual - Prefer charts and diagrams"),
                            ("narrative", "Narrative - Story-based explanations"),
                        ],
                        default="balanced",
                        max_length=50,
                    ),
                ),
                (
                    "preferred_channels",
                    models.JSONField(
                        default=dict,
                        help_text="Preferred communication channels by context (e.g., {urgent: 'phone', updates: 'email'})",
                    ),
                ),
                (
                    "optimal_meeting_times",
                    models.JSONField(
                        default=list,
                        help_text="Best times for meetings/calls (e.g., ['9-11am PST', '2-4pm PST'])",
                    ),
                ),
                (
                    "decision_framework",
                    models.CharField(
                        choices=[
                            (
                                "data_driven",
                                "Data-Driven - Metrics and analytics focused",
                            ),
                            ("intuitive", "Intuitive - Gut feeling and experience"),
                            ("collaborative", "Collaborative - Team consensus"),
                            ("analytical", "Analytical - Pros/cons analysis"),
                            ("rapid", "Rapid - Quick decisions, iterate later"),
                        ],
                        default="analytical",
                        max_length=50,
                    ),
                ),
                (
                    "delegation_preferences",
                    models.JSONField(
                        default=dict, help_text="What to delegate vs handle personally"
                    ),
                ),
                (
                    "work_schedule",
                    models.JSONField(
                        default=dict, help_text="Typical work hours by day of week"
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(default="America/Los_Angeles", max_length=50),
                ),
                (
                    "morning_routine",
                    models.TextField(
                        blank=True, help_text="Morning routine for optimal productivity"
                    ),
                ),
                (
                    "energy_patterns",
                    models.JSONField(
                        default=dict,
                        help_text="Energy levels throughout the day (e.g., {morning: 'high', afternoon: 'medium'})",
                    ),
                ),
                (
                    "dietary_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Dietary restrictions, allergies, preferences",
                    ),
                ),
                (
                    "travel_preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Travel hubs, airline preferences, hotel chains, etc.",
                    ),
                ),
                (
                    "personal_values",
                    models.JSONField(
                        default=list,
                        help_text="Core personal values that guide decisions",
                    ),
                ),
                (
                    "stress_indicators",
                    models.JSONField(
                        default=list,
                        help_text="Signs of stress and preferred interventions",
                    ),
                ),
                (
                    "core_competencies",
                    models.JSONField(
                        default=dict, help_text="Skills with proficiency levels (1-10)"
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Visual - Images, diagrams, videos"),
                            ("auditory", "Auditory - Lectures, discussions"),
                            ("reading", "Reading/Writing - Text-based"),
                            ("kinesthetic", "Kinesthetic - Hands-on practice"),
                            ("mixed", "Mixed - Combination of styles"),
                        ],
                        default="mixed",
                        max_length=50,
                    ),
                ),
                (
                    "current_learning_goals",
                    models.JSONField(
                        default=list, help_text="Skills or topics currently learning"
                    ),
                ),
                (
                    "knowledge_gaps",
                    models.JSONField(
                        default=list, help_text="Identified areas for improvement"
                    ),
                ),
                (
                    "preferred_learning_resources",
                    models.JSONField(
                        default=dict,
                        help_text="Favorite learning platforms, authors, courses",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        default=list,
                        help_text="Professional certifications with expiry dates",
                    ),
                ),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("public", "Public - Share with all agents"),
                            ("professional", "Professional - Work-related only"),
                            ("personal", "Personal - Close assistants only"),
                            ("private", "Private - Encrypted, user only"),
                        ],
                        default="professional",
                        max_length=20,
                    ),
                ),
                (
                    "sensitive_topics",
                    models.JSONField(
                        default=list, help_text="Topics to handle with extra care"
                    ),
                ),
                (
                    "data_retention_days",
                    models.IntegerField(
                        default=90,
                        help_text="How long to retain interaction history",
                        validators=[
                            django.core.validators.MinValueValidator(7),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                (
                    "update_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily - High-frequency updates"),
                            ("weekly", "Weekly - Regular check-ins"),
                            ("biweekly", "Bi-weekly - Every two weeks"),
                            ("monthly", "Monthly - Monthly review"),
                            ("quarterly", "Quarterly - Seasonal updates"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "last_profile_review",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Last time profile was reviewed/updated",
                    ),
                ),
                (
                    "stable_attributes",
                    models.JSONField(
                        default=dict,
                        help_text="Rarely changing attributes (personality, core values)",
                    ),
                ),
                (
                    "dynamic_attributes",
                    models.JSONField(
                        default=dict,
                        help_text="Frequently changing attributes (current mood, energy)",
                    ),
                ),
                (
                    "profile_completeness",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("interaction_count", models.IntegerField(default=0)),
                (
                    "memory_retrieval_stats",
                    models.JSONField(
                        default=dict,
                        help_text="Statistics on which profile fields are most accessed",
                    ),
                ),
                (
                    "ai_insights",
                    models.JSONField(
                        default=dict,
                        help_text="AI-generated insights about user patterns",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Enhanced User Profile",
                "verbose_name_plural": "Enhanced User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserMemoryContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("decision", "Decision Made"),
                            ("preference", "Preference Stated"),
                            ("feedback", "Feedback Given"),
                            ("instruction", "Instruction Provided"),
                            ("context", "Context Shared"),
                            ("goal", "Goal Mentioned"),
                            ("constraint", "Constraint Identified"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("related_project", models.CharField(blank=True, max_length=200)),
                ("related_goal", models.CharField(blank=True, max_length=200)),
                (
                    "importance",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                (
                    "context_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context like mood, energy level, time of day",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this memory becomes less relevant",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-importance", "-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="core_jobapp_user_id_42479b_idx",
            old_name="core_jobapp_user_id_1a1e72_idx",
        ),
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="core_jobapp_status_be6268_idx",
            old_name="core_jobapp_status_fbf8c7_idx",
        ),
        migrations.RenameIndex(
            model_name="jobapplication",
            new_name="core_jobapp_platfor_1c039f_idx",
            old_name="core_jobapp_platfor_45a2b8_idx",
        ),
        migrations.RenameIndex(
            model_name="userembedding",
            new_name="core_userem_user_id_011313_idx",
            old_name="core_useren_user_id_e1f59e_idx",
        ),
        migrations.RenameIndex(
            model_name="userembedding",
            new_name="core_userem_confide_3af62d_idx",
            old_name="core_useren_confide_c46fa6_idx",
        ),
        migrations.RenameIndex(
            model_name="userembedding",
            new_name="core_userem_last_us_9eea5e_idx",
            old_name="core_useren_last_us_d68c54_idx",
        ),
        migrations.AddField(
            model_name="enhanceduserprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enhanced_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usermemorycontext",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.enhanceduserprofile",
            ),
        ),
        migrations.AddField(
            model_name="usermemorycontext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory_contexts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usermemorycontext",
            index=models.Index(
                fields=["user", "memory_type", "-created_at"],
                name="core_userme_user_id_64cbd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usermemorycontext",
            index=models.Index(
                fields=["user", "-importance"], name="core_userme_user_id_8cc6ec_idx"
            ),
        ),
    ]
