# Generated by Django 5.0.6 on 2025-09-17 22:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_usermemorycontext_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentExecutionMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=100)),
                ("agent_id", models.CharField(blank=True, max_length=100, null=True)),
                ("task_type", models.CharField(db_index=True, max_length=50)),
                ("task_description", models.TextField()),
                ("original_prompt", models.TextField()),
                (
                    "success_score",
                    models.FloatField(
                        help_text="Success score from 0.0 (failed) to 1.0 (perfect)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("execution_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "outcome_description",
                    models.TextField(
                        help_text="Human-readable description of what the agent accomplished"
                    ),
                ),
                (
                    "outcome_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Quantifiable metrics like views, clicks, conversions, etc.",
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User's 1-5 star rating of the result",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, null=True)),
                (
                    "page_context",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "conversation_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("execution_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-execution_date"],
            },
        ),
        migrations.CreateModel(
            name="AgentPerformanceStats",
            fields=[
                (
                    "agent_name",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("total_executions", models.IntegerField(default=0)),
                ("avg_success_rate", models.FloatField(default=0.0)),
                ("avg_execution_time", models.FloatField(default=0.0)),
                (
                    "task_type_stats",
                    models.JSONField(
                        default=dict, help_text="Performance breakdown by task type"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "highest_rated_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.agentexecutionmemory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(db_index=True, max_length=50)),
                ("recommended_agent", models.CharField(max_length=100)),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("avg_success_rate", models.FloatField()),
                ("total_executions", models.IntegerField()),
                ("best_outcome_description", models.TextField()),
                ("best_outcome_metrics", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.AddIndex(
            model_name="agentexecutionmemory",
            index=models.Index(
                fields=["user", "task_type", "-success_score"],
                name="core_agente_user_id_445889_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecutionmemory",
            index=models.Index(
                fields=["user", "agent_name", "-execution_date"],
                name="core_agente_user_id_4b6607_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecutionmemory",
            index=models.Index(
                fields=["task_type", "-success_score"],
                name="core_agente_task_ty_c45845_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentexecutionmemory",
            index=models.Index(
                fields=["-execution_date"], name="core_agente_executi_010776_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["user", "task_type", "-confidence_score"],
                name="core_agentr_user_id_f6cebf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentrecommendation",
            unique_together={("user", "task_type", "recommended_agent")},
        ),
    ]
