# Generated by Django 5.0.6 on 2025-09-23 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_application_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLearningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("agent_type", models.CharField(max_length=50)),
                ("total_errors_encountered", models.IntegerField(default=0)),
                ("total_errors_fixed", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("average_resolution_time", models.FloatField(default=0.0)),
                ("new_patterns_learned", models.IntegerField(default=0)),
                ("patterns_improved", models.IntegerField(default=0)),
                ("knowledge_base_size_before", models.IntegerField(default=0)),
                ("knowledge_base_size_after", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("session_duration_minutes", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Agent Learning Session",
                "verbose_name_plural": "Agent Learning Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insight_type", models.CharField(max_length=50)),
                ("insight_category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("code_example", models.TextField(blank=True)),
                ("solution_approach", models.TextField()),
                ("supporting_instances", models.IntegerField(default=1)),
                ("confidence_level", models.FloatField(default=0.5)),
                ("applicability_scope", models.JSONField(default=dict)),
                ("times_applied", models.IntegerField(default=0)),
                ("success_when_applied", models.IntegerField(default=0)),
                ("impact_score", models.FloatField(default=0.0)),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_validated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Learning Insight",
                "verbose_name_plural": "Learning Insights",
                "ordering": ["-confidence_level", "-impact_score"],
            },
        ),
        migrations.CreateModel(
            name="ErrorPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_type", models.CharField(max_length=100)),
                ("error_message_pattern", models.TextField()),
                ("file_extension", models.CharField(default=".py", max_length=10)),
                ("project_type", models.CharField(blank=True, max_length=50)),
                ("solution_strategy", models.CharField(max_length=50)),
                ("solution_template", models.TextField()),
                ("confidence_score", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "Error Pattern",
                "verbose_name_plural": "Error Patterns",
                "ordering": ["-confidence_score", "-success_rate"],
                "unique_together": {
                    ("error_type", "error_message_pattern", "file_extension")
                },
            },
        ),
        migrations.CreateModel(
            name="ErrorInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.TextField()),
                ("error_type", models.CharField(max_length=100)),
                ("error_message", models.TextField()),
                ("error_line_number", models.IntegerField(blank=True, null=True)),
                ("error_context", models.TextField(blank=True)),
                ("original_code", models.TextField()),
                ("solution_applied", models.TextField()),
                ("fixed_code", models.TextField()),
                ("fix_method", models.CharField(max_length=50)),
                ("was_successful", models.BooleanField(default=False)),
                ("attempts_count", models.IntegerField(default=1)),
                ("resolution_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pattern_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.errorpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Error Instance",
                "verbose_name_plural": "Error Instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_agent", models.CharField(max_length=50)),
                ("assisting_agent", models.CharField(max_length=50)),
                ("collaboration_type", models.CharField(max_length=50)),
                ("problem_domain", models.CharField(max_length=100)),
                ("problem_complexity", models.CharField(max_length=20)),
                ("collaboration_successful", models.BooleanField(default=False)),
                ("primary_agent_contribution", models.TextField(blank=True)),
                ("assisting_agent_contribution", models.TextField(blank=True)),
                ("final_solution", models.TextField()),
                ("knowledge_transferred", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pattern_reinforced",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.errorpattern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Collaboration",
                "verbose_name_plural": "Agent Collaborations",
                "ordering": ["-created_at"],
            },
        ),
    ]
