# Generated by Django 5.0.6 on 2025-09-23 22:24

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_agentlearningsession_learninginsight_errorpattern_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("name", models.CharField(help_text="Project name", max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        help_text="Type of project (e.g., ecommerce, content_factory)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Project description"),
                ),
                (
                    "agents_used",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="List of agent names that worked on this project",
                        size=None,
                    ),
                ),
                (
                    "advisors_consulted",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="List of advisors consulted for this project",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="generating",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_generated_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Name of the file", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path from project root", max_length=500
                    ),
                ),
                ("content", models.TextField(help_text="The actual code content")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("sql", "SQL"),
                            ("json", "JSON"),
                            ("yaml", "YAML"),
                            ("other", "Other"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                (
                    "agent_creator",
                    models.CharField(
                        help_text="Name of the agent that created this code",
                        max_length=100,
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the task this code was created for",
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the latest version of this file",
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("untested", "Untested"),
                            ("success", "Executed Successfully"),
                            ("error", "Execution Error"),
                            ("timeout", "Execution Timeout"),
                            ("fixed", "Auto-Fixed and Working"),
                        ],
                        default="untested",
                        max_length=50,
                    ),
                ),
                (
                    "execution_output",
                    models.TextField(
                        blank=True,
                        help_text="Output from code execution or error messages",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_files",
                        to="core.generatedproject",
                    ),
                ),
            ],
            options={
                "db_table": "core_generated_code",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "filename"],
                        name="core_genera_project_6e75ed_idx",
                    ),
                    models.Index(
                        fields=["project", "is_latest"],
                        name="core_genera_project_68321d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_genera_user_id_0fa7e2_idx",
                    ),
                ],
            },
        ),
    ]
