# Generated by Django 5.0.6 on 2025-09-28 23:38
# Session 416: Fixed duplicate Revenue model creation - model already exists in 0006
# This migration is now a no-op since Revenue was already created in 0006
# But we keep the AddIndex operations in migration state so 0012 can remove them

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_embedding_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Session 416: Revenue model already created in migration 0006
        # Use SeparateDatabaseAndState to add indexes to migration state without touching DB
        # (indexes may or may not exist in DB depending on which migration ran first)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='revenue',
                    index=models.Index(fields=['user', 'status'], name='core_revenu_user_id_41fd3f_idx'),
                ),
                migrations.AddIndex(
                    model_name='revenue',
                    index=models.Index(fields=['user', 'created_at'], name='core_revenu_user_id_8c8fa6_idx'),
                ),
                migrations.AddIndex(
                    model_name='revenue',
                    index=models.Index(fields=['status', 'amount'], name='core_revenu_status_3b825d_idx'),
                ),
            ],
            database_operations=[
                # No-op for database - indexes may already exist from 0006
            ],
        ),
    ]
