# Generated by Django 5.0.6 on 2025-09-30 00:06
# Session 416: Fixed RemoveIndex operations to use SeparateDatabaseAndState
# Session 425: Fixed RemoveField operations - fields may not exist in migration state
# Session 452: Fixed AddField/AlterField operations - fields already exist from migration 0006
# The Revenue model was already fully created in 0006, so all field operations here
# are state-only to sync migration state with actual database structure.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_add_revenue_model"),
    ]

    operations = [
        # Session 416: Use SeparateDatabaseAndState to remove indexes from state
        # without trying to drop them from DB (they may not exist)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="revenue",
                    name="core_revenu_user_id_41fd3f_idx",
                ),
                migrations.RemoveIndex(
                    model_name="revenue",
                    name="core_revenu_user_id_8c8fa6_idx",
                ),
                migrations.RemoveIndex(
                    model_name="revenue",
                    name="core_revenu_status_3b825d_idx",
                ),
            ],
            database_operations=[
                # No-op for database - indexes may not exist
            ],
        ),
        # Session 452: All AddField/AlterField operations are state-only because
        # Revenue model with all these fields was already created in migration 0006.
        # These operations sync migration state without touching the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="revenue",
                    name="agent",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agent",
                    ),
                ),
                migrations.AddField(
                    model_name="revenue",
                    name="currency",
                    field=models.CharField(default="USD", max_length=3),
                ),
                migrations.AddField(
                    model_name="revenue",
                    name="earned_at",
                    field=models.DateTimeField(null=True),
                ),
                migrations.AddField(
                    model_name="revenue",
                    name="paid_at",
                    field=models.DateTimeField(null=True),
                ),
                migrations.AddField(
                    model_name="revenue",
                    name="source_id",
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name="revenue",
                    name="source_type",
                    field=models.CharField(default="sports", max_length=50),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name="revenue",
                    name="amount",
                    field=models.DecimalField(decimal_places=2, max_digits=12),
                ),
                migrations.AlterField(
                    model_name="revenue",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
                migrations.AlterField(
                    model_name="revenue",
                    name="description",
                    field=models.TextField(),
                ),
                migrations.AlterField(
                    model_name="revenue",
                    name="metadata",
                    field=models.JSONField(default=dict),
                ),
                migrations.AlterField(
                    model_name="revenue",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                migrations.AlterModelTable(
                    name="revenue",
                    table=None,
                ),
            ],
            database_operations=[
                # No-op for database - columns already exist from migration 0006
            ],
        ),
    ]
