# Generated by Django 5.0.6 on 2025-09-30 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_update_user_agent_learning_collaborative"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=100)),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                ("page_views", models.IntegerField(default=0)),
                (
                    "time_on_page",
                    models.IntegerField(default=0, help_text="Time in seconds"),
                ),
                ("opportunities_shown", models.IntegerField(default=0)),
                ("opportunities_clicked", models.IntegerField(default=0)),
                ("opportunities_applied", models.IntegerField(default=0)),
                ("ctr", models.FloatField(default=0.0, help_text="Click-through rate")),
                (
                    "application_rate",
                    models.FloatField(
                        default=0.0, help_text="Application rate from clicks"
                    ),
                ),
                ("personalized_results", models.BooleanField(default=False)),
                ("personalization_boost_applied", models.FloatField(default=0.0)),
                (
                    "ab_test_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("control", "Control (No Personalization)"),
                            ("treatment", "Treatment (With Personalization)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "potential_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("opportunity_id", models.CharField(max_length=200)),
                ("opportunity_title", models.CharField(max_length=500)),
                ("opportunity_platform", models.CharField(max_length=100)),
                (
                    "opportunity_salary",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("click", "Clicked"),
                            ("apply", "Applied"),
                            ("reject", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("was_personalized", models.BooleanField(default=False)),
                ("personalization_boost", models.FloatField(default=0.0)),
                ("match_score", models.IntegerField(default=0)),
                (
                    "interaction_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "time_to_interact",
                    models.IntegerField(
                        default=0, help_text="Seconds from view to interaction"
                    ),
                ),
                ("resulted_in_application", models.BooleanField(default=False)),
                ("application_success", models.BooleanField(blank=True, null=True)),
                (
                    "engagement_session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="core.engagementmetrics",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-interaction_timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="engagementmetrics",
            index=models.Index(
                fields=["user", "-created_at"], name="core_engage_user_id_a5f36c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementmetrics",
            index=models.Index(
                fields=["ab_test_group", "-created_at"],
                name="core_engage_ab_test_69d784_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="engagementmetrics",
            index=models.Index(
                fields=["personalized_results", "-created_at"],
                name="core_engage_persona_7bedfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityinteraction",
            index=models.Index(
                fields=["user", "-interaction_timestamp"],
                name="core_opport_user_id_50db43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityinteraction",
            index=models.Index(
                fields=["opportunity_platform", "-interaction_timestamp"],
                name="core_opport_opportu_e64a5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunityinteraction",
            index=models.Index(
                fields=["interaction_type", "-interaction_timestamp"],
                name="core_opport_interac_cc1083_idx",
            ),
        ),
    ]
