# Generated by Django - Sports Betting Learning Integration (Session 37-A)

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_engagementmetrics_opportunityinteraction_and_more'),
    ]

    operations = [
        # Add created_at and submitted_at fields to Application
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

        # Extend UserAgentLearning.learning_domain with sports betting domains
        migrations.AlterField(
            model_name='useragentlearning',
            name='learning_domain',
            field=models.CharField(
                choices=[
                    ('opportunity_matching', 'Job/Opportunity Matching'),
                    ('content_creation', 'Content Creation Style'),
                    ('communication', 'Communication Preferences'),
                    ('decision_making', 'Decision Making Patterns'),
                    ('skill_development', 'Skill Development Path'),
                    ('revenue_optimization', 'Revenue Optimization'),
                    ('platform_preferences', 'Platform Preferences'),
                    ('salary_preferences', 'Salary Range Preferences'),
                    ('skill_preferences', 'Skill Type Preferences'),
                    ('company_size_preferences', 'Company Size Preferences'),
                    ('remote_preferences', 'Remote Work Preferences'),
                    ('timing_patterns', 'Optimal Timing Patterns'),
                    ('success_factors', 'Success Factor Analysis'),
                    # NEW: Sports Betting Learning Domains (Session 37-A Integration)
                    ('sports_betting_nfl', 'Sports Betting - NFL'),
                    ('sports_betting_nba', 'Sports Betting - NBA'),
                    ('sports_betting_mlb', 'Sports Betting - MLB'),
                    ('sports_betting_nhl', 'Sports Betting - NHL'),
                    ('betting_risk_management', 'Betting Risk Management'),
                    ('kelly_criterion_optimization', 'Kelly Criterion Optimization'),
                    ('general', 'General Learning'),
                ],
                default='general',
                help_text='What domain is this learning about',
                max_length=100
            ),
        ),
    ]
