# Generated by Django 5.0.6 on 2025-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_sports_betting_learning_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="ai_capabilities_match",
            field=models.JSONField(
                default=list, help_text="What AI brings to partnership (optional)"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="ai_contribution_potential",
            field=models.IntegerField(
                default=0,
                help_text="0-100: How much can AI contribute? (0 = no AI help possible)",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="collaboration_feasibility",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_applicable", "Not a partnership opportunity"),
                    ("low", "Minimal AI contribution possible"),
                    ("medium", "Moderate AI assistance available"),
                    ("high", "Strong partnership potential"),
                    ("ideal", "Perfect for human-AI collaboration"),
                ],
                default="not_applicable",
                help_text="Partnership assessment (optional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="estimated_partnership_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hours with AI partnership (optional)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="estimated_solo_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hours if user did alone (optional)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="partnership_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("solo", "Traditional - User Only"),
                    ("ai_assisted", "AI-Assisted - User Leads"),
                    ("collaborative", "True Partnership - Equal"),
                    ("ai_led", "AI-Led - User Validates"),
                ],
                default="solo",
                help_text="How human + AI will work together (optional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="partnership_workflow",
            field=models.JSONField(
                blank=True,
                help_text="Step-by-step collaboration plan (optional)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="required_human_skills",
            field=models.JSONField(
                default=list, help_text="What human brings to partnership (optional)"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="time_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Efficiency gain (e.g., 3.5x faster) (optional)",
                max_digits=4,
                null=True,
            ),
        ),
    ]
