# Generated by Django 5.0.6 on 2025-09-30 19:39

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_add_advisor_consultation_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnershipProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("content_creation", "Content Creation"),
                            ("data_analysis", "Data Analysis"),
                            ("research", "Research Project"),
                            ("development", "Software Development"),
                            ("design", "Design Work"),
                            ("consulting", "Consulting/Advisory"),
                            ("writing", "Writing/Copywriting"),
                            ("marketing", "Marketing Content"),
                            ("technical_writing", "Technical Documentation"),
                            ("other", "Other Partnership"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What are we building together?"),
                ),
                (
                    "workflow_steps",
                    models.JSONField(
                        default=list,
                        help_text="List of steps in collaboration: [{step, ai_role, human_role, status}]",
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                (
                    "ai_contributions",
                    models.JSONField(
                        default=list,
                        help_text="What AI did: [{agent, task, time_saved, output, timestamp}]",
                    ),
                ),
                (
                    "human_contributions",
                    models.JSONField(
                        default=list,
                        help_text="What human did: [{task, time_spent, value_added, timestamp}]",
                    ),
                ),
                (
                    "ai_time_equivalent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Hours of work AI did (if human did it)",
                        max_digits=8,
                    ),
                ),
                (
                    "human_time_actual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual hours human spent",
                        max_digits=8,
                    ),
                ),
                (
                    "ai_contribution_percent",
                    models.IntegerField(
                        default=0, help_text="AI's % of total work (0-100)"
                    ),
                ),
                (
                    "human_contribution_percent",
                    models.IntegerField(
                        default=100, help_text="Human's % of total work (0-100)"
                    ),
                ),
                (
                    "deliverable_description",
                    models.TextField(
                        blank=True, help_text="Description of what was delivered"
                    ),
                ),
                (
                    "deliverable_url",
                    models.URLField(
                        blank=True, help_text="Link to deliverable if applicable"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        default=0, help_text="0-100: Quality of output (self-assessed)"
                    ),
                ),
                (
                    "client_satisfaction",
                    models.IntegerField(
                        blank=True,
                        help_text="0-100: Client rating if available",
                        null=True,
                    ),
                ),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total contract value",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Actual payment received",
                        max_digits=10,
                    ),
                ),
                (
                    "ai_value_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="$ value AI contributed (based on time saved)",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning Partnership"),
                            ("in_progress", "Working Together"),
                            ("review", "Human Review/Polish"),
                            ("submitted", "Delivered to Client"),
                            ("completed", "Completed & Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "what_worked",
                    models.TextField(
                        blank=True, help_text="What worked well in this partnership?"
                    ),
                ),
                (
                    "what_to_improve",
                    models.TextField(
                        blank=True, help_text="What could be improved next time?"
                    ),
                ),
                (
                    "lessons_learned",
                    models.JSONField(
                        default=dict, help_text="Key lessons for future partnerships"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnership_projects",
                        to="core.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partnership_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CollaborativeContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("blog_post", "Blog Post"),
                            ("article", "Article"),
                            ("social_media", "Social Media Post"),
                            ("email", "Email"),
                            ("documentation", "Documentation"),
                            ("marketing_copy", "Marketing Copy"),
                            ("technical_writing", "Technical Writing"),
                            ("product_description", "Product Description"),
                            ("landing_page", "Landing Page Copy"),
                            ("video_script", "Video Script"),
                            ("other", "Other Content"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "ai_first_draft",
                    models.TextField(help_text="What AI generated initially"),
                ),
                (
                    "ai_agents_used",
                    models.JSONField(
                        default=list,
                        help_text="Which agents contributed: ['ContentGenerator', 'SEOOptimizer']",
                    ),
                ),
                (
                    "ai_generation_time",
                    models.DurationField(
                        default=datetime.timedelta(0), help_text="How long AI took"
                    ),
                ),
                (
                    "human_edits",
                    models.JSONField(
                        default=list,
                        help_text="What human changed: [{timestamp, section, change, reason}]",
                    ),
                ),
                (
                    "human_additions",
                    models.JSONField(
                        default=list,
                        help_text="What human added: [{section, content, value}]",
                    ),
                ),
                (
                    "human_time_spent",
                    models.DurationField(
                        default=datetime.timedelta(0),
                        help_text="Total time human spent",
                    ),
                ),
                (
                    "final_content",
                    models.TextField(blank=True, help_text="The delivered version"),
                ),
                ("word_count", models.IntegerField(default=0)),
                (
                    "seo_score",
                    models.IntegerField(
                        blank=True, help_text="0-100 SEO quality score", null=True
                    ),
                ),
                (
                    "readability_score",
                    models.IntegerField(
                        blank=True, help_text="0-100 readability score", null=True
                    ),
                ),
                (
                    "ai_generated_words",
                    models.IntegerField(default=0, help_text="Words in AI draft"),
                ),
                (
                    "human_written_words",
                    models.IntegerField(default=0, help_text="Words human added"),
                ),
                (
                    "ai_contribution_percent",
                    models.IntegerField(
                        default=0, help_text="% of final content from AI"
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("client_feedback", models.TextField(blank=True)),
                (
                    "revision_count",
                    models.IntegerField(
                        default=0, help_text="Number of revision rounds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "AI Drafting"),
                            ("editing", "Human Editing"),
                            ("review", "Final Review"),
                            ("delivered", "Delivered"),
                            ("accepted", "Accepted by Client"),
                            ("revision", "Needs Revision"),
                        ],
                        default="drafting",
                        max_length=20,
                    ),
                ),
                (
                    "partnership_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_pieces",
                        to="core.partnershipproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Collaborative Content Pieces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="partnershipproject",
            index=models.Index(
                fields=["user", "status"], name="core_partne_user_id_11af3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partnershipproject",
            index=models.Index(fields=["status"], name="core_partne_status_1d0168_idx"),
        ),
        migrations.AddIndex(
            model_name="partnershipproject",
            index=models.Index(
                fields=["-started_at"], name="core_partne_started_b1908b_idx"
            ),
        ),
    ]
