# Generated by Django 5.0.6 on 2025-11-27 02:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_partnership_learning_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiderAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spider_name", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("items_collected", models.IntegerField(default=0)),
                ("unique_topics", models.IntegerField(default=0)),
                ("unique_sources", models.IntegerField(default=0)),
                ("avg_relevance_score", models.FloatField(default=0.0)),
                ("data_freshness_hours", models.FloatField(default=0.0)),
                ("execution_time_seconds", models.FloatField(default=0.0)),
                ("errors", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=1.0)),
                ("raw_data_size_kb", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Spider Analytics",
                "verbose_name_plural": "Spider Analytics",
                "ordering": ["-date", "spider_name"],
                "unique_together": {("spider_name", "date")},
            },
        ),
        migrations.CreateModel(
            name="TrendSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(db_index=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("mention_count", models.IntegerField(default=1)),
                ("source_count", models.IntegerField(default=1)),
                ("sources", models.JSONField(default=list)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("snapshot_date", models.DateField(db_index=True)),
                ("previous_score", models.FloatField(default=0.0)),
                ("score_change", models.FloatField(default=0.0)),
                ("is_emerging", models.BooleanField(default=False)),
                ("is_declining", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trend Snapshot",
                "verbose_name_plural": "Trend Snapshots",
                "ordering": ["-snapshot_date", "-score"],
                "unique_together": {("topic", "snapshot_date")},
            },
        ),
    ]
