# Generated by Django 5.0.6 on 2025-11-27 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_session_209_spider_analytics"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferenceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True, unique=True)),
                ("style_scores", models.JSONField(default=dict)),
                ("model_scores", models.JSONField(default=dict)),
                ("top_styles", models.JSONField(default=list)),
                ("top_models", models.JSONField(default=list)),
                ("total_signals", models.IntegerField(default=0)),
                ("total_generations", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preference Profile",
                "verbose_name_plural": "User Preference Profiles",
            },
        ),
        migrations.CreateModel(
            name="StyleEvolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("domain", models.CharField(default="image", max_length=50)),
                ("style_distribution", models.JSONField(default=dict)),
                ("top_styles", models.JSONField(default=list)),
                ("total_generations", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                ("satisfaction_rate", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Style Evolution",
                "verbose_name_plural": "Style Evolutions",
                "ordering": ["-date"],
                "unique_together": {("user_id", "date", "domain")},
            },
        ),
        migrations.CreateModel(
            name="StyleTrend",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("style_name", models.CharField(db_index=True, max_length=100)),
                ("date", models.DateField(db_index=True)),
                ("domain", models.CharField(default="image", max_length=50)),
                ("usage_count", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("download_count", models.IntegerField(default=0)),
                ("avg_satisfaction", models.FloatField(default=0.0)),
                ("previous_usage", models.IntegerField(default=0)),
                ("growth_rate", models.FloatField(default=0.0)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_declining", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Style Trend",
                "verbose_name_plural": "Style Trends",
                "ordering": ["-date", "-usage_count"],
                "unique_together": {("style_name", "date", "domain")},
            },
        ),
        migrations.CreateModel(
            name="UserBehaviorSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                (
                    "content_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("signal_type", models.CharField(db_index=True, max_length=50)),
                ("weight", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "User Behavior Signal",
                "verbose_name_plural": "User Behavior Signals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "signal_type"],
                        name="core_userbe_user_id_2f1541_idx",
                    ),
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="core_userbe_user_id_416383_idx",
                    ),
                ],
            },
        ),
    ]
