# Generated by Django 5.0.6 on 2025-11-27 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_session_210_implicit_learning"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("exposed", models.BooleanField(default=False)),
                ("exposed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "A/B Assignment",
                "verbose_name_plural": "A/B Assignments",
            },
        ),
        migrations.CreateModel(
            name="ABExperiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "experiment_type",
                    models.CharField(
                        choices=[
                            ("recommendation", "Recommendation Strategy"),
                            ("ui", "UI Variation"),
                            ("feature", "Feature Toggle"),
                            ("algorithm", "Algorithm Comparison"),
                        ],
                        default="recommendation",
                        max_length=50,
                    ),
                ),
                (
                    "domain",
                    models.CharField(default="style_recommendations", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("traffic_percentage", models.IntegerField(default=100)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "primary_metric",
                    models.CharField(default="conversion_rate", max_length=100),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "A/B Experiment",
                "verbose_name_plural": "A/B Experiments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABConversion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversion_type",
                    models.CharField(
                        choices=[
                            ("click", "Clicked Recommendation"),
                            ("apply", "Applied Style"),
                            ("download", "Downloaded Content"),
                            ("share", "Shared Content"),
                            ("purchase", "Made Purchase"),
                            ("signup", "Signed Up"),
                            ("engagement", "Engaged with Feature"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField(default=1.0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("converted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="core.abassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "A/B Conversion",
                "verbose_name_plural": "A/B Conversions",
                "ordering": ["-converted_at"],
            },
        ),
        migrations.AddField(
            model_name="abassignment",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.abexperiment",
            ),
        ),
        migrations.CreateModel(
            name="ABVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_control", models.BooleanField(default=False)),
                ("weight", models.IntegerField(default=50)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.abexperiment",
                    ),
                ),
            ],
            options={
                "verbose_name": "A/B Variant",
                "verbose_name_plural": "A/B Variants",
                "ordering": ["is_control", "name"],
            },
        ),
        migrations.CreateModel(
            name="ABExperimentResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("variant_stats", models.JSONField(default=dict)),
                ("is_significant", models.BooleanField(default=False)),
                ("confidence_level", models.FloatField(default=0.0)),
                ("p_value", models.FloatField(blank=True, null=True)),
                ("lift_percentage", models.FloatField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("sample_size", models.IntegerField(default=0)),
                (
                    "experiment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.abexperiment",
                    ),
                ),
                (
                    "winning_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_experiments",
                        to="core.abvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "A/B Experiment Result",
                "verbose_name_plural": "A/B Experiment Results",
            },
        ),
        migrations.AddField(
            model_name="abassignment",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="core.abvariant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="abassignment",
            unique_together={("experiment", "session_id"), ("experiment", "user_id")},
        ),
    ]
