# Generated by Django 5.0.6 on 2025-11-27 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_session_211_ab_testing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("content_type", models.CharField(default="custom", max_length=50)),
                ("category", models.CharField(default="custom", max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("use_count", models.IntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_scheduled", models.BooleanField(default=False)),
                ("schedule_cron", models.CharField(blank=True, max_length=100)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Workflow",
                "verbose_name_plural": "Custom Workflows",
                "ordering": ["-updated_at"],
                "unique_together": {("created_by", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cron_expression", models.CharField(max_length=100)),
                ("timezone", models.CharField(default="America/Denver", max_length=50)),
                ("default_topic", models.CharField(max_length=500)),
                ("default_parameters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_status", models.CharField(blank=True, max_length=20)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="core.customworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Workflow",
                "verbose_name_plural": "Scheduled Workflows",
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("workflow_type", models.CharField(max_length=50)),
                ("workflow_name", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=500)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("step_results", models.JSONField(default=list)),
                ("error_message", models.TextField(blank=True)),
                ("project_id", models.UUIDField(blank=True, null=True)),
                ("image_ids", models.JSONField(default=list)),
                ("video_ids", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "custom_workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="core.customworkflow",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="core_workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomWorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "agent",
                    models.CharField(
                        choices=[
                            ("web_search", "Web Search"),
                            ("coleadership_agent", "Executive Team Review"),
                            ("image_generation_agent", "Image Generation"),
                            ("video_generation_agent", "Video Generation"),
                            ("audio_generation_agent", "Audio Generation"),
                            ("image_selection", "Image Selection"),
                            ("image_variation_agent", "Image Variations"),
                            ("create_project_from_research", "Create Project"),
                        ],
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("is_required", models.BooleanField(default=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.customworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Workflow Step",
                "verbose_name_plural": "Custom Workflow Steps",
                "ordering": ["workflow", "order"],
                "unique_together": {("workflow", "order")},
            },
        ),
    ]
