# Generated by Django 5.0.6 on 2025-11-27 03:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_session_212_custom_workflows"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentPerformanceMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(max_length=200, unique=True)),
                ("total_executions", models.IntegerField(default=0)),
                ("successful_executions", models.IntegerField(default=0)),
                ("failed_executions", models.IntegerField(default=0)),
                ("total_collaborations", models.IntegerField(default=0)),
                ("successful_collaborations", models.IntegerField(default=0)),
                ("delegations_made", models.IntegerField(default=0)),
                ("delegations_received", models.IntegerField(default=0)),
                ("consultations_given", models.IntegerField(default=0)),
                ("consultations_received", models.IntegerField(default=0)),
                ("avg_response_time_ms", models.FloatField(default=0.0)),
                ("quality_score", models.FloatField(default=0.0)),
                ("knowledge_contributions", models.IntegerField(default=0)),
                ("knowledge_consumed", models.IntegerField(default=0)),
                ("specialization_scores", models.JSONField(default=dict)),
                ("last_execution", models.DateTimeField(blank=True, null=True)),
                ("last_collaboration", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Performance Metric",
                "verbose_name_plural": "Agent Performance Metrics",
                "ordering": ["-quality_score", "-total_executions"],
            },
        ),
        migrations.CreateModel(
            name="InterAgentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sender_agent", models.CharField(max_length=200)),
                ("receiver_agent", models.CharField(max_length=200)),
                ("message_type", models.CharField(max_length=50)),
                ("content", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                ("priority", models.IntegerField(default=5)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("response_to", models.UUIDField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Inter-Agent Message",
                "verbose_name_plural": "Inter-Agent Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_agent", models.CharField(max_length=200)),
                ("knowledge_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("knowledge_content", models.JSONField(default=dict)),
                ("domain", models.CharField(max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("applied_count", models.IntegerField(default=0)),
                ("effectiveness_score", models.FloatField(default=0.0)),
                ("learned_by_agents", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shared Knowledge",
                "verbose_name_plural": "Shared Knowledge",
                "ordering": ["-effectiveness_score", "-applied_count"],
            },
        ),
        migrations.CreateModel(
            name="CollaborationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requester_agent", models.CharField(max_length=200)),
                ("collaboration_type", models.CharField(max_length=50)),
                ("task_description", models.TextField()),
                ("input_data", models.JSONField(default=dict)),
                ("participating_agents", models.JSONField(default=list)),
                ("status", models.CharField(default="pending", max_length=50)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("quality_score", models.FloatField(default=0.0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.FloatField(default=0.0)),
                ("workflow_execution_id", models.UUIDField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaboration Session",
                "verbose_name_plural": "Collaboration Sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
