# Generated by Django 5.0.6 on 2025-11-27 06:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_session_214_agent_collaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishedWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("image_generation", "Image Generation"),
                            ("video_creation", "Video Creation"),
                            ("audio_production", "Audio Production"),
                            ("brand_identity", "Brand Identity"),
                            ("social_media", "Social Media"),
                            ("ecommerce", "E-Commerce"),
                            ("research", "Research & Analysis"),
                            ("productivity", "Productivity"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("tags", models.JSONField(default=list)),
                ("preview_image", models.URLField(blank=True)),
                ("preview_images", models.JSONField(default=list)),
                ("download_count", models.IntegerField(default=0)),
                ("view_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("review_count", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication",
                        to="core.customworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Published Workflow",
                "verbose_name_plural": "Published Workflows",
                "ordering": ["-is_featured", "-download_count", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowInstallation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("times_executed", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "installed_workflow",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installation_source",
                        to="core.customworkflow",
                    ),
                ),
                (
                    "published_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="core.publishedworkflow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Installation",
                "verbose_name_plural": "Workflow Installations",
                "unique_together": {("published_workflow", "user")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rating", models.IntegerField()),
                ("review_text", models.TextField(blank=True)),
                ("helpful_count", models.IntegerField(default=0)),
                ("not_helpful_count", models.IntegerField(default=0)),
                ("is_verified_purchase", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.publishedworkflow",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Review",
                "verbose_name_plural": "Workflow Reviews",
                "ordering": ["-helpful_count", "-created_at"],
                "unique_together": {("published_workflow", "user")},
            },
        ),
    ]
