# Generated by Django 5.0.6 on 2025-11-27 07:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_session_220_collaboration"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("cost_daily", "Daily Cost"),
                            ("cost_monthly", "Monthly Cost"),
                            ("api_errors", "API Errors"),
                            ("response_time", "Response Time"),
                            ("usage_count", "Usage Count"),
                            ("credits_remaining", "Credits Remaining"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("eq", "Equal To"),
                            ("gte", "Greater Than or Equal"),
                            ("lte", "Less Than or Equal"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(decimal_places=4, max_digits=15),
                ),
                ("notify_email", models.BooleanField(default=False)),
                ("notify_websocket", models.BooleanField(default=True)),
                ("cooldown_minutes", models.IntegerField(default=60)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Alert",
                "verbose_name_plural": "Analytics Alerts",
            },
        ),
        migrations.CreateModel(
            name="AnalyticsDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("layout", models.JSONField(default=dict)),
                ("widgets", models.JSONField(default=list)),
                (
                    "default_time_range",
                    models.CharField(
                        choices=[
                            ("1h", "Last Hour"),
                            ("24h", "Last 24 Hours"),
                            ("7d", "Last 7 Days"),
                            ("30d", "Last 30 Days"),
                            ("90d", "Last 90 Days"),
                            ("custom", "Custom Range"),
                        ],
                        default="24h",
                        max_length=10,
                    ),
                ),
                ("auto_refresh", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Dashboard",
                "verbose_name_plural": "Analytics Dashboards",
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="CostTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stability", "Stability AI"),
                            ("runway", "Runway ML"),
                            ("elevenlabs", "ElevenLabs"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("replicate", "Replicate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("service", models.CharField(max_length=100)),
                ("operation", models.CharField(max_length=100)),
                (
                    "credits_used",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("billing_period", models.CharField(blank=True, max_length=7)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Tracking",
                "verbose_name_plural": "Cost Tracking Records",
                "indexes": [
                    models.Index(
                        fields=["provider", "timestamp"],
                        name="core_costtr_provide_1402a7_idx",
                    ),
                    models.Index(
                        fields=["user", "billing_period"],
                        name="core_costtr_user_id_f1bed3_idx",
                    ),
                    models.Index(
                        fields=["service", "timestamp"],
                        name="core_costtr_service_3f53a7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("api", "API Endpoint"),
                            ("websocket", "WebSocket"),
                            ("database", "Database"),
                            ("cache", "Cache"),
                            ("external", "External API"),
                            ("worker", "Background Worker"),
                            ("ml", "ML Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("component_name", models.CharField(max_length=100)),
                ("response_time_ms", models.IntegerField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_type", models.CharField(blank=True, max_length=100)),
                (
                    "memory_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cpu_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("method", models.CharField(blank=True, max_length=10)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Log",
                "verbose_name_plural": "Performance Logs",
                "indexes": [
                    models.Index(
                        fields=["component_type", "timestamp"],
                        name="core_perfor_compone_00cf7e_idx",
                    ),
                    models.Index(
                        fields=["success", "timestamp"],
                        name="core_perfor_success_75fc0b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("image", "Image Generation"),
                            ("video", "Video Generation"),
                            ("audio", "Audio Generation"),
                            ("3d", "3D Generation"),
                            ("workflow", "Workflow Execution"),
                            ("agent", "Agent Execution"),
                            ("spider", "Spider Data"),
                            ("collaboration", "Collaboration"),
                            ("api", "API Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                ("feature_name", models.CharField(max_length=100)),
                ("count", models.IntegerField(default=1)),
                (
                    "value",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("hour", models.IntegerField(default=0)),
                ("day_of_week", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Metric",
                "verbose_name_plural": "Usage Metrics",
                "indexes": [
                    models.Index(
                        fields=["category", "timestamp"],
                        name="core_usagem_categor_9d4bb0_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="core_usagem_user_id_34b3ca_idx",
                    ),
                    models.Index(
                        fields=["feature_name", "timestamp"],
                        name="core_usagem_feature_a85543_idx",
                    ),
                ],
            },
        ),
    ]
