# Generated by Django 5.0.6 on 2025-11-27 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_session_224_revenue_reality"),
        ("core", "0028_session_223_opportunity_engine"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("3d_model", "3D Model"),
                            ("template", "Template"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "workflow_used",
                    models.CharField(
                        blank=True,
                        help_text="Which workflow created this content",
                        max_length=100,
                    ),
                ),
                (
                    "workflow_execution_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the workflow execution",
                        max_length=100,
                    ),
                ),
                (
                    "production_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost to create this content (API costs, etc.)",
                        max_digits=10,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_platforms",
                    models.JSONField(
                        default=list, help_text="Where this content was published"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_created",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_content",
                        to="core.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_created",
                        to="content.videohistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpportunityPredictionAccuracy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_opportunities", models.IntegerField(default=0)),
                ("opportunities_with_revenue", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.FloatField(
                        default=0, help_text="% of opportunities that generated revenue"
                    ),
                ),
                (
                    "total_predicted_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_actual_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "revenue_accuracy",
                    models.FloatField(default=0, help_text="Actual/Predicted * 100"),
                ),
                (
                    "mean_absolute_error",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Average absolute difference between predicted and actual",
                        max_digits=12,
                    ),
                ),
                (
                    "accuracy_by_category",
                    models.JSONField(
                        default=dict,
                        help_text="Accuracy broken down by opportunity category",
                    ),
                ),
                (
                    "accuracy_by_source",
                    models.JSONField(
                        default=dict, help_text="Accuracy broken down by source type"
                    ),
                ),
                ("avg_predicted_score", models.FloatField(default=0)),
                (
                    "avg_actual_performance",
                    models.FloatField(
                        default=0, help_text="Normalized actual performance score"
                    ),
                ),
                (
                    "score_correlation",
                    models.FloatField(
                        default=0,
                        help_text="Correlation between predicted scores and actual outcomes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User-specific accuracy (null for system-wide)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "unique_together": {("user", "period_start", "period_type")},
            },
        ),
        migrations.CreateModel(
            name="OpportunityRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total revenue amount",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Platform/marketplace fee",
                        max_digits=10,
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount after fees", max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("received", "Received"),
                            ("partial", "Partial Payment"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("3d_model", "3D Model"),
                            ("template", "Template"),
                            ("bundle", "Bundle"),
                            ("service", "Service/Freelance"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Sale"),
                            ("etsy", "Etsy"),
                            ("gumroad", "Gumroad"),
                            ("creative_market", "Creative Market"),
                            ("shutterstock", "Shutterstock"),
                            ("adobe_stock", "Adobe Stock"),
                            ("envato", "Envato Elements"),
                            ("fiverr", "Fiverr"),
                            ("upwork", "Upwork"),
                            ("freelancer", "Freelancer"),
                            ("other", "Other"),
                        ],
                        default="direct",
                        max_length=30,
                    ),
                ),
                (
                    "content_ids",
                    models.JSONField(
                        default=list,
                        help_text="Additional content IDs associated with this revenue",
                    ),
                ),
                (
                    "estimated_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What was predicted vs actual",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "prediction_accuracy",
                    models.FloatField(
                        blank=True,
                        help_text="Accuracy percentage: actual/estimated * 100",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the sale/revenue"
                    ),
                ),
                ("sale_date", models.DateTimeField(help_text="When the sale occurred")),
                (
                    "payment_received_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When payment was actually received",
                        null=True,
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        help_text="External order ID or reference",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_revenues",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to="core.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunity_revenues",
                        to="content.videohistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-sale_date"],
                "indexes": [
                    models.Index(
                        fields=["opportunity", "status"],
                        name="core_opport_opportu_d0ae22_idx",
                    ),
                    models.Index(
                        fields=["user", "sale_date"],
                        name="core_opport_user_id_4a24c7_idx",
                    ),
                    models.Index(
                        fields=["platform", "status"],
                        name="core_opport_platfor_b38878_idx",
                    ),
                ],
            },
        ),
    ]
