# Generated by Django 5.0.6 on 2025-11-27 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_session_224_revenue_reality"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("designer", "Designer - Creates visual content"),
                            ("researcher", "Researcher - Gathers information"),
                            ("reviewer", "Reviewer - Reviews and critiques work"),
                            ("writer", "Writer - Creates written content"),
                            ("analyst", "Analyst - Analyzes data and trends"),
                            ("strategist", "Strategist - Plans and coordinates"),
                            ("optimizer", "Optimizer - Improves and refines"),
                            ("communicator", "Communicator - Handles messaging"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "capabilities",
                    models.JSONField(
                        default=list, help_text="List of capability strings"
                    ),
                ),
                (
                    "available_tools",
                    models.JSONField(
                        default=list, help_text="List of tool names this role can use"
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(
                        default=dict, help_text="Role-specific constraints"
                    ),
                ),
                (
                    "role_prompt",
                    models.TextField(
                        blank=True, help_text="Additional system prompt for this role"
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Role",
                "verbose_name_plural": "Agent Roles",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgentTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("creative", "Creative Team"),
                            ("research", "Research Team"),
                            ("marketing", "Marketing Team"),
                            ("content", "Content Production Team"),
                            ("custom", "Custom Team"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_teams",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Team",
                "verbose_name_plural": "Agent Teams",
            },
        ),
        migrations.CreateModel(
            name="AgentTeamMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_lead", models.BooleanField(default=False)),
                ("can_delegate", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="core.agent",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agentrole",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.agentteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Team Membership",
                "verbose_name_plural": "Agent Team Memberships",
                "unique_together": {("team", "agent")},
            },
        ),
        migrations.AddField(
            model_name="agentteam",
            name="agents",
            field=models.ManyToManyField(
                related_name="teams",
                through="core.AgentTeamMembership",
                to="core.agent",
            ),
        ),
        migrations.CreateModel(
            name="TeamWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("workflow_template", models.CharField(blank=True, max_length=100)),
                ("steps", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("progress", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("results", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_workflows",
                        to="core.agent",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_workflows",
                        to="core.opportunity",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="core.agentteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Workflow",
                "verbose_name_plural": "Team Workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamWorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("step_name", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("review", "In Review"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("review_score", models.FloatField(blank=True, null=True)),
                ("review_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_steps",
                        to="core.agent",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_by",
                        to="core.teamworkflowstep",
                    ),
                ),
                (
                    "required_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.agentrole",
                    ),
                ),
                (
                    "reviewer_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_steps",
                        to="core.agent",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="core.teamworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Workflow Step",
                "verbose_name_plural": "Team Workflow Steps",
                "ordering": ["workflow", "step_number"],
            },
        ),
        migrations.CreateModel(
            name="AgentMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("request", "Task Request"),
                            ("response", "Task Response"),
                            ("feedback", "Feedback"),
                            ("handoff", "Task Handoff"),
                            ("notification", "Notification"),
                            ("question", "Question"),
                            ("answer", "Answer"),
                            ("status", "Status Update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("attachments", models.JSONField(default=list)),
                ("thread_id", models.UUIDField(default=uuid.uuid4)),
                ("task_context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="core.agentmessage",
                    ),
                ),
                (
                    "receiver_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="core.agent",
                    ),
                ),
                (
                    "sender_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Message",
                "verbose_name_plural": "Agent Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["thread_id"], name="core_agentm_thread__987d95_idx"
                    ),
                    models.Index(
                        fields=["sender_agent", "created_at"],
                        name="core_agentm_sender__1f3dee_idx",
                    ),
                    models.Index(
                        fields=["receiver_agent", "status"],
                        name="core_agentm_receive_24ced6_idx",
                    ),
                ],
            },
        ),
    ]
