# Generated by Django 5.0.6 on 2025-11-27 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0031_session_224_revenue_reality"),
        ("core", "0030_session_227_team_power"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionPlatform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("marketplace", "Marketplace"),
                            ("social", "Social Media"),
                            ("stock", "Stock Content"),
                            ("print_on_demand", "Print on Demand"),
                            ("nft", "NFT Marketplace"),
                            ("direct", "Direct Sales"),
                            ("freelance", "Freelance Platform"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("supported_content_types", models.JSONField(default=list)),
                ("supported_formats", models.JSONField(default=list)),
                ("max_file_size_mb", models.IntegerField(default=100)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("has_subscription", models.BooleanField(default=False)),
                (
                    "subscription_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "payment_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("api_available", models.BooleanField(default=False)),
                ("api_documentation_url", models.URLField(blank=True)),
                ("requires_approval", models.BooleanField(default=False)),
                ("popularity_score", models.IntegerField(default=50)),
                (
                    "avg_earnings_per_item",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "competition_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Distribution Platform",
                "verbose_name_plural": "Distribution Platforms",
                "ordering": ["-popularity_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="DistributionRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform Recommendation"),
                            ("pricing", "Pricing Recommendation"),
                            ("timing", "Timing Recommendation"),
                            ("tags", "Tags/Keywords Recommendation"),
                            ("optimization", "Optimization Recommendation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("title", models.CharField(max_length=200)),
                ("reasoning", models.TextField()),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("suggested_tags", models.JSONField(default=list)),
                ("suggested_title", models.CharField(blank=True, max_length=500)),
                ("suggested_description", models.TextField(blank=True)),
                ("estimated_views", models.IntegerField(blank=True, null=True)),
                ("estimated_sales", models.IntegerField(blank=True, null=True)),
                (
                    "estimated_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_applied", models.BooleanField(default=False)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distribution_recommendations",
                        to="core.opportunity",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.distributionplatform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="content.videohistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribution Recommendation",
                "verbose_name_plural": "Distribution Recommendations",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPlatformAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_username", models.CharField(blank=True, max_length=200)),
                ("account_url", models.URLField(blank=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_secret", models.CharField(blank=True, max_length=500)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("total_items_listed", models.IntegerField(default=0)),
                ("total_sales", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_item_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("follower_count", models.IntegerField(default=0)),
                ("auto_upload_enabled", models.BooleanField(default=False)),
                ("notification_settings", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_accounts",
                        to="core.distributionplatform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Platform Account",
                "verbose_name_plural": "User Platform Accounts",
                "unique_together": {("user", "platform")},
            },
        ),
        migrations.CreateModel(
            name="ContentDistribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("license_type", models.CharField(blank=True, max_length=50)),
                ("platform_listing_id", models.CharField(blank=True, max_length=200)),
                ("platform_listing_url", models.URLField(blank=True)),
                ("platform_metadata", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Upload"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("live", "Live"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                            ("sold_out", "Sold Out"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("downloads", models.IntegerField(default=0)),
                ("sales", models.IntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("listed_at", models.DateTimeField(blank=True, null=True)),
                ("last_sale_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributions",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributions",
                        to="core.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributions",
                        to="content.videohistory",
                    ),
                ),
                (
                    "platform_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distributions",
                        to="core.userplatformaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Distribution",
                "verbose_name_plural": "Content Distributions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistributionAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("total_views", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                ("total_sales", models.IntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("new_listings", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("top_content_ids", models.JSONField(default=list)),
                ("top_tags", models.JSONField(default=list)),
                (
                    "best_performing_category",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.distributionplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribution Analytics",
                "verbose_name_plural": "Distribution Analytics",
                "ordering": ["-date"],
                "unique_together": {("user", "platform", "date", "period_type")},
            },
        ),
    ]
