# Generated by Django 5.0.6 on 2025-11-27 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_session_229_smart_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPerformancePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_type", models.CharField(max_length=50)),
                ("content_id", models.UUIDField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("analyzed_attributes", models.JSONField(default=dict)),
                ("platform_predictions", models.JSONField(default=dict)),
                (
                    "overall_success_probability",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "expected_total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("expected_time_to_first_sale", models.IntegerField(default=0)),
                (
                    "prediction_confidence",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("recommended_platforms", models.JSONField(default=list)),
                ("recommended_price_range", models.JSONField(default=dict)),
                ("recommended_tags", models.JSONField(default=list)),
                (
                    "recommended_upload_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("matching_success_patterns", models.JSONField(default=list)),
                ("actual_success", models.BooleanField(blank=True, null=True)),
                (
                    "actual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prediction_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("prediction_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Performance Prediction",
                "verbose_name_plural": "Content Performance Predictions",
                "ordering": ["-prediction_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DistributionInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("opportunity", "New Opportunity"),
                            ("improvement", "Improvement Suggestion"),
                            ("warning", "Warning/Alert"),
                            ("milestone", "Achievement/Milestone"),
                            ("trend", "Trend Detected"),
                            ("prediction", "Future Prediction"),
                            ("comparison", "Performance Comparison"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("detailed_analysis", models.TextField(blank=True)),
                ("supporting_data", models.JSONField(default=dict)),
                ("recommended_actions", models.JSONField(default=list)),
                (
                    "potential_revenue_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("is_acted_upon", models.BooleanField(default=False)),
                (
                    "user_feedback",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("incorrect", "Incorrect"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("valid_from", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_still_relevant", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Distribution Insight",
                "verbose_name_plural": "Distribution Insights",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("platform", "Platform-wide"),
                            ("category", "Category"),
                            ("style", "Style"),
                            ("price_tier", "Price Tier"),
                            ("experience_level", "Experience Level"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scope_value", models.CharField(max_length=100)),
                ("user_metrics", models.JSONField(default=dict)),
                ("benchmark_metrics", models.JSONField(default=dict)),
                ("percentile_rankings", models.JSONField(default=dict)),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("improvement_opportunities", models.JSONField(default=list)),
                ("trend_vs_last_period", models.JSONField(default=dict)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("sample_size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Performance Comparison",
                "verbose_name_plural": "Performance Comparisons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PricingOptimization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_category", models.CharField(blank=True, max_length=100)),
                ("content_style", models.CharField(blank=True, max_length=100)),
                (
                    "market_avg_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "market_median_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("market_price_range", models.JSONField(default=dict)),
                ("competitor_prices", models.JSONField(default=list)),
                (
                    "user_avg_sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user_best_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "user_price_elasticity",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "optimal_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "optimal_price_confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("price_range_suggestion", models.JSONField(default=dict)),
                ("tested_prices", models.JSONField(default=list)),
                (
                    "best_tested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("seasonal_multipliers", models.JSONField(default=dict)),
                ("pricing_insights", models.JSONField(default=list)),
                ("current_ab_test_id", models.UUIDField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("data_freshness_days", models.IntegerField(default=0)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.distributionplatform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_optimizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing Optimization",
                "verbose_name_plural": "Pricing Optimizations",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="SuccessPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("content_style", "Content Style"),
                            ("pricing_strategy", "Pricing Strategy"),
                            ("timing", "Upload Timing"),
                            ("platform_match", "Platform Match"),
                            ("tag_combination", "Tag Combination"),
                            ("description_format", "Description Format"),
                            ("category_niche", "Category Niche"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pattern_name", models.CharField(max_length=200)),
                ("pattern_description", models.TextField(blank=True)),
                ("pattern_attributes", models.JSONField(default=dict)),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                (
                    "success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_revenue_per_success",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_revenue_attributed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("sample_size", models.IntegerField(default=0)),
                ("statistical_significance", models.BooleanField(default=False)),
                ("best_platforms", models.JSONField(default=list)),
                ("best_upload_times", models.JSONField(default=list)),
                ("best_seasons", models.JSONField(default=list)),
                ("example_content_ids", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_validated", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="success_patterns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Success Pattern",
                "verbose_name_plural": "Success Patterns",
                "ordering": ["-success_rate", "-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="UserLearningProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("preferred_styles", models.JSONField(default=list)),
                ("preferred_platforms", models.JSONField(default=list)),
                ("preferred_content_types", models.JSONField(default=list)),
                ("preferred_price_ranges", models.JSONField(default=dict)),
                ("typical_upload_times", models.JSONField(default=list)),
                ("productivity_patterns", models.JSONField(default=dict)),
                (
                    "avg_content_per_week",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "overall_success_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("strongest_categories", models.JSONField(default=list)),
                ("weakest_categories", models.JSONField(default=list)),
                ("total_successful_distributions", models.IntegerField(default=0)),
                (
                    "total_lifetime_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("patterns_discovered", models.IntegerField(default=0)),
                ("insights_generated", models.IntegerField(default=0)),
                ("insights_acted_upon", models.IntegerField(default=0)),
                (
                    "prediction_accuracy_avg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("notification_preferences", models.JSONField(default=dict)),
                ("revenue_goals", models.JSONField(default=dict)),
                ("conversation_context", models.JSONField(default=dict)),
                ("recent_interactions", models.JSONField(default=list)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("profile_completeness", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Learning Profile",
                "verbose_name_plural": "User Learning Profiles",
            },
        ),
    ]
