# Generated by Django 5.0.6 on 2025-11-27 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_learning_loop_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProactiveAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Alert"),
                            ("trend", "Trend Alert"),
                            ("anomaly", "Anomaly Detection"),
                            ("opportunity", "Opportunity Alert"),
                            ("deadline", "Deadline Reminder"),
                            ("goal", "Goal Progress"),
                            ("competitor", "Competitor Activity"),
                            ("market", "Market Change"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("metric_name", models.CharField(max_length=100)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("above", "Above"),
                            ("below", "Below"),
                            ("equals", "Equals"),
                            ("change_up", "Increases By"),
                            ("change_down", "Decreases By"),
                            ("anomaly", "Anomaly Detected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "threshold_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=50)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "check_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("cooldown_hours", models.IntegerField(default=24)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("trigger_count", models.IntegerField(default=0)),
                ("notification_channels", models.JSONField(default=list)),
                ("auto_actions", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.distributionplatform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proactive Alert",
                "verbose_name_plural": "Proactive Alerts",
                "ordering": ["-is_active", "-trigger_count"],
            },
        ),
        migrations.CreateModel(
            name="AutomatedAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("price_adjust", "Adjust Pricing"),
                            ("distribute", "Auto-Distribute"),
                            ("notify", "Send Notification"),
                            ("tag_update", "Update Tags"),
                            ("schedule_upload", "Schedule Upload"),
                            ("apply_promotion", "Apply Promotion"),
                            ("generate_report", "Generate Report"),
                            ("backup_data", "Backup Data"),
                            ("optimize_listing", "Optimize Listing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("alert", "On Alert"),
                            ("schedule", "On Schedule"),
                            ("event", "On Event"),
                            ("threshold", "On Threshold"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_schedule", models.CharField(blank=True, max_length=100)),
                ("trigger_event", models.CharField(blank=True, max_length=100)),
                ("action_params", models.JSONField(default=dict)),
                ("conditions", models.JSONField(default=list)),
                ("platform_scope", models.JSONField(default=list)),
                ("content_type_scope", models.JSONField(default=list)),
                ("max_executions_per_day", models.IntegerField(default=10)),
                (
                    "max_price_change_percent",
                    models.DecimalField(decimal_places=2, default=25, max_digits=5),
                ),
                ("requires_confirmation", models.BooleanField(default=False)),
                ("dry_run_first", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_paused", models.BooleanField(default=False)),
                ("pause_reason", models.CharField(blank=True, max_length=200)),
                ("total_executions", models.IntegerField(default=0)),
                ("successful_executions", models.IntegerField(default=0)),
                ("failed_executions", models.IntegerField(default=0)),
                ("last_executed", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.JSONField(default=dict)),
                ("executions_today", models.IntegerField(default=0)),
                ("executions_today_reset", models.DateField(blank=True, null=True)),
                (
                    "total_revenue_impact",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_impact_per_execution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automated_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trigger_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automated_actions",
                        to="core.proactivealert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Automated Action",
                "verbose_name_plural": "Automated Actions",
                "ordering": ["-is_active", "-total_executions"],
            },
        ),
        migrations.CreateModel(
            name="SmartSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing Adjustment"),
                            ("timing", "Upload Timing"),
                            ("platform", "Platform Recommendation"),
                            ("content", "Content Improvement"),
                            ("tags", "Tag Optimization"),
                            ("description", "Description Enhancement"),
                            ("bundle", "Bundle Suggestion"),
                            ("promotion", "Promotion Opportunity"),
                            ("cross_sell", "Cross-Sell Opportunity"),
                            ("expansion", "Market Expansion"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("revenue", "Increase Revenue"),
                            ("efficiency", "Improve Efficiency"),
                            ("reach", "Expand Reach"),
                            ("quality", "Improve Quality"),
                            ("risk", "Reduce Risk"),
                        ],
                        default="revenue",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("detailed_rationale", models.TextField(blank=True)),
                ("supporting_patterns", models.JSONField(default=list)),
                ("supporting_data", models.JSONField(default=dict)),
                ("similar_successes", models.JSONField(default=list)),
                ("action_steps", models.JSONField(default=list)),
                ("current_state", models.JSONField(default=dict)),
                ("suggested_state", models.JSONField(default=dict)),
                ("estimated_impact", models.JSONField(default=dict)),
                (
                    "estimated_revenue_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                ("priority_score", models.IntegerField(default=50)),
                (
                    "effort_level",
                    models.CharField(
                        choices=[
                            ("low", "Low (Quick Win)"),
                            ("medium", "Medium"),
                            ("high", "High (Requires Work)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=100)),
                ("implemented_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_tracked", models.BooleanField(default=False)),
                ("actual_impact", models.JSONField(default=dict)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_still_relevant", models.BooleanField(default=True)),
                ("related_content_ids", models.JSONField(default=list)),
                ("related_distribution_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Suggestion",
                "verbose_name_plural": "Smart Suggestions",
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProactiveNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("alert", "Alert"),
                            ("suggestion", "Suggestion"),
                            ("insight", "Insight"),
                            ("reminder", "Reminder"),
                            ("celebration", "Celebration"),
                            ("warning", "Warning"),
                            ("update", "System Update"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("rich_content", models.JSONField(default=dict)),
                ("icon", models.CharField(default="bell", max_length=50)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("action_label", models.CharField(blank=True, max_length=100)),
                ("quick_actions", models.JSONField(default=list)),
                ("channels_sent", models.JSONField(default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("is_acted_upon", models.BooleanField(default=False)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("action_result", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.proactivealert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proactive_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suggestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="core.smartsuggestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proactive Notification",
                "verbose_name_plural": "Proactive Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("alert_notifications", models.BooleanField(default=True)),
                ("suggestion_notifications", models.BooleanField(default=True)),
                ("insight_notifications", models.BooleanField(default=True)),
                ("celebration_notifications", models.BooleanField(default=True)),
                ("warning_notifications", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly Digest"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "min_priority_email",
                    models.CharField(default="medium", max_length=20),
                ),
                ("min_priority_push", models.CharField(default="high", max_length=20)),
                ("enabled_categories", models.JSONField(default=list)),
                ("unsubscribed_types", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Notification Preference",
                "verbose_name_plural": "User Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="AutomatedActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger_type", models.CharField(max_length=50)),
                ("trigger_source", models.CharField(blank=True, max_length=200)),
                ("input_params", models.JSONField(default=dict)),
                ("output_result", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("items_affected", models.IntegerField(default=0)),
                (
                    "revenue_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("can_rollback", models.BooleanField(default=False)),
                ("rollback_data", models.JSONField(default=dict)),
                ("was_rolled_back", models.BooleanField(default=False)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="core.automatedaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Automated Action Log",
                "verbose_name_plural": "Automated Action Logs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "status", "started_at"],
                        name="core_automa_action__279430_idx",
                    ),
                    models.Index(
                        fields=["user", "started_at"],
                        name="core_automa_user_id_d920eb_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="smartsuggestion",
            index=models.Index(
                fields=["user", "status", "suggestion_type"],
                name="core_smarts_user_id_70f59b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="smartsuggestion",
            index=models.Index(
                fields=["priority_score", "confidence_score"],
                name="core_smarts_priorit_ef6375_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proactivenotification",
            index=models.Index(
                fields=["user", "is_read", "is_dismissed"],
                name="core_proact_user_id_81c246_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="proactivenotification",
            index=models.Index(
                fields=["delivery_status", "scheduled_at"],
                name="core_proact_deliver_f47c7e_idx",
            ),
        ),
    ]
