# Generated by Django 5.0.6 on 2025-11-27 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_session_234_proactive_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("pricing", "Pricing Test"),
                            ("title", "Title Test"),
                            ("tags", "Tags Test"),
                            ("description", "Description Test"),
                            ("timing", "Timing Test"),
                            ("platform", "Platform Test"),
                            ("bundle", "Bundle Test"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "hypothesis",
                    models.TextField(blank=True, help_text="What you expect to happen"),
                ),
                (
                    "primary_metric",
                    models.CharField(
                        default="conversion_rate",
                        help_text="Main metric to measure success",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_metrics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional metrics to track",
                    ),
                ),
                (
                    "confidence_level",
                    models.FloatField(
                        default=0.95,
                        help_text="Statistical confidence level (0.90-0.99)",
                    ),
                ),
                (
                    "minimum_sample_size",
                    models.IntegerField(
                        default=100,
                        help_text="Minimum samples per variant before concluding",
                    ),
                ),
                (
                    "content_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filter which content participates",
                    ),
                ),
                (
                    "platform_filter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Limit to specific platforms",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("max_duration_days", models.IntegerField(default=30)),
                ("conclusion", models.TextField(blank=True)),
                ("statistical_significance", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ab_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_control", models.BooleanField(default=False)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Variant-specific settings (price, title, etc.)",
                    ),
                ),
                (
                    "traffic_percentage",
                    models.IntegerField(
                        default=50, help_text="Percentage of traffic to this variant"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.abtest",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_control", "name"],
            },
        ),
        migrations.AddField(
            model_name="abtest",
            name="winner_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_tests",
                to="core.abtestvariant",
            ),
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Goal"),
                            ("sales", "Sales Count"),
                            ("downloads", "Download Count"),
                            ("views", "View Count"),
                            ("distribution", "Distribution Count"),
                            ("content", "Content Created"),
                            ("conversion", "Conversion Rate"),
                            ("custom", "Custom Metric"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("custom_metric", models.CharField(blank=True, max_length=100)),
                ("is_achieved", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notify_at_milestones", models.BooleanField(default=True)),
                (
                    "milestone_percentages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Percentages to notify at (e.g., [25, 50, 75, 100])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("impression", "Impression"),
                            ("click", "Click"),
                            ("conversion", "Conversion"),
                            ("revenue", "Revenue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.CharField(blank=True, max_length=255)),
                ("platform", models.CharField(blank=True, max_length=100)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.abtestvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "event_type"],
                        name="core_abtest_variant_1a503b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="core_abtest_created_cf0189_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="abtest",
            index=models.Index(
                fields=["user", "status"], name="core_abtest_user_id_e1ad9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abtest",
            index=models.Index(
                fields=["test_type", "status"], name="core_abtest_test_ty_60eec9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abtest",
            index=models.Index(
                fields=["status", "created_at"], name="core_abtest_status_0ab96a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergoal",
            index=models.Index(
                fields=["user", "is_active"], name="core_usergo_user_id_b42d88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usergoal",
            index=models.Index(
                fields=["goal_type", "is_achieved"],
                name="core_usergo_goal_ty_e2ece4_idx",
            ),
        ),
    ]
