# Generated by Django 5.0.6 on 2025-11-28 05:23

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_session_235_ab_testing_framework"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiderCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🕷️", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Spider Categories",
            },
        ),
        migrations.CreateModel(
            name="AgentSpiderConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this agent the primary handler for this category?",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="Routing priority (1=highest, 10=lowest)"
                    ),
                ),
                ("total_processed", models.IntegerField(default=0)),
                ("successful_processed", models.IntegerField(default=0)),
                ("avg_processing_time_ms", models.IntegerField(default=0)),
                ("last_processed_at", models.DateTimeField(blank=True, null=True)),
                ("avg_quality_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spider_connections",
                        to="core.agent",
                    ),
                ),
                (
                    "spider_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_connections",
                        to="core.spidercategory",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-is_primary"],
                "unique_together": {("agent", "spider_category")},
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="spider_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Spider categories that feed data to this agent",
                related_name="agents",
                through="core.AgentSpiderConnection",
                to="core.spidercategory",
            ),
        ),
        migrations.CreateModel(
            name="AgentKnowledgeSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend Data"),
                            ("market", "Market Intelligence"),
                            ("opportunity", "Opportunity"),
                            ("competitor", "Competitor Info"),
                            ("pricing", "Pricing Data"),
                            ("user_behavior", "User Behavior"),
                            ("content_idea", "Content Ideas"),
                            ("tool_discovery", "Tool Discovery"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source_spider_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Names of spiders that contributed to this knowledge",
                        size=None,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(help_text="Summary of the knowledge")),
                (
                    "key_insights",
                    models.JSONField(default=list, help_text="List of key insights"),
                ),
                (
                    "data_points_count",
                    models.IntegerField(
                        default=0, help_text="Number of spider data points used"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0, help_text="Confidence in this knowledge (0.0-1.0)"
                    ),
                ),
                ("relevance_score", models.FloatField(default=0.0)),
                (
                    "freshness_score",
                    models.FloatField(
                        default=1.0,
                        help_text="How fresh/current this knowledge is (0.0-1.0)",
                    ),
                ),
                ("first_discovered_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_validated", models.BooleanField(default=False)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="core.agent",
                    ),
                ),
                (
                    "spider_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.spidercategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-last_updated_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "knowledge_type"],
                        name="core_agentk_agent_i_57018a_idx",
                    ),
                    models.Index(
                        fields=["spider_category", "is_active"],
                        name="core_agentk_spider__04dfbf_idx",
                    ),
                ],
            },
        ),
    ]
