# Generated by Django 5.0.6 on 2025-11-28 05:37

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_spider_agent_connections"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentLearningConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "learning_type",
                    models.CharField(
                        choices=[
                            ("complementary", "Complementary Skills"),
                            ("specialization", "Specialization"),
                            ("pipeline", "Pipeline"),
                            ("validation", "Validation"),
                            ("collaborative", "Collaborative"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "shareable_knowledge_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="Types of knowledge that can be transferred",
                        size=None,
                    ),
                ),
                ("total_transfers", models.IntegerField(default=0)),
                ("successful_transfers", models.IntegerField(default=0)),
                (
                    "avg_improvement_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average improvement from knowledge transfer",
                    ),
                ),
                ("last_transfer_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "strength",
                    models.FloatField(
                        default=0.5, help_text="Connection strength 0.0-1.0"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="core.agent",
                    ),
                ),
                (
                    "teacher_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-strength", "-total_transfers"],
                "unique_together": {("teacher_agent", "student_agent")},
            },
        ),
        migrations.CreateModel(
            name="KnowledgeTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transfer_summary",
                    models.TextField(help_text="Summary of what was learned"),
                ),
                ("key_points", models.JSONField(default=list)),
                ("was_useful", models.BooleanField(blank=True, null=True)),
                (
                    "usefulness_score",
                    models.FloatField(
                        default=0.0, help_text="How useful was this transfer (0.0-1.0)"
                    ),
                ),
                ("student_feedback", models.TextField(blank=True)),
                ("was_applied", models.BooleanField(default=False)),
                (
                    "application_result",
                    models.JSONField(
                        default=dict, help_text="Result of applying the knowledge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="core.agentlearningconnection",
                    ),
                ),
                (
                    "source_knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="core.agentknowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
