# Generated by Django 5.0.6 on 2025-11-28 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_session_244_agent_conversations"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short catchy title for the dream", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="The full dream content/idea")),
                (
                    "dream_type",
                    models.CharField(
                        choices=[
                            ("creative_idea", "Creative Idea"),
                            ("what_if", "What If?"),
                            ("mashup", "Mashup"),
                            ("prediction", "Prediction"),
                            ("improvement", "Improvement"),
                            ("observation", "Observation"),
                            ("wild_thought", "Wild Thought"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "inspiration_source",
                    models.CharField(
                        blank=True,
                        help_text="What inspired this dream (knowledge, trend, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "related_topics",
                    models.JSONField(
                        default=list,
                        help_text="List of topics/tags related to this dream",
                    ),
                ),
                (
                    "vividness_score",
                    models.FloatField(
                        default=0.7,
                        help_text="How vivid/detailed the dream is (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "creativity_score",
                    models.FloatField(
                        default=0.7,
                        help_text="How creative/novel the dream is (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("shown_to_user", models.BooleanField(default=False)),
                ("shown_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user_reaction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("loved", "Loved It"),
                            ("interesting", "Interesting"),
                            ("meh", "Meh"),
                            ("dismissed", "Dismissed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("dreamed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dreams",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Dream",
                "verbose_name_plural": "Agent Dreams",
                "ordering": ["-dreamed_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-dreamed_at"],
                        name="core_agentd_agent_i_fcec09_idx",
                    ),
                    models.Index(
                        fields=["dream_type", "shown_to_user"],
                        name="core_agentd_dream_t_1c5de4_idx",
                    ),
                ],
            },
        ),
    ]
