# Generated by Django 5.0.6 on 2025-11-28 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_agent_dream_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamExploration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "exploration_content",
                    models.TextField(
                        blank=True,
                        help_text="Deeper exploration/research on the dream topic",
                    ),
                ),
                (
                    "insights_generated",
                    models.JSONField(
                        default=list,
                        help_text="List of insights discovered during exploration",
                    ),
                ),
                (
                    "related_knowledge_added",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this exploration added to agent's knowledge",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explorations",
                        to="core.agentdream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dream Exploration",
                "verbose_name_plural": "Dream Explorations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamFeedbackPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dream_type",
                    models.CharField(
                        blank=True,
                        help_text="Dream type preference (creative_idea, what_if, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Topic/subject preference learned from inspiration_source",
                        max_length=200,
                    ),
                ),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("interesting_count", models.PositiveIntegerField(default=0)),
                ("explore_count", models.PositiveIntegerField(default=0)),
                (
                    "preference_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Weighted score: like=1, interesting=2, explore=3",
                    ),
                ),
                ("last_reaction_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific agent preference (null = global preference)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dream_preferences",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dream Feedback Preference",
                "verbose_name_plural": "Dream Feedback Preferences",
                "indexes": [
                    models.Index(
                        fields=["-preference_score"],
                        name="core_dreamf_prefere_e4098c_idx",
                    ),
                    models.Index(
                        fields=["dream_type", "-preference_score"],
                        name="core_dreamf_dream_t_ab4b61_idx",
                    ),
                    models.Index(
                        fields=["agent", "-preference_score"],
                        name="core_dreamf_agent_i_785211_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dreamfeedbackpreference",
            constraint=models.UniqueConstraint(
                fields=("agent", "dream_type", "topic"), name="unique_dream_preference"
            ),
        ),
    ]
