# Generated by Django 5.0.6 on 2025-11-28 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_session_250_hive_mind_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title/summary of the memory", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Detailed content of the memory"),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True, help_text="Context in which this memory was formed"
                    ),
                ),
                (
                    "memory_type",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("preference", "User Preference"),
                            ("technique", "Technique"),
                            ("insight", "Insight"),
                            ("interaction", "Interaction"),
                            ("feedback", "Feedback"),
                        ],
                        default="interaction",
                        max_length=50,
                    ),
                ),
                (
                    "valence",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "importance_score",
                    models.FloatField(
                        default=0.5, help_text="How important is this memory (0-1)"
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embedding for semantic retrieval",
                        null=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="What triggered this memory: task, conversation, dream, hive_mind",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the source event/task/conversation",
                        max_length=100,
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this memory has been retrieved",
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this memory was last retrieved",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="core.agent",
                    ),
                ),
                (
                    "connected_memories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related memories that form conceptual connections",
                        to="core.agentmemory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Memory",
                "verbose_name_plural": "Agent Memories",
                "ordering": ["-importance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemoryConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("causal", "Caused By"),
                            ("similar", "Similar To"),
                            ("contrast", "Contrasts With"),
                            ("elaborates", "Elaborates"),
                            ("temporal", "Follows"),
                        ],
                        default="similar",
                        max_length=50,
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        default=0.5, help_text="How strong is this connection (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "memory_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_from",
                        to="core.agentmemory",
                    ),
                ),
                (
                    "memory_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_to",
                        to="core.agentmemory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Connection",
                "verbose_name_plural": "Memory Connections",
            },
        ),
        migrations.CreateModel(
            name="MemoryPalaceRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🏠", max_length=50)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("techniques", "Techniques Library"),
                            ("successes", "Hall of Victories"),
                            ("lessons", "Lessons Learned"),
                            ("preferences", "User Preferences"),
                            ("insights", "Insight Garden"),
                            ("experiments", "Experiment Lab"),
                            ("general", "General Archive"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("color", models.CharField(default="#8b5cf6", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_rooms",
                        to="core.agent",
                    ),
                ),
                (
                    "memories",
                    models.ManyToManyField(
                        blank=True, related_name="rooms", to="core.agentmemory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Memory Palace Room",
                "verbose_name_plural": "Memory Palace Rooms",
                "ordering": ["agent", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["agent", "memory_type"], name="core_agentm_agent_i_d1624c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentmemory",
            index=models.Index(
                fields=["agent", "importance_score"],
                name="core_agentm_agent_i_81578a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="memoryconnection",
            unique_together={("memory_from", "memory_to")},
        ),
    ]
