# Generated by Django 5.0.6 on 2025-11-28 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_session_251_memory_palace"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentMood",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_mood",
                    models.CharField(
                        choices=[
                            ("inspired", "Inspired"),
                            ("focused", "Focused"),
                            ("curious", "Curious"),
                            ("confident", "Confident"),
                            ("contemplative", "Contemplative"),
                            ("energetic", "Energetic"),
                            ("calm", "Calm"),
                            ("frustrated", "Frustrated"),
                            ("tired", "Tired"),
                            ("playful", "Playful"),
                        ],
                        default="calm",
                        max_length=50,
                    ),
                ),
                ("intensity", models.FloatField(default=0.5)),
                (
                    "creativity_level",
                    models.FloatField(
                        default=0.5, help_text="How creative/experimental"
                    ),
                ),
                (
                    "precision_level",
                    models.FloatField(default=0.5, help_text="How precise/methodical"),
                ),
                (
                    "sociability_level",
                    models.FloatField(default=0.5, help_text="How chatty/verbose"),
                ),
                (
                    "risk_tolerance",
                    models.FloatField(
                        default=0.5, help_text="How willing to try new things"
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("memory", "Memory Recall"),
                            ("task_success", "Task Success"),
                            ("task_failure", "Task Failure"),
                            ("user_feedback", "User Feedback"),
                            ("collaboration", "Collaboration"),
                            ("idle", "Idle Time"),
                            ("time_of_day", "Time of Day"),
                            ("streak", "Success Streak"),
                            ("manual", "Manual Override"),
                        ],
                        default="idle",
                        max_length=50,
                    ),
                ),
                ("trigger_source", models.CharField(blank=True, max_length=200)),
                ("mood_started_at", models.DateTimeField(auto_now_add=True)),
                ("mood_expires_at", models.DateTimeField(blank=True, null=True)),
                ("total_mood_changes", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Mood",
                "verbose_name_plural": "Agent Moods",
            },
        ),
        migrations.CreateModel(
            name="MoodTriggerRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("task_success_streak", "Task Success Streak"),
                            ("task_failure_streak", "Task Failure Streak"),
                            ("positive_feedback", "Positive Feedback"),
                            ("negative_feedback", "Negative Feedback"),
                            ("memory_valence", "Memory Valence"),
                            ("idle_time", "Idle Time"),
                            ("time_of_day", "Time of Day"),
                            ("collaboration_count", "Collaboration Count"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition_value",
                    models.JSONField(default=dict, help_text="Condition parameters"),
                ),
                ("target_mood", models.CharField(max_length=50)),
                ("target_intensity", models.FloatField(default=0.7)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("priority", models.PositiveIntegerField(default=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_rules",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood Trigger Rule",
                "verbose_name_plural": "Mood Trigger Rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="MoodHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mood", models.CharField(max_length=50)),
                ("intensity", models.FloatField(default=0.5)),
                ("trigger_type", models.CharField(max_length=50)),
                ("trigger_source", models.CharField(blank=True, max_length=200)),
                ("creativity_level", models.FloatField(default=0.5)),
                ("precision_level", models.FloatField(default=0.5)),
                ("sociability_level", models.FloatField(default=0.5)),
                ("risk_tolerance", models.FloatField(default=0.5)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_history",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mood History Entry",
                "verbose_name_plural": "Mood History Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "created_at"],
                        name="core_moodhi_agent_i_cea692_idx",
                    ),
                    models.Index(
                        fields=["agent", "mood"], name="core_moodhi_agent_i_cb40af_idx"
                    ),
                ],
            },
        ),
    ]
