# Generated by Django 5.0.6 on 2025-11-28 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_session_252_agent_mood_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("alliance", "Alliance"),
                            ("rivalry", "Rivalry"),
                            ("mentorship", "Mentorship"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                ("strength", models.FloatField(default=0.5)),
                ("trust_level", models.FloatField(default=0.5)),
                ("respect_level", models.FloatField(default=0.5)),
                ("competition_wins", models.PositiveIntegerField(default=0)),
                ("competition_losses", models.PositiveIntegerField(default=0)),
                ("successful_collaborations", models.PositiveIntegerField(default=0)),
                ("failed_collaborations", models.PositiveIntegerField(default=0)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("auto_formed", "Automatically Formed"),
                            ("manual", "Manually Created"),
                            ("task_outcome", "Task Outcome"),
                            ("competition", "Competition"),
                            ("mentorship", "Mentorship Assignment"),
                        ],
                        default="auto_formed",
                        max_length=20,
                    ),
                ),
                ("origin_details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                ("total_interactions", models.PositiveIntegerField(default=0)),
                (
                    "agent_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_initiated",
                        to="core.agent",
                    ),
                ),
                (
                    "agent_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_received",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Relationship",
                "verbose_name_plural": "Agent Relationships",
                "ordering": ["-strength", "-updated_at"],
                "unique_together": {("agent_from", "agent_to")},
            },
        ),
        migrations.CreateModel(
            name="Alliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("creative", "Creative Excellence"),
                            ("research", "Research & Analysis"),
                            ("execution", "Fast Execution"),
                            ("quality", "Quality Assurance"),
                            ("innovation", "Innovation"),
                            ("general", "General Purpose"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("successful_projects", models.PositiveIntegerField(default=0)),
                ("combined_strength", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("formed_at", models.DateTimeField(auto_now_add=True)),
                ("disbanded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_alliances",
                        to="core.agent",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(related_name="alliances", to="core.agent"),
                ),
            ],
            options={
                "verbose_name": "Alliance",
                "verbose_name_plural": "Alliances",
                "ordering": ["-combined_strength", "name"],
            },
        ),
        migrations.CreateModel(
            name="RelationshipEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("collaboration_success", "Successful Collaboration"),
                            ("collaboration_failure", "Failed Collaboration"),
                            ("competition_win", "Competition Win"),
                            ("competition_loss", "Competition Loss"),
                            ("trust_increase", "Trust Increased"),
                            ("trust_decrease", "Trust Decreased"),
                            ("type_change", "Relationship Type Changed"),
                            ("strength_milestone", "Strength Milestone"),
                            ("first_interaction", "First Interaction"),
                            ("conflict", "Conflict"),
                            ("reconciliation", "Reconciliation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("strength_at_event", models.FloatField()),
                ("trust_at_event", models.FloatField()),
                ("relationship_type_at_event", models.CharField(max_length=20)),
                ("trigger_type", models.CharField(blank=True, max_length=50)),
                ("trigger_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "relationship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.agentrelationship",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relationship Event",
                "verbose_name_plural": "Relationship Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rivalry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("agent_vs_agent", "Agent vs Agent"),
                            ("alliance_vs_alliance", "Alliance vs Alliance"),
                            ("agent_vs_alliance", "Agent vs Alliance"),
                        ],
                        default="agent_vs_agent",
                        max_length=20,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("speed", "Speed"),
                            ("quality", "Quality"),
                            ("creativity", "Creativity"),
                            ("accuracy", "Accuracy"),
                            ("efficiency", "Efficiency"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("challenger_wins", models.PositiveIntegerField(default=0)),
                ("defender_wins", models.PositiveIntegerField(default=0)),
                ("draws", models.PositiveIntegerField(default=0)),
                ("intensity", models.FloatField(default=0.5)),
                ("is_active", models.BooleanField(default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agent_challenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rivalries_as_challenger",
                        to="core.agent",
                    ),
                ),
                (
                    "agent_defender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rivalries_as_defender",
                        to="core.agent",
                    ),
                ),
                (
                    "alliance_challenger",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rivalries_as_challenger",
                        to="core.alliance",
                    ),
                ),
                (
                    "alliance_defender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rivalries_as_defender",
                        to="core.alliance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rivalry",
                "verbose_name_plural": "Rivalries",
                "ordering": ["-intensity", "name"],
            },
        ),
    ]
