# Generated by Django 5.0.6 on 2025-11-28 20:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_session_253_agent_rivalries_alliances"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentEvolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_xp", models.PositiveIntegerField(default=0)),
                ("current_level", models.PositiveIntegerField(default=1)),
                ("xp_to_next_level", models.PositiveIntegerField(default=100)),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("tasks_failed", models.PositiveIntegerField(default=0)),
                ("collaborations_completed", models.PositiveIntegerField(default=0)),
                ("mentorship_sessions", models.PositiveIntegerField(default=0)),
                ("speed_bonus", models.FloatField(default=0.0)),
                ("quality_bonus", models.FloatField(default=0.0)),
                ("creativity_bonus", models.FloatField(default=0.0)),
                ("efficiency_bonus", models.FloatField(default=0.0)),
                ("prestige_level", models.PositiveIntegerField(default=0)),
                ("lifetime_xp", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_level_up", models.DateTimeField(blank=True, null=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolution",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Evolution",
                "verbose_name_plural": "Agent Evolutions",
                "ordering": ["-current_level", "-total_xp"],
            },
        ),
        migrations.CreateModel(
            name="XPHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xp_amount", models.IntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("task_completion", "Task Completion"),
                            ("task_failure", "Task Failure"),
                            ("collaboration", "Collaboration"),
                            ("mentorship", "Mentorship"),
                            ("rivalry_win", "Rivalry Win"),
                            ("rivalry_loss", "Rivalry Loss"),
                            ("alliance_project", "Alliance Project"),
                            ("user_feedback", "User Feedback"),
                            ("daily_bonus", "Daily Bonus"),
                            ("streak_bonus", "Streak Bonus"),
                            ("prestige_reset", "Prestige Reset"),
                            ("manual", "Manual Adjustment"),
                        ],
                        default="task_completion",
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                ("level_at_time", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xp_history",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "XP History",
                "verbose_name_plural": "XP Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentAbility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ability_code", models.CharField(max_length=50)),
                ("ability_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_upgraded", models.BooleanField(default=False)),
                ("upgrade_level", models.PositiveIntegerField(default=0)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abilities",
                        to="core.agentevolution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Ability",
                "verbose_name_plural": "Agent Abilities",
                "ordering": ["unlocked_at"],
                "unique_together": {("evolution", "ability_code")},
            },
        ),
        migrations.CreateModel(
            name="LevelMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("level_reached", models.PositiveIntegerField()),
                ("title_earned", models.CharField(max_length=50)),
                ("abilities_unlocked", models.JSONField(default=list)),
                ("total_xp_at_milestone", models.PositiveIntegerField()),
                ("tasks_completed_at_milestone", models.PositiveIntegerField()),
                ("achieved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_milestones",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Level Milestone",
                "verbose_name_plural": "Level Milestones",
                "ordering": ["-level_reached"],
                "unique_together": {("agent", "level_reached")},
            },
        ),
    ]
