# Generated by Django 5.0.6 on 2025-11-28 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_session_254_agent_evolution_system"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(max_length=100)),
                ("task_description", models.TextField()),
                ("input_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("output_data", models.JSONField(blank=True, default=dict, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("total_decisions", models.PositiveIntegerField(default=0)),
                ("token_usage", models.PositiveIntegerField(default=0)),
                ("api_calls", models.PositiveIntegerField(default=0)),
                ("is_bookmarked", models.BooleanField(default=False)),
                ("bookmark_note", models.TextField(blank=True, null=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debug_sessions",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Debug Session",
                "verbose_name_plural": "Agent Debug Sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DecisionPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Analyzing Input"),
                            ("planning", "Planning Approach"),
                            ("tool_selection", "Selecting Tool"),
                            ("parameter_choice", "Choosing Parameters"),
                            ("quality_check", "Quality Assessment"),
                            ("retry_decision", "Retry Decision"),
                            ("output_format", "Output Formatting"),
                            ("delegation", "Delegating to Another Agent"),
                            ("memory_recall", "Recalling Memory"),
                            ("learning", "Learning from Result"),
                            ("other", "Other Decision"),
                        ],
                        max_length=30,
                    ),
                ),
                ("context", models.JSONField(default=dict)),
                ("reasoning", models.TextField()),
                ("alternatives", models.JSONField(default=list)),
                ("action_taken", models.CharField(max_length=200)),
                ("action_params", models.JSONField(default=dict)),
                ("confidence_score", models.FloatField(default=0.8)),
                ("was_successful", models.BooleanField(blank=True, null=True)),
                ("outcome_notes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flag_reason", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="core.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Point",
                "verbose_name_plural": "Decision Points",
                "ordering": ["session", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="DebugAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("annotation_type", models.CharField(default="note", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="core.decisionpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Debug Annotation",
                "verbose_name_plural": "Debug Annotations",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReplayBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bookmark_type",
                    models.CharField(
                        choices=[
                            ("interesting", "Interesting"),
                            ("bug", "Possible Bug"),
                            ("learning", "Learning Opportunity"),
                            ("success", "Great Decision"),
                            ("failure", "Failed Decision"),
                            ("review", "Needs Review"),
                        ],
                        default="interesting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="core.decisionpoint",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="core.agentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replay Bookmark",
                "verbose_name_plural": "Replay Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThoughtBubble",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "thought_type",
                    models.CharField(
                        choices=[
                            ("observation", "Observing"),
                            ("hypothesis", "Forming Hypothesis"),
                            ("evaluation", "Evaluating Options"),
                            ("concern", "Expressing Concern"),
                            ("insight", "Having Insight"),
                            ("memory", "Recalling Memory"),
                            ("preference", "Applying Preference"),
                            ("constraint", "Noting Constraint"),
                            ("goal", "Clarifying Goal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("importance", models.FloatField(default=0.5)),
                ("influences_decision", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thoughts",
                        to="core.decisionpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thought Bubble",
                "verbose_name_plural": "Thought Bubbles",
                "ordering": ["decision", "sequence_number"],
            },
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["agent", "-started_at"], name="core_agents_agent_i_b91e24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["status", "-started_at"], name="core_agents_status_67006f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentsession",
            index=models.Index(
                fields=["is_bookmarked", "-started_at"],
                name="core_agents_is_book_3656f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionpoint",
            index=models.Index(
                fields=["decision_type", "was_successful"],
                name="core_decisi_decisio_cff800_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionpoint",
            index=models.Index(
                fields=["is_flagged", "-timestamp"],
                name="core_decisi_is_flag_bf6dd0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="decisionpoint",
            unique_together={("session", "sequence_number")},
        ),
    ]
