# Generated by Django 4.2 on 2025-11-28
# Session 257: Agent Memory Clusters

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_session_256_agent_personality'),
    ]

    operations = [
        # Create MemoryCluster model
        migrations.CreateModel(
            name='MemoryCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='AI-generated name describing the cluster theme', max_length=200)),
                ('description', models.TextField(blank=True, help_text='AI-generated description of what this cluster represents')),
                ('keywords', models.JSONField(default=list, help_text='Key terms/concepts that define this cluster')),
                ('color', models.CharField(default='#8b5cf6', max_length=20)),
                ('icon', models.CharField(default='🧠', max_length=50)),
                ('centroid_embedding', models.JSONField(blank=True, help_text="Average embedding vector representing this cluster's center", null=True)),
                ('coherence_score', models.FloatField(default=0.0, help_text='How tightly clustered the memories are (0-1)')),
                ('stability_score', models.FloatField(default=0.0, help_text='How stable the cluster is across re-clustering (0-1)')),
                ('cluster_method', models.CharField(
                    choices=[
                        ('kmeans', 'K-Means'),
                        ('hierarchical', 'Hierarchical'),
                        ('dbscan', 'DBSCAN'),
                        ('semantic', 'Semantic Similarity'),
                        ('manual', 'Manually Curated'),
                    ],
                    default='semantic',
                    max_length=50
                )),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_clustered_at', models.DateTimeField(blank=True, null=True)),
                ('memory_count_at_clustering', models.PositiveIntegerField(default=0, help_text='Number of memories when last clustered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(
                    blank=True,
                    help_text='If null, this is a cross-agent cluster',
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memory_clusters',
                    to='core.agent'
                )),
                ('parent_cluster', models.ForeignKey(
                    blank=True,
                    help_text='For hierarchical clustering',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sub_clusters',
                    to='core.memorycluster'
                )),
                ('related_clusters', models.ManyToManyField(
                    blank=True,
                    help_text='Clusters with related themes',
                    to='core.memorycluster'
                )),
            ],
            options={
                'verbose_name': 'Memory Cluster',
                'verbose_name_plural': 'Memory Clusters',
                'ordering': ['-coherence_score', '-created_at'],
            },
        ),

        # Create MemoryClusterMembership through model
        migrations.CreateModel(
            name='MemoryClusterMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_to_centroid', models.FloatField(default=0.0, help_text='Cosine similarity to cluster centroid (0-1)')),
                ('is_core_member', models.BooleanField(default=False, help_text='Core members are closest to centroid')),
                ('position_x', models.FloatField(default=0.0)),
                ('position_y', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memberships',
                    to='core.memorycluster'
                )),
                ('memory', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='cluster_memberships',
                    to='core.agentmemory'
                )),
            ],
            options={
                'verbose_name': 'Memory Cluster Membership',
                'verbose_name_plural': 'Memory Cluster Memberships',
                'ordering': ['-similarity_to_centroid'],
                'unique_together': {('cluster', 'memory')},
            },
        ),

        # Add memories ManyToMany with through model
        migrations.AddField(
            model_name='memorycluster',
            name='memories',
            field=models.ManyToManyField(
                related_name='clusters',
                through='core.MemoryClusterMembership',
                to='core.agentmemory'
            ),
        ),

        # Create ClusterEvolution model
        migrations.CreateModel(
            name='ClusterEvolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(
                    choices=[
                        ('created', 'Cluster Created'),
                        ('merged', 'Clusters Merged'),
                        ('split', 'Cluster Split'),
                        ('grown', 'Cluster Grew'),
                        ('shrunk', 'Cluster Shrunk'),
                        ('dissolved', 'Cluster Dissolved'),
                    ],
                    max_length=50
                )),
                ('details', models.JSONField(default=dict, help_text='Additional details about the evolution')),
                ('memories_before', models.PositiveIntegerField(default=0)),
                ('memories_after', models.PositiveIntegerField(default=0)),
                ('coherence_before', models.FloatField(default=0.0)),
                ('coherence_after', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='cluster_evolutions',
                    to='core.agent'
                )),
                ('cluster', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='evolution_events',
                    to='core.memorycluster'
                )),
            ],
            options={
                'verbose_name': 'Cluster Evolution',
                'verbose_name_plural': 'Cluster Evolutions',
                'ordering': ['-created_at'],
            },
        ),

        # Add index to MemoryCluster
        migrations.AddIndex(
            model_name='memorycluster',
            index=models.Index(fields=['agent', 'coherence_score'], name='core_memory_agent_i_a7e8f2_idx'),
        ),
    ]
