# Generated by Django 5.0.6 on 2025-11-28 23:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_session_259_time_capsules"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("decision_summary", "Decision Summary"),
                            ("framework", "Named Framework"),
                            ("feature_spec", "Feature Specification"),
                            ("action_plan", "Action Plan"),
                            ("insight_list", "Insight List"),
                            ("trade_off_analysis", "Trade-off Analysis"),
                        ],
                        default="decision_summary",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Structured content of the artifact"
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list, help_text="List of insights from the conversation"
                    ),
                ),
                (
                    "proposed_feature",
                    models.JSONField(
                        default=dict, help_text="Proposed feature specification"
                    ),
                ),
                (
                    "next_steps",
                    models.JSONField(
                        default=list, help_text="Action items from the conversation"
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        default=0,
                        help_text="Quality score (0-100) from conversation validation",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "tension_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of tension/disagreement instances in conversation",
                    ),
                ),
                (
                    "grounding_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of platform grounding references in conversation",
                    ),
                ),
                (
                    "grounding_refs",
                    models.JSONField(
                        default=list,
                        help_text="List of platform metrics and systems referenced",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the conversation met all contract requirements",
                    ),
                ),
                (
                    "validation_issues",
                    models.JSONField(
                        default=list, help_text="List of validation issues if any"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conversation Artifact",
                "verbose_name_plural": "Conversation Artifacts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="agentprediction",
            new_name="core_agentp_agent_i_9bfbe6_idx",
            old_name="core_agentp_agent_i_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprediction",
            new_name="core_agentp_status_8ee86b_idx",
            old_name="core_agentp_status__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprediction",
            new_name="core_agentp_categor_b36d3c_idx",
            old_name="core_agentp_categor_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprediction",
            new_name="core_agentp_deadlin_5020ed_idx",
            old_name="core_agentp_deadlin_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="agentprediction",
            new_name="core_agentp_is_feat_12717f_idx",
            old_name="core_agentp_is_feat_m3n4o5_idx",
        ),
        migrations.RenameIndex(
            model_name="memorycluster",
            new_name="core_memory_agent_i_4faad3_idx",
            old_name="core_memory_agent_i_a7e8f2_idx",
        ),
        migrations.RenameIndex(
            model_name="timecapsule",
            new_name="core_timeca_agent_i_4105d0_idx",
            old_name="core_timeca_agent_i_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="timecapsule",
            new_name="core_timeca_status_ab71f8_idx",
            old_name="core_timeca_status__d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="timecapsule",
            new_name="core_timeca_reveal__e17ed1_idx",
            old_name="core_timeca_reveal__g7h8i9_idx",
        ),
        migrations.AddField(
            model_name="conversationartifact",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artifacts",
                to="core.agentconversation",
            ),
        ),
    ]
