# Generated by Django 5.0.6 on 2025-11-29 02:44

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_autonomy_engine_phase6"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningCompanion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "charter",
                    models.TextField(
                        blank=True,
                        help_text="User's one-sentence description of their ideal learning companion",
                    ),
                ),
                ("charter_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "active_track",
                    models.CharField(
                        choices=[
                            ("tech_trends", "Tech Trends → Shippable Experiments"),
                            ("ai_design", "AI + Design for Branding"),
                            ("agentic_ai", "Agentic AI Systems"),
                            ("creative_ops", "Creative Operations"),
                            ("custom", "Custom Track"),
                        ],
                        default="tech_trends",
                        max_length=50,
                    ),
                ),
                (
                    "custom_track_description",
                    models.TextField(
                        blank=True, help_text="Description for custom tracks"
                    ),
                ),
                (
                    "session_format",
                    models.CharField(
                        default="micro_lesson",
                        help_text="Preferred format: micro_lesson, deep_dive, action_focused",
                        max_length=50,
                    ),
                ),
                (
                    "preferred_length",
                    models.CharField(
                        default="medium",
                        help_text="Preferred content length: short, medium, long",
                        max_length=20,
                    ),
                ),
                (
                    "learning_frequency",
                    models.CharField(
                        default="daily",
                        help_text="How often: daily, weekly, on_demand",
                        max_length=20,
                    ),
                ),
                ("current_topic", models.CharField(blank=True, max_length=200)),
                ("current_trend_index", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_session_at", models.DateTimeField(blank=True, null=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_companion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Learning Companion",
                "verbose_name_plural": "Learning Companions",
            },
        ),
        migrations.CreateModel(
            name="TrackSpiderMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("track", models.CharField(max_length=50)),
                ("spider_category", models.CharField(max_length=50)),
                (
                    "relevance_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="How relevant this spider is for this track (0-2)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a primary spider for this track?",
                    ),
                ),
            ],
            options={
                "ordering": ["track", "-relevance_weight"],
                "unique_together": {("track", "spider_category")},
            },
        ),
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("trend_category", models.CharField(blank=True, max_length=100)),
                ("content_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("introduced", "Introduced"),
                            ("explored", "Explored"),
                            ("applied", "Applied"),
                            ("mastered", "Mastered"),
                        ],
                        default="introduced",
                        max_length=20,
                    ),
                ),
                ("action_suggested", models.TextField(blank=True)),
                ("action_completed", models.BooleanField(default=False)),
                ("action_result", models.TextField(blank=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("follow_up_questions", models.PositiveIntegerField(default=0)),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="User rating 1-5", null=True
                    ),
                ),
                ("related_project_id", models.UUIDField(blank=True, null=True)),
                (
                    "spider_categories_used",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "companion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="core.learningcompanion",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["companion", "-started_at"],
                        name="core_learni_compani_90454c_idx",
                    ),
                    models.Index(fields=["topic"], name="core_learni_topic_7bee2e_idx"),
                    models.Index(
                        fields=["status"], name="core_learni_status_ce7900_idx"
                    ),
                ],
            },
        ),
    ]
