# Generated by Django 5.0.6 on 2025-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_learning_companion_session266"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmemory",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of tags for memory grouping (replaces MemoryCluster)",
            ),
        ),
    ]
