# Generated by Django 5.0.6 on 2025-11-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_add_session_mode_to_hivemindsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderdata",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="Vector embedding for semantic search across all items",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="spiderdata",
            name="embedding_text",
            field=models.TextField(
                blank=True,
                help_text="The combined text used to generate the aggregate embedding",
            ),
        ),
        migrations.AddField(
            model_name="spiderdata",
            name="item_embeddings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Individual embeddings for each item: {index: embedding}",
            ),
        ),
    ]
