# Generated by Django 5.0.6 on 2025-12-01 04:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_add_business_research_result_with_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("3d_model", "3D Model"),
                            ("text", "Text/Document"),
                        ],
                        help_text="Type of content this provenance record covers",
                        max_length=20,
                    ),
                ),
                (
                    "image_history_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Link to ImageHistory if content_type is image",
                        null=True,
                    ),
                ),
                (
                    "video_history_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Link to VideoHistory if content_type is video",
                        null=True,
                    ),
                ),
                (
                    "audio_history_id",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Link to AudioHistory if content_type is audio",
                        null=True,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the content bytes",
                        max_length=64,
                    ),
                ),
                (
                    "perceptual_hash",
                    models.CharField(
                        blank=True,
                        help_text="Perceptual hash for similar-image detection (pHash)",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation_params",
                    models.JSONField(
                        default=dict,
                        help_text="Complete generation parameters (prompt, model, style, seed)",
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Digital signature proving creation timestamp",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.CharField(
                        default="sha256_hmac",
                        help_text="Algorithm used for signature",
                        max_length=20,
                    ),
                ),
                (
                    "derivative_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("original", "Original Creation"),
                            ("edit", "Edited Version"),
                            ("upscale", "Upscaled Version"),
                            ("variation", "Style Variation"),
                            ("composite", "Composite/Mashup"),
                        ],
                        default="original",
                        help_text="Type of derivative relationship",
                        max_length=30,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this provenance record has been verified",
                    ),
                ),
                (
                    "verification_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the verification was performed",
                        null=True,
                    ),
                ),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="User who created this content",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_provenance",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent provenance if this is a derivative work",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derivatives",
                        to="core.contentprovenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Provenance",
                "verbose_name_plural": "Content Provenance Records",
            },
        ),
        migrations.CreateModel(
            name="ContentAuditResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
                ("audit_version", models.CharField(default="1.0", max_length=10)),
                (
                    "overall_safety_score",
                    models.IntegerField(
                        help_text="Overall safety score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("bias_detected", models.BooleanField(default=False)),
                (
                    "bias_categories",
                    models.JSONField(
                        default=list, help_text="List of detected bias categories"
                    ),
                ),
                (
                    "bias_details",
                    models.TextField(
                        blank=True, help_text="Detailed explanation of detected biases"
                    ),
                ),
                (
                    "ethics_flags",
                    models.JSONField(
                        default=list, help_text="Ethical concerns flagged"
                    ),
                ),
                (
                    "representation_analysis",
                    models.JSONField(
                        default=dict, help_text="Analysis of representation in content"
                    ),
                ),
                (
                    "prompt_safety_score",
                    models.IntegerField(
                        default=100,
                        help_text="Safety score of the input prompt",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "prompt_suggestions",
                    models.JSONField(
                        default=list,
                        help_text="Suggested prompt modifications for less bias",
                    ),
                ),
                (
                    "model_known_biases",
                    models.JSONField(
                        default=list, help_text="Known biases of the model used"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Recommendations for creator"
                    ),
                ),
                (
                    "provenance",
                    models.ForeignKey(
                        help_text="Provenance record being audited",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.contentprovenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Audit Result",
                "verbose_name_plural": "Content Audit Results",
                "ordering": ["-audited_at"],
            },
        ),
        migrations.CreateModel(
            name="OriginalityScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "overall_originality",
                    models.IntegerField(
                        help_text="Overall originality score (0-100, higher = more original)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "prompt_originality",
                    models.IntegerField(
                        default=50,
                        help_text="How unique is the prompt compared to common prompts",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "style_originality",
                    models.IntegerField(
                        default=50,
                        help_text="How unique is the style choice",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "composition_originality",
                    models.IntegerField(
                        default=50,
                        help_text="How unique is the composition/layout",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trend_similarity",
                    models.IntegerField(
                        default=50,
                        help_text="How similar to current trending content (higher = more similar)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trending_elements_used",
                    models.JSONField(
                        default=list,
                        help_text="List of trending elements found in this content",
                    ),
                ),
                (
                    "generic_patterns_detected",
                    models.JSONField(
                        default=list,
                        help_text="Generic AI patterns detected (e.g., 'smooth skin', 'perfect lighting')",
                    ),
                ),
                (
                    "differentiation_suggestions",
                    models.JSONField(
                        default=list,
                        help_text="Suggestions to make content more unique",
                    ),
                ),
                (
                    "alternative_prompts",
                    models.JSONField(
                        default=list,
                        help_text="Alternative prompt suggestions for more originality",
                    ),
                ),
                (
                    "similar_content_count",
                    models.IntegerField(
                        default=0,
                        help_text="Estimated number of similar AI-generated content",
                    ),
                ),
                (
                    "uniqueness_percentile",
                    models.IntegerField(
                        default=50,
                        help_text="Percentile ranking (100 = most unique)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "provenance",
                    models.ForeignKey(
                        help_text="Provenance record being scored",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="originality_scores",
                        to="core.contentprovenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Originality Score",
                "verbose_name_plural": "Originality Scores",
                "ordering": ["-scored_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentprovenance",
            index=models.Index(
                fields=["content_hash"], name="core_conten_content_898747_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprovenance",
            index=models.Index(
                fields=["creator", "created_at"], name="core_conten_creator_172b3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprovenance",
            index=models.Index(
                fields=["content_type", "created_at"],
                name="core_conten_content_dbb804_idx",
            ),
        ),
    ]
