# Generated by Django 5.0.6 on 2025-12-03 01:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_add_userpreference_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Channel name (e.g., #brand-strategy, #content-creation)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this channel is for"),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("project", "Project Channel"),
                            ("topic", "Topic Channel"),
                            ("workflow", "Workflow Channel"),
                            ("team", "Team Channel"),
                            ("announcement", "Announcements"),
                            ("emergency", "Emergency Response"),
                        ],
                        default="topic",
                        max_length=30,
                    ),
                ),
                (
                    "project_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Associated project ID (if project channel)",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Whether any agent can join"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Archived channels are read-only"
                    ),
                ),
                (
                    "auto_invite_types",
                    models.JSONField(
                        default=list,
                        help_text="Agent types to auto-invite (e.g., ['strategy', 'creative'])",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        help_text="Current channel topic/focus",
                        max_length=200,
                    ),
                ),
                (
                    "pinned_messages",
                    models.JSONField(
                        default=list, help_text="List of pinned message IDs"
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("member_count", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent that created this channel",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_channels",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Channel",
                "verbose_name_plural": "Agent Channels",
                "ordering": ["-last_activity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Channel Owner"),
                            ("admin", "Channel Admin"),
                            ("member", "Member"),
                            ("guest", "Guest"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("messages_sent", models.IntegerField(default=0)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("last_posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "presence_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("idle", "Idle"),
                            ("away", "Away"),
                            ("dnd", "Do Not Disturb"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_memberships",
                        to="core.agent",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.agentchannel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Membership",
                "verbose_name_plural": "Channel Memberships",
                "unique_together": {("channel", "agent")},
            },
        ),
        migrations.CreateModel(
            name="ChannelMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(help_text="The message text")),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("message", "Regular Message"),
                            ("insight", "Insight"),
                            ("question", "Question"),
                            ("answer", "Answer"),
                            ("announcement", "Announcement"),
                            ("action_item", "Action Item"),
                            ("decision", "Decision Made"),
                            ("summary", "Summary"),
                            ("system", "System Message"),
                        ],
                        default="message",
                        max_length=30,
                    ),
                ),
                ("reply_count", models.IntegerField(default=0)),
                (
                    "reactions",
                    models.JSONField(
                        default=dict,
                        help_text="Reactions from agents: {'emoji': ['agent_id1', 'agent_id2']}",
                    ),
                ),
                (
                    "referenced_knowledge",
                    models.JSONField(
                        default=list,
                        help_text="List of AgentKnowledgeSource IDs referenced",
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        default=list, help_text="List of attachment metadata"
                    ),
                ),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.8,
                        help_text="How relevant/useful was this message",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_posts",
                        to="core.agent",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_messages",
                        to="core.agentchannel",
                    ),
                ),
                (
                    "mentioned_agents",
                    models.ManyToManyField(
                        blank=True, related_name="channel_mentions", to="core.agent"
                    ),
                ),
                (
                    "thread_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thread_replies",
                        to="core.channelmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel Message",
                "verbose_name_plural": "Channel Messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"],
                        name="core_channe_channel_749f39_idx",
                    ),
                    models.Index(
                        fields=["agent", "created_at"],
                        name="core_channe_agent_i_e352ac_idx",
                    ),
                    models.Index(
                        fields=["thread_parent"], name="core_channe_thread__084842_idx"
                    ),
                ],
            },
        ),
    ]
