# Generated by Django 5.0.6 on 2025-12-03 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_session_319_agent_slack_channels"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentDecisionSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy"),
                            ("architecture", "Architecture"),
                            ("pipeline", "Pipeline"),
                            ("product", "Product Feature"),
                            ("experiment", "Experiment"),
                            ("guideline", "Guideline"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "impact_area",
                    models.CharField(
                        choices=[
                            ("prompting", "Prompt Engineering"),
                            ("memory", "Memory & Storage"),
                            ("image", "Image Generation"),
                            ("video", "Video Generation"),
                            ("audio", "Audio Generation"),
                            ("workflow", "Workflows"),
                            ("agents", "Agent Behavior"),
                            ("security", "Security & Privacy"),
                            ("infrastructure", "Infrastructure"),
                            ("product", "Product/UX"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key_insights", models.JSONField(default=list)),
                ("recommended_stance", models.TextField()),
                ("suggested_feature", models.TextField(blank=True)),
                ("rationale", models.TextField(blank=True)),
                ("participants", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("canonical", "Canonical Policy"),
                            ("experiment", "Active Experiment"),
                            ("superseded", "Superseded"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_canonical", models.BooleanField(default=False)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("promoted_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="core.agentconversation",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="core.agentdecisionsummary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Decision Summary",
                "verbose_name_plural": "Agent Decision Summaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["decision_type", "impact_area"],
                        name="core_agentd_decisio_e12a99_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_agentd_status_88df1f_idx"
                    ),
                    models.Index(
                        fields=["is_canonical"], name="core_agentd_is_cano_d3481e_idx"
                    ),
                ],
            },
        ),
    ]
