# Generated by Django 5.0.6 on 2025-12-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_session_324_unified_project_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessresearchresult",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this research is linked to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_reports",
                to="core.partnershipproject",
            ),
        ),
    ]
