# Generated by Django 5.0.6 on 2025-12-03 07:39
# Session 452: Fixed duplicate SpiderCategory creation - already exists from migration 0035

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_businessresearchresult_project"),
    ]

    operations = [
        # Session 452: SpiderCategory already created in migration 0035_spider_agent_connections.py
        # Use SeparateDatabaseAndState to add it to state without trying to create it again
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SpiderCategory",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("slug", models.SlugField(unique=True)),
                        ("name", models.CharField(max_length=100)),
                        ("description", models.TextField(blank=True)),
                        ("icon", models.CharField(default="🕷️", max_length=10)),
                    ],
                    options={
                        "verbose_name_plural": "Spider Categories",
                    },
                ),
            ],
            database_operations=[
                # No-op - table already exists from migration 0035
            ],
        ),
        migrations.CreateModel(
            name="ProjectResearchFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("accept", "Accepted - Useful"),
                            ("reject", "Rejected - Not Useful"),
                            ("partial", "Partially Useful"),
                            ("starred", "Starred - Excellent"),
                        ],
                        default="accept",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=3,
                        help_text="1-5 star rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why was this research useful/not useful?"
                    ),
                ),
                (
                    "feedback_context",
                    models.JSONField(
                        default=dict,
                        help_text="Context: {section: 'competitors', item: 'Jasper AI', reason: 'outdated'}",
                    ),
                ),
                (
                    "applied_to_knowledge",
                    models.BooleanField(
                        default=False,
                        help_text="Has this feedback been applied to agent knowledge?",
                    ),
                ),
                (
                    "knowledge_delta",
                    models.FloatField(
                        default=0.0, help_text="Confidence adjustment made (-1 to +1)"
                    ),
                ),
                (
                    "affected_knowledge_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(),
                        default=list,
                        help_text="IDs of AgentKnowledgeSource entries affected by this feedback",
                        size=None,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSpiderPriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority_weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight multiplier for this category (1.0 = normal)",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "matched_keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Keywords that matched this project to this category",
                        size=None,
                    ),
                ),
                (
                    "data_used_count",
                    models.IntegerField(
                        default=0,
                        help_text="How many spider data points were used from this category",
                    ),
                ),
                (
                    "useful_data_count",
                    models.IntegerField(
                        default=0,
                        help_text="How many were marked useful by user feedback",
                    ),
                ),
                (
                    "is_auto_detected",
                    models.BooleanField(
                        default=True,
                        help_text="Was this priority auto-detected from project content?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority_weight"],
            },
        ),
        migrations.AddField(
            model_name="agentknowledgesource",
            name="feedback_adjusted_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence after user feedback adjustments",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentknowledgesource",
            name="feedback_negative",
            field=models.IntegerField(
                default=0, help_text="Count of negative feedback"
            ),
        ),
        migrations.AddField(
            model_name="agentknowledgesource",
            name="feedback_positive",
            field=models.IntegerField(
                default=0, help_text="Count of positive feedback"
            ),
        ),
        migrations.AddField(
            model_name="agentknowledgesource",
            name="source_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this knowledge was derived from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_knowledge",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="agentknowledgesource",
            name="source_research",
            field=models.ForeignKey(
                blank=True,
                help_text="Research result this knowledge was derived from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_knowledge",
                to="core.businessresearchresult",
            ),
        ),
        migrations.AddIndex(
            model_name="agentknowledgesource",
            index=models.Index(
                fields=["source_project"], name="core_agentk_source__968028_idx"
            ),
        ),
        migrations.AddField(
            model_name="projectresearchfeedback",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_feedback",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="projectresearchfeedback",
            name="research",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific research result this feedback applies to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback",
                to="core.businessresearchresult",
            ),
        ),
        migrations.AddField(
            model_name="projectresearchfeedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectspiderpriority",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spider_priorities",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="projectspiderpriority",
            name="spider_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_priorities",
                to="core.spidercategory",
            ),
        ),
        migrations.AddIndex(
            model_name="projectresearchfeedback",
            index=models.Index(
                fields=["project", "feedback_type"],
                name="core_projec_project_2a5937_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectresearchfeedback",
            index=models.Index(
                fields=["research"], name="core_projec_researc_4d6082_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectresearchfeedback",
            index=models.Index(
                fields=["user", "-created_at"], name="core_projec_user_id_eb1655_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectspiderpriority",
            unique_together={("project", "spider_category")},
        ),
    ]
