# Generated by Django 4.2 on 2025-12-03
# Session 327: Project-Scoped Agent Intelligence

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Session 327: Add project field to agent intelligence models.

    This enables filtering agent activity (conversations, decisions, learning)
    by project, so each project becomes its own intelligence hub.
    """

    dependencies = [
        ('core', '0065_session_326_project_agent_learning_bridge'),
    ]

    operations = [
        # Add project field to HiveMindSession (for conversations)
        migrations.AddField(
            model_name='hivemindsession',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hive_sessions',
                to='core.partnershipproject',
                help_text='Session 327: Optional project context for this session'
            ),
        ),

        # Add project field to AgentDecisionSummary (for boardroom)
        migrations.AddField(
            model_name='agentdecisionsummary',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='boardroom_decisions',
                to='core.partnershipproject',
                help_text='Session 327: Optional project context for this decision'
            ),
        ),

        # Add project field to AgentDream (for dreams - even though deprecated, for completeness)
        migrations.AddField(
            model_name='agentdream',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agent_dreams',
                to='core.partnershipproject',
                help_text='Session 327: Optional project context for this dream'
            ),
        ),

        # Add project field to AgentConversation (legacy, for completeness)
        migrations.AddField(
            model_name='agentconversation',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agent_conversations',
                to='core.partnershipproject',
                help_text='Session 327: Optional project context for this conversation'
            ),
        ),
    ]
