# Generated by Django 5.0.6 on 2025-12-04 01:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_session_327_project_agent_intelligence"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivingProjectConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this project actively learning?"
                    ),
                ),
                (
                    "watch_topics",
                    models.JSONField(
                        default=list, help_text="Topics to monitor across the ecosystem"
                    ),
                ),
                (
                    "watch_competitors",
                    models.JSONField(
                        default=list, help_text="Competitor names to track"
                    ),
                ),
                (
                    "watch_keywords",
                    models.JSONField(
                        default=list, help_text="Keywords to watch for in spider data"
                    ),
                ),
                (
                    "enabled_sources",
                    models.JSONField(
                        default=list, help_text="Which sources to pull insights from"
                    ),
                ),
                (
                    "spider_categories",
                    models.JSONField(
                        default=list, help_text="Which spider categories to prioritize"
                    ),
                ),
                (
                    "min_relevance_score",
                    models.FloatField(
                        default=0.6,
                        help_text="Minimum relevance score to surface insight",
                    ),
                ),
                (
                    "min_confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Minimum confidence score to surface insight",
                    ),
                ),
                ("notify_on_competitor", models.BooleanField(default=True)),
                ("notify_on_opportunity", models.BooleanField(default=True)),
                ("notify_on_trend", models.BooleanField(default=True)),
                (
                    "max_daily_insights",
                    models.IntegerField(
                        default=10, help_text="Maximum insights to surface per day"
                    ),
                ),
                (
                    "auto_expand_topics",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically add related topics based on insights",
                    ),
                ),
                (
                    "learn_from_ratings",
                    models.BooleanField(
                        default=True,
                        help_text="Adjust relevance scoring based on user ratings",
                    ),
                ),
                ("total_insights_surfaced", models.IntegerField(default=0)),
                ("total_insights_acted_on", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_insight_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="living_config",
                        to="core.partnershipproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("spider_data", "Spider Data"),
                            ("competitor", "Competitor Alert"),
                            ("trend", "Market Trend"),
                            ("pain_point", "Pain Point"),
                            ("opportunity", "Opportunity"),
                            ("agent_insight", "Agent Insight"),
                            ("decision", "Decision"),
                            ("dream", "Creative Idea"),
                            ("learning", "Learning"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField()),
                ("details", models.JSONField(default=dict)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("spider", "Spider Network"),
                            ("agent_conversation", "Agent Conversation"),
                            ("agent_decision", "Agent Decision"),
                            ("agent_learning", "Agent Learning"),
                            ("agent_dream", "Agent Dream"),
                            ("user_research", "User Research"),
                            ("system", "System Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=200)),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.5,
                        help_text="How relevant is this to the project (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="How confident are we in this insight (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "matched_topics",
                    models.JSONField(
                        default=list,
                        help_text="Which project topics triggered this match",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("seen", "Seen"),
                            ("acted_on", "Acted On"),
                            ("dismissed", "Dismissed"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User's rating of this insight (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_notes", models.TextField(blank=True)),
                (
                    "actions_taken",
                    models.JSONField(
                        default=list,
                        help_text="Actions user took based on this insight",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("acted_on_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="core.partnershipproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="core_projec_project_a3d4de_idx",
                    ),
                    models.Index(
                        fields=["project", "insight_type"],
                        name="core_projec_project_bde99d_idx",
                    ),
                    models.Index(
                        fields=["project", "-created_at"],
                        name="core_projec_project_4caad6_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="core_projec_source__29900c_idx",
                    ),
                ],
            },
        ),
    ]
