# Generated by Django 5.0.6 on 2025-12-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_living_project_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnershipproject",
            name="last_learning_run",
            field=models.DateTimeField(
                blank=True, help_text="When the last learning cycle ran", null=True
            ),
        ),
        migrations.AddField(
            model_name="partnershipproject",
            name="learning_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable continuous learning for this project"
            ),
        ),
        migrations.AddField(
            model_name="partnershipproject",
            name="learning_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Every 2 Weeks"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
                help_text="How often to run learning cycles",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="partnershipproject",
            name="learning_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="History of learning runs: [{date, findings_count, deltas}]",
            ),
        ),
        migrations.AddField(
            model_name="partnershipproject",
            name="learning_topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Topics to track: ['coffee trends', 'specialty drinks']",
            ),
        ),
        migrations.AddField(
            model_name="partnershipproject",
            name="next_learning_run",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next learning cycle should run",
                null=True,
            ),
        ),
    ]
