# Generated by Django 5.0.6 on 2025-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_session_362_decision_quality_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdecisionsummary",
            name="propagated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentconversation",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("learning_transfer", "During Knowledge Transfer"),
                    ("synthesis", "During Synthesis"),
                    ("scheduled", "Scheduled Discussion"),
                    ("user_triggered", "User Initiated"),
                    ("anomaly", "Anomaly Detected"),
                    ("opportunity", "New Opportunity"),
                    ("spider_data", "New Spider Data"),
                    ("project_need", "Project Research Need"),
                ],
                default="scheduled",
                max_length=50,
            ),
        ),
    ]
