# Generated by Django 5.0.6 on 2025-12-05 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_session_366_dream_productization"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamImplementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Assignment"),
                            ("assigned", "Agent Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("validated", "User Validated"),
                            ("rejected", "Rejected/Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "implementation_type",
                    models.CharField(
                        choices=[
                            ("feature", "New Feature"),
                            ("improvement", "Improvement/Enhancement"),
                            ("content", "Content Creation"),
                            ("research", "Research/Analysis"),
                            ("experiment", "Experiment"),
                            ("workflow", "Workflow Automation"),
                            ("other", "Other"),
                        ],
                        default="feature",
                        max_length=30,
                    ),
                ),
                (
                    "implementation_plan",
                    models.TextField(
                        blank=True,
                        help_text="Step-by-step plan to implement this dream",
                    ),
                ),
                (
                    "deliverable_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of deliverable (code, document, image, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "deliverable_path",
                    models.CharField(
                        blank=True,
                        help_text="Path or URL to the deliverable",
                        max_length=500,
                    ),
                ),
                (
                    "deliverable_summary",
                    models.TextField(
                        blank=True, help_text="Summary of what was delivered"
                    ),
                ),
                (
                    "effort_estimate",
                    models.CharField(
                        blank=True,
                        help_text="Estimated effort (small/medium/large)",
                        max_length=20,
                    ),
                ),
                (
                    "actual_effort",
                    models.CharField(
                        blank=True, help_text="Actual effort spent", max_length=20
                    ),
                ),
                (
                    "quality_rating",
                    models.FloatField(
                        blank=True,
                        help_text="User rating of implementation quality (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True, help_text="User feedback on the implementation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent assigned to implement this dream",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dream_implementations",
                        to="core.agent",
                    ),
                ),
                (
                    "dream",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="implementation",
                        to="core.agentdream",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project this implementation is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dream_implementations",
                        to="core.partnershipproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dream Implementation",
                "verbose_name_plural": "Dream Implementations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_dreami_status_21c39a_idx",
                    ),
                    models.Index(
                        fields=["assigned_agent", "status"],
                        name="core_dreami_assigne_5a1fb5_idx",
                    ),
                ],
            },
        ),
    ]
