# Generated by Django 5.0.6 on 2025-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_session_367_dream_implementation"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamimplementation",
            name="deliverable_content",
            field=models.TextField(
                blank=True,
                help_text="Full content of the deliverable (report, spec, etc.)",
            ),
        ),
    ]
