# Generated by Django 5.0.6 on 2025-12-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_add_deliverable_content_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreamimplementation",
            name="generated_media",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of generated images/videos [{id, url, prompt, type}]",
            ),
        ),
        migrations.AlterField(
            model_name="dreamimplementation",
            name="implementation_type",
            field=models.CharField(
                choices=[
                    ("feature", "New Feature"),
                    ("improvement", "Improvement/Enhancement"),
                    ("content", "Content Creation"),
                    ("research", "Research/Analysis"),
                    ("experiment", "Experiment"),
                    ("workflow", "Workflow Automation"),
                    ("visual", "Visual/Image Creation"),
                    ("other", "Other"),
                ],
                default="feature",
                max_length=30,
            ),
        ),
    ]
