# Generated by Django 5.0.6 on 2025-12-10 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_legal_case_intake_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseKnowledgeGraph",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parties",
                    models.JSONField(
                        default=dict,
                        help_text="All parties mentioned: {name: {role, mentions, documents}}",
                    ),
                ),
                (
                    "timeline",
                    models.JSONField(
                        default=list,
                        help_text="Chronological events: [{date, event, source_document, category}]",
                    ),
                ),
                (
                    "allegations",
                    models.JSONField(
                        default=dict,
                        help_text="Allegations by party: {party: [{allegation, document, date, contradicts}]}",
                    ),
                ),
                (
                    "legal_issues",
                    models.JSONField(
                        default=list,
                        help_text="List of legal issues: [{issue, related_documents, status}]",
                    ),
                ),
                (
                    "claims",
                    models.JSONField(
                        default=dict,
                        help_text="Claims by party: {party: [{claim, document, evidence}]}",
                    ),
                ),
                (
                    "relief_requested",
                    models.JSONField(
                        default=dict,
                        help_text="Relief by motion: {motion_id: [{relief_type, specifics}]}",
                    ),
                ),
                (
                    "evidence_referenced",
                    models.JSONField(
                        default=dict,
                        help_text="Evidence items: {evidence_id: {type, description, supports, contradicts}}",
                    ),
                ),
                (
                    "contradictions",
                    models.JSONField(
                        default=list,
                        help_text="Cross-document contradictions: [{doc1, claim1, doc2, claim2, analysis}]",
                    ),
                ),
                (
                    "procedural_posture",
                    models.JSONField(
                        default=dict,
                        help_text="Current procedural state: {pending_motions, deadlines, next_hearing}",
                    ),
                ),
                (
                    "deadlines",
                    models.JSONField(
                        default=list,
                        help_text="Upcoming deadlines: [{date, motion, type, days_remaining}]",
                    ),
                ),
                (
                    "court_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Court-specific requirements: {rule: requirement}",
                    ),
                ),
                (
                    "unaddressed_issues",
                    models.JSONField(
                        default=list,
                        help_text="Issues not yet responded to: [{issue, source_document}]",
                    ),
                ),
                (
                    "misinformation",
                    models.JSONField(
                        default=list,
                        help_text="Potential misinformation: [{claim, document, contradicting_evidence}]",
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        default=dict,
                        help_text="Stats: {total_documents, pending_responses, contradictions_found}",
                    ),
                ),
                ("last_rebuilt", models.DateTimeField(auto_now=True)),
                ("rebuild_needed", models.BooleanField(default=True)),
                (
                    "case_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_graph",
                        to="core.caseprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Knowledge Graph",
                "verbose_name_plural": "Case Knowledge Graphs",
            },
        ),
        migrations.CreateModel(
            name="LitigationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("court_order", "Court Orders"),
                            ("motion", "Motions"),
                            ("response", "Responses/Replies"),
                            ("evidence", "Evidence"),
                            ("court_rule", "Court Rules"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("temporary_orders", "Temporary Orders"),
                            ("prior_parenting", "Prior Parenting Orders"),
                            ("status_quo", "Status Quo Orders"),
                            ("restriction", "Restrictions"),
                            ("emergency_ruling", "Emergency Ruling"),
                            ("permanent_orders", "Permanent Orders"),
                            ("separation_agreement", "Separation Agreement"),
                            ("parenting_plan", "Parenting Plan"),
                            ("support_order", "Support Order"),
                            ("protection_order", "Protection Order"),
                            ("my_motion", "Motion I Filed"),
                            ("opposing_motion", "Motion Filed by Opposing Party"),
                            ("pending_motion", "Pending Motion"),
                            ("response", "Response to Motion"),
                            ("reply", "Reply"),
                            ("exhibit_attachment", "Exhibit Attachment"),
                            ("affidavit", "Affidavit"),
                            ("messages", "Messages/Texts"),
                            ("call_logs", "Call Logs"),
                            ("calendar", "Calendar/Schedule"),
                            ("photos", "Photos"),
                            ("transcript", "Transcript"),
                            ("notes", "Notes"),
                            ("email_evidence", "Email Evidence"),
                            ("financial_record", "Financial Record"),
                            ("school_record", "School Record"),
                            ("medical_record", "Medical Record"),
                            ("crcp", "C.R.C.P. Rule"),
                            ("jdf_form", "JDF Form"),
                            ("local_standard", "Local Practice Standard"),
                            ("division_requirement", "Division-Specific Requirement"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "filing_party",
                    models.CharField(
                        choices=[
                            ("petitioner", "Petitioner (Me)"),
                            ("respondent", "Respondent (Opposing Party)"),
                            ("court", "Court"),
                            ("third_party", "Third Party"),
                        ],
                        default="petitioner",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="litigation_documents/"
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("file_size", models.IntegerField(default=0)),
                ("extracted_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("analyzed", "Analyzed"),
                            ("linked", "Linked to Case"),
                            ("responded", "Response Generated"),
                            ("archived", "Archived"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, help_text="Date on document", null=True
                    ),
                ),
                (
                    "filed_date",
                    models.DateField(
                        blank=True, help_text="Date filed with court", null=True
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True, help_text="Response deadline", null=True
                    ),
                ),
                (
                    "extracted_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Extracted: parties, dates, allegations, claims, relief requested",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litigation_documents",
                        to="core.caseprofile",
                    ),
                ),
                (
                    "responds_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="core.litigationdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Litigation Document",
                "verbose_name_plural": "Litigation Documents",
                "ordering": ["-filed_date", "-document_date", "-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "response_content",
                    models.TextField(
                        help_text="Main response (Admit/Deny/Insufficient)"
                    ),
                ),
                ("factual_corrections", models.TextField(blank=True)),
                ("legal_standard", models.TextField(blank=True)),
                ("argument", models.TextField(blank=True)),
                ("relief_requested", models.TextField(blank=True)),
                ("full_document", models.TextField(blank=True)),
                ("proposed_order", models.TextField(blank=True)),
                ("exhibits", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("filed", "Filed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("generation_context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_responses",
                        to="core.caseprofile",
                    ),
                ),
                (
                    "responds_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_responses",
                        to="core.litigationdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated Response",
                "verbose_name_plural": "Generated Responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExhibitList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Exhibit List", max_length=300)),
                (
                    "exhibits",
                    models.JSONField(
                        default=list,
                        help_text="[{number, letter, title, document_id, description, page_count}]",
                    ),
                ),
                ("formatted_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibit_lists",
                        to="core.caseprofile",
                    ),
                ),
                (
                    "for_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exhibit_lists",
                        to="core.litigationdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exhibit List",
                "verbose_name_plural": "Exhibit Lists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("responds_to", "Responds To"),
                            ("reply_to", "Reply To"),
                            ("exhibit_for", "Exhibit For"),
                            ("supersedes", "Supersedes"),
                            ("references", "References"),
                            ("contradicts", "Contradicts"),
                            ("supports", "Supports"),
                            ("amends", "Amends"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "confidence",
                    models.FloatField(default=1.0, help_text="0-1 confidence score"),
                ),
                ("auto_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relationships",
                        to="core.litigationdocument",
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relationships",
                        to="core.litigationdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Relationship",
                "verbose_name_plural": "Document Relationships",
            },
        ),
        migrations.CreateModel(
            name="CaseMemorandum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "memo_type",
                    models.CharField(
                        choices=[
                            ("case_summary", "Case Summary"),
                            ("status_report", "Status Report"),
                            ("trial_brief", "Trial Brief"),
                            ("settlement_summary", "Settlement Summary"),
                        ],
                        default="case_summary",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("executive_summary", models.TextField(blank=True)),
                ("procedural_history", models.TextField(blank=True)),
                ("factual_background", models.TextField(blank=True)),
                ("issues_presented", models.TextField(blank=True)),
                ("analysis", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("full_content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memoranda",
                        to="core.caseprofile",
                    ),
                ),
                (
                    "source_documents",
                    models.ManyToManyField(blank=True, to="core.litigationdocument"),
                ),
            ],
            options={
                "verbose_name": "Case Memorandum",
                "verbose_name_plural": "Case Memoranda",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="litigationdocument",
            index=models.Index(
                fields=["case_profile", "category"],
                name="core_litiga_case_pr_ac049a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="litigationdocument",
            index=models.Index(
                fields=["case_profile", "document_type"],
                name="core_litiga_case_pr_67f088_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="litigationdocument",
            index=models.Index(fields=["status"], name="core_litiga_status_e2a6c8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentrelationship",
            unique_together={
                ("source_document", "target_document", "relationship_type")
            },
        ),
    ]
