# Generated by Django 5.0.6 on 2025-12-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_session_408_litigation_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="litigationdocument",
            name="litigation_role",
            field=models.CharField(
                choices=[
                    ("motion", "Motion"),
                    ("response", "Response"),
                    ("reply", "Reply"),
                    ("order", "Court Order"),
                    ("exhibit", "Exhibit"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Role in litigation chain: motion, response, reply, order",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="litigationdocument",
            index=models.Index(
                fields=["case_profile", "filing_party"],
                name="core_litiga_case_pr_51664d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="litigationdocument",
            index=models.Index(
                fields=["case_profile", "litigation_role"],
                name="core_litiga_case_pr_aa3f8b_idx",
            ),
        ),
    ]
