# Generated by Django 5.1.3 on 2025-12-11
# Session 425: Opportunity Pipeline Automation

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0080_session_412_boardroom_decisions'),
    ]

    operations = [
        # OpportunityTask model
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[
                    ('pending', 'Pending Review'),
                    ('accepted', 'Task Accepted'),
                    ('in_progress', 'In Progress'),
                    ('applied', 'Applied/Submitted'),
                    ('waiting', 'Waiting for Response'),
                    ('won', 'Won/Accepted'),
                    ('lost', 'Lost/Rejected'),
                    ('expired', 'Expired'),
                    ('cancelled', 'Cancelled'),
                ], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[
                    ('low', 'Low'),
                    ('medium', 'Medium'),
                    ('high', 'High'),
                    ('urgent', 'Urgent'),
                ], default='medium', max_length=10)),
                ('opportunity_score', models.IntegerField(default=0)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('auto_created', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True)),
                ('action_items', models.JSONField(default=list, help_text='Suggested action steps')),
                ('metadata', models.JSONField(default=dict)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='core.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_tasks', to=settings.AUTH_USER_MODEL)),
                ('primary_agent', models.ForeignKey(blank=True, help_text='Lead agent for this opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_tasks', to='core.agent')),
                ('assigned_agents', models.ManyToManyField(blank=True, help_text='Agents that can help with this opportunity', related_name='assigned_tasks', to='core.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunitytask',
            index=models.Index(fields=['user', 'status'], name='core_opport_user_id_task_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitytask',
            index=models.Index(fields=['status', 'priority'], name='core_opport_status_pri_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunitytask',
            index=models.Index(fields=['due_date'], name='core_opport_due_date_idx'),
        ),
        
        # OpportunityOutcome model
        migrations.CreateModel(
            name='OpportunityOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[
                    ('won', 'Won/Accepted'),
                    ('lost', 'Lost/Rejected'),
                    ('expired', 'Expired Without Action'),
                    ('cancelled', 'Cancelled by User'),
                    ('partial', 'Partial Success'),
                ], max_length=20)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('predicted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revenue_variance', models.DecimalField(blank=True, decimal_places=2, help_text='Actual - Predicted', max_digits=12, null=True)),
                ('loss_reason', models.CharField(blank=True, choices=[
                    ('rejected', 'Application Rejected'),
                    ('underbid', 'Underbid by Competitor'),
                    ('not_qualified', 'Not Qualified'),
                    ('timing', 'Bad Timing'),
                    ('competition', 'Too Much Competition'),
                    ('no_response', 'No Response Received'),
                    ('changed_mind', 'Changed Mind'),
                    ('other', 'Other'),
                ], max_length=20)),
                ('days_to_outcome', models.IntegerField(blank=True, help_text='Days from task creation to outcome', null=True)),
                ('notes', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.opportunitytask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        
        # OpportunityDigest model
        migrations.CreateModel(
            name='OpportunityDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('digest_type', models.CharField(choices=[
                    ('weekly', 'Weekly Digest'),
                    ('monthly', 'Monthly Digest'),
                    ('ad_hoc', 'Ad-hoc Report'),
                ], default='weekly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_opportunities', models.IntegerField(default=0)),
                ('high_value_opportunities', models.IntegerField(default=0)),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_won', models.IntegerField(default=0)),
                ('tasks_lost', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('by_category', models.JSONField(default=dict)),
                ('by_source', models.JSONField(default=dict)),
                ('top_opportunities', models.JSONField(default=list)),
                ('win_rate', models.FloatField(default=0)),
                ('avg_score_won', models.FloatField(default=0)),
                ('avg_score_lost', models.FloatField(default=0)),
                ('digest_content', models.TextField(blank=True)),
                ('posted_to_discord', models.BooleanField(default=False)),
                ('discord_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User-specific digest (null for system-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('user', 'digest_type', 'period_start')},
            },
        ),
    ]
