# Generated by Django 5.0.6 on 2025-12-12 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_session_429_discord_linking"),
    ]

    operations = [
        migrations.AddField(
            model_name="unifieduser",
            name="discord_id",
            field=models.CharField(
                blank=True,
                help_text="Discord user ID for account linking",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="unifieduser",
            name="discord_linked_at",
            field=models.DateTimeField(
                blank=True, help_text="When Discord account was linked", null=True
            ),
        ),
        migrations.AddField(
            model_name="unifieduser",
            name="discord_username",
            field=models.CharField(
                blank=True,
                help_text="Discord username (cached for display)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="DiscordLinkCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_link_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
