# Generated by Django 5.0.6 on 2025-12-12 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_session_430_discord_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guild_id",
                    models.CharField(
                        help_text="Discord guild (server) ID",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "guild_name",
                    models.CharField(help_text="Discord server name", max_length=100),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("solo_creator", "Solo Creator"),
                            ("freelancer", "Freelancer"),
                            ("agency", "Agency"),
                            ("custom", "Custom"),
                        ],
                        default="solo_creator",
                        help_text="Server template used",
                        max_length=20,
                    ),
                ),
                (
                    "is_setup_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether server setup wizard is complete",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gallery_channel_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "assistant_channel_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "research_channel_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "opportunities_channel_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "notifications_channel_id",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_servers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Server",
                "verbose_name_plural": "Discord Servers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscordServerChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        help_text="Discord channel ID", max_length=30, unique=True
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(help_text="Channel name", max_length=100),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("gallery", "Gallery - Image deliveries"),
                            ("assistant", "Assistant - PA conversations"),
                            ("research", "Research - Spider data"),
                            ("opportunities", "Opportunities - Job alerts"),
                            ("notifications", "Notifications - System updates"),
                            ("dashboard", "Dashboard - Daily summaries"),
                            ("client", "Client - Client-specific channel"),
                            ("custom", "Custom"),
                        ],
                        help_text="Purpose of this channel",
                        max_length=20,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Client name (for client-type channels)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="core.discordserver",
                    ),
                ),
            ],
            options={
                "ordering": ["channel_type", "channel_name"],
            },
        ),
    ]
