# Generated by Django 5.0.6 on 2025-12-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_session_431_discord_server_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Client name", max_length=100)),
                (
                    "slug",
                    models.CharField(
                        help_text="URL-safe client identifier", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Client email for notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Discord channel ID for this client",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("deliverables_count", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue from this client",
                        max_digits=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the client"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="core.discordserver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Client",
                "verbose_name_plural": "Discord Clients",
                "ordering": ["name"],
                "unique_together": {("server", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ClientDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deliverable_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Deliverable title/description", max_length=200
                    ),
                ),
                (
                    "image_history_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of ImageHistory record if applicable",
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL to the deliverable", null=True
                    ),
                ),
                (
                    "discord_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Discord message ID where this was delivered",
                        max_length=30,
                        null=True,
                    ),
                ),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="core.discordclient",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
            },
        ),
    ]
