# Generated by Django 5.0.6 on 2025-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_session_431_client_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Direct link to opportunity listing",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="user_friendly_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="User-friendly sequential ID (e.g., 1, 2, 3)",
                null=True,
                unique=True,
            ),
        ),
    ]
