# Generated by Django migration - Session 437
# Discord Automation: Add alert settings to EnhancedUserProfile

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_session_433_opportunity_user_friendly_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='discord_alerts_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Enable proactive opportunity alerts via Discord'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='alert_min_score',
            field=models.IntegerField(
                default=70,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                help_text='Minimum opportunity score to trigger an alert (0-100)'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='alert_categories',
            field=models.JSONField(
                default=list,
                help_text='Categories to receive alerts for (empty = all)'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='last_alert_sent',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='Timestamp of last proactive alert sent'
            ),
        ),
    ]
