# Generated by Django migration - Session 438
# Monetization: Add subscription and tier fields to EnhancedUserProfile

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_session_437_discord_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='subscription_tier',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('free', 'Free'),
                    ('pro', 'Pro ($9.99/mo)'),
                    ('premium', 'Premium ($29.99/mo)'),
                ],
                default='free',
                help_text="User's subscription tier"
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='stripe_customer_id',
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                help_text='Stripe customer ID for billing'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='stripe_subscription_id',
            field=models.CharField(
                max_length=255,
                null=True,
                blank=True,
                help_text='Stripe subscription ID for recurring billing'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='subscription_status',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('active', 'Active'),
                    ('canceled', 'Canceled'),
                    ('past_due', 'Past Due'),
                    ('trialing', 'Trialing'),
                    ('incomplete', 'Incomplete'),
                ],
                default='active',
                help_text='Current subscription status'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='subscription_started_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='When subscription started'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='subscription_ends_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='When subscription ends (for canceled subscriptions)'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='discord_role_synced',
            field=models.BooleanField(
                default=False,
                help_text='Whether Discord role matches subscription tier'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='daily_task_count',
            field=models.IntegerField(
                default=0,
                help_text='Number of agent tasks used today'
            ),
        ),
        migrations.AddField(
            model_name='enhanceduserprofile',
            name='daily_task_reset',
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text='When daily task counter was last reset'
            ),
        ),
    ]
