# Generated by Django 5.0.6 on 2025-12-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_session_438_subscription_monetization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhanceduserprofile",
            name="alert_categories",
        ),
        migrations.RemoveField(
            model_name="enhanceduserprofile",
            name="alert_min_score",
        ),
        migrations.RemoveField(
            model_name="enhanceduserprofile",
            name="last_alert_sent",
        ),
        migrations.AlterField(
            model_name="enhanceduserprofile",
            name="discord_alerts_enabled",
            field=models.BooleanField(
                default=True, help_text="Whether to receive Discord opportunity alerts"
            ),
        ),
        migrations.AlterField(
            model_name="enhanceduserprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("premium", "Premium")],
                default="free",
                help_text="User's subscription tier",
                max_length=20,
            ),
        ),
    ]
