# Generated by Django 5.0.6 on 2025-12-14 04:42

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_session_439_subscription_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for the voice", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the voice character"
                    ),
                ),
                (
                    "elevenlabs_voice_id",
                    models.CharField(
                        help_text="ElevenLabs voice ID", max_length=100, unique=True
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("neutral", "Neutral"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("child", "Child (5-12)"),
                            ("teen", "Teen (13-19)"),
                            ("young_adult", "Young Adult (20-35)"),
                            ("adult", "Adult (35-55)"),
                            ("senior", "Senior (55+)"),
                        ],
                        default="adult",
                        max_length=20,
                    ),
                ),
                (
                    "accent",
                    models.CharField(
                        blank=True,
                        help_text="Accent (e.g., British, Southern US)",
                        max_length=50,
                    ),
                ),
                ("language", models.CharField(default="English", max_length=50)),
                (
                    "style_tags",
                    models.JSONField(
                        default=list,
                        help_text="Tags like 'warm', 'authoritative', 'friendly', 'narrator'",
                    ),
                ),
                (
                    "primary_use_case",
                    models.CharField(
                        choices=[
                            ("narration", "Narration/Audiobook"),
                            ("animation", "Animation/Character"),
                            ("commercial", "Commercial/Advertisement"),
                            ("podcast", "Podcast/YouTube"),
                            ("gaming", "Gaming/Character"),
                            ("assistant", "Virtual Assistant"),
                            ("general", "General Purpose"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this voice is available in the public marketplace",
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("per_minute", "Per Minute"),
                            ("per_character", "Per 1000 Characters"),
                            ("flat_rate", "Flat Rate per Generation"),
                        ],
                        default="per_minute",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Price per unit (minute, 1000 chars, or generation)",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "sample_audio_url",
                    models.URLField(
                        blank=True, help_text="URL to sample audio", null=True
                    ),
                ),
                (
                    "sample_text",
                    models.TextField(blank=True, help_text="Text used in the sample"),
                ),
                ("sample_duration_seconds", models.IntegerField(default=0)),
                ("total_uses", models.IntegerField(default=0)),
                ("total_characters_generated", models.IntegerField(default=0)),
                (
                    "total_minutes_generated",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("average_rating", models.FloatField(default=0.0)),
                ("rating_count", models.IntegerField(default=0)),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.5,
                        help_text="AI-assessed quality score 0-1",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verified by platform"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured in marketplace"
                    ),
                ),
                (
                    "creation_method",
                    models.CharField(
                        choices=[
                            ("discord_clone", "Cloned via Discord Recording"),
                            ("web_clone", "Cloned via Web Upload"),
                            ("elevenlabs_library", "From ElevenLabs Library"),
                            ("professional", "Professional Voice Actor"),
                        ],
                        default="discord_clone",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-average_rating", "-total_uses"],
            },
        ),
        migrations.CreateModel(
            name="VoiceCloneRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discord_user_id", models.CharField(max_length=50)),
                ("discord_guild_id", models.CharField(max_length=50)),
                ("discord_channel_id", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Recording"),
                            ("recording", "Recording"),
                            ("processing", "Processing"),
                            ("cloning", "Cloning with ElevenLabs"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("recording_started_at", models.DateTimeField(blank=True, null=True)),
                ("recording_ended_at", models.DateTimeField(blank=True, null=True)),
                ("recording_duration_seconds", models.IntegerField(default=0)),
                ("audio_file_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_clone_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_profile",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clone_request",
                        to="core.voiceprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="1-5 star rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("review_text", models.TextField(blank=True)),
                (
                    "use_case",
                    models.CharField(
                        blank=True,
                        help_text="What they used the voice for",
                        max_length=100,
                    ),
                ),
                (
                    "clarity_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Voice clarity 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "naturalness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="How natural it sounds 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "consistency_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Consistency across generations 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Whether reviewer actually used this voice",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.voiceprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoiceTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text_length",
                    models.IntegerField(help_text="Number of characters generated"),
                ),
                (
                    "audio_duration_seconds",
                    models.IntegerField(help_text="Duration of generated audio"),
                ),
                (
                    "generated_text",
                    models.TextField(
                        blank=True, help_text="Text that was converted to speech"
                    ),
                ),
                (
                    "gross_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Total price charged", max_digits=8
                    ),
                ),
                (
                    "platform_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="30% platform fee", max_digits=8
                    ),
                ),
                (
                    "owner_payout",
                    models.DecimalField(
                        decimal_places=2, help_text="70% to voice owner", max_digits=8
                    ),
                ),
                (
                    "payout_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payout_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("stripe_transfer_id", models.CharField(blank=True, max_length=100)),
                (
                    "project_id",
                    models.UUIDField(
                        blank=True, help_text="Associated project if any", null=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("animated_series", "Animated Series"),
                            ("audiobook", "Audiobook"),
                            ("video", "Video Narration"),
                            ("podcast", "Podcast"),
                            ("commercial", "Commercial"),
                            ("personal", "Personal Use"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="core.voiceprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voiceprofile",
            index=models.Index(
                fields=["owner", "is_public"], name="core_voicep_owner_i_2f0dfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprofile",
            index=models.Index(
                fields=["is_public", "is_active", "-average_rating"],
                name="core_voicep_is_publ_c47f55_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voiceprofile",
            index=models.Index(
                fields=["gender", "age_range", "primary_use_case"],
                name="core_voicep_gender_26b769_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voicereview",
            index=models.Index(
                fields=["voice", "-created_at"], name="core_voicer_voice_i_a0f125_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicereview",
            index=models.Index(
                fields=["voice", "is_active", "-rating"],
                name="core_voicer_voice_i_74582d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voicereview",
            unique_together={("voice", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="voicetransaction",
            index=models.Index(
                fields=["voice", "-created_at"], name="core_voicet_voice_i_fea568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicetransaction",
            index=models.Index(
                fields=["buyer", "-created_at"], name="core_voicet_buyer_i_d77f32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicetransaction",
            index=models.Index(
                fields=["payout_status", "-created_at"],
                name="core_voicet_payout__f281fe_idx",
            ),
        ),
    ]
