# Generated by Django 5.0.6 on 2025-12-14 05:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_session_440_voice_marketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentShowroom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guild_id", models.CharField(max_length=100)),
                ("channel_id", models.CharField(max_length=100, unique=True)),
                ("channel_name", models.CharField(max_length=100)),
                (
                    "tier_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "quick",
                                "Quick ($5-29) - Birthday messages, simple content",
                            ),
                            ("ad", "Ad ($29-99) - Small business ads"),
                            ("brand", "Brand ($99-499) - Full brand packages"),
                            ("series", "Series ($499-2999) - Content series"),
                            ("pitch", "Pitch ($2999-9999) - Series/movie pitches"),
                            ("production", "Production ($9999+) - Full productions"),
                        ],
                        help_text="Only show this tier (null = all)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "category_filter",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("restaurant", "Restaurant & Food"),
                            ("retail", "Retail & Shopping"),
                            ("healthcare", "Healthcare & Medical"),
                            ("education", "Education & Schools"),
                            ("tech", "Tech & Startups"),
                            ("entertainment", "Entertainment & Media"),
                            ("realestate", "Real Estate"),
                            ("fitness", "Fitness & Wellness"),
                            ("finance", "Finance & Banking"),
                            ("nonprofit", "Nonprofit & Charity"),
                            ("personal", "Personal & Events"),
                            ("other", "Other"),
                        ],
                        help_text="Only show this category (null = all)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("max_items", models.IntegerField(default=50)),
                (
                    "auto_refresh",
                    models.BooleanField(
                        default=True, help_text="Auto-post new content"
                    ),
                ),
                ("show_prices", models.BooleanField(default=True)),
                ("show_previews", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Content showrooms",
            },
        ),
        migrations.CreateModel(
            name="ContentPackage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            (
                                "quick",
                                "Quick ($5-29) - Birthday messages, simple content",
                            ),
                            ("ad", "Ad ($29-99) - Small business ads"),
                            ("brand", "Brand ($99-499) - Full brand packages"),
                            ("series", "Series ($499-2999) - Content series"),
                            ("pitch", "Pitch ($2999-9999) - Series/movie pitches"),
                            ("production", "Production ($9999+) - Full productions"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant & Food"),
                            ("retail", "Retail & Shopping"),
                            ("healthcare", "Healthcare & Medical"),
                            ("education", "Education & Schools"),
                            ("tech", "Tech & Startups"),
                            ("entertainment", "Entertainment & Media"),
                            ("realestate", "Real Estate"),
                            ("fitness", "Fitness & Wellness"),
                            ("finance", "Finance & Banking"),
                            ("nonprofit", "Nonprofit & Charity"),
                            ("personal", "Personal & Events"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(help_text="Original creation prompt")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "discount_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued for generation"),
                            ("generating", "Currently generating"),
                            ("ready", "Ready for sale/delivery"),
                            ("sold", "Sold (pending delivery)"),
                            ("delivered", "Delivered to buyer"),
                            ("failed", "Generation failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Show in public marketplace"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature prominently in showroom"
                    ),
                ),
                (
                    "generation_config",
                    models.JSONField(
                        default=dict, help_text="All settings used during generation"
                    ),
                ),
                (
                    "generation_progress",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "generation_stage",
                    models.CharField(
                        blank=True,
                        help_text="Current generation stage (research, script, character, voice, video, package)",
                        max_length=50,
                    ),
                ),
                ("preview_image_url", models.URLField(blank=True, null=True)),
                ("preview_video_url", models.URLField(blank=True, null=True)),
                ("preview_audio_url", models.URLField(blank=True, null=True)),
                ("views", models.IntegerField(default=0)),
                ("purchases", models.IntegerField(default=0)),
                (
                    "discord_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID in showroom channel",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "discord_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Showroom channel ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("purchased_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_content_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchased_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchased_content_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        default="queued",
                        help_text="Current pipeline stage",
                        max_length=20,
                    ),
                ),
                ("research_result", models.JSONField(blank=True, null=True)),
                ("script_result", models.JSONField(blank=True, null=True)),
                ("character_result", models.JSONField(blank=True, null=True)),
                ("voice_result", models.JSONField(blank=True, null=True)),
                ("video_result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_stage", models.CharField(blank=True, max_length=20)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=10
                    ),
                ),
                (
                    "cost_breakdown",
                    models.JSONField(default=dict, help_text="Cost per stage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_job",
                        to="core.contentpackage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image (PNG, JPG)"),
                            ("video", "Video (MP4, WebM)"),
                            ("audio", "Audio (MP3, WAV)"),
                            ("document", "Document (PDF, TXT)"),
                            ("source", "Source File (PSD, AI, etc.)"),
                            ("script", "Script/Copy"),
                            ("thumbnail", "Thumbnail"),
                            ("preview", "Preview Asset"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file_url", models.URLField()),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="Size in bytes"),
                ),
                ("file_format", models.CharField(blank=True, max_length=20)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Type-specific data (dimensions, duration, etc.)",
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Show in marketplace preview"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.contentpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "order", "asset_type"],
            },
        ),
        migrations.CreateModel(
            name="ContentPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("discount_applied", models.IntegerField(default=0)),
                (
                    "original_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "customizations",
                    models.JSONField(
                        blank=True,
                        help_text="Customization requests (name changes, colors, etc.)",
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("processing", "Processing"),
                            ("completed", "Payment completed"),
                            ("failed", "Payment failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "discord_channel_id",
                    models.CharField(
                        blank=True,
                        help_text="Delivery channel ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_records",
                        to="core.contentpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentpackage",
            index=models.Index(
                fields=["tier", "status"], name="core_conten_tier_c1a4e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpackage",
            index=models.Index(
                fields=["category", "is_public"], name="core_conten_categor_ecf9bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentpackage",
            index=models.Index(
                fields=["created_by", "status"], name="core_conten_created_e3c74c_idx"
            ),
        ),
    ]
