# Generated by Django 5.0.6 on 2025-12-14 17:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_session_440_content_pipeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Series title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Series description/concept"
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Original creation prompt from user"),
                ),
                (
                    "series_type",
                    models.CharField(
                        choices=[
                            (
                                "educational",
                                "Educational - Tutorials, explainers, how-tos",
                            ),
                            (
                                "entertainment",
                                "Entertainment - Cartoons, stories, shorts",
                            ),
                            ("marketing", "Marketing - Ad campaigns, brand series"),
                        ],
                        default="educational",
                        max_length=20,
                    ),
                ),
                (
                    "episode_count",
                    models.IntegerField(
                        default=3,
                        help_text="Number of episodes (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Target audience description",
                        max_length=100,
                    ),
                ),
                (
                    "style_config",
                    models.JSONField(
                        default=dict,
                        help_text="Locked visual style settings for consistency",
                    ),
                ),
                (
                    "character_config",
                    models.JSONField(
                        default=dict, help_text="Character definitions for consistency"
                    ),
                ),
                (
                    "story_arc",
                    models.JSONField(
                        default=dict,
                        help_text="Overall story arc and episode summaries",
                    ),
                ),
                (
                    "research_data",
                    models.JSONField(
                        default=dict,
                        help_text="Research gathered during planning phase",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning - Research and structure"),
                            ("generating", "Generating - Creating episodes"),
                            ("complete", "Complete - All episodes ready"),
                            ("failed", "Failed - Generation error"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "current_episode",
                    models.IntegerField(
                        default=0,
                        help_text="Current episode being generated (0 = planning)",
                    ),
                ),
                (
                    "generation_progress",
                    models.IntegerField(
                        default=0,
                        help_text="Overall progress percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("error_stage", models.CharField(blank=True, max_length=50)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Total API costs for series generation",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_breakdown",
                    models.JSONField(default=dict, help_text="Cost per episode"),
                ),
                (
                    "discord_message_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "discord_channel_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("planning_completed_at", models.DateTimeField(blank=True, null=True)),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "AI Series",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SeriesCharacter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        help_text="main, supporting, recurring, guest", max_length=50
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Character description for image generation"
                    ),
                ),
                (
                    "visual_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Detailed prompt for consistent image generation",
                    ),
                ),
                (
                    "reference_image_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference image ID for consistency",
                        null=True,
                    ),
                ),
                ("reference_image_url", models.URLField(blank=True, null=True)),
                (
                    "voice_id",
                    models.CharField(
                        blank=True,
                        help_text="ElevenLabs voice ID for this character",
                        max_length=100,
                    ),
                ),
                ("voice_name", models.CharField(blank=True, max_length=100)),
                (
                    "personality_traits",
                    models.JSONField(
                        default=list, help_text="List of personality traits"
                    ),
                ),
                (
                    "catchphrases",
                    models.JSONField(
                        default=list, help_text="Character catchphrases for dialogue"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characters",
                        to="core.aiseries",
                    ),
                ),
            ],
            options={
                "ordering": ["series", "role", "name"],
            },
        ),
        migrations.CreateModel(
            name="SeriesEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "episode_number",
                    models.IntegerField(help_text="Episode number (1-5)"),
                ),
                ("title", models.CharField(help_text="Episode title", max_length=200)),
                (
                    "synopsis",
                    models.TextField(blank=True, help_text="Episode synopsis/summary"),
                ),
                (
                    "script",
                    models.TextField(blank=True, help_text="Episode script/narration"),
                ),
                (
                    "arc_position",
                    models.CharField(
                        blank=True,
                        help_text="Position in story arc (intro, rising, climax, falling, conclusion)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued - Waiting to generate"),
                            ("generating", "Generating - Currently creating"),
                            ("complete", "Complete - Ready for delivery"),
                            ("failed", "Failed - Generation error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "generation_order",
                    models.IntegerField(
                        default=0, help_text="Order in generation queue"
                    ),
                ),
                ("research_result", models.JSONField(blank=True, null=True)),
                ("script_result", models.JSONField(blank=True, null=True)),
                ("character_result", models.JSONField(blank=True, null=True)),
                ("voice_result", models.JSONField(blank=True, null=True)),
                ("video_result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_stage", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "content_package",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ContentPackage containing episode assets",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="series_episodes",
                        to="core.contentpackage",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="core.aiseries",
                    ),
                ),
            ],
            options={
                "ordering": ["series", "episode_number"],
            },
        ),
        migrations.AddIndex(
            model_name="aiseries",
            index=models.Index(
                fields=["series_type", "status"], name="core_aiseri_series__2b0c33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiseries",
            index=models.Index(
                fields=["created_by", "status"], name="core_aiseri_created_86c66c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seriesepisode",
            unique_together={("series", "episode_number")},
        ),
    ]
