# Generated by Django 5.0.6 on 2025-12-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_session_449_pipeline_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentengagement",
            name="content_package",
        ),
        migrations.RemoveField(
            model_name="contentengagement",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="contentengagement",
            name="series",
        ),
        migrations.DeleteModel(
            name="PipelineLearningInsight",
        ),
        migrations.RemoveField(
            model_name="pipelinestagefeedback",
            name="content_package",
        ),
        migrations.RemoveField(
            model_name="pipelinestagefeedback",
            name="episode",
        ),
        migrations.RemoveField(
            model_name="pipelinestagefeedback",
            name="series",
        ),
        migrations.RemoveField(
            model_name="pipelinestagefeedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="ResearchQueryPerformance",
        ),
        migrations.DeleteModel(
            name="StylePresetPerformance",
        ),
        migrations.DeleteModel(
            name="VoicePerformance",
        ),
        migrations.DeleteModel(
            name="ContentEngagement",
        ),
        migrations.DeleteModel(
            name="PipelineStageFeedback",
        ),
    ]
