# Generated by Django 5.0.6 on 2025-12-15
# Session 455: Cross-platform conversation continuity (web ↔ Discord)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_session_451_user_upload_support'),
    ]

    operations = [
        # Make user nullable (for Discord users who haven't linked accounts)
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='Linked user (null for unlinked Discord users)',
                null=True,
                on_delete=models.deletion.CASCADE,
                to='core.unifieduser',
            ),
        ),

        # Add platform field
        migrations.AddField(
            model_name='chatconversation',
            name='platform',
            field=models.CharField(
                choices=[('web', 'Web App'), ('discord', 'Discord'), ('api', 'API')],
                db_index=True,
                default='web',
                help_text='Platform where this message originated',
                max_length=20,
            ),
        ),

        # Add Discord-specific fields
        migrations.AddField(
            model_name='chatconversation',
            name='discord_user_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Discord user ID (for unlinked users or reference)',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='discord_channel_id',
            field=models.CharField(
                blank=True,
                help_text='Discord channel where conversation occurred',
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='discord_guild_id',
            field=models.CharField(
                blank=True,
                help_text='Discord server (guild) ID',
                max_length=30,
                null=True,
            ),
        ),

        # Add session management fields
        migrations.AddField(
            model_name='chatconversation',
            name='session_title',
            field=models.CharField(
                blank=True,
                help_text='Auto-generated title for the conversation session',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='session_active',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text='Whether this session is still active/resumable',
            ),
        ),

        # Add indexes for cross-platform queries
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['platform', '-created_at'], name='chat_conver_platfor_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['discord_user_id', '-created_at'], name='chat_conver_discord_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session_active', '-created_at'], name='chat_conver_session_idx'),
        ),
    ]
