# Generated by Django - Session 457
# User Certification model for storing certificate file uploads

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0095_session_455_cross_platform_conversations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Certificate name (e.g., 'AWS Solutions Architect')", max_length=200)),
                ('issuer', models.CharField(blank=True, help_text="Issuing organization (e.g., 'Udemy', 'AWS', 'Google')", max_length=200)),
                ('issue_date', models.DateField(blank=True, help_text='Date the certificate was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Expiration date (if applicable)', null=True)),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID or certificate number', max_length=200)),
                ('certificate_file', models.FileField(blank=True, help_text='PDF or image of the certificate', null=True, upload_to='certifications/%Y/%m/')),
                ('verification_url', models.URLField(blank=True, help_text='URL to verify the credential online')),
                ('skills', models.JSONField(blank=True, default=list, help_text='Skills associated with this certification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Certification',
                'verbose_name_plural': 'User Certifications',
                'db_table': 'core_usercertification',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
