# Generated by Django 5.0.6 on 2025-12-17 05:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_session_462_market_intelligence_brief"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccuracyMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        choices=[
                            ("BullCaseAgent", "Bull Case Agent"),
                            ("BearCaseAgent", "Bear Case Agent"),
                        ],
                        help_text="Which agent these metrics track",
                        max_length=50,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(help_text="Start of measurement period"),
                ),
                ("period_end", models.DateField(help_text="End of measurement period")),
                (
                    "total_predictions",
                    models.IntegerField(
                        default=0, help_text="Total predictions made in this period"
                    ),
                ),
                (
                    "correct_predictions_7_days",
                    models.IntegerField(
                        default=0, help_text="Correct predictions after 7 days"
                    ),
                ),
                (
                    "correct_predictions_30_days",
                    models.IntegerField(
                        default=0, help_text="Correct predictions after 30 days"
                    ),
                ),
                (
                    "accuracy_rate_7_days",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage accuracy after 7 days",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "accuracy_rate_30_days",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage accuracy after 30 days",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "high_conviction_accuracy",
                    models.FloatField(
                        default=0.0,
                        help_text="Accuracy rate for HIGH conviction predictions",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "medium_conviction_accuracy",
                    models.FloatField(
                        default=0.0,
                        help_text="Accuracy rate for MEDIUM conviction predictions",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "low_conviction_accuracy",
                    models.FloatField(
                        default=0.0,
                        help_text="Accuracy rate for LOW conviction predictions",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "bull_market_accuracy",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Accuracy during bull markets",
                        null=True,
                    ),
                ),
                (
                    "bear_market_accuracy",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Accuracy during bear markets",
                        null=True,
                    ),
                ),
                (
                    "neutral_market_accuracy",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Accuracy during neutral/ranging markets",
                        null=True,
                    ),
                ),
                (
                    "debate_zone_accuracy",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Accuracy when agent was in debate zone (disagreed with opposite agent)",
                        null=True,
                    ),
                ),
                (
                    "debate_zone_win_rate",
                    models.FloatField(
                        blank=True,
                        default=0.0,
                        help_text="Win rate when in debate zone (agent was right, opposite was wrong)",
                        null=True,
                    ),
                ),
                (
                    "confidence_multiplier",
                    models.FloatField(
                        default=1.0,
                        help_text="Multiplier to adjust confidence scores based on track record (0.5-1.5)",
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(1.5),
                        ],
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When metrics were last calculated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Agent Accuracy Metrics",
                "verbose_name_plural": "Agent Accuracy Metrics",
                "ordering": ["-period_end", "agent_name"],
            },
        ),
        migrations.CreateModel(
            name="PredictionOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        help_text="Stock ticker symbol (e.g., AAPL, MSFT)",
                        max_length=10,
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[("BULL", "Bull Case"), ("BEAR", "Bear Case")],
                        help_text="Whether this was a bull or bear prediction",
                        max_length=10,
                    ),
                ),
                (
                    "conviction_level",
                    models.CharField(
                        choices=[
                            ("HIGH", "High Conviction"),
                            ("MEDIUM", "Medium Conviction"),
                            ("LOW", "Low Conviction"),
                        ],
                        help_text="Conviction level at prediction time",
                        max_length=10,
                    ),
                ),
                (
                    "predicted_move",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Predicted percentage move (e.g., +25.00 for bull, -15.00 for bear)",
                        max_digits=6,
                    ),
                ),
                (
                    "price_at_prediction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock price when prediction was made",
                        max_digits=10,
                    ),
                ),
                (
                    "prediction_date",
                    models.DateField(help_text="Date prediction was made"),
                ),
                (
                    "price_after_7_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock price 7 days after prediction",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_after_30_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock price 30 days after prediction",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "actual_move_7_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual percentage move after 7 days",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "actual_move_30_days",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual percentage move after 30 days",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "was_correct_7_days",
                    models.BooleanField(
                        blank=True,
                        help_text="True if prediction direction was correct after 7 days",
                        null=True,
                    ),
                ),
                (
                    "was_correct_30_days",
                    models.BooleanField(
                        blank=True,
                        help_text="True if prediction direction was correct after 30 days",
                        null=True,
                    ),
                ),
                (
                    "accuracy_score_7_days",
                    models.FloatField(
                        blank=True,
                        help_text="Accuracy score 0-1 (considers direction + magnitude)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "accuracy_score_30_days",
                    models.FloatField(
                        blank=True,
                        help_text="Accuracy score 0-1 (considers direction + magnitude)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "market_regime",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_BULL", "Strong Bull Market"),
                            ("BULL", "Bull Market"),
                            ("NEUTRAL", "Neutral/Ranging"),
                            ("BEAR", "Bear Market"),
                            ("STRONG_BEAR", "Strong Bear Market"),
                        ],
                        help_text="Market regime at prediction time",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "volatility_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXTREME", "Extreme Volatility"),
                            ("HIGH", "High Volatility"),
                            ("MODERATE", "Moderate Volatility"),
                            ("LOW", "Low Volatility"),
                        ],
                        help_text="Volatility level at prediction time",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "was_in_debate_zone",
                    models.BooleanField(
                        default=False,
                        help_text="True if this stock was in the debate zone (bull vs bear disagreed)",
                    ),
                ),
                (
                    "opposite_conviction",
                    models.CharField(
                        blank=True,
                        help_text="Conviction level of the opposite case (bull if this is bear, vice versa)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "outcome_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="True if we've calculated the actual outcome",
                    ),
                ),
                (
                    "outcome_calculated_at",
                    models.DateTimeField(
                        blank=True, help_text="When outcome was calculated", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prediction Outcome",
                "verbose_name_plural": "Prediction Outcomes",
                "ordering": ["-prediction_date", "ticker"],
            },
        ),
        migrations.CreateModel(
            name="UserBriefFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="Did user find the brief helpful?",
                        null=True,
                    ),
                ),
                (
                    "helpfulness_score",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 star rating of brief quality",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        default=list,
                        help_text="List of actions: [{'ticker': 'AAPL', 'action': 'buy', 'reason': 'bull_case'}]",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user first viewed the brief"
                    ),
                ),
                (
                    "acted_on_brief",
                    models.BooleanField(
                        default=False,
                        help_text="True if user took any action based on brief",
                    ),
                ),
                (
                    "time_to_action",
                    models.IntegerField(
                        blank=True,
                        help_text="Minutes between viewing and taking action",
                        null=True,
                    ),
                ),
                (
                    "followed_bullish_recommendation",
                    models.BooleanField(
                        default=False,
                        help_text="Did user buy/hold stocks from bullish_opportunities?",
                    ),
                ),
                (
                    "followed_bearish_warning",
                    models.BooleanField(
                        default=False,
                        help_text="Did user sell/avoid stocks from bearish_warnings?",
                    ),
                ),
                (
                    "explored_debate_zone",
                    models.BooleanField(
                        default=False,
                        help_text="Did user research stocks in debate zone?",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Optional user comment about the brief"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Brief Feedback",
                "verbose_name_plural": "User Brief Feedback",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="chatconversation",
            name="chat_conver_platfor_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatconversation",
            name="chat_conver_discord_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatconversation",
            name="chat_conver_session_idx",
        ),
        migrations.RenameIndex(
            model_name="marketintelligencebrief",
            new_name="core_market_brief_d_ab8e90_idx",
            old_name="core_market_brief_d_idx",
        ),
        migrations.RenameIndex(
            model_name="marketintelligencebrief",
            new_name="core_market_situati_2f947f_idx",
            old_name="core_market_health_idx",
        ),
        migrations.RenameIndex(
            model_name="marketintelligencebrief",
            new_name="core_market_user_id_84cfdd_idx",
            old_name="core_market_user_br_idx",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="discord_channel_id",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="discord_guild_id",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="discord_user_id",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="platform",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="session_active",
        ),
        migrations.RemoveField(
            model_name="chatconversation",
            name="session_title",
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="marketintelligencebrief",
            table=None,
        ),
        migrations.AddIndex(
            model_name="agentaccuracymetrics",
            index=models.Index(
                fields=["agent_name", "-period_end"],
                name="core_agenta_agent_n_610651_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentaccuracymetrics",
            index=models.Index(
                fields=["-calculated_at"], name="core_agenta_calcula_21ce06_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentaccuracymetrics",
            unique_together={("agent_name", "period_start", "period_end")},
        ),
        migrations.AddField(
            model_name="predictionoutcome",
            name="brief",
            field=models.ForeignKey(
                help_text="The Market Intelligence Brief that made this prediction",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prediction_outcomes",
                to="core.marketintelligencebrief",
            ),
        ),
        migrations.AddField(
            model_name="userbrieffeedback",
            name="brief",
            field=models.ForeignKey(
                help_text="The brief being rated",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_feedback",
                to="core.marketintelligencebrief",
            ),
        ),
        migrations.AddField(
            model_name="userbrieffeedback",
            name="user",
            field=models.ForeignKey(
                help_text="User who provided feedback",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brief_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["-prediction_date"], name="core_predic_predict_8bf576_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["ticker", "-prediction_date"],
                name="core_predic_ticker_2cfacd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["prediction_type", "conviction_level"],
                name="core_predic_predict_d3699e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["was_correct_7_days"], name="core_predic_was_cor_26c1c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["was_in_debate_zone"], name="core_predic_was_in__53beb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="predictionoutcome",
            index=models.Index(
                fields=["outcome_calculated"], name="core_predic_outcome_2e80f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbrieffeedback",
            index=models.Index(
                fields=["user", "-viewed_at"], name="core_userbr_user_id_b22b03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbrieffeedback",
            index=models.Index(
                fields=["brief", "user"], name="core_userbr_brief_i_99adf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbrieffeedback",
            index=models.Index(
                fields=["was_helpful"], name="core_userbr_was_hel_e8bbc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbrieffeedback",
            index=models.Index(
                fields=["acted_on_brief"], name="core_userbr_acted_o_8c3a20_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbrieffeedback",
            unique_together={("user", "brief")},
        ),
    ]
