# Generated by Django 5.0.6 on 2025-12-17 07:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_session_463_learning_loop"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Channel name (e.g., 'AI for Kids', 'Space Facts Weekly')",
                        max_length=200,
                    ),
                ),
                (
                    "topic_domain",
                    models.TextField(
                        help_text="Topic focus (e.g., 'artificial intelligence, machine learning, explained for children')"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        help_text="Target audience description (e.g., 'Kids 8-12', 'Tech professionals')",
                        max_length=200,
                    ),
                ),
                (
                    "content_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily - 1 episode per day"),
                            ("weekly", "Weekly - 1 episode per week"),
                            ("biweekly", "Bi-weekly - 2 episodes per week"),
                            ("monthly", "Monthly - 1 episode per month"),
                        ],
                        default="weekly",
                        help_text="How often content is created",
                        max_length=20,
                    ),
                ),
                (
                    "visual_style",
                    models.CharField(
                        default="pixar",
                        help_text="Visual style for content (e.g., 'pixar, colorful, friendly')",
                        max_length=200,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True,
                        help_text="ElevenLabs voice ID from voice marketplace (Session 442-444)",
                        max_length=100,
                    ),
                ),
                (
                    "voice_name",
                    models.CharField(
                        blank=True, help_text="Voice name for reference", max_length=100
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        default="educational",
                        help_text="Content type: educational, entertainment, marketing",
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram Reels"),
                            ("all", "All Platforms"),
                        ],
                        default="youtube",
                        help_text="Publishing platform",
                        max_length=20,
                    ),
                ),
                (
                    "publish_automatically",
                    models.BooleanField(
                        default=False,
                        help_text="If True, publishes content automatically. If False, queues for review.",
                    ),
                ),
                (
                    "total_episodes_created",
                    models.IntegerField(
                        default=0, help_text="Total number of episodes created"
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        default=0, help_text="Cumulative views across all episodes"
                    ),
                ),
                (
                    "total_engagement",
                    models.IntegerField(
                        default=0,
                        help_text="Cumulative engagement (likes + comments + shares)",
                    ),
                ),
                (
                    "avg_retention_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average watch time retention (0-100%)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active - Creating content autonomously"),
                            ("paused", "Paused - Temporarily stopped"),
                            ("completed", "Completed - Goal achieved"),
                            ("failed", "Failed - Critical error"),
                        ],
                        default="active",
                        help_text="Channel operational status",
                        max_length=20,
                    ),
                ),
                (
                    "next_content_due",
                    models.DateTimeField(
                        help_text="When next episode should be created"
                    ),
                ),
                (
                    "last_content_created",
                    models.DateTimeField(
                        blank=True, help_text="When last episode was created", null=True
                    ),
                ),
                (
                    "confidence_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Confidence multiplier (0.5-1.5) based on channel performance",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(1.5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_channels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "content_channel",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChannelEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Episode title", max_length=200)),
                (
                    "topic",
                    models.CharField(
                        help_text="What this episode is about (for learning)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Episode description"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, help_text="When episode was published", null=True
                    ),
                ),
                (
                    "platform_url",
                    models.URLField(
                        blank=True,
                        help_text="URL on publishing platform (YouTube, TikTok, etc.)",
                    ),
                ),
                ("views", models.IntegerField(default=0, help_text="Number of views")),
                ("likes", models.IntegerField(default=0, help_text="Number of likes")),
                (
                    "comments",
                    models.IntegerField(default=0, help_text="Number of comments"),
                ),
                (
                    "shares",
                    models.IntegerField(default=0, help_text="Number of shares"),
                ),
                (
                    "watch_time_seconds",
                    models.IntegerField(
                        default=0, help_text="Total watch time in seconds"
                    ),
                ),
                (
                    "retention_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average watch time retention (0-100%)",
                        max_digits=5,
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculated performance score (views * retention * engagement)",
                        max_digits=10,
                    ),
                ),
                (
                    "contributed_to_learning",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this episode's data has been processed for learning",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to AI Series Workflow content (Session 445)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channel_episodes",
                        to="core.aiseries",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="core.contentchannel",
                    ),
                ),
            ],
            options={
                "db_table": "channel_episode",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentDebate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("debate_date", models.DateTimeField(auto_now_add=True)),
                (
                    "proposed_topic",
                    models.CharField(help_text="Topic being debated", max_length=200),
                ),
                (
                    "proposed_by",
                    models.CharField(
                        help_text="Which agent proposed this topic (e.g., 'TopicMinerAgent')",
                        max_length=100,
                    ),
                ),
                (
                    "topic_miner_position",
                    models.TextField(
                        help_text="TopicMinerAgent's argument (e.g., 'Trending now because...')"
                    ),
                ),
                (
                    "contrarian_position",
                    models.TextField(
                        help_text="ContrarianAgent's argument (e.g., 'Too saturated, try...')"
                    ),
                ),
                (
                    "analyst_position",
                    models.TextField(
                        help_text="PerformanceAnalystAgent's argument (e.g., 'Past data shows...')"
                    ),
                ),
                (
                    "director_position",
                    models.TextField(
                        help_text="CreativeDirectorAgent's argument (e.g., 'Unique angle could be...')"
                    ),
                ),
                (
                    "final_decision",
                    models.CharField(
                        help_text="Final topic decision after debate", max_length=200
                    ),
                ),
                (
                    "chosen_angle",
                    models.TextField(help_text="Unique angle or approach chosen"),
                ),
                (
                    "decision_reasoning",
                    models.TextField(help_text="Why this decision was made"),
                ),
                (
                    "consensus_reached",
                    models.BooleanField(
                        default=False,
                        help_text="Whether agents agreed or coordinator had to decide",
                    ),
                ),
                (
                    "content_created",
                    models.BooleanField(
                        default=False,
                        help_text="Whether content was actually created from this debate",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debates",
                        to="core.contentchannel",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        help_text="Episode that resulted from this debate (if created)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debates",
                        to="core.channelepisode",
                    ),
                ),
            ],
            options={
                "db_table": "content_debate",
                "ordering": ["-debate_date"],
            },
        ),
        migrations.CreateModel(
            name="TopicPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Topic keyword or category", max_length=200
                    ),
                ),
                (
                    "episode_count",
                    models.IntegerField(
                        default=0, help_text="Number of episodes about this topic"
                    ),
                ),
                (
                    "avg_views",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average views for this topic",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_engagement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average engagement (likes + comments + shares)",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_retention",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average retention rate (0-100%)",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_performance_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average composite performance score",
                        max_digits=10,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Confidence multiplier (0.5-2.0) - how confident we are this topic works",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.5),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                    ),
                ),
                (
                    "last_tested",
                    models.DateTimeField(
                        help_text="When we last created content about this topic"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_performance",
                        to="core.contentchannel",
                    ),
                ),
            ],
            options={
                "db_table": "topic_performance",
                "ordering": ["-avg_performance_score"],
            },
        ),
        migrations.AddIndex(
            model_name="contentchannel",
            index=models.Index(
                fields=["user", "status"], name="content_cha_user_id_f0082b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentchannel",
            index=models.Index(
                fields=["next_content_due"], name="content_cha_next_co_05a00e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentchannel",
            index=models.Index(fields=["status"], name="content_cha_status_ef10e5_idx"),
        ),
        migrations.AddIndex(
            model_name="channelepisode",
            index=models.Index(
                fields=["channel", "-created_at"], name="channel_epi_channel_500166_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="channelepisode",
            index=models.Index(fields=["topic"], name="channel_epi_topic_406572_idx"),
        ),
        migrations.AddIndex(
            model_name="channelepisode",
            index=models.Index(
                fields=["contributed_to_learning"],
                name="channel_epi_contrib_41b9bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentdebate",
            index=models.Index(
                fields=["channel", "-debate_date"],
                name="content_deb_channel_8f69bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentdebate",
            index=models.Index(
                fields=["proposed_topic"], name="content_deb_propose_55d71c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="topicperformance",
            index=models.Index(
                fields=["channel", "-avg_performance_score"],
                name="topic_perfo_channel_d237b8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="topicperformance",
            index=models.Index(fields=["topic"], name="topic_perfo_topic_e764cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="topicperformance",
            unique_together={("channel", "topic")},
        ),
    ]
