# Generated by Django 5.0.6 on 2025-12-17 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_session_466_autonomous_content_studio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Model version string (e.g., v1.0, v2.1)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "trained_at",
                    models.DateTimeField(help_text="When the model was trained"),
                ),
                (
                    "training_samples",
                    models.IntegerField(
                        default=0, help_text="Number of samples used for training"
                    ),
                ),
                (
                    "training_duration_seconds",
                    models.IntegerField(default=0, help_text="How long training took"),
                ),
                (
                    "train_mse",
                    models.FloatField(
                        blank=True,
                        help_text="Mean squared error on training set",
                        null=True,
                    ),
                ),
                (
                    "test_mse",
                    models.FloatField(
                        blank=True,
                        help_text="Mean squared error on test set",
                        null=True,
                    ),
                ),
                (
                    "train_r2",
                    models.FloatField(
                        blank=True,
                        help_text="R-squared score on training set",
                        null=True,
                    ),
                ),
                (
                    "test_r2",
                    models.FloatField(
                        blank=True, help_text="R-squared score on test set", null=True
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        default=list,
                        help_text="Feature importance rankings from XGBoost",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the currently active model",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Whether this model has been archived"
                    ),
                ),
                (
                    "model_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the saved model file",
                        max_length=500,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Training notes or comments"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-trained_at"],
                "indexes": [
                    models.Index(
                        fields=["version"], name="core_mlmode_version_0ec02c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="core_mlmode_is_acti_e8d9a5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoringExplanation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ml_score", models.FloatField(help_text="Raw ML model score (0-100)")),
                ("rule_score", models.FloatField(help_text="Rule-based score (0-100)")),
                (
                    "hybrid_score",
                    models.FloatField(help_text="Combined hybrid score (0-100)"),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence in the score (0-100)"),
                ),
                (
                    "shap_base_value",
                    models.FloatField(
                        blank=True, help_text="SHAP base/expected value", null=True
                    ),
                ),
                (
                    "shap_values",
                    models.JSONField(
                        default=list, help_text="SHAP values for each feature"
                    ),
                ),
                (
                    "feature_names",
                    models.JSONField(default=list, help_text="Feature names in order"),
                ),
                (
                    "feature_values",
                    models.JSONField(default=list, help_text="Feature values in order"),
                ),
                (
                    "top_positive_features",
                    models.JSONField(
                        default=list, help_text="Top features that increased the score"
                    ),
                ),
                (
                    "top_negative_features",
                    models.JSONField(
                        default=list, help_text="Top features that decreased the score"
                    ),
                ),
                (
                    "rule_reasoning",
                    models.JSONField(
                        default=dict, help_text="Reasoning from rule-based scoring"
                    ),
                ),
                (
                    "scoring_time_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken to generate this score in milliseconds",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="explanations",
                        to="core.mlmodelversion",
                    ),
                ),
                (
                    "opportunity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_explanation",
                        to="core.opportunity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="core_scorin_created_43aad2_idx"
                    ),
                    models.Index(
                        fields=["hybrid_score"], name="core_scorin_hybrid__eb04e6_idx"
                    ),
                ],
            },
        ),
    ]
