# Generated by Django 5.0.6 on 2025-12-17 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0100_session_470_ml_scoring_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scoring_mode",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time (immediate scoring)"),
                            ("batch", "Batch (hourly processing)"),
                            ("auto", "Auto (switch based on SLA)"),
                        ],
                        default="auto",
                        help_text="How scoring requests should be processed",
                        max_length=20,
                    ),
                ),
                (
                    "sla_threshold_ms",
                    models.IntegerField(
                        default=500, help_text="Max acceptable latency in milliseconds"
                    ),
                ),
                (
                    "auto_switch_threshold_ms",
                    models.IntegerField(
                        default=1000,
                        help_text="Latency at which to switch from realtime to batch",
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("high", "High (user-triggered, immediate)"),
                            ("normal", "Normal (background scoring)"),
                            ("low", "Low (backfill/reprocessing)"),
                        ],
                        default="normal",
                        help_text="Default priority for scoring requests",
                        max_length=20,
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=100, help_text="Number of items to process per batch"
                    ),
                ),
                (
                    "batch_interval_minutes",
                    models.IntegerField(
                        default=60, help_text="Minutes between batch processing runs"
                    ),
                ),
                (
                    "enable_shap_explanations",
                    models.BooleanField(
                        default=True,
                        help_text="Generate SHAP explanations (adds latency)",
                    ),
                ),
                (
                    "enable_model_fallback",
                    models.BooleanField(
                        default=True,
                        help_text="Fallback to rule-based scoring if ML fails",
                    ),
                ),
                (
                    "store_explanations",
                    models.BooleanField(
                        default=True,
                        help_text="Store ScoringExplanation records in database",
                    ),
                ),
                ("total_requests", models.IntegerField(default=0)),
                ("realtime_requests", models.IntegerField(default=0)),
                ("batch_requests", models.IntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0.0)),
                ("sla_breaches", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="User this config applies to (null = global default)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scoring Configuration",
                "verbose_name_plural": "Scoring Configurations",
            },
        ),
        migrations.CreateModel(
            name="ScoringQueueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "High"), (2, "Normal"), (3, "Low")],
                        default=2,
                        help_text="Processing priority (1=high, 2=normal, 3=low)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "request_source",
                    models.CharField(
                        default="system",
                        help_text="Where the request came from (api, celery, user, etc.)",
                        max_length=50,
                    ),
                ),
                ("result_score", models.FloatField(blank=True, null=True)),
                ("result_explanation_id", models.UUIDField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spider_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_queue_items",
                        to="core.spiderdata",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="core_scorin_status_0a5dd1_idx",
                    ),
                    models.Index(
                        fields=["spider_data"], name="core_scorin_spider__a54544_idx"
                    ),
                ],
            },
        ),
    ]
