# Generated by Django 5.0.6 on 2025-12-17 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_session_470_scoring_dispatcher"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auto_approve_threshold",
                    models.FloatField(
                        default=85.0,
                        help_text="Auto-approve if confidence >= this (0-100)",
                    ),
                ),
                (
                    "auto_reject_threshold",
                    models.FloatField(
                        default=50.0,
                        help_text="Auto-reject if confidence < this (0-100)",
                    ),
                ),
                (
                    "default_deadline_hours",
                    models.IntegerField(
                        default=24, help_text="Default hours until validation deadline"
                    ),
                ),
                (
                    "escalation_delay_hours",
                    models.IntegerField(
                        default=4, help_text="Hours before unreviewed items escalate"
                    ),
                ),
                (
                    "enable_auto_assignment",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically assign validations to reviewers",
                    ),
                ),
                (
                    "max_assignments_per_user",
                    models.IntegerField(
                        default=10, help_text="Max pending assignments per reviewer"
                    ),
                ),
                (
                    "require_reasoning",
                    models.BooleanField(
                        default=False, help_text="Require reasoning for all decisions"
                    ),
                ),
                (
                    "require_reasoning_for_overrides",
                    models.BooleanField(
                        default=True,
                        help_text="Require reasoning when overriding ML score",
                    ),
                ),
                ("total_validations", models.IntegerField(default=0)),
                ("total_approved", models.IntegerField(default=0)),
                ("total_rejected", models.IntegerField(default=0)),
                ("total_overrides", models.IntegerField(default=0)),
                ("avg_decision_time_seconds", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Configuration",
                "verbose_name_plural": "Validation Configurations",
            },
        ),
        migrations.CreateModel(
            name="ValidationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ml_score",
                    models.FloatField(help_text="ML score at time of request"),
                ),
                (
                    "rule_score",
                    models.FloatField(help_text="Rule-based score at time of request"),
                ),
                (
                    "hybrid_score",
                    models.FloatField(help_text="Combined score at time of request"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence level that triggered validation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("assigned", "Assigned to Reviewer"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("escalated", "Escalated"),
                            ("expired", "Expired"),
                            ("auto_approved", "Auto-Approved (High Confidence)"),
                            ("auto_rejected", "Auto-Rejected (Low Confidence)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Critical"),
                            (2, "High"),
                            (3, "Normal"),
                            (4, "Low"),
                        ],
                        default=3,
                        help_text="Review priority (1=critical, 4=low)",
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "request_reason",
                    models.CharField(
                        default="confidence_threshold",
                        help_text="Why validation was requested",
                        max_length=100,
                    ),
                ),
                (
                    "request_source",
                    models.CharField(
                        default="auto",
                        help_text="What triggered this request (auto, manual, escalation)",
                        max_length=50,
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time by which decision must be made",
                        null=True,
                    ),
                ),
                (
                    "escalate_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="Escalate if not reviewed by this time",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_requests",
                        to="core.opportunity",
                    ),
                ),
                (
                    "scoring_explanation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_requests",
                        to="core.scoringexplanation",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_with_changes", "Approve with Score Override"),
                            ("reject", "Reject"),
                            ("escalate", "Escalate to Higher Authority"),
                            ("defer", "Defer Decision"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "override_score",
                    models.FloatField(
                        blank=True,
                        help_text="Human-assigned score (if different from ML)",
                        null=True,
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="Why this decision was made"
                    ),
                ),
                (
                    "reasoning_tags",
                    models.JSONField(
                        default=list,
                        help_text="Structured tags for reasoning (e.g., ['price_too_high', 'wrong_category'])",
                    ),
                ),
                (
                    "agreement_with_ml",
                    models.BooleanField(
                        default=True, help_text="Did human agree with ML's assessment?"
                    ),
                ),
                (
                    "ml_error_magnitude",
                    models.FloatField(
                        blank=True,
                        help_text="How far off was ML? (override_score - hybrid_score)",
                        null=True,
                    ),
                ),
                (
                    "decision_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="How long the human took to decide",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validation_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision",
                        to="core.validationrequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["status", "priority", "created_at"],
                name="core_valida_status_529aef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["assigned_to", "status"], name="core_valida_assigne_2eb9a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationrequest",
            index=models.Index(
                fields=["deadline"], name="core_valida_deadlin_efc156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationdecision",
            index=models.Index(
                fields=["decision"], name="core_valida_decisio_adbb6f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="validationdecision",
            index=models.Index(
                fields=["decided_by", "created_at"],
                name="core_valida_decided_4b7d92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="validationdecision",
            index=models.Index(
                fields=["agreement_with_ml"], name="core_valida_agreeme_867c55_idx"
            ),
        ),
    ]
