# Generated by Django 5.0.6 on 2025-12-17 17:57

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_session_471_narrative_drift_detector"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("spider_crawl", "Spider Crawl"),
                            ("data_import", "Data Import"),
                            ("ml_score", "ML Scoring"),
                            ("rule_score", "Rule-Based Scoring"),
                            ("hybrid_score", "Hybrid Scoring"),
                            ("validation_queued", "Validation Queued"),
                            ("validation_assigned", "Validation Assigned"),
                            ("validation_approved", "Validation Approved"),
                            ("validation_rejected", "Validation Rejected"),
                            ("validation_escalated", "Validation Escalated"),
                            ("validation_expired", "Validation Expired"),
                            ("auto_approved", "Auto-Approved"),
                            ("auto_rejected", "Auto-Rejected"),
                            ("human_override", "Human Override"),
                            ("outcome_recorded", "Outcome Recorded"),
                            ("model_trained", "Model Trained"),
                            ("model_deployed", "Model Deployed"),
                            ("config_changed", "Configuration Changed"),
                            ("alert_triggered", "Alert Triggered"),
                        ],
                        db_index=True,
                        help_text="Type of action being logged",
                        max_length=50,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "Human User"),
                            ("agent", "AI Agent"),
                            ("system", "System Process"),
                            ("scheduler", "Scheduled Task"),
                        ],
                        help_text="Type of actor that performed this action",
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the actor (user ID, agent ID, or task name)",
                        max_length=100,
                    ),
                ),
                (
                    "actor_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable name of the actor",
                        max_length=100,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of entity being acted upon",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of the target entity",
                        max_length=100,
                    ),
                ),
                (
                    "before_state",
                    models.JSONField(
                        default=dict,
                        help_text="State of the entity before the action (for changes)",
                    ),
                ),
                (
                    "after_state",
                    models.JSONField(
                        default=dict, help_text="State of the entity after the action"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Additional context about the action"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for the action (especially for human actions)",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "log_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the log entry for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "previous_log_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the previous log entry (chain verification)",
                        max_length=64,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Request/correlation ID for tracing",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request (for user actions)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this rule",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this rule checks"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0", help_text="Version of the rule", max_length=20
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("data_freshness", "Data Freshness"),
                            ("source_attribution", "Source Attribution"),
                            ("confidence_threshold", "Confidence Threshold"),
                            ("human_review", "Human Review Required"),
                            ("model_version", "Model Version Compliance"),
                            ("data_quality", "Data Quality"),
                            ("bias_check", "Bias Detection"),
                            ("rate_limit", "Rate Limit Compliance"),
                            ("retention", "Data Retention"),
                            ("privacy", "Privacy Compliance"),
                        ],
                        help_text="Type of compliance check",
                        max_length=50,
                    ),
                ),
                (
                    "entity_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        default=list,
                        help_text="Entity types this rule applies to",
                        size=None,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Rule configuration parameters"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        help_text="Severity level if rule fails",
                        max_length=20,
                    ),
                ),
                (
                    "blocking",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a failure blocks the operation",
                    ),
                ),
                (
                    "auto_remediate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to attempt automatic remediation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Compliance Rule",
                "verbose_name_plural": "Compliance Rules",
                "ordering": ["check_type", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="narrativeshift",
            name="new_narrative",
        ),
        migrations.RemoveField(
            model_name="narrativeevidence",
            name="narrative",
        ),
        migrations.RemoveField(
            model_name="narrativealert",
            name="narrative",
        ),
        migrations.RemoveField(
            model_name="narrativeshift",
            name="old_narrative",
        ),
        migrations.RemoveField(
            model_name="narrativealert",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="narrativeevidence",
            name="spider_data",
        ),
        migrations.CreateModel(
            name="DataProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("spider_data", "Spider Data"),
                            ("opportunity", "Opportunity"),
                            ("scoring_result", "Scoring Result"),
                            ("validation_request", "Validation Request"),
                            ("validation_decision", "Validation Decision"),
                            ("outcome", "Outcome"),
                            ("ml_model", "ML Model"),
                            ("alert", "System Alert"),
                        ],
                        db_index=True,
                        help_text="Type of entity this provenance record tracks",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID of the entity (UUID or other identifier)",
                        max_length=100,
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        default=0, help_text="Depth in the lineage chain (0 = root)"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("spider", "Spider Crawl"),
                            ("api", "External API"),
                            ("user_input", "User Input"),
                            ("ml_prediction", "ML Prediction"),
                            ("agent_action", "Agent Action"),
                            ("system", "System Process"),
                            ("human_review", "Human Review"),
                        ],
                        help_text="Type of source that created this data",
                        max_length=30,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the source (spider name, agent name, username, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "source_version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the source (model version, spider version, etc.)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "data_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Original timestamp of the data (may differ from record creation)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Full metadata snapshot at this stage"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of the entity content for integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash of the parent provenance record (blockchain-style)",
                        max_length=64,
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("exempt", "Exempt"),
                        ],
                        default="pending",
                        help_text="Compliance verification status",
                        max_length=20,
                    ),
                ),
                (
                    "compliance_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When compliance was last checked",
                        null=True,
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True, help_text="Notes from compliance review"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered this data creation (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provenance_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent provenance record in the lineage chain",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.dataprovenance",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        help_text="Root provenance record (original spider data)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descendants",
                        to="core.dataprovenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Provenance",
                "verbose_name_plural": "Data Provenance Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("data_freshness", "Data Freshness"),
                            ("source_attribution", "Source Attribution"),
                            ("confidence_threshold", "Confidence Threshold"),
                            ("human_review", "Human Review Required"),
                            ("model_version", "Model Version Compliance"),
                            ("data_quality", "Data Quality"),
                            ("bias_check", "Bias Detection"),
                            ("rate_limit", "Rate Limit Compliance"),
                            ("retention", "Data Retention"),
                            ("privacy", "Privacy Compliance"),
                        ],
                        help_text="Type of compliance check",
                        max_length=50,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="Name of the compliance rule", max_length=100
                    ),
                ),
                (
                    "rule_version",
                    models.CharField(
                        default="1.0",
                        help_text="Version of the compliance rule",
                        max_length=20,
                    ),
                ),
                (
                    "rule_config",
                    models.JSONField(
                        default=dict, help_text="Configuration parameters for the rule"
                    ),
                ),
                ("passed", models.BooleanField(help_text="Whether the check passed")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informational"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        help_text="Severity if check failed",
                        max_length=20,
                    ),
                ),
                (
                    "actual_value",
                    models.JSONField(
                        blank=True, help_text="Actual value that was checked", null=True
                    ),
                ),
                (
                    "expected_value",
                    models.JSONField(
                        blank=True, help_text="Expected value or threshold", null=True
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Human-readable result message"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict, help_text="Additional check details"
                    ),
                ),
                (
                    "remediation_required",
                    models.BooleanField(
                        default=False, help_text="Whether remediation is required"
                    ),
                ),
                (
                    "remediation_action",
                    models.TextField(
                        blank=True, help_text="Suggested remediation action"
                    ),
                ),
                (
                    "remediated",
                    models.BooleanField(
                        default=False, help_text="Whether the issue has been remediated"
                    ),
                ),
                (
                    "remediated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the issue was remediated", null=True
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "audit_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated audit log entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_checks",
                        to="core.auditlog",
                    ),
                ),
                (
                    "remediated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the remediation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remediations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provenance",
                    models.ForeignKey(
                        help_text="Provenance record being checked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_checks",
                        to="core.dataprovenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compliance Check",
                "verbose_name_plural": "Compliance Checks",
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="provenance",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated provenance record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.dataprovenance",
            ),
        ),
        migrations.DeleteModel(
            name="Narrative",
        ),
        migrations.DeleteModel(
            name="NarrativeAlert",
        ),
        migrations.DeleteModel(
            name="NarrativeShift",
        ),
        migrations.DeleteModel(
            name="NarrativeEvidence",
        ),
        migrations.AddIndex(
            model_name="dataprovenance",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="core_datapr_entity__3c4dd6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprovenance",
            index=models.Index(
                fields=["source_type", "source_name"],
                name="core_datapr_source__da2a1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprovenance",
            index=models.Index(
                fields=["compliance_status"], name="core_datapr_complia_ef4f2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataprovenance",
            index=models.Index(
                fields=["root", "depth"], name="core_datapr_root_id_efb639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["check_type", "passed"], name="core_compli_check_t_6aaafc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["provenance", "check_type"],
                name="core_compli_provena_580f59_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compliancecheck",
            index=models.Index(
                fields=["severity", "remediated"], name="core_compli_severit_fb3688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action_type", "timestamp"],
                name="core_auditl_action__64f4df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_type", "actor_id"], name="core_auditl_actor_t_d59199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="core_auditl_target__6c66b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["request_id"], name="core_auditl_request_2f651b_idx"
            ),
        ),
    ]
