# Generated by Django 5.1.4 - Session 477
# Autonomous Alert Models for Blockchain Security and Stock Market Intelligence

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_session_472_roi_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # BlockchainSecurityAlert
        migrations.CreateModel(
            name='BlockchainSecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[
                    ('whale_movement', 'Whale Movement'),
                    ('suspicious_tx', 'Suspicious Transaction'),
                    ('contract_exploit', 'Contract Exploit'),
                    ('flash_loan', 'Flash Loan Attack'),
                    ('rug_pull', 'Rug Pull Warning'),
                    ('unusual_volume', 'Unusual Volume'),
                    ('large_transfer', 'Large Transfer'),
                    ('dex_arbitrage', 'DEX Arbitrage'),
                    ('price_manipulation', 'Price Manipulation'),
                    ('governance_attack', 'Governance Attack'),
                ], db_index=True, help_text='Type of security alert', max_length=50)),
                ('severity', models.CharField(choices=[
                    ('critical', 'Critical - Active Exploit'),
                    ('high', 'High - Immediate Attention'),
                    ('medium', 'Medium - Monitor Closely'),
                    ('low', 'Low - Informational'),
                ], db_index=True, help_text='Alert severity level', max_length=20)),
                ('chain', models.CharField(default='ethereum', help_text='Blockchain network', max_length=50)),
                ('address', models.CharField(blank=True, help_text='Contract or wallet address', max_length=100)),
                ('token_symbol', models.CharField(blank=True, help_text='Token symbol if applicable', max_length=20)),
                ('title', models.CharField(help_text='Short alert title', max_length=200)),
                ('summary', models.TextField(help_text='Detailed summary')),
                ('value_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('detecting_agent', models.CharField(help_text='Which agent detected this', max_length=100)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('analysis_details', models.JSONField(default=dict)),
                ('transaction_hash', models.CharField(blank=True, max_length=100)),
                ('source_data', models.JSONField(default=dict)),
                ('evidence_links', models.JSONField(default=list)),
                ('recommended_action', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=50)),
                ('discord_sent', models.BooleanField(default=False)),
                ('discord_sent_at', models.DateTimeField(blank=True, null=True)),
                ('discord_message_id', models.CharField(blank=True, max_length=100)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('user_action_taken', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blockchain_security_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blockchainsecurityalert',
            index=models.Index(fields=['severity', '-detected_at'], name='blockchain__severit_6b4e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainsecurityalert',
            index=models.Index(fields=['alert_type', '-detected_at'], name='blockchain__alert_t_a9c8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainsecurityalert',
            index=models.Index(fields=['chain', '-detected_at'], name='blockchain__chain_8d2a1e_idx'),
        ),

        # BlockchainMonitoringSession
        migrations.CreateModel(
            name='BlockchainMonitoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_session_scheduled', models.DateTimeField(blank=True, null=True)),
                ('spider_data_processed', models.IntegerField(default=0)),
                ('transactions_analyzed', models.IntegerField(default=0)),
                ('contracts_audited', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('critical_alerts', models.IntegerField(default=0)),
                ('high_alerts', models.IntegerField(default=0)),
                ('medium_alerts', models.IntegerField(default=0)),
                ('low_alerts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('partial', 'Partial'),
                ], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('discord_summary_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'blockchain_monitoring_session',
                'ordering': ['-started_at'],
            },
        ),

        # StockMarketAlert
        migrations.CreateModel(
            name='StockMarketAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[
                    ('high_conviction_bull', 'High Conviction Bullish'),
                    ('high_conviction_bear', 'High Conviction Bearish'),
                    ('debate_zone', 'Debate Zone - Bull vs Bear'),
                    ('risk_alert', 'Risk Alert'),
                    ('momentum_shift', 'Momentum Shift'),
                    ('institutional_activity', 'Institutional Activity'),
                    ('anomaly_detected', 'Anomaly Detected'),
                    ('earnings_alert', 'Earnings Alert'),
                ], db_index=True, max_length=50)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('bull_case', models.TextField(blank=True)),
                ('bear_case', models.TextField(blank=True)),
                ('disagreement_level', models.CharField(choices=[
                    ('consensus', 'Consensus'),
                    ('mild', 'Mild Disagreement'),
                    ('strong', 'Strong Disagreement'),
                    ('extreme', 'Extreme Disagreement'),
                ], default='mild', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('bull_score', models.IntegerField(default=50)),
                ('bear_score', models.IntegerField(default=50)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source_data', models.JSONField(default=dict)),
                ('related_brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='core.marketintelligencebrief')),
                ('recommended_action', models.CharField(choices=[
                    ('watch', 'Watch'),
                    ('research', 'Research Further'),
                    ('consider_buy', 'Consider Buying'),
                    ('consider_sell', 'Consider Selling'),
                    ('hedge', 'Consider Hedging'),
                    ('avoid', 'Avoid'),
                ], default='watch', max_length=50)),
                ('discord_sent', models.BooleanField(default=False)),
                ('discord_sent_at', models.DateTimeField(blank=True, null=True)),
                ('discord_message_id', models.CharField(blank=True, max_length=100)),
                ('viewed', models.BooleanField(default=False)),
                ('bookmarked', models.BooleanField(default=False)),
                ('user_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_market_alert',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockmarketalert',
            index=models.Index(fields=['symbol', '-detected_at'], name='stock_marke_symbol_3b8f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmarketalert',
            index=models.Index(fields=['alert_type', '-detected_at'], name='stock_marke_alert_t_5c9e1d_idx'),
        ),

        # MarketMonitoringSession
        migrations.CreateModel(
            name='MarketMonitoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_session_scheduled', models.DateTimeField(blank=True, null=True)),
                ('spider_data_processed', models.IntegerField(default=0)),
                ('stocks_analyzed', models.IntegerField(default=0)),
                ('bull_analyses', models.IntegerField(default=0)),
                ('bear_analyses', models.IntegerField(default=0)),
                ('debates_generated', models.IntegerField(default=0)),
                ('alerts_generated', models.IntegerField(default=0)),
                ('high_conviction_count', models.IntegerField(default=0)),
                ('debate_zone_count', models.IntegerField(default=0)),
                ('risk_alerts_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[
                    ('running', 'Running'),
                    ('completed', 'Completed'),
                    ('failed', 'Failed'),
                    ('partial', 'Partial'),
                ], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_sessions', to='core.marketintelligencebrief')),
                ('discord_summary_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'market_monitoring_session',
                'ordering': ['-started_at'],
            },
        ),
    ]
