# Generated by Django 5.0.6 on 2025-12-17 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_session_477_autonomous_alerts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolveRenderJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resolve_job_id",
                    models.CharField(
                        help_text="Job ID from resolve_node server",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("rendering", "Rendering"),
                            ("done", "Done"),
                            ("error", "Error"),
                            ("uploading", "Uploading"),
                            ("uploaded", "Uploaded"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "source_video_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of source video IDs that were rendered",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default_mp4", "Default MP4 (1080p H.264)"),
                            ("high_quality", "High Quality (Multi-pass)"),
                        ],
                        default="default_mp4",
                        max_length=50,
                    ),
                ),
                (
                    "color_grade",
                    models.CharField(
                        blank=True,
                        help_text="Color grade preset applied (e.g., cinematic_warm, cyberpunk_neon)",
                        max_length=50,
                    ),
                ),
                (
                    "spider_trends_used",
                    models.JSONField(
                        default=dict,
                        help_text="Spider creative trends at time of render (for learning)",
                    ),
                ),
                (
                    "auto_grade_selected",
                    models.BooleanField(
                        default=False,
                        help_text="Was the color grade automatically selected based on trends?",
                    ),
                ),
                (
                    "output_url",
                    models.URLField(
                        blank=True, help_text="URL to download the rendered video"
                    ),
                ),
                (
                    "output_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Local file path of rendered video",
                        max_length=500,
                    ),
                ),
                (
                    "file_size_mb",
                    models.FloatField(
                        blank=True, help_text="Output file size in megabytes", null=True
                    ),
                ),
                (
                    "render_duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="How long the render took", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if status is 'error'"
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating 1-5 (for learning which grades work best)",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True,
                        help_text="Optional user feedback on the render quality",
                    ),
                ),
                (
                    "was_used",
                    models.BooleanField(
                        default=False,
                        help_text="Did the user actually use/publish this output?",
                    ),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Revenue attributed to this render (for ROI tracking)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolve_render_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resolve Render Job",
                "verbose_name_plural": "Resolve Render Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="BlockchainMonitoringSession",
        ),
        migrations.DeleteModel(
            name="BlockchainSecurityAlert",
        ),
        migrations.RemoveField(
            model_name="stockmarketalert",
            name="related_brief",
        ),
        migrations.DeleteModel(
            name="MarketMonitoringSession",
        ),
        migrations.DeleteModel(
            name="StockMarketAlert",
        ),
        migrations.AddIndex(
            model_name="resolverenderjob",
            index=models.Index(
                fields=["user", "status"], name="core_resolv_user_id_076f79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resolverenderjob",
            index=models.Index(
                fields=["color_grade", "user_rating"],
                name="core_resolv_color_g_601079_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resolverenderjob",
            index=models.Index(
                fields=["auto_grade_selected"], name="core_resolv_auto_gr_7cd664_idx"
            ),
        ),
    ]
