# Generated by Django 5.1.4 - Session 477 Part 2
# Event-driven Situation Triggers for Autonomous Alerts

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_session_478_resolve_render_job'),
    ]

    operations = [
        # SituationTrigger - Configurable triggers for autonomous alerts
        migrations.CreateModel(
            name='SituationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable trigger name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of what this trigger detects')),
                ('situation_type', models.CharField(
                    choices=[
                        ('blockchain', 'Blockchain Security'),
                        ('stock_market', 'Stock Market Intelligence'),
                        ('both', 'Both Systems'),
                    ],
                    db_index=True,
                    default='blockchain',
                    max_length=20
                )),
                ('trigger_type', models.CharField(
                    choices=[
                        ('whale_movement', 'Whale Movement (Large Transfer)'),
                        ('price_crash', 'Price Crash (Significant Drop)'),
                        ('price_surge', 'Price Surge (Significant Rise)'),
                        ('volume_spike', 'Volume Spike (Unusual Activity)'),
                        ('exploit_keyword', 'Exploit/Hack Keyword Detected'),
                        ('stock_mover', 'Stock Mover (Price Change)'),
                        ('sec_filing', 'SEC Filing Detected'),
                        ('breaking_news', 'Breaking News (Market Keywords)'),
                        ('earnings_surprise', 'Earnings Surprise'),
                        ('institutional_filing', 'Institutional Filing (13F/13D)'),
                    ],
                    db_index=True,
                    max_length=30
                )),
                ('target_spiders', models.JSONField(default=list, help_text='List of spider names to monitor (empty = all spiders)')),
                ('target_field', models.CharField(help_text="JSON path in raw_data to check (e.g., 'items.0.value', 'price_change_percentage_24h')", max_length=100)),
                ('operator', models.CharField(
                    choices=[
                        ('gt', 'Greater Than'),
                        ('gte', 'Greater Than or Equal'),
                        ('lt', 'Less Than'),
                        ('lte', 'Less Than or Equal'),
                        ('eq', 'Equal To'),
                        ('neq', 'Not Equal To'),
                        ('contains', 'Contains (text)'),
                        ('regex', 'Regex Match'),
                    ],
                    default='gt',
                    max_length=20
                )),
                ('threshold_value', models.CharField(help_text='Value to compare against (number or text pattern)', max_length=200)),
                ('severity', models.CharField(
                    choices=[
                        ('critical', 'Critical'),
                        ('high', 'High'),
                        ('medium', 'Medium'),
                        ('low', 'Low'),
                    ],
                    default='high',
                    max_length=20
                )),
                ('alert_title_template', models.CharField(default='{trigger_name}: {matched_value}', help_text='Template for alert title. Use {trigger_name}, {matched_value}, {spider_name}', max_length=200)),
                ('cooldown_minutes', models.IntegerField(default=30, help_text='Minimum minutes between alerts from this trigger')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When this trigger last fired', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=50, help_text='Higher priority triggers are evaluated first (0-100)')),
                ('total_fires', models.IntegerField(default=0)),
                ('total_alerts_generated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'situation_trigger',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='situationtrigger',
            index=models.Index(fields=['situation_type', 'is_active'], name='situation_t_situati_8f3c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='situationtrigger',
            index=models.Index(fields=['trigger_type', 'is_active'], name='situation_t_trigger_9b4d1e_idx'),
        ),

        # TriggerEvent - Record of each trigger firing
        migrations.CreateModel(
            name='TriggerEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.situationtrigger')),
                ('spider_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_events', to='core.spiderdata')),
                ('spider_name', models.CharField(max_length=100)),
                ('matched_field', models.CharField(max_length=100)),
                ('matched_value', models.CharField(max_length=500)),
                ('raw_data_snapshot', models.JSONField(default=dict)),
                ('alert_generated', models.BooleanField(default=False)),
                ('alert_id', models.UUIDField(blank=True, null=True)),
                ('alert_type', models.CharField(blank=True, max_length=50)),
                ('discord_sent', models.BooleanField(default=False)),
                ('discord_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending Processing'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed'),
                        ('skipped', 'Skipped (Cooldown/Duplicate)'),
                    ],
                    default='pending',
                    max_length=20
                )),
                ('error_message', models.TextField(blank=True)),
                ('fired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trigger_event',
                'ordering': ['-fired_at'],
            },
        ),
        migrations.AddIndex(
            model_name='triggerevent',
            index=models.Index(fields=['trigger', '-fired_at'], name='trigger_eve_trigger_6c8e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='triggerevent',
            index=models.Index(fields=['status', '-fired_at'], name='trigger_eve_status_4a7f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='triggerevent',
            index=models.Index(fields=['spider_name', '-fired_at'], name='trigger_eve_spider__5b9a3f_idx'),
        ),
    ]
