# Generated by Django 5.0.6 on 2025-12-18 14:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_session_479_autonomous_situations"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiderExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spider_name", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(default="general", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled (Celery Beat)"),
                            ("manual", "Manual (UI)"),
                            ("on_demand", "On Demand (API)"),
                            ("retry", "Retry"),
                            ("trigger", "Event Trigger"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("items_collected", models.IntegerField(default=0)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full stack trace for debugging"
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True, help_text="Exception class name", max_length=200
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "source_urls_attempted",
                    models.JSONField(
                        default=list, help_text="URLs spider tried to fetch"
                    ),
                ),
                (
                    "response_codes",
                    models.JSONField(
                        default=dict, help_text="HTTP response codes received"
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Spider Execution Log",
                "verbose_name_plural": "Spider Execution Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="situationtrigger",
            new_name="situation_t_situati_a4d029_idx",
            old_name="situation_t_situati_8f3c2a_idx",
        ),
        migrations.RenameIndex(
            model_name="situationtrigger",
            new_name="situation_t_trigger_94e1b9_idx",
            old_name="situation_t_trigger_9b4d1e_idx",
        ),
        migrations.RenameIndex(
            model_name="triggerevent",
            new_name="trigger_eve_trigger_d1796a_idx",
            old_name="trigger_eve_trigger_6c8e2d_idx",
        ),
        migrations.RenameIndex(
            model_name="triggerevent",
            new_name="trigger_eve_status_2bf24c_idx",
            old_name="trigger_eve_status_4a7f1c_idx",
        ),
        migrations.RenameIndex(
            model_name="triggerevent",
            new_name="trigger_eve_spider__8a8b88_idx",
            old_name="trigger_eve_spider__5b9a3f_idx",
        ),
        migrations.AlterField(
            model_name="designtrend",
            name="colors",
            field=models.JSONField(default=list, help_text="List of hex colors"),
        ),
        migrations.AlterField(
            model_name="designtrend",
            name="example_urls",
            field=models.JSONField(default=list, help_text="Example design URLs"),
        ),
        migrations.AlterField(
            model_name="designtrend",
            name="fonts",
            field=models.JSONField(default=list, help_text="List of font names"),
        ),
        migrations.AlterField(
            model_name="designtrend",
            name="keywords",
            field=models.JSONField(default=list, help_text="Associated keywords"),
        ),
        migrations.AlterField(
            model_name="situationtrigger",
            name="situation_type",
            field=models.CharField(
                choices=[
                    ("blockchain", "Blockchain Security"),
                    ("stock_market", "Stock Market Intelligence"),
                    ("market_intelligence", "Market Intelligence Desk"),
                    ("sec_filing", "SEC Filing Analyzer"),
                    ("crypto_sentiment", "Crypto Sentiment Monitor"),
                    ("earnings_prediction", "Earnings Surprise Predictor"),
                    ("content_studio", "Autonomous Content Studio"),
                    ("narrative_drift", "Narrative Drift Detector"),
                    ("design_trends", "Design Trends Monitor"),
                    ("viral_prediction", "Viral Content Predictor"),
                    ("thumbnail_optimization", "Thumbnail A/B Optimizer"),
                    ("job_matching", "Job Match Intelligence"),
                    ("freelance_scout", "Freelance Opportunity Scout"),
                    ("side_hustle", "Side Hustle Detector"),
                    ("tech_stack", "Tech Stack Evolution Tracker"),
                    ("ai_model", "AI Model Release Monitor"),
                    ("skill_gap", "Course & Skill Gap Analyzer"),
                    ("case_law", "Case Law Monitor"),
                    ("regulatory", "Regulatory Change Detector"),
                    ("both", "Multiple Systems"),
                ],
                db_index=True,
                default="blockchain",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="situationtrigger",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("whale_movement", "Whale Movement (Large Transfer)"),
                    ("price_crash", "Price Crash (Significant Drop)"),
                    ("price_surge", "Price Surge (Significant Rise)"),
                    ("volume_spike", "Volume Spike (Unusual Activity)"),
                    ("exploit_keyword", "Exploit/Hack Keyword Detected"),
                    ("crypto_sentiment", "Crypto Sentiment Shift"),
                    ("stock_mover", "Stock Mover (Price Change)"),
                    ("sec_filing", "SEC Filing Detected"),
                    ("breaking_news", "Breaking News (Market Keywords)"),
                    ("earnings_surprise", "Earnings Surprise"),
                    ("institutional_filing", "Institutional Filing (13F/13D)"),
                    ("market_intelligence", "Market Intelligence Signal"),
                    ("content_trend", "Content Trend Detected"),
                    ("narrative_drift", "Narrative Drift Detected"),
                    ("viral_content", "Viral Content Signal"),
                    ("design_trend", "Design Trend Detected"),
                    ("visual_trend", "Visual/Thumbnail Trend"),
                    ("creative_opportunity", "Creative Opportunity"),
                    ("job_match", "Job Match Found"),
                    ("freelance_opportunity", "Freelance Opportunity"),
                    ("side_hustle", "Side Hustle Opportunity"),
                    ("high_paying_gig", "High-Paying Gig Detected"),
                    ("tech_stack_change", "Tech Stack Change"),
                    ("ai_model_release", "AI Model Release"),
                    ("skill_gap", "Skill Gap Opportunity"),
                    ("tech_breakthrough", "Tech Breakthrough"),
                    ("case_law_update", "Case Law Update"),
                    ("regulatory_change", "Regulatory Change"),
                    ("legal_precedent", "Legal Precedent Set"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="spiderexecutionlog",
            name="parent_execution",
            field=models.ForeignKey(
                blank=True,
                help_text="Original execution if this is a retry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="core.spiderexecutionlog",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderexecutionlog",
            index=models.Index(
                fields=["spider_name", "-started_at"],
                name="core_spider_spider__01477d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderexecutionlog",
            index=models.Index(
                fields=["status", "-started_at"], name="core_spider_status_c8d9d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spiderexecutionlog",
            index=models.Index(
                fields=["-started_at"], name="core_spider_started_3429cb_idx"
            ),
        ),
    ]
