# Generated by Django 5.0.6 on 2025-12-19 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_session_492_certificate_service_uuid_fix"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastDebate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("topic_question", models.TextField()),
                ("topic_context", models.TextField(blank=True)),
                ("participants", models.JSONField(default=list)),
                ("research_results", models.JSONField(default=dict)),
                ("arguments", models.JSONField(default=dict)),
                ("debate_transcript", models.JSONField(default=list)),
                ("consensus", models.TextField(blank=True)),
                ("key_takeaways", models.JSONField(default=list)),
                ("winner", models.CharField(blank=True, max_length=100)),
                ("debate_duration_seconds", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("researching", "Researching"),
                            ("debating", "Debating"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Podcast Debate",
                "verbose_name_plural": "Podcast Debates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PodcastParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host/Moderator"),
                            ("advocate", "Advocate (argues FOR)"),
                            ("skeptic", "Skeptic (argues AGAINST)"),
                            ("analyst", "Analyst (data-driven neutral)"),
                            ("expert", "Expert (domain knowledge)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("personality", models.TextField()),
                ("speaking_style", models.CharField(max_length=200)),
                ("expertise_areas", models.JSONField(default=list)),
                (
                    "voice_id",
                    models.CharField(
                        choices=[
                            ("Rachel", "Rachel - Warm, enthusiastic"),
                            ("Drew", "Drew - Confident, clear"),
                            ("Clyde", "Clyde - Authoritative, deep"),
                            ("Paul", "Paul - Calm, conversational"),
                            ("Aria", "Aria - Expressive, dynamic"),
                            ("Domi", "Domi - Strong, assertive"),
                            ("Dave", "Dave - Friendly, approachable"),
                            ("Antoni", "Antoni - Warm narrator"),
                            ("Sarah", "Sarah - Soft, thoughtful"),
                            ("Josh", "Josh - Energetic, young"),
                            ("Bella", "Bella - Gentle, soothing"),
                            ("Charlotte", "Charlotte - Professional, elegant"),
                        ],
                        default="Antoni",
                        max_length=100,
                    ),
                ),
                (
                    "agent_class",
                    models.CharField(default="DebateAdvocateAgent", max_length=100),
                ),
                ("episodes_participated", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Participant",
                "verbose_name_plural": "Podcast Participants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PodcastShow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("topic_domain", models.TextField(blank=True)),
                ("target_audience", models.CharField(blank=True, max_length=200)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("debate", "Debate - Two sides argue"),
                            ("roundtable", "Roundtable - Multiple perspectives"),
                            ("interview", "Interview - Host interviews expert"),
                            ("monologue", "Monologue - Single speaker deep dive"),
                        ],
                        default="debate",
                        max_length=20,
                    ),
                ),
                ("participant_count", models.IntegerField(default=3)),
                ("episode_duration_minutes", models.IntegerField(default=10)),
                ("host_voice_id", models.CharField(default="Antoni", max_length=100)),
                ("participant_voices", models.JSONField(default=list)),
                ("generate_audio", models.BooleanField(default=True)),
                ("include_intro_music", models.BooleanField(default=True)),
                ("include_outro_music", models.BooleanField(default=True)),
                ("episode_count", models.IntegerField(default=0)),
                ("total_listens", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_shows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Show",
                "verbose_name_plural": "Podcast Shows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("topic", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("episode_number", models.IntegerField(default=1)),
                ("script", models.TextField(blank=True)),
                ("script_segments", models.JSONField(default=list)),
                ("show_notes", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="podcasts/audio/"
                    ),
                ),
                ("audio_url", models.URLField(blank=True)),
                ("audio_duration_seconds", models.IntegerField(null=True)),
                ("audio_segments", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("researching", "Researching Positions"),
                            ("debating", "Agents Debating"),
                            ("scripting", "Generating Script"),
                            ("recording", "Recording Audio"),
                            ("assembling", "Assembling Audio"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("progress_percent", models.IntegerField(default=0)),
                ("generation_config", models.JSONField(default=dict)),
                ("listen_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "debate",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode",
                        to="core.podcastdebate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="podcast_episodes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="core.podcastshow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast Episode",
                "verbose_name_plural": "Podcast Episodes",
                "ordering": ["-created_at"],
            },
        ),
    ]
