# Generated by Django 5.0.6 on 2025-12-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_session_496_podcast_studio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autonomoussituationsession",
            name="situation_type",
            field=models.CharField(
                choices=[
                    ("design_trends", "Design Trends"),
                    ("viral_prediction", "Viral Prediction"),
                    ("thumbnail_optimization", "Thumbnail Optimization"),
                    ("content_studio", "Content Studio"),
                    ("job_matching", "Job Matching"),
                    ("freelance_scout", "Freelance Scout"),
                    ("side_hustle", "Side Hustle Detection"),
                    ("sec_filing", "SEC Filing Analysis"),
                    ("crypto_sentiment", "Crypto Sentiment"),
                    ("earnings_prediction", "Earnings Prediction"),
                    ("stock_market", "Stock Market Intelligence"),
                    ("blockchain", "Blockchain Security"),
                    ("tech_stack", "Tech Stack Evolution"),
                    ("ai_model", "AI Model Releases"),
                    ("skill_gap", "Skill Gap Analysis"),
                    ("market_intelligence", "Market Intelligence Desk"),
                    ("narrative_drift", "Narrative Drift Detector"),
                    ("case_law", "Case Law Monitor"),
                    ("regulatory", "Regulatory Changes"),
                ],
                max_length=50,
            ),
        ),
    ]
