# Generated by Django 5.0.6 on 2025-12-24 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_session_513_campaign_orchestrator"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentlearningconnection",
            name="last_mythology_block_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time mythology blocked a transfer",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentlearningconnection",
            name="mythology_blocks",
            field=models.IntegerField(
                default=0, help_text="Transfers blocked by mythology validation"
            ),
        ),
        migrations.CreateModel(
            name="MythologyQuarantine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("blocked_title", models.CharField(max_length=500)),
                (
                    "blocked_content",
                    models.TextField(help_text="The content that was blocked"),
                ),
                (
                    "blocked_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of what would have been transferred",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("financial_myth", "Financial Myth"),
                            ("technical_myth", "Technical Myth"),
                            ("time_myth", "Time Myth"),
                            ("dangerous_myth", "Dangerous Myth"),
                            ("spider_data_myth", "Spider Data Myth"),
                        ],
                        max_length=50,
                    ),
                ),
                ("violation_count", models.IntegerField(default=1)),
                (
                    "violation_patterns",
                    models.JSONField(
                        default=list, help_text="Patterns that triggered the block"
                    ),
                ),
                (
                    "mythology_warning",
                    models.TextField(blank=True, help_text="Mythology's explanation"),
                ),
                (
                    "spider_sources",
                    models.JSONField(
                        default=list,
                        help_text="Spider names that contributed to this knowledge",
                    ),
                ),
                (
                    "source_urls",
                    models.JSONField(
                        default=list, help_text="Original URLs if available"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved (false positive)"),
                            ("rejected", "Rejected (confirmed myth)"),
                            ("edited", "Edited and Released"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quarantined_transfers",
                        to="core.agentlearningconnection",
                    ),
                ),
                (
                    "source_knowledge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mythology_quarantines",
                        to="core.agentknowledgesource",
                    ),
                ),
                (
                    "student_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mythology_blocks_as_student",
                        to="core.agent",
                    ),
                ),
                (
                    "teacher_agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mythology_blocks_as_teacher",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mythology Quarantine",
                "verbose_name_plural": "Mythology Quarantines",
                "ordering": ["-created_at"],
            },
        ),
    ]
