# Generated by Django 5.0.6 on 2025-12-24 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_session_541_mythology_quarantine"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelfBlog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("intro", models.TextField()),
                (
                    "sections",
                    models.JSONField(
                        default=list, help_text="List of {header, content} sections"
                    ),
                ),
                ("conclusion", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("full_text", models.TextField(help_text="Complete blog as markdown")),
                ("tone", models.CharField(default="professional", max_length=50)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "stats_snapshot",
                    models.JSONField(
                        default=dict, help_text="System stats when blog was generated"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Self Blog",
                "verbose_name_plural": "Self Blogs",
                "ordering": ["-created_at"],
            },
        ),
    ]
