# Generated by Django 5.0.6 on 2025-12-24 07:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_session_543_self_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReasoningConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the reasoning engine is active"
                    ),
                ),
                (
                    "thinking_interval_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="How often to run thinking cycles (in minutes)",
                    ),
                ),
                (
                    "min_insights_to_act",
                    models.IntegerField(
                        default=1,
                        help_text="Minimum insights needed before taking action",
                    ),
                ),
                (
                    "min_priority_to_act",
                    models.FloatField(
                        default=3.0,
                        help_text="Minimum priority score to execute actions",
                    ),
                ),
                (
                    "max_actions_per_cycle",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum actions to take per thinking cycle",
                    ),
                ),
                (
                    "allowed_actions",
                    models.JSONField(
                        default=list,
                        help_text="List of action types the engine is allowed to perform",
                    ),
                ),
                (
                    "require_approval_above_priority",
                    models.FloatField(
                        default=8.0,
                        help_text="Priority threshold above which human approval is required",
                    ),
                ),
                (
                    "lookback_hours",
                    models.IntegerField(
                        default=24, help_text="How far back to look for context data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Reasoning Configuration",
                "verbose_name_plural": "Reasoning Configurations",
            },
        ),
        migrations.CreateModel(
            name="ThoughtRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cycle_number",
                    models.IntegerField(help_text="Sequential thinking cycle number"),
                ),
                (
                    "cycle_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled Cycle"),
                            ("triggered", "Event Triggered"),
                            ("manual", "Manual Request"),
                            ("continuous", "Continuous Mode"),
                        ],
                        default="scheduled",
                        max_length=50,
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(help_text="Summary of data considered"),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict, help_text="Raw context data snapshot"
                    ),
                ),
                (
                    "reflection",
                    models.TextField(help_text="System's reflection on the context"),
                ),
                (
                    "insights",
                    models.JSONField(default=list, help_text="Key insights identified"),
                ),
                (
                    "patterns",
                    models.JSONField(
                        default=list, help_text="Patterns noticed across data"
                    ),
                ),
                (
                    "opportunities",
                    models.JSONField(
                        default=list, help_text="Opportunities identified"
                    ),
                ),
                (
                    "concerns",
                    models.JSONField(default=list, help_text="Risks or concerns noted"),
                ),
                (
                    "decisions",
                    models.JSONField(
                        default=list, help_text="Decisions made and reasoning"
                    ),
                ),
                (
                    "priority_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall priority/importance of this cycle's insights",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                (
                    "actions_planned",
                    models.JSONField(default=list, help_text="Actions planned to take"),
                ),
                (
                    "actions_executed",
                    models.JSONField(
                        default=list, help_text="Actions actually executed"
                    ),
                ),
                (
                    "execution_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("thinking", "Thinking"),
                            ("deciding", "Deciding"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("thinking_duration_seconds", models.FloatField(default=0.0)),
                ("model_used", models.CharField(default="gpt-5-mini", max_length=50)),
                ("token_usage", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Thought Record",
                "verbose_name_plural": "Thought Records",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AutonomousAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("spawn_spider", "Spawn Spider Crawl"),
                            ("generate_content", "Generate Content"),
                            ("trigger_debate", "Trigger Agent Debate"),
                            ("create_report", "Create Report"),
                            ("send_alert", "Send Alert/Notification"),
                            ("request_research", "Request Deep Research"),
                            ("schedule_followup", "Schedule Follow-up"),
                            ("trigger_conversation", "Trigger Agent Conversation"),
                            ("update_strategy", "Update Strategy"),
                            ("archive_insight", "Archive Important Insight"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_name",
                    models.CharField(
                        help_text="Human-readable action name", max_length=200
                    ),
                ),
                (
                    "action_params",
                    models.JSONField(
                        default=dict, help_text="Parameters for the action"
                    ),
                ),
                ("reasoning", models.TextField(help_text="Why this action was chosen")),
                (
                    "expected_outcome",
                    models.TextField(blank=True, help_text="What we expect to happen"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical - Execute Immediately"),
                            ("high", "High Priority"),
                            ("medium", "Medium Priority"),
                            ("low", "Low Priority"),
                            ("background", "Background Task"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("executing", "Executing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.JSONField(default=dict, help_text="Result of the action"),
                ),
                (
                    "result_summary",
                    models.TextField(
                        blank=True, help_text="Human-readable result summary"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "outcome_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 rating of how well the action worked",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "outcome_notes",
                    models.TextField(blank=True, help_text="Notes on the outcome"),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "thought_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="core.thoughtrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Autonomous Action",
                "verbose_name_plural": "Autonomous Actions",
                "ordering": ["-created_at"],
            },
        ),
    ]
