# Generated by Django 5.0.6 on 2025-12-26 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_session_546_tracked_concern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proactivenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("alert", "Alert"),
                    ("suggestion", "Suggestion"),
                    ("insight", "Insight"),
                    ("reminder", "Reminder"),
                    ("celebration", "Celebration"),
                    ("warning", "Warning"),
                    ("update", "System Update"),
                    ("action_required", "Human Action Required"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ArtifactExtractionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("artifacts_found", models.IntegerField(default=0)),
                ("extraction_time_ms", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_logs",
                        to="core.agentconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Extraction Log",
                "verbose_name_plural": "Artifact Extraction Logs",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("experiment", "Experiment"),
                            ("risk", "Risk Identified"),
                            ("data_spec", "Data/Pipeline Spec"),
                            ("question", "Open Question"),
                            ("insight", "Key Insight"),
                            ("action_item", "Action Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "source_message_index",
                    models.IntegerField(
                        blank=True,
                        help_text="Index of message in conversation where this was proposed",
                        null=True,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deferred", "Deferred"),
                            ("implemented", "Implemented"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True)),
                (
                    "importance_score",
                    models.FloatField(
                        default=0.5, help_text="0-1, how important is this artifact"
                    ),
                ),
                (
                    "urgency_score",
                    models.FloatField(
                        default=0.5, help_text="0-1, how urgent is this artifact"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5, help_text="0-1, extraction confidence"
                    ),
                ),
                (
                    "composite_score",
                    models.FloatField(
                        default=0.5, help_text="Combined score for ranking in queue"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_artifacts",
                        to="core.agentconversation",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_artifact_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="proposed_extracted_artifacts",
                        to="core.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Artifact",
                "verbose_name_plural": "Extracted Artifacts",
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "artifact_type"],
                        name="core_extrac_status_e3ab1e_idx",
                    ),
                    models.Index(
                        fields=["composite_score"],
                        name="core_extrac_composi_513ca8_idx",
                    ),
                    models.Index(
                        fields=["conversation", "artifact_type"],
                        name="core_extrac_convers_95f66c_idx",
                    ),
                ],
            },
        ),
    ]
