# Generated by Django 5.0.6 on 2025-12-26 01:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_session_555_extracted_artifacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(max_length=100)),
                ("task_description", models.TextField()),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.extractedartifact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artifact Execution",
                "verbose_name_plural": "Artifact Executions",
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_artifa_status_21d796_idx"
                    ),
                    models.Index(
                        fields=["artifact", "status"],
                        name="core_artifa_artifac_070932_idx",
                    ),
                ],
            },
        ),
    ]
