# Generated by Django 5.0.6 on 2025-12-26 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_session_555_artifact_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySynthesis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("artifacts_extracted", models.IntegerField(default=0)),
                ("artifacts_by_type", models.JSONField(default=dict)),
                ("artifacts_by_status", models.JSONField(default=dict)),
                ("top_artifacts", models.JSONField(default=list)),
                ("decisions_approved", models.IntegerField(default=0)),
                ("decisions_rejected", models.IntegerField(default=0)),
                ("decisions_deferred", models.IntegerField(default=0)),
                ("executions_total", models.IntegerField(default=0)),
                ("executions_succeeded", models.IntegerField(default=0)),
                ("executions_failed", models.IntegerField(default=0)),
                ("execution_success_rate", models.FloatField(default=0.0)),
                ("avg_execution_time_ms", models.IntegerField(default=0)),
                ("most_active_agents", models.JSONField(default=list)),
                ("agent_success_rates", models.JSONField(default=dict)),
                ("trend_analysis", models.TextField(blank=True)),
                ("key_themes", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                ("pending_high_priority", models.IntegerField(default=0)),
                ("oldest_pending_days", models.IntegerField(default=0)),
                ("posted_to_discord", models.BooleanField(default=False)),
                ("discord_message_id", models.CharField(blank=True, max_length=100)),
                ("report_markdown", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Weekly Synthesis",
                "verbose_name_plural": "Weekly Syntheses",
                "ordering": ["-period_end"],
            },
        ),
    ]
