# Generated by Django 5.0.6 on 2025-12-26 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_session_555_weekly_synthesis"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("artifact", "Extracted Artifact"),
                            ("dream", "Agent Dream"),
                            ("project", "Creative Project"),
                            ("decision", "Agent Decision"),
                            ("experiment", "Experiment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("neutral_summary", models.TextField()),
                ("pro_case", models.TextField()),
                ("con_case", models.TextField()),
                ("open_questions", models.JSONField(default=list)),
                ("key_evidence", models.JSONField(default=dict)),
                ("ai_recommendation", models.TextField()),
                (
                    "ai_lean",
                    models.CharField(
                        choices=[
                            ("strong_approve", "Strong Approve"),
                            ("lean_approve", "Lean Approve"),
                            ("neutral", "Neutral - Need More Info"),
                            ("lean_decline", "Lean Decline"),
                            ("strong_decline", "Strong Decline"),
                            ("pilot", "Narrow Pilot First"),
                            ("defer", "Defer - Not Now"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ai_confidence", models.FloatField(default=0.5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("awaiting_human", "Awaiting Human Review"),
                            ("approved", "Approved"),
                            ("approved_with_conditions", "Approved with Conditions"),
                            ("declined", "Declined"),
                            ("deferred", "Deferred"),
                        ],
                        default="awaiting_human",
                        max_length=25,
                    ),
                ),
                ("decision_conditions", models.TextField(blank=True)),
                ("decision_reasoning", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("questions_asked_pro", models.IntegerField(default=0)),
                ("questions_asked_con", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Document",
                "verbose_name_plural": "Review Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SideChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("pro", "Pro Side"), ("con", "Con Side")],
                        max_length=10,
                    ),
                ),
                ("messages", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "review_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="side_chats",
                        to="core.reviewdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Side Chat",
                "verbose_name_plural": "Side Chats",
            },
        ),
        migrations.AddIndex(
            model_name="reviewdocument",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="core_review_target__fcf6e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdocument",
            index=models.Index(fields=["status"], name="core_review_status_913aea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="sidechat",
            unique_together={("review_document", "side")},
        ),
    ]
