# Generated by Django 5.0.6 on 2025-12-27 21:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0124_session_555_review_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bankroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "highest_balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "lowest_balance",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=12),
                ),
                (
                    "unit_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Standard unit size for 1-unit bets",
                        max_digits=12,
                    ),
                ),
                (
                    "max_bet_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        help_text="Maximum % of bankroll per single bet",
                        max_digits=5,
                    ),
                ),
                ("total_wagers", models.PositiveIntegerField(default=0)),
                ("total_won", models.PositiveIntegerField(default=0)),
                ("total_lost", models.PositiveIntegerField(default=0)),
                ("total_pushed", models.PositiveIntegerField(default=0)),
                ("total_pending", models.PositiveIntegerField(default=0)),
                (
                    "total_wagered",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_returned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("current_streak", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("worst_streak", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_wager_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betting_bankroll",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bankrolls",
            },
        ),
        migrations.CreateModel(
            name="BettingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("wager_count", models.PositiveIntegerField(default=0)),
                (
                    "total_staked",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("win_count", models.PositiveIntegerField(default=0)),
                ("loss_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bankroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.bankroll",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Wager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport", models.CharField(blank=True, max_length=50)),
                ("event_name", models.CharField(max_length=200)),
                (
                    "selection",
                    models.CharField(help_text="What you bet on", max_length=200),
                ),
                (
                    "bet_type",
                    models.CharField(
                        choices=[
                            ("moneyline", "Moneyline"),
                            ("spread", "Spread"),
                            ("total", "Over/Under"),
                            ("prop", "Prop Bet"),
                            ("parlay", "Parlay"),
                            ("teaser", "Teaser"),
                            ("futures", "Futures"),
                            ("live", "Live Bet"),
                            ("prediction", "Prediction Market"),
                            ("other", "Other"),
                        ],
                        default="moneyline",
                        max_length=20,
                    ),
                ),
                (
                    "line",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Spread or total line",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "odds_american",
                    models.IntegerField(help_text="American odds (e.g., -110, +150)"),
                ),
                (
                    "odds_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("stake", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Units wagered (based on bankroll unit size)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("pushed", "Pushed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("bookmaker", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="discord, web, manual", max_length=50
                    ),
                ),
                ("agent_recommendation", models.BooleanField(default=False)),
                (
                    "recommendation_confidence",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("placed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "bankroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wagers",
                        to="core.bankroll",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
    ]
