# Generated by Django 5.0.6 on 2025-12-28 03:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0127_session_562_push_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="BettingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_wagers", models.IntegerField(default=0)),
                (
                    "total_stake",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_profit_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("pushes", models.IntegerField(default=0)),
                ("pending", models.IntegerField(default=0)),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = win streak, negative = loss streak",
                    ),
                ),
                ("longest_win_streak", models.IntegerField(default=0)),
                ("longest_loss_streak", models.IntegerField(default=0)),
                (
                    "singles_record",
                    models.JSONField(
                        default=dict, help_text="{'wins': 0, 'losses': 0, 'profit': 0}"
                    ),
                ),
                (
                    "parlays_record",
                    models.JSONField(
                        default=dict, help_text="{'wins': 0, 'losses': 0, 'profit': 0}"
                    ),
                ),
                (
                    "stats_by_sport",
                    models.JSONField(
                        default=dict, help_text="{'nba': {'wins': 0, ...}, ...}"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Betting stats",
            },
        ),
        migrations.CreateModel(
            name="PlacedWager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "wager_type",
                    models.CharField(
                        choices=[("single", "Single Bet"), ("parlay", "Parlay")],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "stake",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount wagered", max_digits=10
                    ),
                ),
                ("odds", models.IntegerField(help_text="American odds for the wager")),
                (
                    "potential_payout",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potential winnings including stake",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("push", "Push"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "result_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual P/L",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("placed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="PlacedWagerLeg",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(help_text="The Odds API event ID", max_length=100),
                ),
                ("sport", models.CharField(max_length=50)),
                (
                    "matchup",
                    models.CharField(
                        help_text="e.g., 'Lakers vs Celtics'", max_length=200
                    ),
                ),
                ("commence_time", models.DateTimeField(blank=True, null=True)),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("h2h", "Moneyline"),
                            ("spreads", "Spread"),
                            ("totals", "Total"),
                            ("props", "Player Prop"),
                            ("futures", "Futures"),
                        ],
                        default="h2h",
                        max_length=20,
                    ),
                ),
                (
                    "pick",
                    models.CharField(
                        help_text="e.g., 'Lakers -5.5' or 'Over 220.5'", max_length=200
                    ),
                ),
                ("odds", models.IntegerField(help_text="American odds for this leg")),
                (
                    "line",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Point spread or total",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("bookmaker", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("push", "Push"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "final_score",
                    models.CharField(
                        blank=True, help_text="e.g., '110-105'", max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["wager", "id"],
            },
        ),
        # Session 563: Removed DeleteModel and RenameIndex for non-existent items
        # migrations.DeleteModel(name="GameLineHistory"),
        # migrations.DeleteModel(name="OddsSnapshot"),
        # Index renames also commented out - indexes may not exist
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="push_notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bettingstats",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="betting_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placedwager",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wagers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="placedwagerleg",
            name="wager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legs",
                to="core.placedwager",
            ),
        ),
        migrations.AddIndex(
            model_name="placedwager",
            index=models.Index(
                fields=["user", "status"], name="core_placed_user_id_50184f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placedwager",
            index=models.Index(
                fields=["placed_at"], name="core_placed_placed__f32974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placedwager",
            index=models.Index(fields=["status"], name="core_placed_status_e4f1ab_idx"),
        ),
    ]
