# Generated by Django 5.0.6 on 2025-12-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0128_session_563_bet_tracking"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameLineHistory",
        ),
        migrations.DeleteModel(
            name="OddsSnapshot",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_subscri_009091_idx",
            old_name="notificatio_subscri_e4f5g6_idx",
        ),
        migrations.RenameIndex(
            model_name="notificationlog",
            new_name="notificatio_notific_43656c_idx",
            old_name="notificatio_notific_h7i8j9_idx",
        ),
        migrations.RenameIndex(
            model_name="pushsubscription",
            new_name="push_subscr_user_id_c81a15_idx",
            old_name="push_subscr_user_id_7b8c3f_idx",
        ),
        migrations.RenameIndex(
            model_name="pushsubscription",
            new_name="push_subscr_is_acti_a74a0f_idx",
            old_name="push_subscr_is_acti_a1c2d3_idx",
        ),
    ]
