# Generated by Django 5.0.6 on 2025-12-30 03:10
# Session 616: Spider Item-Level Deduplication
# FIXED: Removed erroneous DeleteModel operations that were auto-generated

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0134_session_609_kpi_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiderItemHash",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spider_name", models.CharField(db_index=True, max_length=100)),
                ("data_type", models.CharField(default="unknown", max_length=50)),
                ("content_hash", models.CharField(db_index=True, max_length=32)),
                ("item_title", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="spideritemhash",
            index=models.Index(
                fields=["spider_name", "created_at"],
                name="core_spider_spider__fd1858_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spideritemhash",
            index=models.Index(
                fields=["content_hash"], name="core_spider_content_b1fd14_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spideritemhash",
            unique_together={("spider_name", "content_hash")},
        ),
        # NOTE: Removed DeleteModel operations for Experiment, PilotExecution, etc.
        # These were erroneously auto-generated by Django makemigrations.
        # The pilot/experiment models should remain in the database.
    ]
