# Generated by Django 5.0.6 on 2025-12-30 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0135_session_616_spider_item_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Initiative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                            ("ON_HOLD", "On Hold"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("current_stage", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="system", max_length=100),
                ),
                ("parent_topic", models.CharField(blank=True, max_length=200)),
                ("source_decision_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Initiative",
                "verbose_name_plural": "Initiatives",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InitiativeStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.IntegerField(
                        choices=[
                            (1, "Stage 1 - Research Brief"),
                            (2, "Stage 2 - Prototype Plan"),
                            (3, "Stage 3 - Evaluation Protocol"),
                            (4, "Stage 4 - Technical Design"),
                            (5, "Stage 5 - Pilot Execution"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_by", models.CharField(blank=True, max_length=100)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiative_stages",
                        to="core.selfblog",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.initiative",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative Stage",
                "verbose_name_plural": "Initiative Stages",
                "ordering": ["initiative", "stage"],
                "unique_together": {("initiative", "stage")},
            },
        ),
    ]
