# Generated by Django 5.0.6 on 2026-01-06 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0141_session_677_agent_model_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelperformancelog",
            name="config",
        ),
        migrations.DeleteModel(
            name="ModelTrainingRun",
        ),
        migrations.DeleteModel(
            name="AgentModelConfig",
        ),
        migrations.DeleteModel(
            name="ModelPerformanceLog",
        ),
    ]
