# Generated by Django - Session 690 Implementation Pipeline
from django.db import migrations


class Migration(migrations.Migration):
    """
    Session 690: Add Implementation Pipeline tables.

    Creates PilotImplementation and ImplementationAction models
    to track and execute implementations from completed pilots.
    """

    dependencies = [
        ('core', '0143_session_686_human_interface_layer'),
        ('core', '0130_session_590_pilot_readiness_gate'),  # Explicit dep: creates core_pilotexecution
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS core_pilotimplementation (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                pilot_id UUID NOT NULL REFERENCES core_pilotexecution(id) ON DELETE CASCADE,
                implementation_type VARCHAR(50) NOT NULL DEFAULT 'task_creation',
                status VARCHAR(50) NOT NULL DEFAULT 'pending',
                target_description TEXT NOT NULL,
                implementation_plan JSONB NOT NULL DEFAULT '{}',
                executed_by VARCHAR(255) DEFAULT '',
                execution_result JSONB NOT NULL DEFAULT '{}',
                artifacts JSONB NOT NULL DEFAULT '[]',
                error_message TEXT DEFAULT '',
                retry_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                started_at TIMESTAMP WITH TIME ZONE,
                completed_at TIMESTAMP WITH TIME ZONE,
                UNIQUE(pilot_id)
            );

            CREATE INDEX IF NOT EXISTS core_pilotimpl_status_idx ON core_pilotimplementation(status);
            CREATE INDEX IF NOT EXISTS core_pilotimpl_created_idx ON core_pilotimplementation(created_at DESC);
            """,
            reverse_sql="DROP TABLE IF EXISTS core_pilotimplementation CASCADE;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS core_implementationaction (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                implementation_id UUID NOT NULL REFERENCES core_pilotimplementation(id) ON DELETE CASCADE,
                action_type VARCHAR(100) NOT NULL,
                description TEXT NOT NULL,
                performed_by VARCHAR(255) NOT NULL,
                success BOOLEAN NOT NULL DEFAULT FALSE,
                result_data JSONB NOT NULL DEFAULT '{}',
                error_message TEXT DEFAULT '',
                files_created JSONB NOT NULL DEFAULT '[]',
                files_modified JSONB NOT NULL DEFAULT '[]',
                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
            );

            CREATE INDEX IF NOT EXISTS core_implaction_impl_idx ON core_implementationaction(implementation_id);
            CREATE INDEX IF NOT EXISTS core_implaction_created_idx ON core_implementationaction(created_at);
            """,
            reverse_sql="DROP TABLE IF EXISTS core_implementationaction CASCADE;"
        ),
    ]
