# Generated by Django 5.0.6 on 2026-01-09 18:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0159_session_730_pgvector_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmemory",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="businessresearchresult",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legalmemory",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legalresearchresult",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memorycluster",
            name="centroid_embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Cluster centroid embedding (pgvector)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="spiderdata",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
    ]
