# Generated by Django 5.0.6 on 2026-01-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_fix_gamelinehistory_fields"),
    ]

    operations = [
        # Session 746: Fix ml_task_type NOT NULL constraint for HumanFeedbackRecord
        # When there's no ML prediction, ml_task_type should be allowed to be NULL
        # Using raw SQL because the Django migration state is out of sync
        migrations.RunSQL(
            sql="ALTER TABLE core_humanfeedbackrecord ALTER COLUMN ml_task_type DROP NOT NULL;",
            reverse_sql="ALTER TABLE core_humanfeedbackrecord ALTER COLUMN ml_task_type SET NOT NULL;",
        ),
    ]
