# Generated by Django 5.0.6 on 2026-01-14 17:32
# Session 746: Add Watch & Verify feature for arbitrage paper trading

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0163_alter_human_feedback_ml_task_type_null"),
    ]

    operations = [
        # Add verification fields to HumanAttentionItem using raw SQL
        # (Django migration state is out of sync)
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_humanattentionitem
                ADD COLUMN IF NOT EXISTS verification_outcome VARCHAR(20) NULL,
                ADD COLUMN IF NOT EXISTS verified_at TIMESTAMP WITH TIME ZONE NULL,
                ADD COLUMN IF NOT EXISTS verification_profit DOUBLE PRECISION NULL,
                ADD COLUMN IF NOT EXISTS verification_notes TEXT DEFAULT '',
                ADD COLUMN IF NOT EXISTS event_completed_at TIMESTAMP WITH TIME ZONE NULL;
            """,
            reverse_sql="""
                ALTER TABLE core_humanattentionitem
                DROP COLUMN IF EXISTS verification_outcome,
                DROP COLUMN IF EXISTS verified_at,
                DROP COLUMN IF EXISTS verification_profit,
                DROP COLUMN IF EXISTS verification_notes,
                DROP COLUMN IF EXISTS event_completed_at;
            """,
        ),
    ]
