# Generated by Django 5.0.6 on 2026-01-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_fix_gamelinehistory_fields"),  # Skip deleted 0163-0164
    ]

    operations = [
        # Session 746: Removed DeleteModel operations for GameLineHistory and OddsSnapshot
        # as these tables were already deleted previously
        migrations.AddField(
            model_name="agentmemory",
            name="memory_outcome",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("partial", "Partial"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text="Outcome of the task/action that created this memory",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="memorycluster",
            name="cluster_type",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("success_pattern", "Success Pattern"),
                    ("failure_pattern", "Failure Pattern"),
                    ("learning_pattern", "Learning Pattern"),
                    ("error_recovery", "Error Recovery"),
                ],
                db_index=True,
                default="general",
                help_text="Classification of cluster based on memory outcomes",
                max_length=30,
            ),
        ),
    ]
