# Generated by Django 5.0.6 on 2026-01-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0166_session_761_inspiration_source_textfield"),
    ]

    operations = [
        # Note: Removed DeleteModel for GameLineHistory and OddsSnapshot as they
        # don't exist in the database (models removed but not from DB in prior session)
        migrations.AddField(
            model_name="customworkflow",
            name="cost_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Maximum allowed cost for workflow execution",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customworkflow",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("sequential", "Sequential"),
                    ("parallel", "Parallel"),
                    ("dependency", "Dependency-Based"),
                ],
                default="sequential",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customworkflow",
            name="max_retries",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="customworkflow",
            name="require_approval_on_error",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customworkflow",
            name="timeout_seconds",
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="approval_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Approval configuration: timeout_hours, auto_approve, message",
            ),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="cost_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Maximum allowed cost for this step",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="depends_on_steps",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of step orders this step depends on (for parallel execution)",
            ),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="requires_approval",
            field=models.BooleanField(
                default=False, help_text="Pause for human approval before proceeding"
            ),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="rollback_step",
            field=models.IntegerField(
                blank=True,
                help_text="Step order to execute if this step fails (for rollback)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customworkflowstep",
            name="timeout_seconds",
            field=models.IntegerField(
                default=300, help_text="Step timeout in seconds (5 min default)"
            ),
        ),
        migrations.AlterField(
            model_name="customworkflowstep",
            name="agent",
            field=models.CharField(
                choices=[
                    ("ImageAgent", "Image Generation"),
                    ("VideoAgent", "Video Generation"),
                    ("AudioAgent", "Audio Generation"),
                    ("ThreeDAgent", "3D Model Generation"),
                    ("ImageEditingAgent", "Image Editing"),
                    ("VideoEditingAgent", "Video Editing"),
                    ("ResearchAgent", "Research"),
                    ("ContentWriterAgent", "Content Writing"),
                    ("ContentStrategyAgent", "Content Strategy"),
                    ("BrandIdentityAgent", "Brand Identity"),
                    ("SEOOptimizerAgent", "SEO Optimization"),
                    ("SocialMediaAgent", "Social Media"),
                    ("CTOAgent", "CTO Review"),
                    ("COOAgent", "COO Review"),
                    ("CreativeDirectorAgent", "Creative Direction"),
                    ("MeetingCoordinatorAgent", "Meeting Coordination"),
                    ("TrendAnalysisAgent", "Trend Analysis"),
                    ("OpportunityScoringAgent", "Opportunity Scoring"),
                    ("CharacterTrainingAgent", "Character Training"),
                    ("TrainedCreationAgent", "Trained Creation"),
                    ("MemoryIsolationAgent", "Memory Isolation"),
                    ("ContentAuditAgent", "Content Audit"),
                    ("CompetitorAnalysisAgent", "Competitor Analysis"),
                    ("CustomerResearchAgent", "Customer Research"),
                    ("BrandStrategyAgent", "Brand Strategy"),
                    ("MarketingStrategyAgent", "Marketing Strategy"),
                    ("MarketIntelligenceAgent", "Market Intelligence"),
                    ("LegalDocDrafterAgent", "Legal Document Drafting"),
                    ("CodeGeneratorAgent", "Code Generation"),
                    ("FullStackDeveloperAgent", "Full Stack Development"),
                    ("CodeReviewAgent", "Code Review"),
                    ("DevOpsAgent", "DevOps"),
                    ("StockAuditCoordinator", "Stock Audit Coordination"),
                    ("StockAnalystAgent", "Stock Analysis"),
                    ("MarketMovementMonitorAgent", "Market Movement Monitor"),
                    ("BullCaseAgent", "Bull Case Analysis"),
                    ("BearCaseAgent", "Bear Case Analysis"),
                    ("SignalScannerAgent", "Signal Scanning"),
                    ("BlockchainAuditCoordinator", "Blockchain Audit"),
                    ("SmartContractAuditorAgent", "Smart Contract Audit"),
                    ("TransactionMonitorAgent", "Transaction Monitor"),
                    ("WhaleWatcherAgent", "Whale Watcher"),
                    ("ExploitDetectorAgent", "Exploit Detection"),
                    ("NarrativeDriftCoordinator", "Narrative Drift"),
                    ("NarrativeHistorianAgent", "Narrative History"),
                    ("TrendBreakDetectorAgent", "Trend Break Detection"),
                    ("CulturalImpactAgent", "Cultural Impact"),
                    ("AutonomousContentStudioCoordinator", "Autonomous Content Studio"),
                    ("TopicMinerAgent", "Topic Mining"),
                    ("ContrarianAgent", "Contrarian Analysis"),
                    ("PerformanceAnalystAgent", "Performance Analysis"),
                    ("ContentDiversityOrchestrator", "Content Diversity"),
                    ("ResolveAgent", "Resolve Rendering"),
                    ("PodcastCoordinatorAgent", "Podcast Coordination"),
                    ("DebateAdvocateAgent", "Debate Advocate"),
                    ("DebateSkepticAgent", "Debate Skeptic"),
                    ("ModeratorAgent", "Debate Moderation"),
                    ("WorkflowAgent", "Workflow Orchestration"),
                    ("WorkflowOrchestrationAgent", "Workflow Orchestration (Advanced)"),
                    ("CampaignOrchestratorAgent", "Campaign Orchestration"),
                    ("OpportunityPipelineAgent", "Opportunity Pipeline"),
                    ("ContentExecutorAgent", "Content Execution"),
                    ("PredictionMarketAnalyst", "Prediction Market Analysis"),
                    ("SportsOddsAnalyst", "Sports Odds Analysis"),
                    ("ArbitrageDetector", "Arbitrage Detection"),
                    ("ThinkingAgent", "AI Thinking"),
                    ("TechnicalDocumentAgent", "Technical Documentation"),
                    ("SystemIntelligenceAgent", "System Intelligence"),
                    ("PersonalAssistantAgent", "Personal Assistant"),
                ],
                max_length=100,
            ),
        ),
    ]
