# Generated by Django 5.0.6 on 2026-01-16 03:20
# Session 764: Orchestration Layer - New Models

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0167_orchestration_layer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create OrchestrationExecution model
        migrations.CreateModel(
            name="OrchestrationExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=0)),
                ("checkpoint_data", models.JSONField(default=dict)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=10,
                    ),
                ),
                ("total_tokens", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_step", models.IntegerField(blank=True, null=True)),
                ("final_output", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestration_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orchestration_executions",
                        to="core.customworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Execution",
                "verbose_name_plural": "Orchestration Executions",
                "ordering": ["-created_at"],
            },
        ),
        # Create OrchestrationStepExecution model
        migrations.CreateModel(
            name="OrchestrationStepExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("agent_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("waiting_approval", "Waiting Approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=10,
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "orchestration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_executions",
                        to="core.orchestrationexecution",
                    ),
                ),
                (
                    "workflow_step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestration_executions",
                        to="core.customworkflowstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Step Execution",
                "verbose_name_plural": "Orchestration Step Executions",
                "ordering": ["orchestration", "step_number"],
            },
        ),
        # Create OrchestrationApprovalGate model
        migrations.CreateModel(
            name="OrchestrationApprovalGate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("modified", "Modified"),
                            ("auto_approved", "Auto-Approved"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_config", models.JSONField(default=dict)),
                ("decision_notes", models.TextField(blank=True)),
                ("modifications", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                # attention_item FK will be added in a later step
                ("attention_item_id", models.UUIDField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orchestration_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orchestration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_gates",
                        to="core.orchestrationexecution",
                    ),
                ),
                (
                    "step_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_gates",
                        to="core.orchestrationstepexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orchestration Approval Gate",
                "verbose_name_plural": "Orchestration Approval Gates",
                "ordering": ["-created_at"],
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(
                fields=["status", "created_at"],
                name="core_orches_status_c319dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(
                fields=["workflow", "status"],
                name="core_orches_workflo_3172b1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationexecution",
            index=models.Index(
                fields=["triggered_by", "status"],
                name="core_orches_trigger_cb77a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationstepexecution",
            index=models.Index(
                fields=["orchestration", "step_number"],
                name="core_orches_orchest_6fc9b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationstepexecution",
            index=models.Index(
                fields=["status"],
                name="core_orches_status_b9780f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationstepexecution",
            index=models.Index(
                fields=["agent_name", "status"],
                name="core_orches_agent_n_3e0368_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationapprovalgate",
            index=models.Index(
                fields=["status", "expires_at"],
                name="core_orches_status_3af87f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orchestrationapprovalgate",
            index=models.Index(
                fields=["orchestration", "status"],
                name="core_orches_orchest_ee8a7d_idx",
            ),
        ),
    ]
