# Generated by Django 5.0.6 on 2026-01-18
# Session 768: Memory Safety Classification

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Session 768: Add Memory Safety Classification fields to AgentMemory.

    These fields prevent test interactions from polluting the learning system
    by classifying memories as:
    - test_only: Health checks, connectivity tests - NEVER embed/learn
    - exploratory: Research, exploration - review before using
    - candidate: Potential learning - requires validation
    - approved: Validated, safe to embed and learn from

    Also adds poison risk detection to flag content that could pollute embeddings.
    """

    dependencies = [
        ("core", "0171_opportunity_project_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentmemory",
            name="safety_class",
            field=models.CharField(
                choices=[
                    ("test_only", "Test Only"),
                    ("exploratory", "Exploratory"),
                    ("candidate", "Candidate Learning"),
                    ("approved", "Approved Learning"),
                ],
                db_index=True,
                default="candidate",
                help_text="Memory safety classification - controls embedding/learning eligibility",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agentmemory",
            name="poison_risk_score",
            field=models.FloatField(
                default=0.0,
                help_text="Risk of this memory poisoning embeddings (0=safe, 1=dangerous)",
            ),
        ),
        migrations.AddField(
            model_name="agentmemory",
            name="poison_risk_factors",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of detected risk factors (self_promotional, too_short, lacks_context, etc.)",
            ),
        ),
    ]
