# Generated by Django 5.0.6 on 2026-01-20 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0178_session_784_voice_critique"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanAttentionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_type", models.CharField(max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("source_agent", models.CharField(blank=True, max_length=100)),
                ("item_type", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.FloatField(default=0.0)),
                ("impact_estimate", models.CharField(blank=True, max_length=20)),
                ("ml_prediction", models.JSONField(blank=True, null=True)),
                ("ml_confidence", models.FloatField(blank=True, null=True)),
                ("ml_recommendation", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("viewed", "Viewed"),
                            ("acted", "Acted"),
                            ("deferred", "Deferred"),
                            ("ignored", "Ignored"),
                            ("expired", "Expired"),
                            ("watching", "Watching"),
                            ("verified", "Verified"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("modify", "Modify"),
                            ("defer", "Defer"),
                            ("delegate", "Delegate"),
                            ("ignore", "Ignore"),
                            ("escalate", "Escalate"),
                            ("watch", "Watch & Verify"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("decision_feedback", models.TextField(blank=True)),
                ("decision_confidence", models.FloatField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("time_to_decision_ms", models.IntegerField(blank=True, null=True)),
                ("human_overrode_ml", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("deferred_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Verification"),
                            ("won", "Would Have Won"),
                            ("lost", "Would Have Lost"),
                            ("push", "Push (No Action)"),
                            ("cancelled", "Event Cancelled"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_profit", models.FloatField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("event_completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-priority_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HumanControlAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("pause_agent", "Pause Agent"),
                            ("resume_agent", "Resume Agent"),
                            ("pause_all", "Pause All"),
                            ("resume_all", "Resume All"),
                            ("override_decision", "Override Decision"),
                            ("adjust_threshold", "Adjust Threshold"),
                            ("block_source", "Block Source"),
                            ("unblock_source", "Unblock Source"),
                            ("priority_boost", "Priority Boost"),
                            ("quiet_mode", "Quiet Mode"),
                            ("review_mode", "Review Mode"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("agent", "Agent"),
                            ("source", "Source"),
                            ("model", "Model"),
                            ("system", "System"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(max_length=100)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("auto_revert_at", models.DateTimeField(blank=True, null=True)),
                ("reverted", models.BooleanField(default=False)),
                ("reverted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HumanFeedbackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision", models.CharField(max_length=20)),
                ("feedback_text", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "ml_task_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ml_models_used", models.JSONField(blank=True, null=True)),
                ("ml_prediction", models.JSONField(blank=True, null=True)),
                ("ml_confidence", models.FloatField(blank=True, null=True)),
                ("human_agreed_with_ml", models.BooleanField(null=True)),
                ("confidence_delta", models.FloatField(blank=True, null=True)),
                ("fed_to_ml", models.BooleanField(default=False)),
                ("fed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HumanPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "min_urgency_to_notify",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[
                            ("discord", "Discord"),
                            ("web", "Web Dashboard"),
                            ("email", "Email"),
                        ],
                        default="discord",
                        max_length=50,
                    ),
                ),
                (
                    "review_depth",
                    models.CharField(
                        choices=[
                            ("quick", "Quick (< 30s)"),
                            ("standard", "Standard (30s-2min)"),
                            ("thorough", "Thorough (> 2min)"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("auto_approve_low_risk", models.BooleanField(default=False)),
                ("require_review_above_confidence", models.FloatField(default=0.95)),
                ("trusted_agents", models.JSONField(default=list)),
                ("blocked_sources", models.JSONField(default=list)),
                ("topic_weights", models.JSONField(default=dict)),
                ("source_weights", models.JSONField(default=dict)),
                ("avg_decision_time_ms", models.IntegerField(blank=True, null=True)),
                ("approval_rate", models.FloatField(blank=True, null=True)),
                ("total_decisions", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HumanSystemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_paused", models.BooleanField(default=False)),
                ("review_mode", models.BooleanField(default=False)),
                ("quiet_mode", models.BooleanField(default=False)),
                ("quiet_mode_until", models.DateTimeField(blank=True, null=True)),
                ("paused_agents", models.JSONField(default=list)),
                ("ml_confidence_threshold", models.FloatField(default=0.6)),
                ("auto_approve_threshold", models.FloatField(default=0.95)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Human System State",
                "verbose_name_plural": "Human System State",
            },
        ),
        migrations.CreateModel(
            name="WorkspaceTrigger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("spider_code_insight", "Spider: Code/Tech Insight"),
                            ("spider_bug_pattern", "Spider: Bug Pattern Detected"),
                            ("spider_security_alert", "Spider: Security Alert"),
                            ("spider_dependency_update", "Spider: Dependency Update"),
                            ("spider_best_practice", "Spider: Best Practice Detected"),
                            ("agent_refactor", "Agent: Refactor Suggestion"),
                            ("agent_test_needed", "Agent: Test Coverage Needed"),
                            ("agent_doc_needed", "Agent: Documentation Needed"),
                            ("agent_optimization", "Agent: Optimization Opportunity"),
                            ("human_task", "Human: Task Request"),
                            ("human_review", "Human: Review Response"),
                            ("scheduled_category", "Scheduled: Category Rotation"),
                            ("scheduled_maintenance", "Scheduled: Maintenance"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the work to be done",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description or context for the work",
                    ),
                ),
                (
                    "dedupe_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "target_agent",
                    models.CharField(
                        blank=True,
                        help_text="Specific agent to handle (empty = auto-route)",
                        max_length=100,
                    ),
                ),
                (
                    "target_category",
                    models.CharField(
                        blank=True,
                        help_text="Agent category (e.g., 'development', 'research')",
                        max_length=50,
                    ),
                ),
                (
                    "source_spider",
                    models.CharField(
                        blank=True,
                        help_text="Spider that generated this trigger",
                        max_length=100,
                    ),
                ),
                (
                    "source_spider_data_id",
                    models.UUIDField(
                        blank=True,
                        help_text="SpiderData record that triggered this",
                        null=True,
                    ),
                ),
                (
                    "source_agent",
                    models.CharField(
                        blank=True,
                        help_text="Agent that requested this work",
                        max_length=100,
                    ),
                ),
                (
                    "source_user_id",
                    models.IntegerField(
                        blank=True, help_text="User who requested this work", null=True
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context passed to the executing agent",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Normal"),
                            (3, "High"),
                            (4, "Urgent"),
                            (5, "Critical"),
                        ],
                        db_index=True,
                        default=2,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Trigger expires and won't be processed after this time",
                    ),
                ),
                (
                    "ttl_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Default TTL in hours (used to calculate expires_at)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued for Execution"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired (TTL)"),
                            ("skipped", "Skipped (Dedupe/Gate)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "execution_id",
                    models.UUIDField(
                        blank=True, help_text="AgentExecution ID if started", null=True
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(
                        blank=True, help_text="Brief summary of execution result"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workspace Trigger",
                "verbose_name_plural": "Workspace Triggers",
                "db_table": "core_workspace_triggers",
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceTriggerConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "target_spiders",
                    models.JSONField(
                        default=list,
                        help_text="List of spider names to monitor (empty = all)",
                    ),
                ),
                (
                    "match_field",
                    models.CharField(
                        help_text="JSON path in raw_data to check (e.g., 'items.0.title')",
                        max_length=100,
                    ),
                ),
                (
                    "match_operator",
                    models.CharField(
                        choices=[
                            ("contains", "Contains (text)"),
                            ("regex", "Regex Match"),
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                        ],
                        default="contains",
                        max_length=20,
                    ),
                ),
                (
                    "match_value",
                    models.CharField(
                        help_text="Value to match against (keywords separated by | for contains)",
                        max_length=500,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("spider_code_insight", "Spider: Code/Tech Insight"),
                            ("spider_bug_pattern", "Spider: Bug Pattern Detected"),
                            ("spider_security_alert", "Spider: Security Alert"),
                            ("spider_dependency_update", "Spider: Dependency Update"),
                            ("spider_best_practice", "Spider: Best Practice Detected"),
                            ("agent_refactor", "Agent: Refactor Suggestion"),
                            ("agent_test_needed", "Agent: Test Coverage Needed"),
                            ("agent_doc_needed", "Agent: Documentation Needed"),
                            ("agent_optimization", "Agent: Optimization Opportunity"),
                            ("human_task", "Human: Task Request"),
                            ("human_review", "Human: Review Response"),
                            ("scheduled_category", "Scheduled: Category Rotation"),
                            ("scheduled_maintenance", "Scheduled: Maintenance"),
                        ],
                        default="spider_code_insight",
                        max_length=50,
                    ),
                ),
                (
                    "trigger_title_template",
                    models.CharField(
                        default="{match_field}: {matched_value}",
                        help_text="Template for trigger title. Use {spider_name}, {match_field}, {matched_value}",
                        max_length=200,
                    ),
                ),
                (
                    "target_agent",
                    models.CharField(
                        blank=True,
                        help_text="Agent to handle (empty = auto-route)",
                        max_length=100,
                    ),
                ),
                (
                    "target_category",
                    models.CharField(
                        blank=True,
                        help_text="Agent category for routing",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Low"),
                            (2, "Normal"),
                            (3, "High"),
                            (4, "Urgent"),
                            (5, "Critical"),
                        ],
                        default=2,
                    ),
                ),
                ("ttl_hours", models.IntegerField(default=24)),
                (
                    "cooldown_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Minimum minutes between triggers from this config",
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("total_triggers_created", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workspace Trigger Config",
                "verbose_name_plural": "Workspace Trigger Configs",
                "db_table": "core_workspace_trigger_configs",
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="GameLineHistory",
        ),
        migrations.DeleteModel(
            name="OddsSnapshot",
        ),
        migrations.RenameIndex(
            model_name="agentdream",
            new_name="core_agentd_origin_fbaa47_idx",
            old_name="core_agentd_origin_9b1c3f_idx",
        ),
        migrations.RenameIndex(
            model_name="agentdream",
            new_name="core_agentd_origin_7bf698_idx",
            old_name="core_agentd_origin_7d4e2a_idx",
        ),
        migrations.RenameIndex(
            model_name="channelepisode",
            new_name="channel_epi_intent__f34247_idx",
            old_name="channel_epi_intent__f8e4c3_idx",
        ),
        migrations.RenameIndex(
            model_name="channelepisode",
            new_name="channel_epi_voice_c_8ca637_idx",
            old_name="channel_epi_voice_c_a1b2c3_idx",
        ),
        migrations.AlterField(
            model_name="podcastepisode",
            name="tts_cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="podcastepisode",
            name="tts_cost_breakdown",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="humanattentionitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attention_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humancontrolaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humanfeedbackrecord",
            name="attention_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_records",
                to="core.humanattentionitem",
            ),
        ),
        migrations.AddField(
            model_name="humanfeedbackrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="humanpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="humansystemstate",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacetrigger",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Target workspace (null = system-wide)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggers",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="humanattentionitem",
            index=models.Index(
                fields=["user", "status"], name="core_humana_user_id_dc28e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humanattentionitem",
            index=models.Index(
                fields=["user", "urgency"], name="core_humana_user_id_c58e21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humanattentionitem",
            index=models.Index(
                fields=["source_type"], name="core_humana_source__5e8027_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humanattentionitem",
            index=models.Index(
                fields=["created_at"], name="core_humana_created_d6e235_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetrigger",
            index=models.Index(
                fields=["status", "-priority", "created_at"],
                name="core_worksp_status_aec73b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetrigger",
            index=models.Index(
                fields=["trigger_type", "status"], name="core_worksp_trigger_f835bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetrigger",
            index=models.Index(
                fields=["target_category", "status"],
                name="core_worksp_target__98ab45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetrigger",
            index=models.Index(
                fields=["expires_at"], name="core_worksp_expires_e8acdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacetrigger",
            index=models.Index(
                fields=["dedupe_hash", "status"], name="core_worksp_dedupe__65bac0_idx"
            ),
        ),
    ]
