# Generated by Django 5.0.6 on 2026-01-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0179_workspace_triggers_session_785"),
    ]

    operations = [
        migrations.AddField(
            model_name="intelligentpromptmetric",
            name="included_documentation",
            field=models.BooleanField(default=False),
        ),
    ]
