# Generated by Django 5.0.6 on 2026-01-23 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0182_add_missing_body_system_columns"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrainPulse",
        ),
        migrations.DeleteModel(
            name="CognitiveChannel",
        ),
        migrations.DeleteModel(
            name="CognitiveStatus",
        ),
        migrations.DeleteModel(
            name="NervousPulse",
        ),
        migrations.DeleteModel(
            name="NervousStatus",
        ),
        migrations.DeleteModel(
            name="SkinPulse",
        ),
        migrations.DeleteModel(
            name="SkinStatus",
        ),
        migrations.DeleteModel(
            name="WebSocketConnectionLog",
        ),
    ]
