# Generated by Django 5.0.6 on 2026-01-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0185_fix_body_system_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfblog",
            name="category",
            field=models.CharField(
                choices=[
                    ("blog", "Blog Post"),
                    ("audit", "System Audit"),
                    ("technical_document", "Technical Document"),
                    ("prototype_plan", "Prototype Plan"),
                    ("research_brief", "Research Brief"),
                ],
                db_index=True,
                default="blog",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="selfblog",
            name="conclusion",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="selfblog",
            name="intro",
            field=models.TextField(blank=True),
        ),
    ]
