# Generated by Django 5.0.6 on 2026-01-25 04:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0186_add_selfblog_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Human-readable title for the deliverable",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier", max_length=280, unique=True
                    ),
                ),
                (
                    "deliverable_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("code", "Code"),
                            ("analysis", "Analysis"),
                            ("report", "Report"),
                            ("template", "Template"),
                            ("research", "Research"),
                            ("strategy", "Strategy"),
                            ("plan", "Plan"),
                            ("script", "Script"),
                        ],
                        db_index=True,
                        default="document",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Business category (e.g., Marketing, Development, Research)",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Tags for filtering and discovery",
                        size=None,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the agent that created this",
                        max_length=100,
                    ),
                ),
                (
                    "agent_task",
                    models.TextField(
                        blank=True, help_text="The task/prompt given to the agent"
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The actual deliverable content"),
                ),
                (
                    "content_format",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                            ("python", "Python"),
                            ("typescript", "TypeScript"),
                            ("javascript", "JavaScript"),
                        ],
                        default="text",
                        help_text="Format of the content (for rendering)",
                        max_length=20,
                    ),
                ),
                (
                    "preview_content",
                    models.TextField(
                        blank=True, help_text="Truncated preview for card display"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Thumbnail image URL for visual deliverables",
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0, help_text="AI-assessed quality score (0.0 to 1.0)"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Agent confidence in the output (0.0 to 1.0)",
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="User has saved this to their library",
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="This deliverable is a reusable template",
                    ),
                ),
                (
                    "is_starred",
                    models.BooleanField(
                        default=False, help_text="User has starred/favorited this"
                    ),
                ),
                (
                    "clone_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this has been cloned"
                    ),
                ),
                (
                    "execution_time_ms",
                    models.IntegerField(
                        default=0, help_text="How long the agent took to produce this"
                    ),
                ),
                (
                    "llm_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Cost of LLM calls in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(
                        default=list,
                        help_text="List of tool calls made during execution",
                    ),
                ),
                (
                    "raw_output",
                    models.JSONField(
                        default=dict,
                        help_text="Complete raw output from the agent (for debugging)",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (file paths, URLs, etc.)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original deliverable if this is a clone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clones",
                        to="core.deliverable",
                    ),
                ),
                (
                    "source_operation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The workspace operation that produced this deliverable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliverables",
                        to="core.workspaceoperation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this deliverable",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliverable",
                "verbose_name_plural": "Deliverables",
                "db_table": "core_deliverables",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliverableCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deliverables",
                    models.ManyToManyField(
                        blank=True, related_name="collections", to="core.deliverable"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_deliverable_collections",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliverableExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("html", "HTML"),
                            ("markdown", "Markdown"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to exported file (if stored)",
                        max_length=500,
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, help_text="Download URL for exported file"
                    ),
                ),
                ("file_size_bytes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="core.deliverable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_deliverable_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["user", "-created_at"], name="core_delive_user_id_400313_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["deliverable_type", "-created_at"],
                name="core_delive_deliver_260251_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["agent_name", "-created_at"],
                name="core_delive_agent_n_0af3b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["is_saved", "-created_at"],
                name="core_delive_is_save_1fcaaf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["is_template", "-created_at"],
                name="core_delive_is_temp_79dc13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["category", "-created_at"],
                name="core_delive_categor_dce676_idx",
            ),
        ),
    ]
