# Generated by Django 5.0.6 on 2026-01-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0189_session_826_goal_driven_conversations"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfblog",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
