# Generated by Django 5.0.6 on 2026-01-27 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0191_add_experiment_fk_to_agent_execution"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdecisionsummary",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 843: Project this decision belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decision_summaries",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="agentdecisionsummary",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID for cross-artifact linking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="owner_agent",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session 843: Agent that owns/created this execution",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="parent_object_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: ID of parent that triggered this execution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="parent_object_type",
            field=models.CharField(
                blank=True,
                help_text="Session 843: Type of parent (conversation, orchestration, gate)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 843: Project this execution belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_executions",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID linking this execution to a broader workflow",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 843: Project this report belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_reports",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="auditreport",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID for cross-artifact linking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="parent_object_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: ID of parent object",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="parent_object_type",
            field=models.CharField(
                blank=True,
                help_text="Session 843: Type of parent (agent_execution, conversation)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="deliverable",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID for cross-artifact linking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractedartifact",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 843: Project this artifact belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extracted_artifacts",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="extractedartifact",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID for cross-artifact linking",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 843: Project this blog belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="self_blogs",
                to="core.partnershipproject",
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="trace_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Session 843: Trace ID for cross-artifact linking",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WiringDefect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "defect_type",
                    models.CharField(
                        choices=[
                            ("missing_project_id", "Missing Project ID"),
                            ("missing_trace_id", "Missing Trace ID"),
                            ("missing_parent", "Missing Parent Object"),
                            ("orphan_artifact", "Orphan Artifact"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("object_type", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.UUIDField(db_index=True)),
                ("trace_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("agent_name", models.CharField(blank=True, max_length=100)),
                ("execution_context", models.JSONField(default=dict)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wiring Defect",
                "verbose_name_plural": "Wiring Defects",
                "db_table": "core_wiring_defect",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["defect_type", "is_resolved"],
                        name="core_wiring_defect__67100d_idx",
                    ),
                    models.Index(
                        fields=["object_type", "-created_at"],
                        name="core_wiring_object__862fc3_idx",
                    ),
                ],
            },
        ),
    ]
