# Generated by Django 5.0.6 on 2026-01-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0194_session_847_initiative_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentdecisionsummary",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("learning", "Learning"),
                    ("initiative_stage_doc", "Initiative Stage Document"),
                    ("report", "Report"),
                    ("playbook", "Playbook"),
                    ("decision", "Decision"),
                ],
                default="decision",
                help_text="Session 849: Type of artifact this decision represents",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="agentdecisionsummary",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 849: Initiative created from this decision's proposed feature",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_decisions",
                to="core.initiative",
            ),
        ),
    ]
