# Generated by Django 5.0.6 on 2026-01-28 18:24
# Session 856: Diagnostic Pipeline Models

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0196_session_852_fix_artifact_categories"),
    ]

    operations = [
        # Create FailureSignature model
        migrations.CreateModel(
            name="FailureSignature",
            fields=[
                ("id", models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ("signature", models.CharField(
                    db_index=True,
                    help_text="Stable signature like OPENAI_429_QUOTA",
                    max_length=255,
                    unique=True
                )),
                ("signature_hash", models.CharField(
                    help_text="MD5 hash for fast lookup",
                    max_length=32,
                    unique=True
                )),
                ("category", models.CharField(
                    choices=[
                        ("provider_error", "Provider Error"),
                        ("timeout", "Timeout"),
                        ("data_error", "Data Error"),
                        ("execution_error", "Execution Error"),
                        ("resource_error", "Resource Error"),
                        ("unknown", "Unknown"),
                    ],
                    default="unknown",
                    max_length=30
                )),
                ("provider", models.CharField(
                    blank=True,
                    help_text="Provider name if provider-related (openai, anthropic, etc.)",
                    max_length=50
                )),
                ("error_code", models.CharField(
                    blank=True,
                    help_text="HTTP status code or error code (429, 500, etc.)",
                    max_length=50
                )),
                ("occurrence_count", models.PositiveIntegerField(
                    default=0,
                    help_text="Total times this signature has been seen"
                )),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("last_diagnosed_at", models.DateTimeField(
                    blank=True,
                    help_text="Last time this signature was diagnosed (for cooldown)",
                    null=True
                )),
                ("status", models.CharField(
                    choices=[
                        ("active", "Active"),
                        ("known_outage", "Known Outage"),
                        ("diagnosed", "Diagnosed"),
                        ("resolved", "Resolved"),
                        ("ignored", "Ignored"),
                    ],
                    default="active",
                    max_length=20
                )),
                ("description", models.TextField(
                    blank=True,
                    help_text="Human-readable explanation of this failure type"
                )),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "core_failure_signature",
                "ordering": ["-occurrence_count", "-last_seen_at"],
            },
        ),
        # Add indexes to FailureSignature
        migrations.AddIndex(
            model_name="failuresignature",
            index=models.Index(fields=["status"], name="core_failur_status_a1e8b2_idx"),
        ),
        migrations.AddIndex(
            model_name="failuresignature",
            index=models.Index(fields=["category"], name="core_failur_categor_b2e9c3_idx"),
        ),
        migrations.AddIndex(
            model_name="failuresignature",
            index=models.Index(fields=["provider"], name="core_failur_provide_c3f0d4_idx"),
        ),
        migrations.AddIndex(
            model_name="failuresignature",
            index=models.Index(fields=["-last_seen_at"], name="core_failur_last_se_d4g1e5_idx"),
        ),

        # Create FailureDetection model
        migrations.CreateModel(
            name="FailureDetection",
            fields=[
                ("id", models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ("source_type", models.CharField(
                    choices=[
                        ("experiment", "Experiment"),
                        ("agent_execution", "Agent Execution"),
                        ("spider", "Spider"),
                        ("celery_task", "Celery Task"),
                        ("api_call", "API Call"),
                        ("provider", "Provider"),
                    ],
                    max_length=30
                )),
                ("source_id", models.UUIDField(
                    blank=True,
                    help_text="ID of the failed entity (experiment, execution, etc.)",
                    null=True
                )),
                ("source_name", models.CharField(
                    blank=True,
                    help_text="Human-readable name of what failed",
                    max_length=255
                )),
                ("error_message", models.TextField(help_text="The actual error message")),
                ("error_code", models.CharField(
                    blank=True,
                    help_text="HTTP status or error code",
                    max_length=50
                )),
                ("stack_trace", models.TextField(
                    blank=True,
                    help_text="Full stack trace if available"
                )),
                ("context_snapshot", models.JSONField(
                    default=dict,
                    help_text="Context data: provider, endpoint, model, params, etc."
                )),
                ("is_diagnosed", models.BooleanField(
                    default=False,
                    help_text="Has this detection been processed for diagnosis?"
                )),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("diagnosed_at", models.DateTimeField(blank=True, null=True)),
                ("signature", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="detections",
                    to="core.failuresignature"
                )),
            ],
            options={
                "db_table": "core_failure_detection",
                "ordering": ["-detected_at"],
            },
        ),
        # Add indexes to FailureDetection
        migrations.AddIndex(
            model_name="failuredetection",
            index=models.Index(fields=["source_type"], name="core_failur_source__e5h2f6_idx"),
        ),
        migrations.AddIndex(
            model_name="failuredetection",
            index=models.Index(fields=["is_diagnosed"], name="core_failur_is_diag_f6i3g7_idx"),
        ),
        migrations.AddIndex(
            model_name="failuredetection",
            index=models.Index(fields=["-detected_at"], name="core_failur_detecte_g7j4h8_idx"),
        ),
        migrations.AddIndex(
            model_name="failuredetection",
            index=models.Index(fields=["signature", "is_diagnosed"], name="core_failur_signatu_h8k5i9_idx"),
        ),

        # Create FailureDiagnosis model
        migrations.CreateModel(
            name="FailureDiagnosis",
            fields=[
                ("id", models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ("root_cause", models.TextField(
                    help_text="Detailed explanation of why this is happening"
                )),
                ("root_cause_confidence", models.FloatField(
                    default=0.0,
                    help_text="Confidence score 0-1"
                )),
                ("evidence_sources", models.JSONField(
                    default=list,
                    help_text="List of evidence types used: ['exception', 'provider', 'rate_limit', 'system_event', 'llm_synthesis']"
                )),
                ("evidence_details", models.JSONField(
                    default=dict,
                    help_text="Detailed evidence per source type"
                )),
                ("blast_radius", models.CharField(
                    choices=[
                        ("isolated", "Isolated (single component)"),
                        ("limited", "Limited (few components)"),
                        ("widespread", "Widespread (many components)"),
                        ("critical", "Critical (system-wide)"),
                    ],
                    default="isolated",
                    max_length=20
                )),
                ("affected_components", models.JSONField(
                    default=list,
                    help_text="List of affected components/agents/services"
                )),
                ("sample_count", models.PositiveIntegerField(
                    default=0,
                    help_text="Number of detections used for this diagnosis"
                )),
                ("sample_time_range", models.JSONField(
                    default=dict,
                    help_text="{'from': ISO timestamp, 'to': ISO timestamp}"
                )),
                ("diagnosed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signature", models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="diagnosis",
                    to="core.failuresignature"
                )),
            ],
            options={
                "db_table": "core_failure_diagnosis",
                "ordering": ["-diagnosed_at"],
            },
        ),

        # Create FailurePrescription model
        migrations.CreateModel(
            name="FailurePrescription",
            fields=[
                ("id", models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("scope", models.CharField(
                    choices=[
                        ("immediate", "Immediate (stop bleeding)"),
                        ("structural", "Structural (prevent recurrence)"),
                        ("observability", "Observability (make obvious)"),
                    ],
                    max_length=20
                )),
                ("expected_impact", models.CharField(
                    choices=[
                        ("high", "High Impact"),
                        ("medium", "Medium Impact"),
                        ("low", "Low Impact"),
                    ],
                    default="medium",
                    max_length=10
                )),
                ("effort", models.CharField(
                    choices=[
                        ("trivial", "Trivial (<30 min)"),
                        ("small", "Small (1-2 hours)"),
                        ("medium", "Medium (half day)"),
                        ("large", "Large (full day+)"),
                    ],
                    default="small",
                    max_length=10
                )),
                ("confidence", models.FloatField(
                    default=0.0,
                    help_text="Confidence that this fix will work (0-1)"
                )),
                ("priority_score", models.FloatField(
                    default=0.0,
                    help_text="Computed priority score for ranking"
                )),
                ("technical_steps", models.JSONField(
                    default=list,
                    help_text="List of technical steps to implement"
                )),
                ("files_to_modify", models.JSONField(
                    default=list,
                    help_text="List of file paths that need changes"
                )),
                ("commands_to_run", models.JSONField(
                    default=list,
                    help_text="Shell commands to execute"
                )),
                ("success_criteria", models.TextField(
                    blank=True,
                    help_text="How we'll know this fix worked"
                )),
                ("verification_steps", models.JSONField(
                    default=list,
                    help_text="Steps to verify the fix"
                )),
                ("status", models.CharField(
                    choices=[
                        ("proposed", "Proposed"),
                        ("approved", "Approved"),
                        ("in_progress", "In Progress"),
                        ("completed", "Completed"),
                        ("verified", "Verified"),
                        ("rejected", "Rejected"),
                    ],
                    default="proposed",
                    max_length=20
                )),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("diagnosis", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="prescriptions",
                    to="core.failurediagnosis"
                )),
                ("initiative", models.ForeignKey(
                    blank=True,
                    help_text="Auto-created Initiative for tracking remediation",
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="prescriptions",
                    to="core.initiative"
                )),
            ],
            options={
                "db_table": "core_failure_prescription",
                "ordering": ["-priority_score", "scope"],
            },
        ),
        # Add indexes to FailurePrescription
        migrations.AddIndex(
            model_name="failureprescription",
            index=models.Index(fields=["status"], name="core_failur_status_i9l6j0_idx"),
        ),
        migrations.AddIndex(
            model_name="failureprescription",
            index=models.Index(fields=["scope"], name="core_failur_scope_j0m7k1_idx"),
        ),
        migrations.AddIndex(
            model_name="failureprescription",
            index=models.Index(fields=["-priority_score"], name="core_failur_priorit_k1n8l2_idx"),
        ),
    ]
