# Generated by Django 5.0.6 on 2026-01-29 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0199_session_861_learning_backup"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("agent_name", models.CharField(db_index=True, max_length=255)),
                ("decision_type", models.CharField(db_index=True, max_length=50)),
                ("date", models.DateField(db_index=True)),
                ("total_decisions", models.IntegerField(default=0)),
                ("successful_decisions", models.IntegerField(default=0)),
                ("failed_decisions", models.IntegerField(default=0)),
                ("pending_decisions", models.IntegerField(default=0)),
                ("avg_confidence", models.FloatField(default=0.0)),
                ("min_confidence", models.FloatField(default=0.0)),
                ("max_confidence", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_decision_aggregate",
                "ordering": ["-date", "agent_name"],
                "unique_together": {("agent_name", "decision_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="DecisionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trace_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Trace ID for linking related decisions",
                        null=True,
                    ),
                ),
                (
                    "conversation_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Conversation ID if from chat context",
                        null=True,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the agent that made the decision",
                        max_length=255,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        db_index=True, help_text="Type of decision", max_length=50
                    ),
                ),
                ("action", models.TextField(help_text="The action taken")),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="Why this decision was made"
                    ),
                ),
                (
                    "alternatives",
                    models.JSONField(
                        default=list, help_text="Other options that were considered"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Additional context for this decision"
                    ),
                ),
                (
                    "task_summary",
                    models.CharField(
                        blank=True,
                        help_text="Summary of the task being executed",
                        max_length=500,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=0.8, help_text="Confidence score (0-1)"),
                ),
                (
                    "was_successful",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether the decision led to success (set after completion)",
                        null=True,
                    ),
                ),
                (
                    "outcome_notes",
                    models.TextField(blank=True, help_text="Notes about the outcome"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "core_decision_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent_name", "created_at"],
                        name="core_decisi_agent_n_d187dc_idx",
                    ),
                    models.Index(
                        fields=["decision_type", "created_at"],
                        name="core_decisi_decisio_024ad0_idx",
                    ),
                    models.Index(
                        fields=["trace_id", "created_at"],
                        name="core_decisi_trace_i_4cb73e_idx",
                    ),
                ],
            },
        ),
    ]
