# Generated by Django 5.0.6 on 2026-01-29 02:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0200_session_861_decision_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpiderAggregation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aggregation_type",
                    models.CharField(
                        choices=[
                            ("category_summary", "Category Summary"),
                            ("cross_spider_trend", "Cross-Spider Trend"),
                            ("opportunity_summary", "Opportunity Summary"),
                            ("relevance_distribution", "Relevance Distribution"),
                            ("topic_analysis", "Topic Analysis"),
                            ("hourly_activity", "Hourly Activity"),
                            ("daily_summary", "Daily Summary"),
                            ("weekly_summary", "Weekly Summary"),
                        ],
                        db_index=True,
                        help_text="Type of aggregation",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Spider category (financial, tech, news, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "spider_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Specific spider name (if single-spider aggregation)",
                        max_length=100,
                    ),
                ),
                (
                    "date_range_start",
                    models.DateTimeField(
                        db_index=True, help_text="Start of the aggregation period"
                    ),
                ),
                (
                    "date_range_end",
                    models.DateTimeField(
                        db_index=True, help_text="End of the aggregation period"
                    ),
                ),
                (
                    "aggregation_data",
                    models.JSONField(
                        default=dict, help_text="The computed aggregation data"
                    ),
                ),
                (
                    "items_analyzed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of SpiderData items included in aggregation",
                    ),
                ),
                (
                    "computation_time_ms",
                    models.IntegerField(
                        default=0, help_text="Time taken to compute this aggregation"
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When this cached aggregation should be recomputed",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "core_spider_aggregation",
                "ordering": ["-computed_at"],
                "indexes": [
                    models.Index(
                        fields=["aggregation_type", "category", "computed_at"],
                        name="core_spider_aggrega_930130_idx",
                    ),
                    models.Index(
                        fields=["aggregation_type", "date_range_start"],
                        name="core_spider_aggrega_3b24e1_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="core_spider_expires_b0bbc7_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "aggregation_type",
                        "category",
                        "spider_name",
                        "date_range_start",
                        "date_range_end",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="TrendDataPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("item_count", "Item Count"),
                            ("relevance_avg", "Average Relevance"),
                            ("topic_frequency", "Topic Frequency"),
                            ("source_activity", "Source Activity"),
                            ("opportunity_count", "Opportunity Count"),
                        ],
                        db_index=True,
                        help_text="Type of trend being tracked",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Spider category",
                        max_length=100,
                    ),
                ),
                (
                    "spider_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Specific spider",
                        max_length=100,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Specific topic (for topic_frequency trends)",
                        max_length=100,
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        db_index=True,
                        help_text="Time granularity of this data point",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(db_index=True, help_text="Time bucket"),
                ),
                ("value", models.FloatField(help_text="The trend value")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional context for this data point"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "core_trend_data_point",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["trend_type", "granularity", "timestamp"],
                        name="core_trend__trend_t_9217ea_idx",
                    ),
                    models.Index(
                        fields=["category", "trend_type", "timestamp"],
                        name="core_trend__categor_d00137_idx",
                    ),
                    models.Index(
                        fields=["spider_name", "trend_type", "timestamp"],
                        name="core_trend__spider__bfacea_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "trend_type",
                        "category",
                        "spider_name",
                        "topic",
                        "granularity",
                        "timestamp",
                    )
                },
            },
        ),
    ]
