# Generated by Django 5.0.6 on 2026-01-29 03:01
# Session 862: Content Flow Unification - Phase 1: Add Foreign Keys
#
# This migration adds FK relationships between:
# - AgentDream -> Initiative (when promoted)
# - Deliverable -> Initiative, Dream, SelfBlog, PodcastEpisode
# - SelfBlog -> Initiative, Dream, InitiativeStage
# - PodcastEpisode -> Initiative, Dream, InitiativeStage

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0201_session_861_spider_aggregation"),
    ]

    operations = [
        # AgentDream -> Initiative
        migrations.AddField(
            model_name="agentdream",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative created from this dream",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_dreams",
                to="core.initiative",
            ),
        ),

        # Deliverable -> Dream
        migrations.AddField(
            model_name="deliverable",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Dream that originated this deliverable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="core.agentdream",
            ),
        ),

        # Deliverable -> Initiative
        migrations.AddField(
            model_name="deliverable",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative that produced this deliverable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="core.initiative",
            ),
        ),

        # Deliverable -> PodcastEpisode
        migrations.AddField(
            model_name="deliverable",
            name="podcast_episode",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Podcast episode for this deliverable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="core.podcastepisode",
            ),
        ),

        # Deliverable -> SelfBlog
        migrations.AddField(
            model_name="deliverable",
            name="self_blog",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: SelfBlog content for this deliverable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="core.selfblog",
            ),
        ),

        # PodcastEpisode -> Dream
        migrations.AddField(
            model_name="podcastepisode",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Dream that originated this podcast",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_episodes",
                to="core.agentdream",
            ),
        ),

        # PodcastEpisode -> Initiative
        migrations.AddField(
            model_name="podcastepisode",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative this podcast belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_episodes",
                to="core.initiative",
            ),
        ),

        # PodcastEpisode -> InitiativeStage
        migrations.AddField(
            model_name="podcastepisode",
            name="initiative_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative stage this podcast fulfills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_episodes",
                to="core.initiativestage",
            ),
        ),

        # SelfBlog -> Dream
        migrations.AddField(
            model_name="selfblog",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Dream that originated this blog",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="core.agentdream",
            ),
        ),

        # SelfBlog -> Initiative
        migrations.AddField(
            model_name="selfblog",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative this blog belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="core.initiative",
            ),
        ),

        # SelfBlog -> InitiativeStage
        migrations.AddField(
            model_name="selfblog",
            name="initiative_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 862: Initiative stage this blog fulfills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="core.initiativestage",
            ),
        ),

        # Add indexes for Deliverable FK fields
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["initiative", "-created_at"], name="core_delive_initiat_2f8f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["dream", "-created_at"], name="core_delive_dream_i_c50b01_idx"
            ),
        ),
    ]
