# Generated by Django 5.0.6 on 2026-01-29 03:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0203_session_862_research_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchQueryPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "query_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of research query (trending, competitor, audience, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "query_keywords",
                    models.JSONField(default=list, help_text="Keywords used in query"),
                ),
                ("series_type", models.CharField(blank=True, max_length=50)),
                ("target_audience", models.CharField(blank=True, max_length=100)),
                ("total_uses", models.IntegerField(default=0)),
                (
                    "avg_content_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average rating of content produced from this research",
                        max_digits=3,
                    ),
                ),
                (
                    "avg_engagement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Average engagement of content from this research",
                        max_digits=5,
                    ),
                ),
                ("successful_series_count", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-avg_content_rating", "-total_uses"],
            },
        ),
        migrations.RemoveField(
            model_name="failurediagnosis",
            name="signature",
        ),
        migrations.RemoveField(
            model_name="failureprescription",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="failureprescription",
            name="initiative",
        ),
        migrations.CreateModel(
            name="ContentEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        db_index=True,
                        help_text="Platform where content is published (youtube, tiktok, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="External platform ID for tracking",
                        max_length=200,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("saves", models.IntegerField(default=0)),
                ("avg_watch_time_seconds", models.IntegerField(default=0)),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage who watched to completion (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue generated by this content",
                        max_digits=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending - Not yet delivered"),
                            ("delivered", "Delivered - Sent to client"),
                            ("approved", "Approved - Client accepted"),
                            ("rejected", "Rejected - Client rejected"),
                            ("published", "Published - Live on platform"),
                            ("viral", "Viral - High engagement"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                (
                    "content_context",
                    models.JSONField(
                        default=dict,
                        help_text="Content configuration at time of creation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to="core.contentpackage",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to="core.seriesepisode",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to="core.aiseries",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineLearningInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("research", "Research - Topic and audience analysis"),
                            ("script", "Script - Script/narration generation"),
                            ("image", "Image - Character and scene generation"),
                            ("voice", "Voice - Voiceover generation"),
                            ("video", "Video - Video content generation"),
                            ("package", "Package - Final content packaging"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        help_text="Type of insight (best_style, best_voice, correlation, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "insight_summary",
                    models.CharField(
                        help_text="Human-readable insight summary", max_length=500
                    ),
                ),
                (
                    "insight_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured insight data for automated use",
                    ),
                ),
                (
                    "applicable_to",
                    models.JSONField(
                        default=dict, help_text="Conditions where this insight applies"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Confidence in this insight (0-1)",
                        max_digits=3,
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        default=0,
                        help_text="Number of data points supporting this insight",
                    ),
                ),
                (
                    "estimated_impact",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated improvement percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to apply this insight"
                    ),
                ),
                ("times_applied", models.IntegerField(default=0)),
                (
                    "times_validated",
                    models.IntegerField(
                        default=0, help_text="Times insight was validated as correct"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this insight should be re-evaluated",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence", "-sample_size"],
                "indexes": [
                    models.Index(
                        fields=["stage", "is_active"],
                        name="core_pipeli_stage_b94619_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineStageFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("research", "Research - Topic and audience analysis"),
                            ("script", "Script - Script/narration generation"),
                            ("image", "Image - Character and scene generation"),
                            ("voice", "Voice - Voiceover generation"),
                            ("video", "Video - Video content generation"),
                            ("package", "Package - Final content packaging"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("user_rating", "User Rating (1-5 stars)"),
                            ("implicit", "Implicit (completion, engagement)"),
                            ("automated", "Automated (quality checks)"),
                            ("ab_test", "A/B Test Result"),
                        ],
                        default="user_rating",
                        max_length=20,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rating from 1.0 to 5.0",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Stage-specific context (style, voice, audience, etc.)",
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_feedback",
                        to="core.contentpackage",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_feedback",
                        to="core.seriesepisode",
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_feedback",
                        to="core.aiseries",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StylePresetPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "style_preset",
                    models.CharField(
                        db_index=True,
                        help_text="Style preset (pixar, disney, anime, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        db_index=True,
                        help_text="Target audience category",
                        max_length=100,
                    ),
                ),
                (
                    "series_type",
                    models.CharField(
                        blank=True,
                        help_text="Series type (educational, entertainment, marketing)",
                        max_length=50,
                    ),
                ),
                ("total_uses", models.IntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of content approved/published (0-100)",
                        max_digits=5,
                    ),
                ),
                (
                    "engagement_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Normalized engagement score (0-100)",
                        max_digits=5,
                    ),
                ),
                ("successful_series_count", models.IntegerField(default=0)),
                ("viral_content_count", models.IntegerField(default=0)),
                ("rejection_count", models.IntegerField(default=0)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Confidence in this recommendation (0-1)",
                        max_digits=3,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-avg_rating", "-total_uses"],
                "unique_together": {("style_preset", "target_audience", "series_type")},
            },
        ),
        migrations.CreateModel(
            name="SyntheticUserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Synthetic user display name", max_length=100
                    ),
                ),
                (
                    "archetype",
                    models.CharField(
                        db_index=True,
                        help_text="Persona archetype (e.g., 'career_pivoter', 'new_grad', 'freelancer')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of this persona",
                    ),
                ),
                (
                    "age_bracket",
                    models.CharField(
                        choices=[
                            ("18-24", "18-24"),
                            ("25-34", "25-34"),
                            ("35-44", "35-44"),
                            ("45-54", "45-54"),
                            ("55-64", "55-64"),
                            ("65+", "65+"),
                        ],
                        default="25-34",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(default="United States", max_length=100)),
                (
                    "income_bracket",
                    models.CharField(
                        choices=[
                            ("under_25k", "Under $25,000"),
                            ("25k_50k", "$25,000 - $50,000"),
                            ("50k_75k", "$50,000 - $75,000"),
                            ("75k_100k", "$75,000 - $100,000"),
                            ("100k_150k", "$100,000 - $150,000"),
                            ("150k_200k", "$150,000 - $200,000"),
                            ("over_200k", "Over $200,000"),
                        ],
                        default="50k_75k",
                        max_length=30,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=200)),
                ("current_role", models.CharField(blank=True, max_length=200)),
                ("experience_years", models.IntegerField(default=0)),
                (
                    "skills",
                    models.JSONField(
                        default=list,
                        help_text="List of skills (e.g., ['Python', 'SQL', 'Project Management'])",
                    ),
                ),
                (
                    "industries",
                    models.JSONField(
                        default=list,
                        help_text="Industries of experience (e.g., ['Technology', 'Finance'])",
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("some_college", "Some College"),
                            ("associates", "Associate Degree"),
                            ("bachelors", "Bachelor's Degree"),
                            ("masters", "Master's Degree"),
                            ("phd", "PhD/Doctorate"),
                            ("bootcamp", "Bootcamp/Certification"),
                        ],
                        default="bachelors",
                        max_length=50,
                    ),
                ),
                ("remote_only", models.BooleanField(default=False)),
                ("contract_work", models.BooleanField(default=True)),
                ("full_time", models.BooleanField(default=True)),
                ("part_time", models.BooleanField(default=False)),
                (
                    "hourly_rate_min",
                    models.IntegerField(
                        blank=True, help_text="Minimum hourly rate", null=True
                    ),
                ),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True, help_text="Minimum salary expectation", null=True
                    ),
                ),
                (
                    "primary_goal",
                    models.CharField(
                        choices=[
                            ("find_job", "Find a New Job"),
                            ("increase_income", "Increase Income"),
                            ("career_change", "Change Careers"),
                            ("start_freelancing", "Start Freelancing"),
                            ("build_passive_income", "Build Passive Income"),
                            ("learn_new_skills", "Learn New Skills"),
                            ("start_business", "Start a Business"),
                            ("work_life_balance", "Improve Work-Life Balance"),
                        ],
                        default="find_job",
                        max_length=50,
                    ),
                ),
                (
                    "secondary_goals",
                    models.JSONField(default=list, help_text="Additional goals"),
                ),
                (
                    "income_target",
                    models.IntegerField(
                        blank=True, help_text="Target annual income", null=True
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate (0-1 month)"),
                            ("short_term", "Short-term (1-3 months)"),
                            ("medium_term", "Medium-term (3-6 months)"),
                            ("long_term", "Long-term (6-12 months)"),
                            ("exploratory", "Exploratory (no timeline)"),
                        ],
                        default="short_term",
                        max_length=30,
                    ),
                ),
                (
                    "engagement_level",
                    models.CharField(
                        choices=[
                            ("passive", "Passive - Just browsing"),
                            ("moderate", "Moderate - Occasionally engages"),
                            ("active", "Active - Regularly engages"),
                            ("power_user", "Power User - Daily engagement"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "decision_style",
                    models.CharField(
                        choices=[
                            ("impulsive", "Impulsive - Quick decisions"),
                            ("deliberate", "Deliberate - Careful analysis"),
                            ("collaborative", "Collaborative - Seeks input"),
                            ("risk_averse", "Risk-Averse - Very cautious"),
                        ],
                        default="deliberate",
                        max_length=20,
                    ),
                ),
                (
                    "tech_comfort",
                    models.CharField(
                        choices=[
                            ("novice", "Novice"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "constraints",
                    models.JSONField(
                        default=dict,
                        help_text="Constraints like location restrictions, visa status, availability",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context (family situation, health, etc.)",
                    ),
                ),
                (
                    "expected_recommendations",
                    models.JSONField(
                        default=list,
                        help_text="Types of recommendations this persona should receive",
                    ),
                ),
                (
                    "expected_agents",
                    models.JSONField(
                        default=list,
                        help_text="Agents that should be particularly relevant for this persona",
                    ),
                ),
                (
                    "success_criteria",
                    models.JSONField(
                        default=dict,
                        help_text="Criteria for evaluating recommendation quality",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.CharField(
                        default="system",
                        help_text="Who created this persona (system, manual, generated)",
                        max_length=50,
                    ),
                ),
                (
                    "generation_seed",
                    models.CharField(
                        blank=True,
                        help_text="Seed used if this was randomly generated",
                        max_length=100,
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "test_results",
                    models.JSONField(
                        default=list,
                        help_text="History of test results for this persona",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_synthetic_user_profile",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["archetype", "is_active"],
                        name="core_synthe_archety_2049f4_idx",
                    ),
                    models.Index(
                        fields=["primary_goal", "is_active"],
                        name="core_synthe_primary_f5e4bf_idx",
                    ),
                    models.Index(
                        fields=["experience_years", "is_active"],
                        name="core_synthe_experie_8418f9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyntheticUserTestRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Test run name/description", max_length=200
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("agent_validation", "Agent Validation"),
                            ("recommendation_quality", "Recommendation Quality"),
                            ("coverage_test", "Coverage Test"),
                            ("regression_test", "Regression Test"),
                            ("a_b_test", "A/B Test"),
                        ],
                        default="agent_validation",
                        max_length=50,
                    ),
                ),
                (
                    "agents_tested",
                    models.JSONField(
                        default=list, help_text="List of agent names that were tested"
                    ),
                ),
                ("total_executions", models.IntegerField(default=0)),
                ("successful_executions", models.IntegerField(default=0)),
                ("failed_executions", models.IntegerField(default=0)),
                ("avg_relevance_score", models.FloatField(blank=True, null=True)),
                ("avg_quality_score", models.FloatField(blank=True, null=True)),
                ("coverage_percentage", models.FloatField(blank=True, null=True)),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="Detailed results by persona and agent"
                    ),
                ),
                (
                    "issues_found",
                    models.JSONField(
                        default=list, help_text="Issues or anomalies discovered"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Recommendations for improvement"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("ci_cd", "CI/CD Pipeline"),
                            ("pre_deploy", "Pre-Deployment"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "personas_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="test_runs",
                        to="core.syntheticuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "core_synthetic_user_test_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="VoicePerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        db_index=True, help_text="ElevenLabs voice ID", max_length=100
                    ),
                ),
                ("voice_name", models.CharField(db_index=True, max_length=100)),
                (
                    "voice_style",
                    models.CharField(
                        blank=True,
                        help_text="Voice style category (friendly, authoritative, etc.)",
                        max_length=50,
                    ),
                ),
                ("series_type", models.CharField(blank=True, max_length=50)),
                ("target_audience", models.CharField(blank=True, max_length=100)),
                ("total_uses", models.IntegerField(default=0)),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                (
                    "approval_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Video completion rate when this voice is used",
                        max_digits=5,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-avg_rating", "-total_uses"],
                "unique_together": {("voice_id", "series_type", "target_audience")},
            },
        ),
        migrations.DeleteModel(
            name="FailureDetection",
        ),
        migrations.DeleteModel(
            name="FailureSignature",
        ),
        migrations.DeleteModel(
            name="FailureDiagnosis",
        ),
        migrations.DeleteModel(
            name="FailurePrescription",
        ),
        migrations.AddIndex(
            model_name="contentengagement",
            index=models.Index(
                fields=["platform", "outcome"], name="core_conten_platfor_440b0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentengagement",
            index=models.Index(
                fields=["series", "outcome"], name="core_conten_series__a778ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagefeedback",
            index=models.Index(
                fields=["stage", "created_at"], name="core_pipeli_stage_46e510_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestagefeedback",
            index=models.Index(
                fields=["series", "stage"], name="core_pipeli_series__6625da_idx"
            ),
        ),
    ]
