# Generated by Django 5.0.6 on 2026-01-29 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0204_session_862_synthetic_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptForgeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("blog", "Blog Post"),
                            ("decision_summary", "Decision Summary"),
                            ("research_brief", "Research Brief"),
                            ("audit", "System Audit"),
                            ("manual", "Manual Trigger"),
                        ],
                        default="blog",
                        max_length=30,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        help_text="UUID of the source content (e.g., SelfBlog.id)"
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="Title of source content for display",
                        max_length=500,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domain lab (legal, market, tech, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "advisor_panel_snapshot",
                    models.JSONField(
                        default=dict, help_text="Snapshot of advisor panel at run start"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        help_text="Current stage being executed",
                        max_length=30,
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        default=0, help_text="Total execution time in milliseconds"
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="system",
                        help_text="What triggered this run (signal, manual, celery_beat)",
                        max_length=50,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Quality score of source content that triggered run",
                    ),
                ),
                ("celery_task_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conceptforge_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ConceptForge Run",
                "verbose_name_plural": "ConceptForge Runs",
                "db_table": "core_conceptforge_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConceptForgeStageRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        db_index=True,
                        help_text="Stage name: research, debate, feasibility, risk, market, synthesis",
                        max_length=30,
                    ),
                ),
                (
                    "stage_order",
                    models.IntegerField(
                        default=0, help_text="Order of execution (1-6)"
                    ),
                ),
                (
                    "agent_used",
                    models.CharField(
                        blank=True,
                        help_text="Core agent that executed this stage",
                        max_length=100,
                    ),
                ),
                (
                    "advisors_used",
                    models.JSONField(
                        default=list,
                        help_text="Persona advisors consulted for this stage",
                    ),
                ),
                (
                    "legendary_advisors_used",
                    models.JSONField(
                        default=list,
                        help_text="Legendary advisors that provided positions",
                    ),
                ),
                (
                    "inputs_snapshot",
                    models.JSONField(
                        default=dict, help_text="Inputs provided to this stage"
                    ),
                ),
                (
                    "output_text",
                    models.TextField(
                        blank=True, help_text="Main output text from this stage"
                    ),
                ),
                (
                    "output_metadata",
                    models.JSONField(
                        default=dict, help_text="Structured metadata from output"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        default=0, help_text="Execution time in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="core.conceptforgerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConceptForge Stage Run",
                "verbose_name_plural": "ConceptForge Stage Runs",
                "db_table": "core_conceptforge_stage_run",
                "ordering": ["run", "stage_order"],
            },
        ),
        migrations.CreateModel(
            name="ConceptForgeArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Artifact name (e.g., "Research Brief", "Final Dossier")',
                        max_length=200,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("md", "Markdown"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                            ("html", "HTML"),
                        ],
                        default="md",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Artifact content (for md/json/html)"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to file if stored in workspace",
                        max_length=500,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1, help_text="Version number for this artifact"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary/final dossier artifact?",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (word count, sections, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="core.conceptforgerun",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="core.conceptforgestagerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "ConceptForge Artifact",
                "verbose_name_plural": "ConceptForge Artifacts",
                "db_table": "core_conceptforge_artifact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conceptforgerun",
            index=models.Index(
                fields=["source_type", "source_id"],
                name="core_concep_source__c8a5cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptforgerun",
            index=models.Index(
                fields=["status", "-created_at"], name="core_concep_status_51e13b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conceptforgerun",
            index=models.Index(
                fields=["domain", "status"], name="core_concep_domain_991e60_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conceptforgestagerun",
            unique_together={("run", "stage_name")},
        ),
    ]
