# Generated by Django 5.0.6 on 2026-01-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0205_conceptforge_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="selfblog",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("public", "Public Content"),
                    ("internal", "Internal Content"),
                    ("strategic", "Strategic Content"),
                ],
                db_index=True,
                default="public",
                help_text="Session 862: Determines routing - public (external), internal (learning), strategic (operators)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="gate_notes",
            field=models.TextField(
                blank=True, help_text="Session 862: Notes from PublishGate evaluation"
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="novelty_score",
            field=models.FloatField(
                blank=True, help_text="How unique vs existing content (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="publish_ready",
            field=models.BooleanField(
                default=False, help_text="True if passed PublishGate quality checks"
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="quality_score",
            field=models.FloatField(
                blank=True, help_text="Overall content quality (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="structure_score",
            field=models.FloatField(
                blank=True,
                help_text="Section variety, hooks, formatting (0-1)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="selfblog",
            name="category",
            field=models.CharField(
                choices=[
                    ("blog", "Blog Post"),
                    ("audit", "System Audit"),
                    ("technical_document", "Technical Document"),
                    ("prototype_plan", "Prototype Plan"),
                    ("research_brief", "Research Brief"),
                    ("build_log", "Build Log"),
                    ("internal_note", "Internal Note"),
                    ("playbook", "Playbook/Doctrine"),
                    ("dossier", "Strategic Dossier"),
                ],
                db_index=True,
                default="blog",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="selfblog",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending Review"),
                    ("needs_enhancement", "Needs Enhancement"),
                    ("approved", "Approved"),
                    ("published", "Published"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
