# Generated by Django 5.0.6 on 2026-01-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0206_session_862_content_intelligence"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceoperation",
            name="initiative_id",
            field=models.UUIDField(
                blank=True,
                help_text="Initiative this operation is associated with",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workspaceoperation",
            name="is_warmup",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Quick filter for warmup operations",
            ),
        ),
        migrations.AddField(
            model_name="workspaceoperation",
            name="run_mode",
            field=models.CharField(
                choices=[("production", "Production"), ("warmup", "Warmup/Exercise")],
                db_index=True,
                default="production",
                help_text="Whether this is a production run or warmup exercise",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspaceoperation",
            name="trigger_source",
            field=models.CharField(
                choices=[
                    ("initiative", "Initiative Stage"),
                    ("user", "User Request"),
                    ("dream", "Dream Execution"),
                    ("schedule", "Scheduled Task"),
                    ("warmup", "Warmup/Exercise"),
                    ("self_healing", "Self-Healing"),
                    ("conceptforge", "ConceptForge"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="What triggered this agent execution",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceoperation",
            index=models.Index(
                fields=["is_warmup", "-created_at"],
                name="core_worksp_is_warm_239c73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workspaceoperation",
            index=models.Index(
                fields=["run_mode", "-created_at"],
                name="core_worksp_run_mod_35ed3b_idx",
            ),
        ),
    ]
