# Generated by Django 5.0.6 on 2026-01-29 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0207_session_864_run_mode_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATSKeywordMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canonical",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "variations",
                    models.JSONField(
                        default=list,
                        help_text="List of variations that should be normalized to canonical",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical_skill", "Technical Skill"),
                            ("soft_skill", "Soft Skill"),
                            ("certification", "Certification"),
                            ("tool", "Tool/Software"),
                            ("methodology", "Methodology"),
                            ("industry_term", "Industry Term"),
                        ],
                        default="technical_skill",
                        max_length=50,
                    ),
                ),
                (
                    "industries",
                    models.JSONField(
                        default=list,
                        help_text="Industries where this keyword is particularly valuable",
                    ),
                ),
                (
                    "resume_frequency",
                    models.IntegerField(
                        default=0, help_text="How often this appears in resumes"
                    ),
                ),
                (
                    "job_frequency",
                    models.IntegerField(
                        default=0,
                        help_text="How often this appears in job descriptions",
                    ),
                ),
                (
                    "interview_correlation",
                    models.FloatField(
                        default=0, help_text="Correlation with getting interviews (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ATS Keyword Mapping",
                "verbose_name_plural": "ATS Keyword Mappings",
                "ordering": ["-job_frequency", "canonical"],
            },
        ),
        migrations.CreateModel(
            name="PersonaResumeTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("fintech", "Fintech"),
                            ("healthcare", "Healthcare"),
                            ("ecommerce", "E-commerce"),
                            ("saas", "SaaS"),
                            ("ai_ml", "AI/ML"),
                            ("consulting", "Consulting"),
                            ("marketing", "Marketing"),
                            ("sales", "Sales"),
                            ("general", "General"),
                        ],
                        default="tech",
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level (0-2 years)"),
                            ("mid", "Mid Level (3-5 years)"),
                            ("senior", "Senior (6-10 years)"),
                            ("lead", "Lead/Principal (10+ years)"),
                            ("executive", "Executive"),
                        ],
                        default="mid",
                        max_length=20,
                    ),
                ),
                (
                    "target_roles",
                    models.JSONField(
                        default=list,
                        help_text="List of role titles this template is optimized for",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("free_guide", "Free Guide"),
                            ("paid_basic", "Paid Basic ($79)"),
                            ("paid_premium", "Paid Premium ($149)"),
                            ("paid_executive", "Paid Executive ($249)"),
                        ],
                        default="free_guide",
                        max_length=20,
                    ),
                ),
                (
                    "price_cents",
                    models.IntegerField(
                        default=0, help_text="Price in cents (0 for free)"
                    ),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of resume sections with guidelines",
                    ),
                ),
                (
                    "required_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords that should appear in resumes using this template",
                    ),
                ),
                (
                    "recommended_keywords",
                    models.JSONField(
                        default=list, help_text="Keywords that are good to include"
                    ),
                ),
                (
                    "action_verbs",
                    models.JSONField(
                        default=list,
                        help_text="Recommended action verbs for bullet points",
                    ),
                ),
                (
                    "example_summary",
                    models.TextField(
                        blank=True, help_text="Example professional summary"
                    ),
                ),
                (
                    "example_bullets",
                    models.JSONField(
                        default=list,
                        help_text="Example bullet points for experience section",
                    ),
                ),
                (
                    "formatting_guidelines",
                    models.JSONField(
                        default=dict, help_text="ATS-friendly formatting rules"
                    ),
                ),
                ("downloads", models.IntegerField(default=0)),
                (
                    "conversions",
                    models.IntegerField(
                        default=0, help_text="Number of users who got interviews"
                    ),
                ),
                ("avg_ats_score_improvement", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Persona Resume Template",
                "verbose_name_plural": "Persona Resume Templates",
                "ordering": ["industry", "experience_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="ResumeOptimizationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("job_title_target", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=50)),
                ("experience_level", models.CharField(blank=True, max_length=20)),
                ("initial_ats_score", models.FloatField(blank=True, null=True)),
                ("final_ats_score", models.FloatField(blank=True, null=True)),
                ("missing_keywords_count", models.IntegerField(default=0)),
                ("keywords_added", models.JSONField(default=list)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("signup", "Signed Up"),
                            ("analyzed", "Resume Analyzed"),
                            ("downloaded_free", "Downloaded Free Guide"),
                            ("purchased_basic", "Purchased Basic Rewrite"),
                            ("purchased_premium", "Purchased Premium Rewrite"),
                            ("purchased_executive", "Purchased Executive Rewrite"),
                            ("resume_delivered", "Rewrite Delivered"),
                            ("applied", "Applied to Jobs"),
                            ("interview", "Got Interview"),
                            ("offer", "Received Offer"),
                        ],
                        default="signup",
                        max_length=30,
                    ),
                ),
                (
                    "stage_timestamps",
                    models.JSONField(
                        default=dict, help_text="Timestamp for each stage reached"
                    ),
                ),
                ("revenue_cents", models.IntegerField(default=0)),
                (
                    "ab_test_variant",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("utm_source", models.CharField(blank=True, max_length=100)),
                ("utm_medium", models.CharField(blank=True, max_length=100)),
                ("utm_campaign", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="optimization_logs",
                        to="core.personaresumetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_optimizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Optimization Log",
                "verbose_name_plural": "Resume Optimization Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeRewriteOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("free_guide", "Free Guide"),
                            ("basic", "Basic Rewrite"),
                            ("premium", "Premium Rewrite"),
                            ("executive", "Executive Rewrite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_cents", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("in_progress", "In Progress"),
                            ("review", "Ready for Review"),
                            ("revision", "Revision Requested"),
                            ("completed", "Completed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("target_job_description", models.TextField(blank=True)),
                ("target_industry", models.CharField(blank=True, max_length=50)),
                ("additional_notes", models.TextField(blank=True)),
                ("before_ats_score", models.FloatField(blank=True, null=True)),
                ("after_ats_score", models.FloatField(blank=True, null=True)),
                ("payment_intent_id", models.CharField(blank=True, max_length=100)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("revision_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "optimization_log",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewrite_order",
                        to="core.resumeoptimizationlog",
                    ),
                ),
                (
                    "original_resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewrite_orders",
                        to="core.resumeversion",
                    ),
                ),
                (
                    "rewritten_resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_orders",
                        to="core.resumeversion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_rewrite_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Rewrite Order",
                "verbose_name_plural": "Resume Rewrite Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="resumeoptimizationlog",
            index=models.Index(
                fields=["current_stage", "-created_at"],
                name="core_resume_current_0432c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resumeoptimizationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="core_resume_user_id_523b86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resumeoptimizationlog",
            index=models.Index(
                fields=["ab_test_variant", "current_stage"],
                name="core_resume_ab_test_387a0e_idx",
            ),
        ),
    ]
