# Generated by Django 5.0.6 on 2026-01-30 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0208_session_866_ats_optimization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rivalry",
            name="alliance_defender",
        ),
        migrations.RemoveField(
            model_name="rivalry",
            name="alliance_challenger",
        ),
        migrations.RemoveField(
            model_name="rivalry",
            name="agent_challenger",
        ),
        migrations.RemoveField(
            model_name="rivalry",
            name="agent_defender",
        ),
        migrations.CreateModel(
            name="BadContextEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique trace ID for correlating events across the pipeline",
                        max_length=64,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("llm_raw", "LLM Raw Output"),
                            ("parser", "Parser Output"),
                            ("pre_enqueue", "Pre-Enqueue"),
                            ("post_deserialize", "Post-Deserialize"),
                            ("router", "Router"),
                            ("agent", "Agent Entry"),
                        ],
                        db_index=True,
                        help_text="Stage in the execution pipeline where the bad context was detected",
                        max_length=32,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name of the agent being executed (if known at this stage)",
                        max_length=128,
                    ),
                ),
                (
                    "action_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the action/next_step being executed",
                        max_length=128,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True,
                        help_text="Celery task name if applicable",
                        max_length=256,
                    ),
                ),
                (
                    "context_type",
                    models.CharField(
                        help_text="The actual type received (e.g., 'list', 'str', 'NoneType')",
                        max_length=64,
                    ),
                ),
                (
                    "context_preview",
                    models.TextField(
                        blank=True,
                        help_text="Truncated string representation of the bad context (max 1000 chars)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message or diagnostic information"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional diagnostic data (e.g., raw LLM preview, parent trace)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source of the trace (e.g., conversation_id, task_id)",
                        max_length=256,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Bad Context Event",
                "verbose_name_plural": "Bad Context Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trace_id", "stage"],
                        name="core_badcon_trace_i_aef963_idx",
                    ),
                    models.Index(
                        fields=["agent_name", "created_at"],
                        name="core_badcon_agent_n_2e1a27_idx",
                    ),
                    models.Index(
                        fields=["context_type", "created_at"],
                        name="core_badcon_context_7b76c2_idx",
                    ),
                ],
            },
        ),
        migrations.DeleteModel(
            name="Alliance",
        ),
        migrations.DeleteModel(
            name="Rivalry",
        ),
    ]
