# Generated by Django 5.0.6 on 2026-02-01 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0210_podcast_style_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The auto-generated topic name", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Extended description of the topic"
                    ),
                ),
                (
                    "derived_from_pattern",
                    models.CharField(
                        blank=True,
                        help_text="Pattern type that generated this topic",
                        max_length=100,
                    ),
                ),
                (
                    "rationale",
                    models.TextField(
                        blank=True,
                        help_text="Explanation of why this topic was auto-generated",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence that this topic is worth discussing (0-1)",
                    ),
                ),
                (
                    "urgency",
                    models.FloatField(
                        default=0.0, help_text="Time-sensitivity of this topic (0-1)"
                    ),
                ),
                (
                    "relevance",
                    models.FloatField(
                        default=0.0, help_text="Relevance to user/system goals (0-1)"
                    ),
                ),
                (
                    "suggested_agent_names",
                    models.JSONField(
                        default=list, help_text="Agent names recommended for this topic"
                    ),
                ),
                (
                    "suggested_conversation_type",
                    models.CharField(
                        choices=[
                            ("analytical", "Analytical"),
                            ("creative", "Creative"),
                            ("debate", "Debate"),
                            ("planning", "Planning"),
                            ("critique", "Critique"),
                        ],
                        default="analytical",
                        help_text="Recommended conversation type for this topic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("triggered", "Triggered"),
                            ("skipped", "Skipped"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_session_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the HiveMindSession this topic triggered",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this topic should be considered stale",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auto Topic",
                "verbose_name_plural": "Auto Topics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="hivemindsession",
            name="trigger_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Session 900: Confidence score of the trigger (0-1)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hivemindsession",
            name="auto_topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 900: The auto-generated topic that triggered this conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_sessions",
                to="core.autotopic",
            ),
        ),
        migrations.CreateModel(
            name="SignalCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this signal pattern",
                        max_length=200,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("demand_spike", "Demand Spike"),
                            ("trend_emergence", "Trend Emergence"),
                            ("sentiment_shift", "Sentiment Shift"),
                            ("opportunity_window", "Opportunity Window"),
                            ("knowledge_gap", "Knowledge Gap"),
                            ("competitive_signal", "Competitive Signal"),
                            ("market_movement", "Market Movement"),
                            ("skill_demand", "Skill Demand"),
                            ("content_gap", "Content Gap"),
                            ("user_need", "User Need"),
                        ],
                        default="demand_spike",
                        help_text="Classification of the detected pattern",
                        max_length=30,
                    ),
                ),
                (
                    "spider_data_ids",
                    models.JSONField(
                        default=list,
                        help_text="List of SpiderData UUIDs that contributed to this cluster",
                    ),
                ),
                (
                    "trigger_event_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of TriggerEvent UUIDs that contributed",
                    ),
                ),
                (
                    "source_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Count of signals per source: {'bluesky': 12, 'reddit': 6}",
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        default=0.0, help_text="Overall signal strength (0-1)"
                    ),
                ),
                (
                    "novelty",
                    models.FloatField(
                        default=0.0, help_text="How new/unusual is this pattern (0-1)"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Confidence in pattern validity (0-1)"
                    ),
                ),
                (
                    "urgency",
                    models.FloatField(
                        default=0.0, help_text="Time-sensitivity of this pattern (0-1)"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords that define this cluster"
                    ),
                ),
                (
                    "sample_signals",
                    models.JSONField(
                        default=list,
                        help_text="Sample signal snippets for display: [{'source': 'bluesky', 'text': '...'}]",
                    ),
                ),
                (
                    "signal_window_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Earliest signal timestamp in cluster",
                        null=True,
                    ),
                ),
                (
                    "signal_window_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="Latest signal timestamp in cluster",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detecting", "Detecting"),
                            ("active", "Active"),
                            ("triggered", "Triggered"),
                            ("decayed", "Decayed"),
                            ("archived", "Archived"),
                        ],
                        default="detecting",
                        max_length=20,
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decay_rate",
                    models.FloatField(
                        default=0.1,
                        help_text="How fast this pattern loses relevance (per day)",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this pattern should be considered stale",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Signal Cluster",
                "verbose_name_plural": "Signal Clusters",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="core_signal_status_81c9a6_idx",
                    ),
                    models.Index(
                        fields=["pattern_type", "-strength"],
                        name="core_signal_pattern_49db37_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="autotopic",
            name="signal_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="The signal cluster that triggered this topic",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_topics",
                to="core.signalcluster",
            ),
        ),
        migrations.AddField(
            model_name="hivemindsession",
            name="signal_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 900: The signal cluster that triggered this conversation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_sessions",
                to="core.signalcluster",
            ),
        ),
        migrations.CreateModel(
            name="TopicSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "reason_not_primary",
                    models.CharField(
                        blank=True,
                        help_text="Why this wasn't the primary topic",
                        max_length=200,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auto_topic",
                    models.ForeignKey(
                        help_text="The primary auto topic this is an alternative to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="core.autotopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Suggestion",
                "verbose_name_plural": "Topic Suggestions",
            },
        ),
        migrations.AddIndex(
            model_name="autotopic",
            index=models.Index(
                fields=["status", "-created_at"], name="core_autoto_status_ab16f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="autotopic",
            index=models.Index(
                fields=["-confidence", "-urgency"],
                name="core_autoto_confide_54ade6_idx",
            ),
        ),
    ]
