# Generated by Django 5.0.6 on 2026-02-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0211_session_900_signal_intelligence"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="confidence",
            field=models.FloatField(
                default=0.5, help_text="Confidence in success (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="impact_score",
            field=models.FloatField(
                default=0.5, help_text="Expected impact of this initiative (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="program",
            field=models.CharField(
                choices=[
                    ("growth_intelligence", "Growth Intelligence"),
                    ("platform_health", "Platform Health"),
                    ("monetization", "Monetization"),
                    ("content_pipeline", "Content Pipeline"),
                    ("ai_capabilities", "AI Capabilities"),
                    ("user_experience", "User Experience"),
                    ("infrastructure", "Infrastructure"),
                    ("research", "Research"),
                    ("experiments", "Experiments"),
                    ("uncategorized", "Uncategorized"),
                ],
                default="uncategorized",
                help_text="Portfolio program this initiative belongs to",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("revenue", "Revenue & Growth"),
                    ("stability", "Platform Health"),
                    ("learning", "Research & Learning"),
                    ("expansion", "New Capabilities"),
                    ("maintenance", "Maintenance"),
                ],
                default="learning",
                help_text="Primary purpose of this initiative",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="revenue_potential",
            field=models.FloatField(
                default=0.0, help_text="Potential revenue impact (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="urgency",
            field=models.FloatField(
                default=0.5, help_text="Time-sensitivity of this initiative (0-1)"
            ),
        ),
    ]
