# Generated by Django 5.0.6 on 2026-02-02 01:10
# Session 902: Initiative Action Items - Track next steps from conversations

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0212_session_901_initiative_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeActionItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_text",
                    models.TextField(
                        blank=True,
                        help_text="Original text from conclusion that was parsed",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "assigned_agent",
                    models.CharField(
                        blank=True,
                        help_text='Agent name responsible (e.g., "ResearchAgent")',
                        max_length=100,
                    ),
                ),
                (
                    "timeline_text",
                    models.CharField(
                        blank=True,
                        help_text='Original timeline text (e.g., "Week 0-1")',
                        max_length=50,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Calculated or manually set due date",
                        null=True,
                    ),
                ),
                (
                    "estimated_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated effort in hours",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_by", models.CharField(blank=True, max_length=100)),
                ("completion_notes", models.TextField(blank=True)),
                ("blocked_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(default="system", max_length=100)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within initiative"
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_action_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blocks",
                        to="core.initiativeactionitem",
                    ),
                ),
                (
                    "initiative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_items",
                        to="core.initiative",
                    ),
                ),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="The conversation that generated this action item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_action_items",
                        to="core.hivemindsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative Action Item",
                "verbose_name_plural": "Initiative Action Items",
                "ordering": ["initiative", "order", "-priority", "created_at"],
            },
        ),
    ]
