# Generated by Django 5.0.6 on 2026-02-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0213_session_902_action_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchresult",
            name="blocked_reason",
            field=models.TextField(
                blank=True,
                help_text='Reason research is blocked (e.g., "Insufficient spider data")',
            ),
        ),
        migrations.AddField(
            model_name="researchresult",
            name="data_sufficient",
            field=models.BooleanField(
                default=True,
                help_text="Whether research has sufficient data to proceed",
            ),
        ),
        migrations.AddField(
            model_name="researchresult",
            name="max_retries",
            field=models.IntegerField(
                default=3, help_text="Maximum retry attempts before escalation"
            ),
        ),
        migrations.AddField(
            model_name="researchresult",
            name="retry_after",
            field=models.DateTimeField(
                blank=True, help_text="When to retry blocked research", null=True
            ),
        ),
        migrations.AddField(
            model_name="researchresult",
            name="retry_count",
            field=models.IntegerField(
                default=0, help_text="Number of times research has been retried"
            ),
        ),
        migrations.AddField(
            model_name="researchresult",
            name="unblock_trigger",
            field=models.CharField(
                blank=True,
                help_text='What should trigger unblocking (e.g., "spider_data_arrival")',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="initiativestage",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DRAFT", "Draft"),
                    ("IN_REVIEW", "In Review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("SUPERSEDED", "Superseded"),
                    ("BLOCKED", "Blocked - Awaiting Data"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="researchresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("blocked", "Blocked - Awaiting Data"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
