# Generated by Django 5.0.6 on 2026-02-02 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0216_add_initiative_target_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="auto_topic",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 913: Auto-generated topic that created this initiative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiatives",
                to="core.autotopic",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="signal_cluster",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 913: Signal cluster that triggered this initiative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiatives",
                to="core.signalcluster",
            ),
        ),
    ]
