# Generated by Django 5.0.2 on 2026-02-02
# Session 914.3: Semantic Quality Gates

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_session_914_2_execution_track'),
    ]

    operations = [
        # Initiative drift settings
        migrations.AddField(
            model_name='initiative',
            name='drift_threshold',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('strict', 'Strict (75%+ similarity required)'),
                    ('balanced', 'Balanced (65%+ similarity required)'),
                    ('relaxed', 'Relaxed (55%+ similarity required)'),
                    ('disabled', 'Disabled (no drift check)'),
                ],
                default='balanced',
                help_text='Session 914.3: How strictly to enforce semantic alignment'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='drift_check_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Session 914.3: Whether to perform semantic drift checks'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='last_drift_score',
            field=models.FloatField(
                null=True, blank=True,
                help_text='Session 914.3: Last recorded drift score (0=aligned, 1=drifted)'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='last_drift_check_at',
            field=models.DateTimeField(
                null=True, blank=True,
                help_text='Session 914.3: When drift was last checked'
            ),
        ),

        # InitiativeStage drift tracking
        migrations.AddField(
            model_name='initiativestage',
            name='drift_score',
            field=models.FloatField(
                null=True, blank=True,
                help_text='Session 914.3: Semantic drift score (0=aligned, 1=drifted)'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='similarity_score',
            field=models.FloatField(
                null=True, blank=True,
                help_text='Session 914.3: Semantic similarity to initiative intent (0-1)'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='drift_checked_at',
            field=models.DateTimeField(
                null=True, blank=True,
                help_text='Session 914.3: When drift was last checked'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='drift_flagged',
            field=models.BooleanField(
                default=False,
                help_text='Session 914.3: Whether this stage was flagged for drift'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='drift_override',
            field=models.BooleanField(
                default=False,
                help_text='Session 914.3: Human override to allow progression despite drift'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='drift_override_by',
            field=models.CharField(
                max_length=100, blank=True, default='',
                help_text='Session 914.3: Who approved the drift override'
            ),
        ),
        migrations.AddField(
            model_name='initiativestage',
            name='drift_override_reason',
            field=models.TextField(
                blank=True, default='',
                help_text='Session 914.3: Reason for allowing drift override'
            ),
        ),
    ]
