# Generated by Django 5.0.2 on 2026-02-02
# Session 914.5: Daily Priorities

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_session_914_3_semantic_drift'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='is_daily_focus',
            field=models.BooleanField(
                default=False,
                help_text='Session 914.5: Is this initiative in today\'s daily focus?'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='daily_focus_date',
            field=models.DateField(
                null=True, blank=True,
                help_text='Session 914.5: Date when marked as daily focus'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='manual_priority_rank',
            field=models.IntegerField(
                null=True, blank=True,
                help_text='Session 914.5: Manual priority rank (1-5, lower = higher priority)'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='manual_priority_reason',
            field=models.TextField(
                blank=True, default='',
                help_text='Session 914.5: Reason for manual priority override'
            ),
        ),
    ]
