# Generated by Django 5.0.2 on 2026-02-02
# Session 914.6: Boardroom Approval Fix

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_session_914_5_daily_priorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='boardroom_approved',
            field=models.BooleanField(
                default=False,
                help_text='Session 914.6: Has this initiative been approved by the Boardroom?'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='boardroom_approved_at',
            field=models.DateTimeField(
                null=True, blank=True,
                help_text='Session 914.6: When was boardroom approval granted?'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='boardroom_approved_by',
            field=models.CharField(
                max_length=100, blank=True, default='',
                help_text='Session 914.6: Who approved this initiative in the Boardroom?'
            ),
        ),
        migrations.AddField(
            model_name='initiative',
            name='boardroom_approval_notes',
            field=models.TextField(
                blank=True, default='',
                help_text='Session 914.6: Notes or conditions from boardroom approval'
            ),
        ),
    ]
