# Generated by Django 5.0.2 on 2026-02-02
# Session 914.7: Operating Rhythm

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0222_session_914_6_boardroom_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderFeedback',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False
                )),
                ('feedback_type', models.CharField(
                    choices=[
                        ('daily_priorities', 'Daily Priorities'),
                        ('weekly_feedback', 'Weekly Feedback'),
                        ('initiative_feedback', 'Initiative-Specific Feedback'),
                        ('agent_feedback', 'Agent Performance Feedback'),
                    ],
                    db_index=True,
                    help_text='Session 914.7: Type of feedback',
                    max_length=32
                )),
                ('content', models.JSONField(
                    default=dict,
                    help_text='Session 914.7: Feedback content (priorities, text, etc.)'
                )),
                ('created_by', models.CharField(
                    default='founder',
                    help_text='Session 914.7: Who submitted this feedback',
                    max_length=100
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    db_index=True
                )),
                ('processed_as_learning', models.BooleanField(
                    default=False,
                    help_text='Session 914.7: Has this been converted to agent learning?'
                )),
                ('processed_at', models.DateTimeField(
                    blank=True,
                    null=True,
                    help_text='Session 914.7: When was this processed?'
                )),
            ],
            options={
                'verbose_name': 'Founder Feedback',
                'verbose_name_plural': 'Founder Feedback',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['feedback_type', 'created_at'],
                        name='core_founde_feedbac_idx'
                    ),
                ],
            },
        ),
    ]
