# Generated by Django 5.0.6 on 2026-02-03 04:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0223_session_914_7_operating_rhythm"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageTransitionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("system", "System (Auto-progression)"),
                            ("agent", "Agent"),
                            ("user", "User"),
                            ("api", "API Call"),
                            ("celery", "Celery Task"),
                            ("manual", "Manual Override"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        help_text="Agent name, user ID, task name, or system component",
                        max_length=200,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Quality score at time of transition (0-1)",
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence in the quality assessment (0-1)",
                        null=True,
                    ),
                ),
                (
                    "document_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Document ID at time of transition",
                        null=True,
                    ),
                ),
                (
                    "document_word_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Document word count at transition",
                        null=True,
                    ),
                ),
                (
                    "checks_passed",
                    models.JSONField(
                        default=dict,
                        help_text="Dict of validation checks and their results",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context or notes about this transition",
                    ),
                ),
                ("had_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Stage Transition Log",
                "verbose_name_plural": "Stage Transition Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="founderfeedback",
            new_name="core_founde_feedbac_04083a_idx",
            old_name="core_founde_feedbac_idx",
        ),
        migrations.AlterField(
            model_name="initiative",
            name="compliance_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="Session 914.2: Has compliance review been completed?",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="compliance_reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Session 914.2: When was compliance review completed?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="compliance_reviewed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Session 914.2: Who completed compliance review?",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="content_flags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Session 914.2: Content flags detected (e.g., external_data,user_data)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="execution_track",
            field=models.CharField(
                choices=[
                    ("fast_track", "Fast Track (Stage 1-2, quick experiments)"),
                    (
                        "institutional",
                        "Institutional (Full 5-stage, compliance required)",
                    ),
                ],
                default="fast_track",
                help_text="Session 914.2: Fast Track (Stage 1-2) or Institutional (Full 5-stage)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="stage_2_approved",
            field=models.BooleanField(
                default=False,
                help_text="Session 914.2: Has Stage 2 (Prototype Plan) been explicitly approved?",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="stage_3_approved",
            field=models.BooleanField(
                default=False,
                help_text="Session 914.2: Has Stage 3 (Evaluation Protocol) been explicitly approved?",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="stage_4_approved",
            field=models.BooleanField(
                default=False,
                help_text="Session 914.2: Has Stage 4 (Technical Design) been explicitly approved?",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="track_auto_detected",
            field=models.BooleanField(
                default=False,
                help_text="Session 914.2: Was the execution track auto-detected from content?",
            ),
        ),
        migrations.AlterField(
            model_name="initiativestage",
            name="drift_override_by",
            field=models.CharField(
                blank=True,
                help_text="Session 914.3: Who approved the drift override",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="initiativestage",
            name="drift_override_reason",
            field=models.TextField(
                blank=True,
                help_text="Session 914.3: Reason for allowing drift override",
            ),
        ),
        migrations.AddField(
            model_name="stagetransitionlog",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transition_logs",
                to="core.initiativestage",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransitionlog",
            index=models.Index(
                fields=["stage", "-timestamp"], name="core_staget_stage_i_0de600_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransitionlog",
            index=models.Index(
                fields=["triggered_by", "-timestamp"],
                name="core_staget_trigger_ba8f1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stagetransitionlog",
            index=models.Index(
                fields=["to_status", "-timestamp"],
                name="core_staget_to_stat_8d8607_idx",
            ),
        ),
    ]
