# Generated by Django 5.0.6 on 2026-02-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0224_session_916_stage_transition_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="voice_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ElevenLabs voice ID or name (Rachel, Antoni, etc.)",
                max_length=100,
            ),
        ),
    ]
