# Generated by Django 5.0.6 on 2026-02-05 00:16

import core.models_audio_cache
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0225_add_voice_id_and_audio_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of text + voice_id for deduplication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Cached audio file (MP3)",
                        upload_to=core.models_audio_cache.audio_cache_upload_path,
                    ),
                ),
                (
                    "text_preview",
                    models.CharField(
                        help_text="First 200 chars of the text for debugging",
                        max_length=200,
                    ),
                ),
                (
                    "text_length",
                    models.IntegerField(help_text="Full length of the original text"),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="ElevenLabs voice ID used", max_length=100
                    ),
                ),
                (
                    "voice_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable voice name if known",
                        max_length=50,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Duration of the audio file", null=True
                    ),
                ),
                (
                    "file_size_bytes",
                    models.IntegerField(help_text="Size of the audio file in bytes"),
                ),
                (
                    "generation_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Estimated cost in USD (~$0.30 per 1000 chars)",
                        max_digits=6,
                    ),
                ),
                (
                    "access_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times this cache entry was accessed",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this cache entry was accessed",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Audio Cache",
                "verbose_name_plural": "Audio Cache",
                "ordering": ["-last_accessed"],
                "indexes": [
                    models.Index(
                        fields=["content_hash"], name="core_audioc_content_ea4126_idx"
                    ),
                    models.Index(
                        fields=["last_accessed"], name="core_audioc_last_ac_a4fc63_idx"
                    ),
                    models.Index(
                        fields=["voice_id"], name="core_audioc_voice_i_d3b614_idx"
                    ),
                ],
            },
        ),
    ]
