# Generated by Django 5.0.6 on 2026-02-05 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0226_add_audio_cache_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="hivemindsession",
            name="initiative",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 928: The initiative this conversation is discussing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="core.initiative",
            ),
        ),
    ]
