# Generated by Django 5.0.6 on 2026-02-06 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0229_initiative_last_activity_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("ui_ux_issue", "UI/UX Issue"),
                            ("bug", "Bug Report"),
                            ("feature_request", "Feature Request"),
                            ("feedback", "General Feedback"),
                        ],
                        default="feedback",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="The user's feedback message")),
                (
                    "trace_id",
                    models.CharField(
                        blank=True, help_text="PA trace ID for debugging", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("in_progress", "In Progress"),
                            ("addressed", "Addressed"),
                            ("wont_fix", "Won't Fix"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="Notes about how this was addressed"
                    ),
                ),
                (
                    "session_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Session number when this was addressed",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedback",
                "db_table": "core_user_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
