# Generated by Django 5.0.6 on 2026-02-08 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0231_session_949_risk_aware_rag"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliberationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("hivemind", "Hive Mind"),
                            ("conceptforge", "ConceptForge"),
                            ("agent", "Agent"),
                            ("composite", "Composite"),
                        ],
                        default="hivemind",
                        max_length=20,
                    ),
                ),
                ("objective", models.TextField(blank=True, default="")),
                ("participants", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("evidence_pack", models.JSONField(blank=True, default=dict)),
                ("trace", models.JSONField(blank=True, default=dict)),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.deliberationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliberation Session",
                "verbose_name_plural": "Deliberation Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("research", "Research"),
                            ("synthesis", "Synthesis"),
                            ("execution", "Execution"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contract_data", models.JSONField(default=dict)),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="core.deliberationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Record",
                "verbose_name_plural": "Contract Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="agentsession",
            name="deliberation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 962: Unifying deliberation session wrapper",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_sessions",
                to="core.deliberationsession",
            ),
        ),
        migrations.AddField(
            model_name="conceptforgerun",
            name="deliberation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 962: Unifying deliberation session wrapper",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conceptforge_runs",
                to="core.deliberationsession",
            ),
        ),
        migrations.AddField(
            model_name="hivemindsession",
            name="deliberation_session",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 962: Unifying deliberation session wrapper",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hivemind_sessions",
                to="core.deliberationsession",
            ),
        ),
        migrations.CreateModel(
            name="DeliberationTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.IntegerField()),
                ("agent_name", models.CharField(max_length=128)),
                ("role", models.CharField(blank=True, default="", max_length=64)),
                ("content", models.TextField()),
                (
                    "content_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("contract_state", models.JSONField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="core.deliberationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deliberation Turn",
                "verbose_name_plural": "Deliberation Turns",
                "ordering": ["session", "turn_number"],
            },
        ),
        migrations.CreateModel(
            name="DocVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_path", models.CharField(max_length=512)),
                ("version_number", models.IntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("content_snapshot", models.TextField()),
                (
                    "author_agent",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("trace_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "change_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliberation_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doc_versions",
                        to="core.deliberationsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doc Version",
                "verbose_name_plural": "Doc Versions",
                "ordering": ["doc_path", "-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="deliberationsession",
            index=models.Index(
                fields=["-created_at"], name="core_delibe_created_9b17b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliberationsession",
            index=models.Index(fields=["status"], name="core_delibe_status_18114d_idx"),
        ),
        migrations.AddIndex(
            model_name="deliberationsession",
            index=models.Index(
                fields=["trace_id"], name="core_delibe_trace_i_6baee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecord",
            index=models.Index(
                fields=["contract_type"], name="core_contra_contrac_7b48e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contractrecord",
            index=models.Index(
                fields=["trace_id"], name="core_contra_trace_i_6a24b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliberationturn",
            index=models.Index(
                fields=["trace_id"], name="core_delibe_trace_i_383c35_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliberationturn",
            constraint=models.UniqueConstraint(
                fields=("session", "turn_number"), name="unique_session_turn"
            ),
        ),
        migrations.AddIndex(
            model_name="docversion",
            index=models.Index(
                fields=["doc_path"], name="core_docver_doc_pat_e81b4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="docversion",
            index=models.Index(
                fields=["trace_id"], name="core_docver_trace_i_c7e196_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="docversion",
            constraint=models.UniqueConstraint(
                fields=("doc_path", "version_number"), name="unique_doc_version"
            ),
        ),
    ]
