# Generated by Django 5.0.6 on 2026-02-11 00:08
# Session 987: State-only migration — DB columns already exist from migration 0095.
# The model package (core/models/conversations/models.py) was out of sync
# with the dead core/models.py file. This migration reconciles Django's
# internal state without touching the database.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0235_celery_task_event"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="chatconversation",
                    name="discord_channel_id",
                    field=models.CharField(
                        blank=True,
                        help_text="Discord channel where conversation occurred",
                        max_length=30,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="chatconversation",
                    name="discord_guild_id",
                    field=models.CharField(
                        blank=True,
                        help_text="Discord server (guild) ID",
                        max_length=30,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="chatconversation",
                    name="discord_user_id",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Discord user ID (for unlinked users or reference)",
                        max_length=30,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="chatconversation",
                    name="platform",
                    field=models.CharField(
                        choices=[("web", "Web App"), ("discord", "Discord"), ("api", "API")],
                        db_index=True,
                        default="web",
                        help_text="Platform where this message originated",
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name="chatconversation",
                    name="session_active",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this session is still active/resumable",
                    ),
                ),
                migrations.AddField(
                    model_name="chatconversation",
                    name="session_title",
                    field=models.CharField(
                        blank=True,
                        help_text="Auto-generated title for the conversation session",
                        max_length=200,
                    ),
                ),
                migrations.AlterField(
                    model_name="chatconversation",
                    name="user",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Linked user (null for unlinked Discord users)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                migrations.AddIndex(
                    model_name="chatconversation",
                    index=models.Index(
                        fields=["platform", "-created_at"],
                        name="chat_conver_platfor_ab1704_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="chatconversation",
                    index=models.Index(
                        fields=["discord_user_id", "-created_at"],
                        name="chat_conver_discord_61a133_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="chatconversation",
                    index=models.Index(
                        fields=["session_active", "-created_at"],
                        name="chat_conver_session_99953f_idx",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
