# Generated by Django 5.0.6 on 2026-02-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0236_chatconversation_discord_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningjourneystep",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="learningjourneystep",
            name="content_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="learningjourneystep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("lesson", "Lesson"),
                    ("exercise", "Exercise"),
                    ("explore", "Explore"),
                ],
                default="lesson",
                max_length=20,
            ),
        ),
    ]
