# Generated by Django 5.0.6 on 2026-02-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0237_learning_step_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("ARCHIVED", "Archived"),
                    ("ON_HOLD", "On Hold"),
                    ("TRIAGE", "Queued for Triage"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
