# Generated by Django 5.0.6 on 2026-02-13 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0238_session_994_initiative_triage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 996: Human owner responsible for this initiative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_initiatives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="owner_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Session 996: Agent owner responsible (e.g., "ResearchAgent")',
                max_length=100,
            ),
        ),
    ]
