# Generated by Django 5.0.6 on 2026-02-14 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0241_session_998b_recreate_odds_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockchainAuditBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brief_date", models.DateField()),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("security_alerts", models.JSONField(default=dict)),
                ("whale_movements", models.JSONField(default=dict)),
                ("contract_audits", models.JSONField(default=dict)),
                ("exploit_detection", models.JSONField(default=dict)),
                ("agents_run", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                ("generation_time_seconds", models.FloatField(default=0.0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blockchain Audit Brief",
                "verbose_name_plural": "Blockchain Audit Briefs",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["-brief_date"], name="core_blockc_brief_d_473727_idx"
                    ),
                    models.Index(
                        fields=["-generated_at"], name="core_blockc_generat_9385cc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SportsBettingBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brief_date", models.DateField()),
                (
                    "sport_filter",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("executive_summary", models.TextField(blank=True, default="")),
                ("predictions", models.JSONField(default=dict)),
                ("arbitrage_opportunities", models.JSONField(default=dict)),
                ("sharp_action_alerts", models.JSONField(default=dict)),
                ("line_movements", models.JSONField(default=dict)),
                ("top_plays", models.JSONField(default=list)),
                ("agents_run", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                ("generation_time_seconds", models.FloatField(default=0.0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sports Betting Brief",
                "verbose_name_plural": "Sports Betting Briefs",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["-brief_date"], name="core_sports_brief_d_d67405_idx"
                    ),
                    models.Index(
                        fields=["-generated_at"], name="core_sports_generat_b9459f_idx"
                    ),
                ],
            },
        ),
    ]
