# Generated by Django 5.0.6 on 2026-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0244_session_1006_register_market_agents"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpiderAggregation",
        ),
        migrations.DeleteModel(
            name="TrendDataPoint",
        ),
        migrations.AddField(
            model_name="initiative",
            name="blocking_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Session 1016: Why this initiative is blocked/stalled",
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="next_action",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Session 1016: Concrete next action for this initiative",
            ),
        ),
    ]
