# Generated by Django 5.0.6 on 2026-02-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0247_audit_remediation_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalcluster",
            name="intent_score",
            field=models.FloatField(
                default=0.0, help_text="0-1: commercial/actionable potential"
            ),
        ),
        migrations.AddField(
            model_name="signalcluster",
            name="reach_score",
            field=models.FloatField(
                default=0.0, help_text="0-1: viral/audience potential"
            ),
        ),
        migrations.AddField(
            model_name="signalcluster",
            name="replicability_score",
            field=models.FloatField(
                default=0.0, help_text="0-1: can we act on this repeatedly"
            ),
        ),
        migrations.AddField(
            model_name="signalcluster",
            name="source_confidence",
            field=models.FloatField(
                default=0.0, help_text="0-1: trustworthiness of sources"
            ),
        ),
        migrations.AddField(
            model_name="signalcluster",
            name="track",
            field=models.CharField(
                choices=[
                    ("attention", "Attention Radar"),
                    ("intent", "Intent Engine"),
                    ("unclassified", "Unclassified"),
                ],
                default="unclassified",
                help_text="Pipeline track: attention (content) or intent (micro-products)",
                max_length=20,
            ),
        ),
    ]
