# Generated by Django 5.0.6 on 2026-02-19 23:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0248_signalcluster_scoring_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unifieduser",
            name="customer_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("viewer", "Viewer"),
                    ("user", "User"),
                    ("org_admin", "Org Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="scope",
            field=models.CharField(
                choices=[
                    ("system", "System-wide"),
                    ("provider", "Per Provider"),
                    ("agent", "Per Agent"),
                    ("tenant", "Per Tenant"),
                    ("user", "Per User"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("pro", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "monthly_cost_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Hard cap in USD for the current billing period",
                        max_digits=10,
                    ),
                ),
                (
                    "monthly_cost_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "cost_period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"max_agents": 5, "daily_tasks": 50}',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_tenants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_executions",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="costtracking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cost_records_by_tenant",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="enhanceduserprofile",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="unifieduser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.tenant",
            ),
        ),
    ]
