# Generated by Django 5.0.6 on 2026-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0249_session_1039_tenant_model_and_customer_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiative",
            name="human_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Session 1043: Human-friendly ID (e.g., INIT-000001)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="seq_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Session 1043: Sequential human-friendly ID number",
                null=True,
                unique=True,
            ),
        ),
    ]
