# Generated by Django 5.0.6 on 2026-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0251_backfill_initiative_human_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentknowledgesource",
            name="knowledge_type",
            field=models.CharField(
                choices=[
                    ("trend", "Trend Data"),
                    ("market", "Market Intelligence"),
                    ("opportunity", "Opportunity"),
                    ("competitor", "Competitor Info"),
                    ("pricing", "Pricing Data"),
                    ("user_behavior", "User Behavior"),
                    ("content_idea", "Content Ideas"),
                    ("tool_discovery", "Tool Discovery"),
                    ("collaborative_insight", "Collaborative Insight"),
                ],
                max_length=50,
            ),
        ),
    ]
