# Generated by Django 5.0.6 on 2026-02-21 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0252_add_collaborative_insight_knowledge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiativeactionitem",
            name="source_stage",
            field=models.ForeignKey(
                blank=True,
                help_text="The pipeline stage whose document generated this action item",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_items",
                to="core.initiativestage",
            ),
        ),
    ]
