# Generated by Django 5.0.6 on 2026-02-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0253_session_1058_action_item_source_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("digital_product", "Digital Product"),
                    ("freelance", "Freelance Service"),
                    ("content", "Content Creation"),
                    ("template", "Template/Asset"),
                    ("course", "Course/Education"),
                    ("software", "Software/Tool"),
                    ("consulting", "Consulting"),
                    ("affiliate", "Affiliate Marketing"),
                    ("sports_betting", "Sports Betting"),
                    ("trading", "Trading/Investment"),
                ],
                help_text="Category for content creation opportunity",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["is_processed", "created_at"], name="spiderdata_proc_created"
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["spider_name", "created_at"], name="spiderdata_spider_created"
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["data_type", "created_at"], name="spiderdata_type_created"
            ),
        ),
    ]
