# Generated by Django 5.0.6 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0254_spiderdata_composite_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytaskevent",
            name="rss_mb_start",
            field=models.FloatField(blank=True, help_text="RSS in MB when task began", null=True),
        ),
        migrations.AddField(
            model_name="celerytaskevent",
            name="rss_mb_end",
            field=models.FloatField(blank=True, help_text="RSS in MB when task finished", null=True),
        ),
        migrations.AddField(
            model_name="celerytaskevent",
            name="rss_delta_mb",
            field=models.FloatField(blank=True, help_text="RSS growth during task (end - start)", null=True),
        ),
    ]
