# Generated by Django 5.0.6 on 2026-02-24 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_artifacts(apps, schema_editor):
    """Mark all existing approved/implemented artifacts as classified=True."""
    ExtractedArtifact = apps.get_model('core', 'ExtractedArtifact')
    count = ExtractedArtifact.objects.filter(
        status__in=['approved', 'implemented']
    ).update(classified=True)
    if count:
        print(f"  Grandfathered {count} existing approved/implemented artifacts as classified")


def reverse_grandfather(apps, schema_editor):
    """Reverse: mark all as unclassified."""
    ExtractedArtifact = apps.get_model('core', 'ExtractedArtifact')
    ExtractedArtifact.objects.filter(classified=True).update(classified=False)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0255_celerytaskevent_memory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedartifact",
            name="classification",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Decision gate answers: what_is_this, who_is_it_for, data_allowed, phase_approved",
            ),
        ),
        migrations.AddField(
            model_name="extractedartifact",
            name="classified",
            field=models.BooleanField(
                default=False,
                help_text="Whether this artifact has been classified via decision gate",
            ),
        ),
        migrations.AddField(
            model_name="extractedartifact",
            name="classified_at",
            field=models.DateTimeField(
                blank=True, help_text="When the artifact was classified", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractedartifact",
            name="classified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who classified this artifact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classified_artifacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="data_scope",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Session 1070: What data is allowed? (public_only/internal_ops/api_data/user_data/all)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="initiative",
            name="target_audience",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Session 1070: Who is this for? (platform/end_users/founder/agents/public)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="extractedartifact",
            index=models.Index(
                fields=["status", "classified"], name="core_extrac_status_f0c3d4_idx"
            ),
        ),
        # Data migration: grandfather existing approved/implemented artifacts
        migrations.RunPython(grandfather_existing_artifacts, reverse_grandfather),
    ]
