# Generated by Django 5.0.6 on 2026-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0257_mobile_push_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "Web App"),
                    ("mobile", "Mobile App"),
                    ("discord", "Discord"),
                    ("api", "API"),
                    ("claude-code", "Claude Code"),
                    ("pa", "Personal Assistant"),
                ],
                db_index=True,
                default="web",
                help_text="Actor who posted this message (user via web/mobile, claude-code, pa)",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="chatconversation",
            name="platform",
            field=models.CharField(
                choices=[
                    ("web", "Web App"),
                    ("discord", "Discord"),
                    ("api", "API"),
                    ("mobile", "Mobile App"),
                ],
                db_index=True,
                default="web",
                help_text="Platform where this message originated",
                max_length=20,
            ),
        ),
    ]
