# Generated by Django 5.0.6 on 2026-02-25 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0258_add_source_to_chatconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("awaiting_approval", "Awaiting Approval"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "repo_url",
                    models.URLField(
                        default="https://github.com/clwest/donkey-betz-platform",
                        help_text="Always pinned to settings.EXECUTOR_REPO_URL in single-repo mode",
                    ),
                ),
                (
                    "base_branch",
                    models.CharField(
                        default="main",
                        help_text="Branch to clone from (always main in single-repo mode)",
                        max_length=100,
                    ),
                ),
                (
                    "working_branch",
                    models.CharField(
                        blank=True,
                        help_text="Auto-created branch: executor/<run_id>-<slug>",
                        max_length=200,
                    ),
                ),
                (
                    "plan_json",
                    models.JSONField(
                        default=list,
                        help_text="Ordered list of plan steps: [{command, description, tier}, ...]",
                    ),
                ),
                (
                    "plan_summary",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable summary of what this run does",
                    ),
                ),
                (
                    "blocked_steps",
                    models.JSONField(
                        default=list, help_text="Steps blocked by Tier C policy"
                    ),
                ),
                (
                    "approval_required_steps",
                    models.JSONField(
                        default=list, help_text="Steps requiring Tier B approval"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "log_text",
                    models.TextField(
                        blank=True,
                        help_text="Combined stdout/stderr from all executed steps",
                    ),
                ),
                (
                    "diff_patch",
                    models.TextField(
                        blank=True, help_text="git diff output after execution"
                    ),
                ),
                (
                    "changed_files",
                    models.JSONField(
                        default=list,
                        help_text="List of changed file paths from git status",
                    ),
                ),
                (
                    "test_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional: parsed test results",
                    ),
                ),
                ("steps_completed", models.IntegerField(default=0)),
                ("steps_total", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "conversation_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Collaboration protocol conversation to post updates to",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who approved Tier B steps",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_executor_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executor_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "executor_runs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="executor_ru_status_1a069c_idx",
                    ),
                    models.Index(
                        fields=["created_by", "-created_at"],
                        name="executor_ru_created_dd891c_idx",
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="executor_ru_convers_757b13_idx",
                    ),
                ],
            },
        ),
    ]
