# Generated by Django 5.0.6 on 2026-02-25 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0259_add_execution_run_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable repo name (e.g. "donkey-betz-platform")',
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("repo_url", models.URLField(help_text="Git clone URL", unique=True)),
                (
                    "default_base_branch",
                    models.CharField(
                        default="main",
                        help_text="Default branch to clone from",
                        max_length=100,
                    ),
                ),
                (
                    "allowed_base_branches",
                    models.JSONField(
                        default=list,
                        help_text="Branches allowed as base for executor runs",
                    ),
                ),
                (
                    "protected_branches",
                    models.JSONField(
                        default=list,
                        help_text="Branches that cannot be pushed to directly",
                    ),
                ),
                (
                    "policy_profile",
                    models.CharField(
                        default="moderate",
                        help_text="Policy profile name (moderate = Tier A/B/C)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "executor_repos",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="executionrun",
            name="repo",
            field=models.ForeignKey(
                blank=True,
                help_text="Registry repo (null for runs created before repo registry)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="core.repo",
            ),
        ),
    ]
