# Generated by Django 5.0.6 on 2026-02-27 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0263_register_missing_agentmap_agents"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=80)),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("request_body", models.JSONField(default=dict)),
                ("response_summary", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cockpit_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="core_cockpi_action_e6ac5b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_cockpi_user_id_13cbd8_idx",
                    ),
                ],
            },
        ),
    ]
