# Generated by Django 5.0.6 on 2026-02-27 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0264_cockpit_audit_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitAgentState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("paused_reason", models.TextField(blank=True, default="")),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                (
                    "max_runs_per_hour",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cockpit Agent State",
                "verbose_name_plural": "Cockpit Agent States",
            },
        ),
    ]
