# Generated by Django 5.0.6 on 2026-02-27 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0265_cockpit_agent_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="CockpitAutopilotPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=80, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=False)),
                ("thresholds", models.JSONField(default=dict)),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("max_actions_per_run", models.PositiveIntegerField(default=5)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="CockpitAutopilotEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mode", models.CharField(max_length=20)),
                ("proposed_action", models.CharField(max_length=80)),
                ("target_type", models.CharField(blank=True, max_length=60)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True, default="")),
                ("executed", models.BooleanField(default=False)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.cockpitautopilotpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
