# Generated by Django 5.0.6 on 2026-03-01 03:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0041_talking_character_video_type"),
        ("core", "0269_pa_tool_insight_ttl_consistency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitorComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("competitor_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "review_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What they built, with evidence",
                    ),
                ),
                (
                    "comparison_table_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Side-by-side comparison rows",
                    ),
                ),
                (
                    "gap_backlog_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Gaps + acceptance tests"
                    ),
                ),
                (
                    "tools_stack_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Extracted tools/stack"
                    ),
                ),
                (
                    "evidence_json",
                    models.JSONField(
                        blank=True, default=list, help_text="All evidence chunks used"
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "generated_by",
                    models.CharField(
                        choices=[
                            ("PA", "Personal Assistant"),
                            ("API", "API"),
                            ("manual", "Manual"),
                        ],
                        default="PA",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Token costs, timing, etc."
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source document used for RAG evidence extraction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor_comparisons",
                        to="content.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_competitor_comparison",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_compet_status_a73b12_idx",
                    ),
                    models.Index(
                        fields=["competitor_name", "-created_at"],
                        name="core_compet_competi_351348_idx",
                    ),
                ],
            },
        ),
    ]
