# Generated by Django 5.0.6 on 2026-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0272_add_data_sensitivity_and_pinned_to_deliverable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(
                fields=["data_sensitivity", "-created_at"],
                name="core_delive_data_se_f1ad1c_idx",
            ),
        ),
    ]
