# Generated by Django 5.0.6 on 2026-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0273_deliverable_core_delive_data_se_f1ad1c_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitorcomparison",
            name="executive_summary_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Verdict, top advantages/gaps/quick wins",
            ),
        ),
        migrations.AddField(
            model_name="competitorcomparison",
            name="quality_rubric_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Score breakdown: coverage, diversity, recency",
            ),
        ),
        migrations.AddField(
            model_name="competitorcomparison",
            name="sources_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Source provenance: [{title, source_type, document_id}]",
            ),
        ),
        migrations.AlterField(
            model_name="competitorcomparison",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("needs_sources", "Needs More Sources"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
