# Generated by Django 5.0.6 on 2026-03-01 06:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0274_competitor_comparison_sources_summary_rubric"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_key",
                    models.CharField(
                        choices=[("source_pack_comparison", "Source Pack Comparison")],
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collecting", "Collecting Sources"),
                            ("ingesting", "Ingesting Documents"),
                            ("embedding", "Embedding Documents"),
                            ("generating", "Generating Comparison"),
                            ("exporting", "Exporting Deliverable"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=40)),
                ("percent", models.IntegerField(default=0)),
                (
                    "stage_detail",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "input_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Workflow input parameters"
                    ),
                ),
                (
                    "output_json",
                    models.JSONField(
                        blank=True, default=dict, help_text="Accumulated artifact IDs"
                    ),
                ),
                (
                    "events_json",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{timestamp, stage, message}]",
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_workflow_run",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_workfl_status_53726e_idx",
                    ),
                    models.Index(
                        fields=["workflow_key", "-created_at"],
                        name="core_workfl_workflo_a0a674_idx",
                    ),
                ],
            },
        ),
    ]
