# Generated by Django 5.0.6 on 2026-03-02 00:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0276_opportunity_potential_revenue_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("ops_loop", "Ops Loop"),
                            ("smoke_test", "Smoke Test"),
                            ("deploy_verify", "Deploy Verify"),
                            ("manual", "Manual"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("beat", "Beat"),
                            ("pa_tool", "PA Tool"),
                            ("management_cmd", "Management Cmd"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(default=dict)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("fail_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="OpsRunEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("step_start", "Step Start"),
                            ("step_pass", "Step Pass"),
                            ("step_fail", "Step Fail"),
                            ("info", "Info"),
                            ("heartbeat", "Heartbeat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.opsrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
