# Generated by Django 5.0.6 on 2026-03-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0277_ops_runs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opsrun",
            name="run_type",
            field=models.CharField(
                choices=[
                    ("ops_loop", "Ops Loop"),
                    ("smoke_test", "Smoke Test"),
                    ("deploy_verify", "Deploy Verify"),
                    ("manual", "Manual"),
                    ("llm_routing", "LLM Routing"),
                ],
                max_length=40,
            ),
        ),
    ]
