# Generated by Django 5.0.6 on 2026-03-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0278_add_llm_routing_to_opsrun_run_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentControlEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("blocked", "Blocked"), ("enabled", "Enabled")],
                        default="enabled",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("blocked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blocked_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who blocked: 'system', 'rigby', 'claude-code', etc.",
                        max_length=100,
                    ),
                ),
                (
                    "ttl_hours",
                    models.IntegerField(
                        blank=True,
                        help_text="Auto-unblock after N hours (null = permanent)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Agent Control Entry",
                "verbose_name_plural": "Agent Control Entries",
            },
        ),
    ]
