# Generated by Django 5.0.6 on 2026-03-03 02:14
# Session 1080: Seed initial blocked agents from hardcoded frozensets

from django.db import migrations
from django.utils import timezone


def seed_blocked_agents(apps, schema_editor):
    AgentControlEntry = apps.get_model('core', 'AgentControlEntry')
    now = timezone.now()

    # Only CodeGeneratorAgent is currently blocked across all 3 files
    AgentControlEntry.objects.get_or_create(
        agent_name='CodeGeneratorAgent',
        defaults={
            'status': 'blocked',
            'reason': 'No codebase access in Railway sandbox',
            'blocked_at': now,
            'blocked_by': 'system',
            'ttl_hours': None,
        }
    )


def reverse_seed(apps, schema_editor):
    AgentControlEntry = apps.get_model('core', 'AgentControlEntry')
    AgentControlEntry.objects.filter(agent_name='CodeGeneratorAgent').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0279_agent_control_entry"),
    ]

    operations = [
        migrations.RunPython(seed_blocked_agents, reverse_seed),
    ]
