# Generated by Django 5.0.6 on 2026-03-03 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0281_autopilotaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverableEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("synthesis_viewed", "Synthesis Viewed"),
                            ("deliverable_saved", "Deliverable Saved"),
                            ("deliverable_exported", "Deliverable Exported"),
                            ("shared", "Shared"),
                            ("task_created", "Task Created"),
                            ("followup_created", "Follow-up Created"),
                            ("action_taken", "Action Taken"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the event originated: pa_tool, frontend, api",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.deliverable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_deliverable_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AutopilotAction",
        ),
        migrations.AddIndex(
            model_name="deliverableevent",
            index=models.Index(
                fields=["deliverable", "-created_at"],
                name="core_delive_deliver_8041b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverableevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="core_delive_event_t_8e3ab4_idx",
            ),
        ),
    ]
