# Generated by Django 5.0.6 on 2026-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0282_deliverable_event_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliberationsession",
            name="failure_detail",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Human-readable failure detail (exception message, stage info)",
            ),
        ),
        migrations.AddField(
            model_name="deliberationsession",
            name="failure_reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "N/A"),
                    ("TIMEOUT", "Soft/hard time limit exceeded"),
                    ("LLM_UPSTREAM", "LLM provider error or rate limit"),
                    ("EMPTY_TURN", "Zero turns produced"),
                    ("TOOL_ERROR", "Tool call or spider failure"),
                    ("GATE_REJECT", "Publish gate or contract rejection"),
                    ("DRAFT_FAILED", "Draft generation failed"),
                    ("UNKNOWN", "Unclassified failure"),
                ],
                default="",
                help_text="Structured reason code when status=failed",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="deliberationsession",
            index=models.Index(
                fields=["failure_reason_code"], name="core_delibe_failure_222dcc_idx"
            ),
        ),
    ]
