# Generated by Django 5.0.6 on 2026-03-04 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0284_diagnostic_autopilot_state_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopilotaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("block_agent", "Block Agent"),
                    ("unblock_agent", "Unblock Agent"),
                    ("attention_item", "Created Attention Item"),
                    ("deploy_watch", "Deploy Watch Verdict"),
                    ("dry_run", "Dry Run (no action taken)"),
                    ("retry_deliberation", "Retry Failed Deliberation"),
                    ("content_sweep", "Content Pipeline Sweep"),
                    ("auto_resolve", "Auto-resolve Attention Item"),
                    ("content_publish", "Content Auto-Publish"),
                    ("remediate", "Auto-Remediation Applied"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="RemediationPlaybook",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signature_pattern",
                    models.CharField(
                        db_index=True,
                        help_text="Signature pattern to match (exact or prefix, e.g. TIMEOUT_PROVIDER_*)",
                        max_length=255,
                    ),
                ),
                (
                    "failure_category",
                    models.CharField(
                        db_index=True,
                        help_text="FailureSignature.Category value to match",
                        max_length=30,
                    ),
                ),
                (
                    "remediation_type",
                    models.CharField(
                        choices=[
                            ("timeout_adjust", "Adjust Agent Timeout"),
                            ("model_fallback", "Switch to Fallback LLM"),
                            ("retry_config", "Adjust Retry Configuration"),
                            ("block_and_wait", "Block Agent Until Recovery"),
                            ("queue_reroute", "Reroute to Different Queue"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text='Remediation config: {"agent": "X", "timeout_seconds": 900} etc.',
                    ),
                ),
                ("times_applied", models.PositiveIntegerField(default=0)),
                ("times_succeeded", models.PositiveIntegerField(default=0)),
                ("times_rolled_back", models.PositiveIntegerField(default=0)),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0, help_text="times_succeeded / times_applied"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "min_confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="Min success_rate needed to keep auto-applying",
                    ),
                ),
                (
                    "source_diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playbook_entries",
                        to="core.failurediagnosis",
                    ),
                ),
            ],
            options={
                "ordering": ["-success_rate", "-times_applied"],
                "indexes": [
                    models.Index(
                        fields=["failure_category", "enabled"],
                        name="core_remedi_failure_f5a174_idx",
                    ),
                    models.Index(
                        fields=["signature_pattern"],
                        name="core_remedi_signatu_8df059_idx",
                    ),
                ],
            },
        ),
    ]
