# Generated by Django 5.0.6 on 2026-03-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0285_remediation_playbook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopilotaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("block_agent", "Block Agent"),
                    ("unblock_agent", "Unblock Agent"),
                    ("attention_item", "Created Attention Item"),
                    ("deploy_watch", "Deploy Watch Verdict"),
                    ("dry_run", "Dry Run (no action taken)"),
                    ("retry_deliberation", "Retry Failed Deliberation"),
                    ("content_sweep", "Content Pipeline Sweep"),
                    ("auto_resolve", "Auto-resolve Attention Item"),
                    ("content_publish", "Content Auto-Publish"),
                    ("remediate", "Auto-Remediation Applied"),
                    ("config_tune", "Config Self-Tuning"),
                ],
                max_length=30,
            ),
        ),
    ]
