# Generated by Django 5.0.6 on 2026-03-04 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0287_autopilot_budget_freeze_action_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "impact_type",
                    models.CharField(
                        choices=[
                            ("wager_profit", "Wager Profit/Loss"),
                            ("revenue_confirmed", "Revenue Confirmed"),
                            ("content_action", "Content Action Taken"),
                            ("content_save", "Content Saved"),
                            ("content_export", "Content Exported"),
                            ("content_share", "Content Shared"),
                            ("prediction_hit", "ML Prediction Hit"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "desk",
                    models.CharField(
                        choices=[
                            ("sports", "Sports Betting"),
                            ("content", "Content Pipeline"),
                            ("research", "Research & Analysis"),
                            ("career", "Career & Jobs"),
                            ("trading", "Trading & Finance"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "value_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Dollar value (negative for losses, e.g. lost wager)",
                        max_digits=12,
                    ),
                ),
                (
                    "impact_points",
                    models.IntegerField(
                        default=0,
                        help_text="Non-monetary impact points (1=save, 2=export, 5=action_taken)",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "source_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name: Wager, Deliverable, Revenue, etc.",
                        max_length=50,
                    ),
                ),
                ("source_object_id", models.UUIDField(blank=True, null=True)),
                (
                    "trace_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Orchestration trace_id for cost attribution",
                        null=True,
                    ),
                ),
                (
                    "attributed_cost_usd",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="LLM cost attributed to this impact",
                        max_digits=10,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_impact_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["desk", "-created_at"],
                        name="core_impact_desk_1e2304_idx",
                    ),
                    models.Index(
                        fields=["agent_name", "-created_at"],
                        name="core_impact_agent_n_23dc95_idx",
                    ),
                    models.Index(
                        fields=["impact_type", "-created_at"],
                        name="core_impact_impact__3d2008_idx",
                    ),
                ],
            },
        ),
    ]
