# Generated by Django 5.0.6 on 2026-03-04 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0291_impact_credit_multi_touch_attribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "spider_data_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="SpiderData item that sourced this lead",
                    ),
                ),
                ("lead_title", models.CharField(max_length=200)),
                ("lead_source", models.CharField(blank=True, max_length=100)),
                ("lead_url", models.URLField(blank=True, max_length=500)),
                ("lead_score", models.IntegerField(default=0)),
                (
                    "offer_key",
                    models.CharField(
                        blank=True,
                        help_text="Which offer template was used (e.g. 'ai_automation', 'content_engine')",
                        max_length=50,
                    ),
                ),
                ("subject_line", models.CharField(blank=True, max_length=200)),
                (
                    "body_text",
                    models.TextField(help_text="Draft outreach message body"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "touch_number",
                    models.IntegerField(
                        default=1,
                        help_text="Which touch in the sequence (1=initial, 2=first follow-up, etc.)",
                    ),
                ),
                (
                    "next_touch_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When next follow-up should be generated",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — pending review"),
                            ("approved", "Approved — ready to send"),
                            ("rejected", "Rejected"),
                            ("sent", "Sent"),
                            ("replied", "Got reply"),
                            ("expired", "Expired — no response after sequence"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                (
                    "edited_text",
                    models.TextField(
                        blank=True, help_text="If user edited the text before approving"
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked Opportunity record (created on approve)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_drafts",
                        to="core.opportunity",
                    ),
                ),
                (
                    "parent_draft",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous draft in this sequence",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="core.outreachdraft",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_outreach_draft",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_outrea_status_467d11_idx",
                    ),
                    models.Index(
                        fields=["spider_data_id"], name="core_outrea_spider__12a480_idx"
                    ),
                    models.Index(
                        fields=["touch_number", "status"],
                        name="core_outrea_touch_n_e2eb2e_idx",
                    ),
                ],
            },
        ),
    ]
