# Generated by Django 5.0.6 on 2026-03-04 04:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0292_outreach_draft_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClosePack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offer_key",
                    models.CharField(
                        help_text="Which offer template (e.g. 'ai_automation', 'content_engine', 'analytics_dashboard')",
                        max_length=50,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Quoted price in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "timeline_days",
                    models.IntegerField(
                        default=14, help_text="Estimated delivery timeline in days"
                    ),
                ),
                (
                    "proposal_text",
                    models.TextField(
                        blank=True,
                        help_text="1-page proposal: scope, timeline, price, assumptions",
                    ),
                ),
                (
                    "contract_text",
                    models.TextField(
                        blank=True, help_text="SOW/MSA-lite contract draft"
                    ),
                ),
                (
                    "invoice_text",
                    models.TextField(
                        blank=True, help_text="Invoice draft: line items, payment terms"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — pending review"),
                            ("approved", "Approved — ready to send"),
                            ("sent", "Sent to prospect"),
                            ("won", "Deal won"),
                            ("lost", "Deal lost"),
                            ("expired", "Expired — no response"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("edited_proposal", models.TextField(blank=True)),
                ("edited_contract", models.TextField(blank=True)),
                ("edited_invoice", models.TextField(blank=True)),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "followup_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to follow up if no response",
                        null=True,
                    ),
                ),
                ("followup_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="close_packs",
                        to="core.opportunity",
                    ),
                ),
                (
                    "outreach_draft",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked outreach draft that triggered this close pack",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="close_packs",
                        to="core.outreachdraft",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_close_pack",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_close__status_d5434f_idx",
                    ),
                    models.Index(
                        fields=["offer_key", "status"],
                        name="core_close__offer_k_a45bf7_idx",
                    ),
                ],
            },
        ),
    ]
