# Generated by Django 5.0.6 on 2026-03-04 04:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0293_close_pack_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prospect_name", models.CharField(blank=True, max_length=200)),
                ("prospect_company", models.CharField(blank=True, max_length=200)),
                ("prospect_role", models.CharField(blank=True, max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                            ("form", "Contact form"),
                            ("other", "Other"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("subject_line", models.CharField(blank=True, max_length=300)),
                ("message_text", models.TextField(help_text="Inbound message content")),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("positive", "Positive — interested, wants more info"),
                            ("neutral", "Neutral — question or clarification"),
                            ("objection", "Objection — price, timing, scope concern"),
                            ("meeting", "Meeting — wants to schedule a call"),
                            ("unsubscribe", "Unsubscribe — opt-out request"),
                            ("unknown", "Unknown — could not classify"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the engagement"
                    ),
                ),
                (
                    "extracted_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted: company, role, need, budget_cues, timeline_cues",
                    ),
                ),
                (
                    "suggested_action",
                    models.CharField(
                        blank=True,
                        help_text="AI-suggested next step (e.g. 'send_close_pack', 'book_call')",
                        max_length=100,
                    ),
                ),
                (
                    "draft_reply",
                    models.TextField(
                        blank=True, help_text="Draft reply text for approval"
                    ),
                ),
                (
                    "edited_reply",
                    models.TextField(
                        blank=True,
                        help_text="Human-edited reply text (overrides draft)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unread", "Unread — new signal"),
                            ("classified", "Classified — awaiting action"),
                            ("needs_reply", "Needs reply — draft pending approval"),
                            ("actioned", "Actioned — replied or routed"),
                            ("disqualified", "Disqualified"),
                            ("closed", "Closed — no further action"),
                        ],
                        db_index=True,
                        default="unread",
                        max_length=20,
                    ),
                ),
                ("disqualify_reason", models.CharField(blank=True, max_length=300)),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "suppressed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Permanently suppressed (unsubscribe/opt-out)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements",
                        to="core.opportunity",
                    ),
                ),
                (
                    "outreach_draft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements",
                        to="core.outreachdraft",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_engagement_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_engage_status_d2c5bf_idx",
                    ),
                    models.Index(
                        fields=["intent", "status"],
                        name="core_engage_intent_04ce0c_idx",
                    ),
                    models.Index(
                        fields=["channel", "-created_at"],
                        name="core_engage_channel_560133_idx",
                    ),
                ],
            },
        ),
    ]
