# Generated by Django 5.0.6 on 2026-03-04 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0294_engagement_event_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("duration_minutes", models.IntegerField(default=30)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("zoom", "Zoom"),
                            ("meet", "Google Meet"),
                            ("teams", "Microsoft Teams"),
                            ("phone", "Phone call"),
                            ("in_person", "In person"),
                            ("other", "Other"),
                        ],
                        default="zoom",
                        max_length=20,
                    ),
                ),
                ("meeting_link", models.URLField(blank=True, max_length=500)),
                (
                    "attendees",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of attendee dicts: [{name, email, role}]",
                    ),
                ),
                ("prospect_name", models.CharField(blank=True, max_length=200)),
                ("prospect_company", models.CharField(blank=True, max_length=200)),
                ("prospect_role", models.CharField(blank=True, max_length=200)),
                (
                    "brief_text",
                    models.TextField(
                        blank=True, help_text="Auto-generated pre-call brief"
                    ),
                ),
                ("brief_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Meeting notes / outcome summary"
                    ),
                ),
                (
                    "recap_draft",
                    models.TextField(
                        blank=True, help_text="Draft recap email for approval"
                    ),
                ),
                (
                    "next_steps",
                    models.TextField(
                        blank=True, help_text="Agreed next steps from the meeting"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        help_text="Meeting outcome: interested, needs_followup, not_a_fit, deal_agreed",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("briefed", "Brief generated"),
                            ("completed", "Meeting completed"),
                            ("no_show", "No-show"),
                            ("cancelled", "Cancelled"),
                            ("followed_up", "Follow-up sent"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="core.engagementevent",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="core.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_meeting",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="core_meetin_status_9390de_idx",
                    ),
                    models.Index(
                        fields=["-scheduled_at"], name="core_meetin_schedul_15ae80_idx"
                    ),
                ],
            },
        ),
    ]
