# Generated by Django 5.0.6 on 2026-03-04 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0295_meeting_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="KillSwitch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("scheduler", "Pause all schedulers"),
                            ("queue", "Pause specific queue"),
                            ("agent_family", "Block agent family by tag"),
                            ("publishing", "Halt publishing"),
                            ("outbound", "Halt outbound messages"),
                            ("deploys", "Halt deploys"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_detail",
                    models.CharField(
                        blank=True,
                        help_text="Queue name, agent tag, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Why this kill switch was activated"
                    ),
                ),
                (
                    "activated_by",
                    models.CharField(
                        blank=True,
                        help_text="Who activated: user, autopilot, SLO_breach",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Auto-deactivate after this time (required — no permanent kill switches)",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_kill_switch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("agent", "Per-Agent"),
                            ("desk", "Per-Desk"),
                        ],
                        db_index=True,
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "scope_target",
                    models.CharField(
                        blank=True,
                        help_text="Agent name or desk name (empty for global)",
                        max_length=200,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("throttle", "Throttle"),
                            ("freeze", "Freeze"),
                            ("safe_mode", "Safe Mode"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Why this mode was set"),
                ),
                (
                    "set_by",
                    models.CharField(
                        blank=True,
                        help_text="Who/what set this mode (user, autopilot, kill_switch)",
                        max_length=100,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-revert to normal after this time (null = permanent until changed)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_governance_state",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "scope_target"],
                        name="core_govern_scope_a94788_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="governancestate",
            constraint=models.UniqueConstraint(
                fields=("scope", "scope_target"), name="unique_governance_scope_target"
            ),
        ),
        migrations.AddIndex(
            model_name="killswitch",
            index=models.Index(
                fields=["target", "is_active"], name="core_kill_s_target_8395f7_idx"
            ),
        ),
    ]
