# Generated by Django 5.0.6 on 2026-03-06 05:43

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0299_llmcalllog_trace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmcalllog",
            name="trace_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="PA request trace ID for joining LLM calls to Celery tasks",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CongressMember",
            fields=[
                (
                    "bioguide_id",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("party", models.CharField(max_length=50)),
                ("chamber", models.CharField(max_length=20)),
                ("state", models.CharField(max_length=2)),
                ("district", models.IntegerField(blank=True, null=True)),
                ("in_office", models.BooleanField(default=True)),
                ("profile_url", models.URLField(blank=True)),
                ("photo_url", models.URLField(blank=True)),
                ("terms", models.JSONField(default=list)),
                ("committees", models.JSONField(default=list)),
                ("leadership_role", models.CharField(blank=True, max_length=200)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["state", "last_name"],
                "indexes": [
                    models.Index(
                        fields=["state", "chamber"], name="core_congre_state_af0d5b_idx"
                    ),
                    models.Index(fields=["party"], name="core_congre_party_336080_idx"),
                    models.Index(
                        fields=["in_office"], name="core_congre_in_offi_df87a7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_uid",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                ("jurisdiction", models.CharField(default="federal", max_length=20)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("congress", models.IntegerField(blank=True, null=True)),
                ("bill_type", models.CharField(blank=True, max_length=10)),
                ("bill_number", models.IntegerField(blank=True, null=True)),
                ("title", models.TextField()),
                ("short_title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("plain_summary", models.TextField(blank=True)),
                ("summary_source", models.CharField(blank=True, max_length=30)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("status_date", models.DateField(blank=True, null=True)),
                ("introduced_date", models.DateField(blank=True, null=True)),
                ("chamber", models.CharField(blank=True, max_length=20)),
                ("sponsor_names", models.JSONField(default=list)),
                ("committee", models.CharField(blank=True, max_length=200)),
                ("topics", models.JSONField(default=list)),
                ("full_text_url", models.URLField(blank=True)),
                ("congress_gov_url", models.URLField(blank=True)),
                ("legiscan_url", models.URLField(blank=True)),
                (
                    "legiscan_bill_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=20)),
                ("last_action", models.TextField(blank=True)),
                ("last_action_date", models.DateField(blank=True, null=True)),
                ("embedding_text", models.TextField(blank=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("source_urls", models.JSONField(default=list)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sponsors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sponsored_bills",
                        to="core.congressmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RollCallVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("congress", models.IntegerField()),
                ("chamber", models.CharField(max_length=20)),
                ("roll_number", models.IntegerField()),
                ("session", models.IntegerField(default=1)),
                ("date", models.DateField()),
                ("question", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("result", models.CharField(max_length=50)),
                ("yea_count", models.IntegerField(default=0)),
                ("nay_count", models.IntegerField(default=0)),
                ("not_voting_count", models.IntegerField(default=0)),
                ("present_count", models.IntegerField(default=0)),
                ("source_url", models.URLField(blank=True)),
                ("last_fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roll_calls",
                        to="core.bill",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-roll_number"],
            },
        ),
        migrations.CreateModel(
            name="VotePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Yea", "Yea"),
                            ("Nay", "Nay"),
                            ("Present", "Present"),
                            ("Not Voting", "Not Voting"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="core.congressmember",
                    ),
                ),
                (
                    "roll_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.rollcallvote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("heading", models.CharField(blank=True, max_length=300)),
                ("text", models.TextField()),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="core.bill",
                    ),
                ),
            ],
            options={
                "ordering": ["bill", "chunk_index"],
                "unique_together": {("bill", "chunk_index")},
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["congress", "bill_type", "bill_number"],
                name="core_bill_congres_c37f50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["jurisdiction", "state"], name="core_bill_jurisdi_b233d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="core_bill_status_5e1525_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["-updated_at"], name="core_bill_updated_05a687_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rollcallvote",
            index=models.Index(fields=["-date"], name="core_rollca_date_47d7a1_idx"),
        ),
        migrations.AddIndex(
            model_name="rollcallvote",
            index=models.Index(fields=["bill"], name="core_rollca_bill_id_89c574_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="rollcallvote",
            unique_together={("congress", "chamber", "roll_number", "session")},
        ),
        migrations.AddIndex(
            model_name="voteposition",
            index=models.Index(
                fields=["member", "position"], name="core_votepo_member__9ef0bf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="voteposition",
            unique_together={("roll_call", "member")},
        ),
    ]
