# Generated by Django 5.0.6 on 2026-03-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0300_government_legislation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentexecution",
            name="last_heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
