# Generated by Django 5.0.6 on 2026-03-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0302_throttle_polling_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionrun",
            name="commit_sha",
            field=models.CharField(
                blank=True,
                help_text="Final commit SHA on the working branch",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="error_type",
            field=models.CharField(
                blank=True,
                help_text="Error classification (e.g. TimeoutError, CloneError)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="failure_reason_code",
            field=models.CharField(
                blank=True,
                help_text="Structured failure code: TESTS_FAILED, CLONE_AUTH, TIMEOUT, OOM, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="pr_number",
            field=models.IntegerField(
                blank=True, help_text="GitHub PR number", null=True
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="pr_url",
            field=models.URLField(
                blank=True, help_text="GitHub PR URL if one was created"
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="progress",
            field=models.FloatField(
                default=0.0, help_text="Execution progress 0.0 to 1.0"
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="github_installation_id",
            field=models.CharField(
                blank=True,
                help_text="GitHub App installation ID for this repo.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="install_command",
            field=models.CharField(
                blank=True,
                help_text='Override install command (e.g. "pip install -r requirements.txt").',
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="lint_command",
            field=models.CharField(
                blank=True,
                help_text='Override lint command (e.g. "ruff check ."). Empty = auto-detect.',
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="max_patch_files",
            field=models.IntegerField(
                default=50, help_text="Max files a single job can modify."
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="max_runtime_seconds",
            field=models.IntegerField(
                default=600,
                help_text="Default wall-clock timeout for code jobs on this repo.",
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="path_filters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Allowed subdirs for monorepo scope.",
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="test_command",
            field=models.CharField(
                blank=True,
                help_text='Override test command (e.g. "pytest"). Empty = auto-detect.',
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="executionrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("running", "Running"),
                    ("cloning", "Cloning"),
                    ("implementing", "Implementing"),
                    ("testing", "Testing"),
                    ("linting", "Linting"),
                    ("pushing", "Pushing"),
                    ("awaiting_approval", "Awaiting Approval"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("error", "Error"),
                    ("canceled", "Canceled"),
                ],
                db_index=True,
                default="queued",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CodeJobLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sequence",
                    models.IntegerField(
                        help_text="Monotonically increasing log line number within this run"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="info", max_length=10)),
                (
                    "step",
                    models.CharField(
                        help_text="Pipeline step (clone, implement, test, lint, push, pr)",
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_logs",
                        to="core.executionrun",
                    ),
                ),
            ],
            options={
                "db_table": "executor_job_logs",
                "ordering": ["sequence"],
                "indexes": [
                    models.Index(
                        fields=["run", "sequence"], name="executor_jo_run_id_5cd96f_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="codejoblog",
            constraint=models.UniqueConstraint(
                fields=("run", "sequence"), name="unique_run_log_sequence"
            ),
        ),
    ]
