# Generated by Django 5.0.6 on 2026-03-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0303_add_code_worker_fields_and_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionrun",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Celery task ID for the code worker job",
                max_length=100,
            ),
        ),
    ]
