# Generated by Django 5.0.6 on 2026-03-10 02:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0305_add_user_watchlist_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningReadbackEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("trace_id", models.CharField(db_index=True, max_length=100)),
                (
                    "message_snippet",
                    models.CharField(
                        help_text="First 200 chars of user message (for debugging)",
                        max_length=200,
                    ),
                ),
                ("intent", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "routed_to",
                    models.CharField(
                        blank=True,
                        help_text="Tool/agent that was selected",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "learning_consulted",
                    models.BooleanField(
                        default=False, help_text="Whether UserAgentLearning was queried"
                    ),
                ),
                (
                    "learning_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether learning actually changed the routing decision",
                    ),
                ),
                (
                    "learning_record_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UUIDs of UserAgentLearning records that were consulted",
                    ),
                ),
                (
                    "learning_explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable explanation of learning influence",
                    ),
                ),
                (
                    "tool_ok",
                    models.BooleanField(
                        help_text="Whether the tool execution succeeded", null=True
                    ),
                ),
                (
                    "latency_ms",
                    models.IntegerField(help_text="Tool execution latency", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_readback_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="core_learni_user_id_6e6189_idx",
                    ),
                    models.Index(
                        fields=["learning_used", "-created_at"],
                        name="core_learni_learnin_30575f_idx",
                    ),
                ],
            },
        ),
    ]
