# Generated by Django 5.0.6 on 2026-03-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0308_preview_system_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace that produced or owns this deliverable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliverables",
                to="core.projectworkspace",
            ),
        ),
    ]
