# Generated by Django 5.0.6 on 2026-03-18 01:13
# Session 1077: Fix initiative owner_id column type from integer to UUID
# The FK was created as integer but core_unifieduser.id is UUID

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0309_deliverable_workspace_fk"),
    ]

    operations = [
        # Step 1: Drop the FK constraint
        migrations.RunSQL(
            sql="ALTER TABLE core_initiative DROP CONSTRAINT IF EXISTS core_initiative_owner_id_fkey;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Convert column from integer to UUID (nulls stay null, any integer values become null)
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_initiative
                ALTER COLUMN owner_id TYPE uuid
                USING CASE
                    WHEN owner_id IS NULL THEN NULL
                    ELSE NULL  -- integer values can't map to UUID, set to null
                END;
            """,
            reverse_sql="ALTER TABLE core_initiative ALTER COLUMN owner_id TYPE integer USING NULL;",
        ),
        # Step 3: Re-add the FK constraint
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_initiative
                ADD CONSTRAINT core_initiative_owner_id_fkey
                FOREIGN KEY (owner_id) REFERENCES core_unifieduser(id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="ALTER TABLE core_initiative DROP CONSTRAINT IF EXISTS core_initiative_owner_id_fkey;",
        ),
    ]
