# Generated by Django 5.0.6 on 2026-03-26 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0310_fix_initiative_owner_column_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this conversation is bound to (set when started from a workspace)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="core.projectworkspace",
            ),
        ),
        migrations.AlterField(
            model_name="initiative",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Session 996: Human owner responsible for this initiative",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_initiatives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
