# Generated by Django 5.0.6 on 2026-03-26 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0311_add_workspace_to_chatconversation"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this opportunity belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="opportunitytask",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Inherited from parent opportunity's workspace",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity_tasks",
                to="core.projectworkspace",
            ),
        ),
    ]
