# Generated by Django 5.0.6 on 2026-03-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0312_add_workspace_to_opportunity_and_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="vipinvite",
            name="prospect_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Prospect profile deliverable for personalization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vip_invites",
                to="core.deliverable",
            ),
        ),
        migrations.AddField(
            model_name="vipinvite",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                help_text="Display name for the invitee (e.g. 'Matthew Berman')",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="vipinvite",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace to scope the VIP view to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vip_invites",
                to="core.projectworkspace",
            ),
        ),
    ]
