# Generated by Django 5.0.6 on 2026-03-29 17:56

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0313_vip_invite_workspace_personalization"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin — full tool access"),
                            ("vip_viewer", "VIP Viewer — read-only workspace tools"),
                            ("customer", "Customer — standard tool access"),
                        ],
                        default="admin",
                        help_text="Controls default tool access and system prompt",
                        max_length=30,
                    ),
                ),
                (
                    "allowed_tools",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=80),
                        blank=True,
                        default=list,
                        help_text="Explicit tool whitelist. Empty = use role defaults.",
                        size=None,
                    ),
                ),
                (
                    "system_prompt_override",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Custom system prompt added to PA instructions for this user",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Name used in PA greetings (e.g. "Patrick")',
                        max_length=200,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        blank=True,
                        help_text="Scope PA to this workspace",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_profiles",
                        to="core.projectworkspace",
                    ),
                ),
            ],
        ),
    ]
