# Generated by Django 5.0.6 on 2026-04-02 21:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0315_messaging_threads_and_direct_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="", max_length=10)),
                (
                    "category",
                    models.CharField(db_index=True, default="general", max_length=50),
                ),
                (
                    "pipeline_stages",
                    models.JSONField(
                        default=list,
                        help_text="Ordered pipeline stages with agent assignments and automation flags",
                    ),
                ),
                (
                    "agent_pool",
                    models.JSONField(
                        default=list,
                        help_text="List of agent names available for this workspace type",
                    ),
                ),
                (
                    "spider_subscriptions",
                    models.JSONField(
                        default=list,
                        help_text="Spider names this workspace type subscribes to",
                    ),
                ),
                (
                    "deliverable_categories",
                    models.JSONField(
                        default=list,
                        help_text="Deliverable categories pre-configured for this workspace",
                    ),
                ),
                (
                    "default_settings",
                    models.JSONField(
                        default=dict,
                        help_text="Default configuration applied when creating a workspace from this template",
                    ),
                ),
                (
                    "default_quotas",
                    models.JSONField(
                        default=dict,
                        help_text="Resource limits applied to workspaces created from this template",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workspace_templates",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkspaceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "Setting Up"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("pipeline_config", models.JSONField(default=list)),
                ("agent_pool", models.JSONField(default=list)),
                ("spider_subscriptions", models.JSONField(default=list)),
                ("deliverable_categories", models.JSONField(default=list)),
                ("settings", models.JSONField(default=dict)),
                ("quotas", models.JSONField(default=dict)),
                (
                    "governance_mode",
                    models.CharField(
                        blank=True,
                        help_text="Override global governance mode for this workspace (null = inherit global)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "metrics_snapshot",
                    models.JSONField(
                        default=dict,
                        help_text="Cached workspace metrics: deliverable counts, agent runs, costs, etc.",
                    ),
                ),
                ("metrics_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="core.projectworkspace",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="core.workspacetemplate",
                    ),
                ),
            ],
            options={
                "db_table": "workspace_configs",
            },
        ),
    ]
