# Generated by Django 5.0.6 on 2026-04-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0318_pipeline_run_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspaceconfig",
            name="workspace_brief",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"topic": "...", "audience": "...", "tone": "...", "key_sources": [...], "focus_areas": [...], "notes": "..."}',
            ),
        ),
    ]
