# Generated by Django 5.0.6 on 2026-04-04 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


STAGE_TO_ROLE = {
    'Topic Mining': 'research',
    'Deep Research': 'research',
    'Content Strategy': 'strategy',
    'Write Draft': 'draft',
    'Edit & Polish': 'edit_review',
    'Fact Check': 'fact_check',
    'Final Rewrite': 'rewrite',
    'SEO & Headlines': 'seo',
    'Hooks & Distribution': 'distribution',
    'Workspace Brief': 'brief',
}

PRIMARY_ROLES = {'rewrite', 'draft'}  # rewrite preferred, draft as fallback


def backfill_packets(apps, schema_editor):
    """Group existing pipeline deliverables into content packets."""
    Deliverable = apps.get_model('core', 'Deliverable')
    ContentPacket = apps.get_model('core', 'ContentPacket')
    ContentPacketItem = apps.get_model('core', 'ContentPacketItem')
    PipelineRun = apps.get_model('core', 'PipelineRun')

    # Find all pipeline runs that produced deliverables
    runs = PipelineRun.objects.all().order_by('-created_at')

    for run in runs:
        run_id = str(run.id)
        workspace = run.workspace

        # Find deliverables from this run (stored in metadata.pipeline_run_id)
        deliverables = Deliverable.objects.filter(
            workspace=workspace,
            metadata__pipeline_run_id=run_id,
        ).order_by('created_at')

        if not deliverables.exists():
            continue

        # Derive packet title from the first deliverable's title
        first = deliverables.first()
        topic = ''
        if first and first.metadata and isinstance(first.metadata, dict):
            topic = first.metadata.get('workspace_brief_topic', '')
        if not topic and first:
            # Extract from title after "Stage: "
            parts = first.title.split(': ', 1)
            topic = parts[1] if len(parts) > 1 else first.title
        topic = topic[:200] or workspace.name

        packet = ContentPacket.objects.create(
            workspace=workspace,
            pipeline_run=run,
            title=f"Newsletter: {topic}",
            status='draft',
            created_by=run.triggered_by,
        )

        has_primary = False
        for i, d in enumerate(deliverables):
            # Determine role from category
            category = d.category or ''
            stage_name = category.replace('Pipeline — ', '').replace('Pipeline — ', '')
            role = STAGE_TO_ROLE.get(stage_name, 'other')
            if role == 'other' and 'Brief' in category:
                role = 'brief'

            is_primary = (role == 'rewrite') or (role == 'draft' and not has_primary)
            if is_primary:
                has_primary = True

            ContentPacketItem.objects.create(
                packet=packet,
                deliverable=d,
                role=role,
                order=i,
                is_primary=is_primary and role in PRIMARY_ROLES,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0322_add_rewrite_stage_to_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPacket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("approved", "Approved"),
                            ("sent", "Sent"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_packet",
                        to="core.pipelinerun",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_packets",
                        to="core.projectworkspace",
                    ),
                ),
            ],
            options={
                "db_table": "core_content_packet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentPacketItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("brief", "Workspace Brief"),
                            ("research", "Research"),
                            ("strategy", "Content Strategy"),
                            ("draft", "Draft"),
                            ("edit_review", "Editor Review"),
                            ("fact_check", "Fact Check"),
                            ("rewrite", "Final Rewrite"),
                            ("seo", "SEO & Headlines"),
                            ("distribution", "Distribution Plan"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="The main deliverable (final newsletter) — shown prominently",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packet_items",
                        to="core.deliverable",
                    ),
                ),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.contentpacket",
                    ),
                ),
            ],
            options={
                "db_table": "core_content_packet_item",
                "ordering": ["order"],
                "unique_together": {("packet", "deliverable")},
            },
        ),
        migrations.RunPython(backfill_packets, migrations.RunPython.noop),
    ]
