# Generated by Django 5.0.6 on 2026-04-05 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0323_content_packets"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="conceptforgerun",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conceptforge_runs",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="contentchannel",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_channels",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="podcastshow",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="podcast_shows",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="selfblog",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogs",
                to="core.projectworkspace",
            ),
        ),
    ]
