# Generated by Django 5.0.6 on 2026-04-15 23:50
# Session 1086 PR 1: ActivePriority model for priority-aware routing
# (initiative 2dcb79d7-6f2b-4e67-a366-a54e96d7870f).

import uuid
from datetime import timedelta
from django.db import migrations, models


def seed_example_priority(apps, schema_editor):
    """
    Seed ONE short-lived example priority per Rigby's design review.

    Rationale: the seed is intentionally generic and TTL-bounded so anyone
    pulling main doesn't get surprise routing behavior. 6-hour TTL means the
    priority auto-expires the first time get_active_priorities() runs after
    6h. The seed also doubles as the smoke-test fixture for this PR.

    Team members wanting a "Content/Revenue push" priority should add it via
    the active_priority_tool PA tool rather than seeding it here — that's
    the whole point of giving Rigby ownership.
    """
    from django.utils import timezone

    ActivePriority = apps.get_model('core', 'ActivePriority')
    now = timezone.now()

    ActivePriority.objects.get_or_create(
        name='Platform hardening (Ops/Drift)',
        defaults={
            'description': (
                'Seeded in Session 1086 PR 1 as the first example priority. '
                'Short TTL (6h) so it auto-expires without surprising any dev '
                'who pulls main. Demonstrates the tag-based matching pathway.'
            ),
            'tags': ['platform', 'ops', 'routing'],
            'agent_whitelist': [],
            'agent_blacklist': [],
            'enable_keyword_match': False,
            'priority_rank': 100,
            'owner': 'system',
            'status': 'active',
            'expires_at': now + timedelta(hours=6),
        },
    )


def reverse_seed_example_priority(apps, schema_editor):
    ActivePriority = apps.get_model('core', 'ActivePriority')
    ActivePriority.objects.filter(name='Platform hardening (Ops/Drift)').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0328_schedule_experiment_cleanup_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivePriority",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Short human label, e.g. 'Platform hardening (Ops/Drift)'.",
                        max_length=120,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form intent. What is this priority trying to accomplish?",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of tag strings. Matched against derived agent tags (agent_name + Agent.category.slug + AGENT_TAG_OVERRIDES dict). Primary automatic matching mechanism.",
                    ),
                ),
                (
                    "agent_whitelist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of exact agent_name strings that ALWAYS match this priority regardless of tags. Highest precedence in the match algorithm.",
                    ),
                ),
                (
                    "agent_blacklist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of exact agent_name strings that NEVER match this priority even if tags overlap. Forces them into the mismatched lane.",
                    ),
                ),
                (
                    "enable_keyword_match",
                    models.BooleanField(
                        default=False,
                        help_text="Opt-in substring keyword match against agent_name + task. Off by default per Rigby's design review — keyword matching creates false positives ('audit' matches everything), so only enable this when the tag list is explicitly narrow.",
                    ),
                ),
                (
                    "priority_rank",
                    models.IntegerField(
                        default=100,
                        help_text="Lower = higher priority. Multiple priorities can coexist; the router treats any active match as a MATCH. Rank is for future tie-breaking in Option B (dedicated queue) routing.",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        default="rigby",
                        help_text="Who owns this priority: 'rigby', 'chris', 'system'.",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the priority was first created and made active.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional TTL expiry. If set and in the past, get_active_priorities() auto-transitions status → expired.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Active Priority",
                "verbose_name_plural": "Active Priorities",
                "ordering": ["priority_rank", "-activated_at"],
            },
        ),
        migrations.RunPython(seed_example_priority, reverse_seed_example_priority),
    ]
