# Generated by Django 5.0.6 on 2026-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0329_active_priority_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="celerytaskevent",
            name="priority_matched",
            field=models.BooleanField(
                blank=True,
                help_text="Session 1086 PR 3b: Whether PriorityRouter.check() returned matched=True. NULL means the router gate was OFF or the task was not evaluated (pre-PR-3b rows).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="celerytaskevent",
            name="priority_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the ActivePriority row that drove the decision (whitelist/blacklist/tags/keyword match). NULL for user_chat_exempt, fail_open, or no-match MISMATCH.",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="celerytaskevent",
            name="throttle_class",
            field=models.CharField(
                blank=True,
                choices=[("matched", "Matched"), ("mismatched", "Mismatched")],
                help_text="Which semaphore lane the dispatch ran in. NULL when the router gate was OFF or the task was not evaluated.",
                max_length=16,
                null=True,
            ),
        ),
    ]
