# Generated by Django 5.0.6 on 2026-04-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0331_active_priority_governance_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverableevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("synthesis_viewed", "Synthesis Viewed"),
                    ("deliverable_saved", "Deliverable Saved"),
                    ("deliverable_exported", "Deliverable Exported"),
                    ("shared", "Shared"),
                    ("task_created", "Task Created"),
                    ("followup_created", "Follow-up Created"),
                    ("action_taken", "Action Taken"),
                    ("status_transition", "Status Transition"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
