# Generated by Django 5.0.6 on 2026-04-17 05:36
# Session 1095: Rigby's architectural refinement — enum not boolean.

from django.db import migrations, models


# Keep this list in sync with core.services.deliverable_factory._PUBLISH_INTENT_BY_AGENT.
# Duplicated here because migrations can't import application code
# (would break on `makemigrations` on a fresh DB). Migration is idempotent
# and backfills existing rows for known-publishing agents; unknown agents
# stay at the default 'internal_only'.
_PUBLISH_INTENT_BACKFILL = {
    'InitiativePipeline': 'publish_candidate',
    'ContentWriterAgent': 'publish_candidate',
    'BlogWriterAgent': 'publish_candidate',
    'EditorAgent': 'publish_candidate',
}


def backfill_known_publishers(apps, schema_editor):
    """Session 1095: after adding publish_intent=internal_only to every row,
    retroactively mark deliverables from known-publishing agents.
    Forward-only — reverse is a no-op (field removal drops all values)."""
    Deliverable = apps.get_model('core', 'Deliverable')
    for agent_name, intent in _PUBLISH_INTENT_BACKFILL.items():
        updated = Deliverable.objects.filter(
            agent_name=agent_name, publish_intent='internal_only',
        ).update(publish_intent=intent)
        if updated:
            print(f'  [0333-backfill] {agent_name}: {updated} rows → {intent}')


def noop_reverse(apps, schema_editor):
    """Field will be dropped on reverse; no explicit undo needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0332_add_status_transition_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="publish_intent",
            field=models.CharField(
                choices=[
                    ("internal_only", "Internal Only"),
                    ("publish_candidate", "Publish Candidate"),
                    ("publish_required", "Publish Required"),
                ],
                db_index=True,
                default="internal_only",
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_known_publishers, noop_reverse),
    ]
