# Generated by Django 5.0.6 on 2026-05-24 17:23 — Session 1139
#
# Adds the `cluster_method` discriminator to SignalCluster so the
# entity-token clusterer (Session 1139) can stand alongside the legacy
# verb-keyword clusterer without forcing a re-cluster of historical data.
#
# Existing rows are backfilled to 'legacy'. New rows default to
# 'entity_token_v1'. Downstream consumers (quality bar, fleet emit,
# auto-topic generation) opt new rows in by filtering on this field.
#
# Hand-trimmed: makemigrations auto-included unrelated AlterField /
# CreateModel ops for drift left behind by other partial work
# (NarrativeShift, AgentExecution, FleetPAChatAuditRow). Those are not
# part of Session 1139 scope and were stripped so this PR stays
# minimal. The drift is a separate cleanup.

from django.db import migrations, models


def backfill_legacy(apps, schema_editor):
    """Backfill `cluster_method='legacy'` on every pre-1139 SignalCluster row.

    The new field's default is 'entity_token_v1' (so newly-created rows
    from this point forward Just Work), but every existing row was
    produced by the verb-keyword clusterer and must be marked 'legacy'
    so downstream selection can exclude them from the new quality bar.
    """
    SignalCluster = apps.get_model("core", "SignalCluster")
    SignalCluster.objects.update(cluster_method="legacy")


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — AddField reverse drops the column wholesale."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0350_fleetpaidinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalcluster",
            name="cluster_method",
            field=models.CharField(
                choices=[
                    ("legacy", "Legacy verb-keyword clusterer (pre-1139)"),
                    ("entity_token_v1", "Entity-token clusterer (Session 1139)"),
                ],
                db_index=True,
                default="entity_token_v1",
                help_text=(
                    "Which clustering algorithm produced this row. Downstream "
                    "selection filters on this so the rewrite can be "
                    "staircased in without forced re-clustering of historical "
                    "data."
                ),
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_legacy, reverse_code=noop_reverse),
    ]
