# Generated by Django 5.0.6 on 2026-06-13 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0354_session_1163_b_final_applied_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="NervousStatus",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("responsive", "Responsive"),
                            ("active", "Active"),
                            ("sluggish", "Sluggish"),
                            ("numb", "Numb"),
                            ("overloaded", "Overloaded"),
                            ("damaged", "Damaged"),
                            ("dormant", "Dormant"),
                        ],
                        default="responsive",
                        max_length=20,
                    ),
                ),
                ("is_healthy", models.BooleanField(default=True)),
                ("health_score", models.FloatField(default=100.0)),
                ("total_consumers", models.IntegerField(default=0)),
                ("active_connections", models.IntegerField(default=0)),
                (
                    "connection_rate",
                    models.FloatField(default=0, help_text="Connections per minute"),
                ),
                ("messages_24h", models.IntegerField(default=0)),
                ("messages_per_second", models.FloatField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0)),
                ("channel_layer_healthy", models.BooleanField(default=True)),
                ("redis_latency_ms", models.FloatField(default=0)),
                ("active_groups", models.IntegerField(default=0)),
                (
                    "error_rate",
                    models.FloatField(default=0, help_text="Error percentage"),
                ),
                ("disconnections_24h", models.IntegerField(default=0)),
                (
                    "activity_level",
                    models.CharField(
                        default="normal",
                        help_text="dormant, low, normal, high, intense",
                        max_length=20,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("last_check", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nervous Status",
                "verbose_name_plural": "Nervous Status",
                "db_table": "core_nervous_status",
            },
        ),
        migrations.AlterField(
            model_name="agentexecution",
            name="parent_execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentexecution",
            name="root_execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="curatedsignalentry",
            name="action_status",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "draft",
                        "Draft (auto-generated, real LLM output, not yet user-reviewed)",
                    ),
                    (
                        "needs_regen",
                        "Needs regeneration (fallback placeholder — LLM call failed)",
                    ),
                    ("ready", "Ready (user-reviewed)"),
                    ("dismissed", "Dismissed"),
                ],
                default="draft",
                help_text="draft/ready/dismissed. New rows always land as 'draft'. Populated on action_card rows only.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="curatedsignalentry",
            name="rank",
            field=models.IntegerField(
                help_text="1-based rank within the snapshot. rank=1 is the highest curated_score; ties broken by cluster.seq ASC (older row wins) so ranking is deterministic. action_card rows copy rank from their paired cluster_pick so both join+sort."
            ),
        ),
        migrations.AlterField(
            model_name="finalappliedoverrides",
            name="applied_values",
            field=models.JSONField(
                default=dict,
                help_text="Knob name → {value, owner, priority} dict. The owner field identifies the policy that wrote the knob; priority is the merge precedence the arbitrator used to resolve any same-cycle conflicts.",
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("fleet_signature", "Fleet HMAC signature"),
                    ("bearer_only", "Bearer token only (no fleet signature)"),
                    ("session_user", "Django session user"),
                    ("api_user_token", "DRF token (user-scoped)"),
                    ("anonymous", "Anonymous / unauthenticated"),
                ],
                db_index=True,
                help_text="Which auth path the request took through unified_pa_chat",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="claimed_app_slug",
            field=models.CharField(
                blank=True,
                default="",
                help_text="app_slug claimed in the request body's context.app_slug or routing.app_slug, if present. The whole point of the audit is to compare this against verified_app_slug.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this record was created"
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="has_fleet_identity",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when FleetSignatureAuthentication set request.fleet_identity",
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Universal unique identifier",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this record is active/enabled"
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="match",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                help_text="True iff verified_app_slug == claimed_app_slug. NULL when either side is missing (no claim, or no verified identity).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Flexible metadata storage for extensibility",
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="verified_app_slug",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="app_slug from the verified fleet_identity, if present. Empty string when no fleet signature was attached.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fleetpachatauditrow",
            name="version",
            field=models.PositiveIntegerField(
                default=1, help_text="Version number for optimistic locking"
            ),
        ),
        migrations.CreateModel(
            name="Narrative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short title for the narrative", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this narrative claims"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("politics", "Politics & Government"),
                            ("markets", "Financial Markets"),
                            ("tech", "Technology & AI"),
                            ("culture", "Culture & Society"),
                            ("geopolitics", "Geopolitics & International"),
                            ("crypto", "Crypto & Web3"),
                            ("climate", "Climate & Environment"),
                            ("health", "Health & Medicine"),
                        ],
                        default="tech",
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords/phrases that indicate this narrative",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emerging", "Emerging (new narrative forming)"),
                            ("dominant", "Dominant (widely accepted)"),
                            ("shifting", "Shifting (change detected)"),
                            ("fading", "Fading (losing relevance)"),
                            ("dead", "Dead (no longer relevant)"),
                        ],
                        default="emerging",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Confidence in narrative status (0-1)",
                        max_digits=5,
                    ),
                ),
                ("mention_count", models.IntegerField(default=0)),
                ("last_mention", models.DateTimeField(blank=True, null=True)),
                ("peak_mentions", models.IntegerField(default=0)),
                ("peak_date", models.DateTimeField(blank=True, null=True)),
                (
                    "strength_history",
                    models.JSONField(
                        default=list,
                        help_text="List of {date, strength, sources} over time",
                    ),
                ),
                ("auto_detected", models.BooleanField(default=False)),
                (
                    "first_detected",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "narrative",
                "ordering": ["-mention_count", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["domain", "status"], name="narrative_domain_20e4ad_idx"
                    ),
                    models.Index(
                        fields=["status", "-mention_count"],
                        name="narrative_status_210bc2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NarrativeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("source_title", models.CharField(blank=True, max_length=300)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                (
                    "excerpt",
                    models.TextField(help_text="Relevant excerpt from the source"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("supports", "Supports narrative"),
                            ("contradicts", "Contradicts narrative"),
                            ("neutral", "Neutral mention"),
                        ],
                        default="supports",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="How strongly this supports/contradicts (0-1)",
                        max_digits=5,
                    ),
                ),
                ("source_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "narrative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="core.narrative",
                    ),
                ),
                (
                    "spider_data",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrative_evidence",
                        to="core.spiderdata",
                    ),
                ),
            ],
            options={
                "db_table": "narrative_evidence",
                "ordering": ["-source_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("politics", "Politics & Government"),
                            ("markets", "Financial Markets"),
                            ("tech", "Technology & AI"),
                            ("culture", "Culture & Society"),
                            ("geopolitics", "Geopolitics & International"),
                            ("crypto", "Crypto & Web3"),
                            ("climate", "Climate & Environment"),
                            ("health", "Health & Medicine"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shift_summary",
                    models.TextField(help_text="What changed in plain language"),
                ),
                (
                    "old_narrative_summary",
                    models.TextField(help_text="What people believed before"),
                ),
                (
                    "new_narrative_summary",
                    models.TextField(help_text="What people believe now"),
                ),
                (
                    "trigger_events",
                    models.JSONField(
                        default=list, help_text="Events that triggered this shift"
                    ),
                ),
                (
                    "evidence_sources",
                    models.JSONField(
                        default=list,
                        help_text="Sources supporting this shift detection",
                    ),
                ),
                (
                    "second_order_effects",
                    models.JSONField(
                        default=list,
                        help_text="Predicted downstream effects of this shift",
                    ),
                ),
                (
                    "historian_analysis",
                    models.TextField(
                        blank=True, help_text="NarrativeHistorianAgent's analysis"
                    ),
                ),
                (
                    "trend_break_analysis",
                    models.TextField(
                        blank=True, help_text="TrendBreakDetectorAgent's analysis"
                    ),
                ),
                (
                    "contrarian_analysis",
                    models.TextField(
                        blank=True, help_text="ContrarianAgent's counter-view"
                    ),
                ),
                (
                    "cultural_impact_analysis",
                    models.TextField(
                        blank=True, help_text="CulturalImpactAgent's analysis"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="Confidence this is a real shift (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "importance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.5,
                        help_text="How significant is this shift (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this shift been verified by human review",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_narrative",
                    models.ForeignKey(
                        blank=True,
                        help_text="The new narrative replacing it (if identified)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts_to",
                        to="core.narrative",
                    ),
                ),
                (
                    "old_narrative",
                    models.ForeignKey(
                        help_text="The narrative that was dominant before",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts_from",
                        to="core.narrative",
                    ),
                ),
            ],
            options={
                "db_table": "narrative_shift",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="NarrativeAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("shift_detected", "Narrative Shift Detected"),
                            ("new_narrative", "New Narrative Emerging"),
                            ("narrative_dying", "Narrative Fading"),
                            ("contradictions", "Contradictions Detected"),
                            ("high_importance", "High Importance Alert"),
                            ("subscription", "User Subscription"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                ("message", models.TextField(blank=True, default="")),
                ("sent_to_discord", models.BooleanField(default=False)),
                ("discord_message_id", models.CharField(blank=True, max_length=100)),
                (
                    "user_discord_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("is_read", models.BooleanField(default=False)),
                ("dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "narrative",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.narrative",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.narrativeshift",
                    ),
                ),
            ],
            options={
                "db_table": "narrative_alert",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NervousPulse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("responsive", "Responsive"),
                            ("active", "Active"),
                            ("sluggish", "Sluggish"),
                            ("numb", "Numb"),
                            ("overloaded", "Overloaded"),
                            ("damaged", "Damaged"),
                            ("dormant", "Dormant"),
                        ],
                        default="responsive",
                        max_length=20,
                    ),
                ),
                (
                    "health_score",
                    models.FloatField(
                        default=100.0, help_text="Overall nervous health 0-100"
                    ),
                ),
                (
                    "total_consumers",
                    models.IntegerField(
                        default=0, help_text="Total registered consumer types"
                    ),
                ),
                (
                    "active_connections",
                    models.IntegerField(
                        default=0, help_text="Current WebSocket connections"
                    ),
                ),
                (
                    "peak_connections_24h",
                    models.IntegerField(default=0, help_text="Max connections in 24h"),
                ),
                (
                    "disconnections_24h",
                    models.IntegerField(default=0, help_text="Connection drops in 24h"),
                ),
                (
                    "connection_errors_24h",
                    models.IntegerField(
                        default=0, help_text="Connection errors in 24h"
                    ),
                ),
                (
                    "messages_sent_24h",
                    models.IntegerField(default=0, help_text="Messages sent in 24h"),
                ),
                (
                    "messages_received_24h",
                    models.IntegerField(
                        default=0, help_text="Messages received in 24h"
                    ),
                ),
                (
                    "messages_per_second",
                    models.FloatField(default=0, help_text="Current throughput"),
                ),
                (
                    "peak_messages_per_second",
                    models.FloatField(default=0, help_text="Peak throughput in 24h"),
                ),
                (
                    "avg_latency_ms",
                    models.FloatField(default=0, help_text="Average message latency"),
                ),
                (
                    "max_latency_ms",
                    models.FloatField(default=0, help_text="Max latency in 24h"),
                ),
                (
                    "p95_latency_ms",
                    models.FloatField(default=0, help_text="95th percentile latency"),
                ),
                ("channel_layer_connected", models.BooleanField(default=True)),
                (
                    "redis_ping_ms",
                    models.FloatField(default=0, help_text="Redis ping latency"),
                ),
                (
                    "active_groups",
                    models.IntegerField(default=0, help_text="Active channel groups"),
                ),
                (
                    "group_members",
                    models.IntegerField(default=0, help_text="Total group memberships"),
                ),
                (
                    "consumer_stats",
                    models.JSONField(default=dict, help_text="Per-consumer metrics"),
                ),
                (
                    "busiest_consumers",
                    models.JSONField(default=list, help_text="Most active consumers"),
                ),
                (
                    "error_consumers",
                    models.JSONField(default=list, help_text="Consumers with errors"),
                ),
                ("check_duration_ms", models.IntegerField(default=0)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Nervous Pulse",
                "verbose_name_plural": "Nervous Pulses",
                "db_table": "core_nervous_pulses",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["-recorded_at"], name="core_nervous_recorded_idx"
                    ),
                    models.Index(
                        fields=["status", "-recorded_at"],
                        name="core_nervous_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebSocketConnectionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consumer_name", models.CharField(max_length=100)),
                ("channel_name", models.CharField(blank=True, max_length=200)),
                ("group_name", models.CharField(blank=True, max_length=100)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("connect", "Connected"),
                            ("disconnect", "Disconnected"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("connection_duration_ms", models.IntegerField(blank=True, null=True)),
                ("messages_during_session", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WebSocket Connection Log",
                "verbose_name_plural": "WebSocket Connection Logs",
                "db_table": "core_websocket_connection_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="core_ws_log_created_idx"
                    ),
                    models.Index(
                        fields=["consumer_name", "-created_at"],
                        name="core_ws_log_consumer_idx",
                    ),
                    models.Index(
                        fields=["event", "-created_at"], name="core_ws_log_event_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="narrativeshift",
            index=models.Index(
                fields=["domain", "-detected_at"], name="narrative_s_domain_1abbf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="narrativeshift",
            index=models.Index(
                fields=["-importance", "-detected_at"],
                name="narrative_s_importa_b8a3dc_idx",
            ),
        ),
    ]
