# Generated by Django 5.0.6 on 2026-06-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0355_nervousstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcallrecord",
            name="conversation_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Conversation/session identifier; PA uses pa-* ids, not UUIDs.",
                max_length=100,
                null=True,
            ),
        ),
    ]
