# Generated by Django 5.0.6 on 2026-06-20 19:01
#
# Session 1174 PR-2a: Create AgentFollowupSubscription model — the subscription
# record for the agent-follow-up wake design (Phase 1 vertical slice). See
# docs/handoffs/SESSION_1174_FOLLOWUP_WAKE_PR1_SHIP.md for the ratified design.
#
# Like PR-1's 0357 migration, this file has been hand-trimmed to a single
# CreateModel operation. makemigrations swept in 16 unrelated AlterField
# operations + 4 unrelated CreateModel + 2 unrelated AddIndex from accumulated
# model-vs-migration drift in other subsystems. Those are out of scope for
# PR-2a and have been removed to keep the change surgical and rollback clean.

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0357_session_1174_agentexecution_conversation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentFollowupSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("armed", "Armed (waiting for completion event)"),
                            (
                                "fired",
                                "Fired (completion event delivered to conversation)",
                            ),
                            (
                                "expired",
                                "Expired (TTL window elapsed before completion)",
                            ),
                            (
                                "cancelled",
                                "Cancelled (explicit cancel from user, Phase 2)",
                            ),
                        ],
                        db_index=True,
                        default="armed",
                        max_length=16,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="now() + after_seconds at creation; beat-scheduled cleanup expires this row when now() > expires_at and state='armed'.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fired_at", models.DateTimeField(blank=True, null=True)),
                ("result_payload", models.JSONField(blank=True, null=True)),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_subscriptions",
                        to="core.agentexecution",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "expires_at"],
                        name="core_agentf_state_ccbfd1_idx",
                    )
                ],
                "unique_together": {("execution", "conversation_id")},
            },
        ),
    ]
