"""
Collective Intelligence Service
================================

Session 215: Harness the collective intelligence of all agents.

This service enables:
- Aggregate insights from all relevant agents on a topic
- Generate comprehensive reports with multi-agent input
- Identify knowledge gaps across the agent ecosystem
- Propose agent improvements based on learning data
- Real-time collaboration monitoring
- Multi-agent orchestration for complex tasks

The collective intelligence system creates emergent capabilities
by combining the specialized knowledge and abilities of multiple agents.
"""

import logging
import asyncio
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from collections import defaultdict

from django.db import models, transaction
from django.db.models import Q, Count, Avg, F, Sum, Max, Min
from django.utils import timezone
from django.core.cache import cache
from django.conf import settings

from .agent_collaboration import (
    AgentCollaborationService,
    get_collaboration_service,
    CollaborationType,
    MessageType,
    CollaborationStatus,
)

logger = logging.getLogger(__name__)


# =============================================================================
# DATA CLASSES
# =============================================================================

@dataclass
class AgentInsight:
    """Insight from a single agent"""
    agent_name: str
    topic: str
    insight_type: str  # observation, recommendation, warning, opportunity
    content: str
    confidence: float  # 0.0 - 1.0
    supporting_data: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=timezone.now)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'agent_name': self.agent_name,
            'topic': self.topic,
            'insight_type': self.insight_type,
            'content': self.content,
            'confidence': self.confidence,
            'supporting_data': self.supporting_data,
            'timestamp': self.timestamp.isoformat()
        }


@dataclass
class CollectiveReport:
    """Report generated by multiple agents"""
    id: str
    topic: str
    summary: str
    participating_agents: List[str]
    insights: List[AgentInsight]
    recommendations: List[Dict[str, Any]]
    consensus_score: float  # How much agents agreed
    confidence_score: float  # Overall confidence
    knowledge_gaps: List[str]
    generated_at: datetime = field(default_factory=timezone.now)

    def to_dict(self) -> Dict[str, Any]:
        return {
            'id': self.id,
            'topic': self.topic,
            'summary': self.summary,
            'participating_agents': self.participating_agents,
            'insights': [i.to_dict() for i in self.insights],
            'recommendations': self.recommendations,
            'consensus_score': self.consensus_score,
            'confidence_score': self.confidence_score,
            'knowledge_gaps': self.knowledge_gaps,
            'generated_at': self.generated_at.isoformat()
        }


@dataclass
class KnowledgeGap:
    """Identified gap in agent knowledge"""
    domain: str
    description: str
    severity: str  # low, medium, high, critical
    affected_agents: List[str]
    suggested_sources: List[str]
    potential_impact: str
    discovered_at: datetime = field(default_factory=timezone.now)


@dataclass
class AgentImprovement:
    """Proposed improvement for an agent"""
    agent_name: str
    improvement_type: str  # capability, knowledge, performance, collaboration
    description: str
    expected_impact: str
    priority: int  # 1-5, 5 is highest
    evidence: Dict[str, Any] = field(default_factory=dict)
    estimated_effort: str = 'medium'  # low, medium, high


@dataclass
class CollaborationMonitor:
    """Real-time collaboration monitoring data"""
    active_collaborations: int
    pending_collaborations: int
    agents_collaborating: List[str]
    recent_completions: List[Dict[str, Any]]
    collaboration_health: str  # healthy, degraded, critical
    avg_response_time_ms: float
    success_rate_24h: float


# =============================================================================
# COLLECTIVE INTELLIGENCE SERVICE
# =============================================================================

class CollectiveIntelligenceService:
    """
    Harness the collective intelligence of all agents.

    This service orchestrates multiple agents to:
    - Generate comprehensive insights on topics
    - Create multi-perspective reports
    - Identify and address knowledge gaps
    - Monitor and optimize collaboration
    """

    def __init__(self, user=None):
        self.user = user
        self.logger = logging.getLogger(__name__)
        self.collaboration_service = get_collaboration_service(user)
        self._insight_cache = {}

    # =========================================================================
    # INSIGHT AGGREGATION
    # =========================================================================

    def aggregate_insights(self, topic: str, domains: List[str] = None) -> Dict[str, Any]:
        """
        Gather insights from all relevant agents on a topic.

        Args:
            topic: The topic to gather insights on
            domains: Optional list of domains to focus on

        Returns:
            Aggregated insights with consensus analysis
        """
        try:
            from core.models_unified_system import (
                SharedKnowledge,
                CollaborationSession,
                AgentPerformanceMetric
            )

            # Cache key for this query
            cache_key = f'collective_insights:{topic}:{",".join(domains or [])}'
            cached = cache.get(cache_key)
            if cached:
                return cached

            # Find relevant knowledge
            knowledge_query = SharedKnowledge.objects.all()

            if domains:
                knowledge_query = knowledge_query.filter(domain__in=domains)

            # Search for topic in titles and tags
            knowledge_query = knowledge_query.filter(
                Q(title__icontains=topic) |
                Q(tags__icontains=topic) |
                Q(description__icontains=topic)
            ).order_by('-effectiveness_score', '-created_at')[:50]

            insights = []
            agent_contributions = defaultdict(int)
            domain_coverage = defaultdict(list)

            for knowledge in knowledge_query:
                insight = AgentInsight(
                    agent_name=knowledge.source_agent,
                    topic=topic,
                    insight_type='knowledge',
                    content=knowledge.description,
                    confidence=min(knowledge.effectiveness_score / 100, 1.0),
                    supporting_data={
                        'knowledge_id': str(knowledge.id),
                        'domain': knowledge.domain,
                        'tags': knowledge.tags,
                        'learned_by_count': len(knowledge.learned_by_agents)
                    }
                )
                insights.append(insight)
                agent_contributions[knowledge.source_agent] += 1
                domain_coverage[knowledge.domain].append(knowledge.source_agent)

            # Get recent collaboration results related to topic
            recent_collabs = CollaborationSession.objects.filter(
                Q(task_description__icontains=topic) |
                Q(input_data__icontains=topic),
                status='completed'
            ).order_by('-completed_at')[:20]

            for collab in recent_collabs:
                if collab.output_data:
                    insight = AgentInsight(
                        agent_name=collab.requester_agent,
                        topic=topic,
                        insight_type='collaboration_result',
                        content=f"Collaboration on: {collab.task_description[:200]}",
                        confidence=collab.quality_score / 100 if collab.quality_score else 0.5,
                        supporting_data={
                            'collaboration_id': str(collab.id),
                            'collaboration_type': collab.collaboration_type,
                            'participating_agents': collab.participating_agents
                        }
                    )
                    insights.append(insight)
                    for agent in collab.participating_agents:
                        agent_contributions[agent] += 1

            # Calculate consensus and confidence
            confidence_scores = [i.confidence for i in insights]
            avg_confidence = sum(confidence_scores) / len(confidence_scores) if confidence_scores else 0.0

            # Determine consensus based on how many agents contributed similar insights
            unique_agents = len(agent_contributions)
            insights_per_agent = len(insights) / unique_agents if unique_agents > 0 else 0
            consensus_score = min(1.0, unique_agents / 5)  # Higher score with more agents

            result = {
                'topic': topic,
                'total_insights': len(insights),
                'unique_agents': unique_agents,
                'insights': [i.to_dict() for i in insights[:20]],  # Top 20
                'agent_contributions': dict(agent_contributions),
                'domain_coverage': {k: list(set(v)) for k, v in domain_coverage.items()},
                'consensus_score': consensus_score,
                'confidence_score': avg_confidence,
                'generated_at': timezone.now().isoformat()
            }

            # Cache for 5 minutes
            cache.set(cache_key, result, 300)

            return result

        except Exception as e:
            self.logger.error(f"Error aggregating insights for {topic}: {e}")
            return {
                'topic': topic,
                'total_insights': 0,
                'unique_agents': 0,
                'insights': [],
                'error': str(e)
            }

    # =========================================================================
    # COLLECTIVE REPORT GENERATION
    # =========================================================================

    def generate_collective_report(
        self,
        topic: str,
        report_type: str = 'comprehensive',
        include_agents: List[str] = None
    ) -> CollectiveReport:
        """
        Generate a report with input from multiple agents.

        Args:
            topic: The topic for the report
            report_type: Type of report (comprehensive, summary, action_items)
            include_agents: Optional list of specific agents to include

        Returns:
            CollectiveReport with multi-agent insights
        """
        import uuid

        try:
            from core.models_unified_system import (
                SharedKnowledge,
                AgentPerformanceMetric
            )

            # Gather all relevant insights
            aggregated = self.aggregate_insights(topic)

            insights = []
            for insight_data in aggregated.get('insights', []):
                insights.append(AgentInsight(
                    agent_name=insight_data['agent_name'],
                    topic=insight_data['topic'],
                    insight_type=insight_data['insight_type'],
                    content=insight_data['content'],
                    confidence=insight_data['confidence'],
                    supporting_data=insight_data.get('supporting_data', {})
                ))

            # Get top performing agents in relevant domains
            top_agents = AgentPerformanceMetric.objects.order_by(
                '-quality_score', '-total_executions'
            )[:10]

            participating_agents = list(set(
                aggregated.get('agent_contributions', {}).keys()
            ))

            if include_agents:
                participating_agents = [
                    a for a in participating_agents if a in include_agents
                ]

            # Generate recommendations based on insights
            recommendations = self._generate_recommendations(insights, topic)

            # Identify knowledge gaps
            knowledge_gaps = self._identify_topic_gaps(topic, insights)

            # Create summary
            summary = self._create_report_summary(
                topic, insights, recommendations, report_type
            )

            report = CollectiveReport(
                id=str(uuid.uuid4()),
                topic=topic,
                summary=summary,
                participating_agents=participating_agents,
                insights=insights,
                recommendations=recommendations,
                consensus_score=aggregated.get('consensus_score', 0.0),
                confidence_score=aggregated.get('confidence_score', 0.0),
                knowledge_gaps=knowledge_gaps
            )

            self.logger.info(
                f"Generated collective report on '{topic}' with "
                f"{len(participating_agents)} agents, {len(insights)} insights"
            )

            return report

        except Exception as e:
            self.logger.error(f"Error generating collective report: {e}")
            return CollectiveReport(
                id=str(uuid.uuid4()),
                topic=topic,
                summary=f"Error generating report: {str(e)}",
                participating_agents=[],
                insights=[],
                recommendations=[],
                consensus_score=0.0,
                confidence_score=0.0,
                knowledge_gaps=[]
            )

    def _generate_recommendations(
        self,
        insights: List[AgentInsight],
        topic: str
    ) -> List[Dict[str, Any]]:
        """Generate recommendations from insights"""
        recommendations = []

        # Group insights by confidence level
        high_confidence = [i for i in insights if i.confidence >= 0.7]
        medium_confidence = [i for i in insights if 0.4 <= i.confidence < 0.7]

        if high_confidence:
            recommendations.append({
                'type': 'action',
                'priority': 'high',
                'title': f'Act on high-confidence insights for {topic}',
                'description': f'{len(high_confidence)} insights have high confidence scores',
                'supporting_agents': list(set(i.agent_name for i in high_confidence))
            })

        if medium_confidence:
            recommendations.append({
                'type': 'investigation',
                'priority': 'medium',
                'title': f'Investigate medium-confidence findings on {topic}',
                'description': f'{len(medium_confidence)} insights need validation',
                'supporting_agents': list(set(i.agent_name for i in medium_confidence))
            })

        # Look for patterns in insight types
        insight_types = defaultdict(int)
        for insight in insights:
            insight_types[insight.insight_type] += 1

        if insight_types.get('warning', 0) > 2:
            recommendations.append({
                'type': 'warning',
                'priority': 'high',
                'title': f'Multiple warnings detected for {topic}',
                'description': f'{insight_types["warning"]} warning insights found',
                'supporting_agents': [
                    i.agent_name for i in insights if i.insight_type == 'warning'
                ]
            })

        return recommendations

    def _identify_topic_gaps(
        self,
        topic: str,
        insights: List[AgentInsight]
    ) -> List[str]:
        """Identify knowledge gaps for a topic"""
        gaps = []

        # Check if we have insights from key domains
        domains_covered = set()
        for insight in insights:
            if 'domain' in insight.supporting_data:
                domains_covered.add(insight.supporting_data['domain'])

        expected_domains = ['image', 'video', 'audio', 'research', 'workflow']
        missing_domains = set(expected_domains) - domains_covered

        for domain in missing_domains:
            gaps.append(f"No insights from {domain} domain for '{topic}'")

        # Check for low coverage
        if len(insights) < 5:
            gaps.append(f"Limited insight coverage for '{topic}' (only {len(insights)} insights)")

        # Check for low confidence overall
        avg_confidence = sum(i.confidence for i in insights) / len(insights) if insights else 0
        if avg_confidence < 0.5:
            gaps.append(f"Low overall confidence ({avg_confidence:.1%}) for '{topic}'")

        return gaps

    def _create_report_summary(
        self,
        topic: str,
        insights: List[AgentInsight],
        recommendations: List[Dict[str, Any]],
        report_type: str
    ) -> str:
        """Create a summary for the report"""
        if report_type == 'summary':
            return (
                f"Summary report on '{topic}': {len(insights)} insights gathered "
                f"with {len(recommendations)} recommendations."
            )
        elif report_type == 'action_items':
            action_count = len([r for r in recommendations if r['type'] == 'action'])
            return (
                f"Action items for '{topic}': {action_count} actions identified "
                f"from {len(insights)} agent insights."
            )
        else:  # comprehensive
            unique_agents = len(set(i.agent_name for i in insights))
            avg_confidence = sum(i.confidence for i in insights) / len(insights) if insights else 0
            return (
                f"Comprehensive analysis of '{topic}': {unique_agents} agents "
                f"contributed {len(insights)} insights with {avg_confidence:.1%} "
                f"average confidence. {len(recommendations)} recommendations generated."
            )

    # =========================================================================
    # KNOWLEDGE GAP IDENTIFICATION
    # =========================================================================

    def identify_knowledge_gaps(self) -> List[KnowledgeGap]:
        """
        Identify areas where agents lack knowledge.

        Analyzes collaboration failures, low-confidence responses,
        and missing domain coverage to identify gaps.
        """
        try:
            from core.models_unified_system import (
                SharedKnowledge,
                CollaborationSession,
                AgentPerformanceMetric
            )

            gaps = []

            # 1. Find domains with low knowledge density
            domain_counts = SharedKnowledge.objects.values('domain').annotate(
                count=Count('id'),
                avg_effectiveness=Avg('effectiveness_score')
            )

            expected_domains = {
                'image': 10, 'video': 5, 'audio': 5, 'research': 10,
                'workflow': 5, '3d': 3, 'character': 3
            }

            domain_data = {d['domain']: d for d in domain_counts}

            for domain, min_expected in expected_domains.items():
                domain_info = domain_data.get(domain, {'count': 0, 'avg_effectiveness': 0})
                if domain_info['count'] < min_expected:
                    gaps.append(KnowledgeGap(
                        domain=domain,
                        description=f"Insufficient knowledge in {domain} domain",
                        severity='medium' if domain_info['count'] > 0 else 'high',
                        affected_agents=self._get_agents_by_domain(domain),
                        suggested_sources=[
                            f"Training data for {domain}",
                            f"Expert consultations on {domain}",
                            f"Historical success patterns in {domain}"
                        ],
                        potential_impact=f"May affect quality of {domain}-related tasks"
                    ))

            # 2. Find collaboration failure patterns
            failed_collabs = CollaborationSession.objects.filter(
                status='failed',
                created_at__gte=timezone.now() - timedelta(days=7)
            ).values('collaboration_type').annotate(count=Count('id'))

            for collab_data in failed_collabs:
                if collab_data['count'] >= 3:
                    gaps.append(KnowledgeGap(
                        domain='collaboration',
                        description=f"High failure rate in {collab_data['collaboration_type']} collaborations",
                        severity='high' if collab_data['count'] >= 5 else 'medium',
                        affected_agents=['all'],
                        suggested_sources=[
                            "Review failed collaboration logs",
                            "Improve error handling",
                            "Add retry mechanisms"
                        ],
                        potential_impact=f"{collab_data['count']} failures in past 7 days"
                    ))

            # 3. Find agents with low performance scores
            low_performers = AgentPerformanceMetric.objects.filter(
                total_executions__gte=5,
                quality_score__lt=50
            )

            for agent in low_performers:
                gaps.append(KnowledgeGap(
                    domain='performance',
                    description=f"Agent {agent.agent_name} has low quality score",
                    severity='medium',
                    affected_agents=[agent.agent_name],
                    suggested_sources=[
                        "Review agent configuration",
                        "Analyze failure patterns",
                        "Consider retraining or reconfiguration"
                    ],
                    potential_impact=f"Quality score: {agent.quality_score}%"
                ))

            self.logger.info(f"Identified {len(gaps)} knowledge gaps")
            return gaps

        except Exception as e:
            self.logger.error(f"Error identifying knowledge gaps: {e}")
            return []

    def _get_agents_by_domain(self, domain: str) -> List[str]:
        """Get agents that work in a specific domain"""
        try:
            from agents.registry import get_agent_registry
            registry = get_agent_registry()
            agents = registry.list_agents(specialization=domain)
            return [a['name'] for a in agents]
        except Exception:
            return []

    # =========================================================================
    # AGENT IMPROVEMENT PROPOSALS
    # =========================================================================

    def propose_agent_improvements(self) -> List[AgentImprovement]:
        """
        Propose improvements for agents based on learning data.

        Analyzes performance metrics, collaboration patterns, and
        knowledge gaps to suggest actionable improvements.
        """
        try:
            from core.models_unified_system import (
                AgentPerformanceMetric,
                CollaborationSession,
                SharedKnowledge
            )

            improvements = []

            # 1. Analyze performance metrics
            all_metrics = AgentPerformanceMetric.objects.all()

            for metric in all_metrics:
                # Low success rate
                if metric.total_executions >= 10 and metric.successful_executions / max(metric.total_executions, 1) < 0.7:
                    improvements.append(AgentImprovement(
                        agent_name=metric.agent_name,
                        improvement_type='performance',
                        description=f"Success rate below 70% ({metric.successful_executions}/{metric.total_executions})",
                        expected_impact='Improve task completion reliability',
                        priority=4,
                        evidence={
                            'total_executions': metric.total_executions,
                            'successful': metric.successful_executions,
                            'success_rate': metric.successful_executions / max(metric.total_executions, 1)
                        }
                    ))

                # Low collaboration
                if metric.total_executions >= 20 and metric.successful_collaborations < 2:
                    improvements.append(AgentImprovement(
                        agent_name=metric.agent_name,
                        improvement_type='collaboration',
                        description='Rarely collaborates with other agents',
                        expected_impact='Increase problem-solving capability through collaboration',
                        priority=3,
                        evidence={
                            'executions': metric.total_executions,
                            'collaborations': metric.successful_collaborations
                        }
                    ))

                # Low knowledge sharing
                if metric.knowledge_contributions == 0 and metric.total_executions >= 10:
                    improvements.append(AgentImprovement(
                        agent_name=metric.agent_name,
                        improvement_type='knowledge',
                        description='Not contributing to shared knowledge base',
                        expected_impact='Enable other agents to learn from this agent\'s expertise',
                        priority=2,
                        evidence={
                            'executions': metric.total_executions,
                            'contributions': metric.knowledge_contributions
                        }
                    ))

            # 2. Find capability gaps based on consultation patterns
            consultations = CollaborationSession.objects.filter(
                collaboration_type='consultation',
                status='completed'
            ).values('requester_agent').annotate(count=Count('id'))

            frequent_requesters = [c for c in consultations if c['count'] >= 5]
            for requester in frequent_requesters:
                improvements.append(AgentImprovement(
                    agent_name=requester['requester_agent'],
                    improvement_type='capability',
                    description=f"Frequently requests consultations ({requester['count']} times)",
                    expected_impact='Could benefit from expanded internal capabilities',
                    priority=2,
                    evidence={'consultation_count': requester['count']},
                    estimated_effort='high'
                ))

            # 3. Identify agents that could benefit from learning
            knowledge_items = SharedKnowledge.objects.filter(
                effectiveness_score__gte=70
            ).values('domain').annotate(count=Count('id'))

            high_value_domains = [k['domain'] for k in knowledge_items if k['count'] >= 3]

            for metric in all_metrics:
                # Check if agent should learn from high-value domains
                specs = metric.specialization_scores or {}
                for domain in high_value_domains:
                    if domain not in specs or specs[domain] < 50:
                        improvements.append(AgentImprovement(
                            agent_name=metric.agent_name,
                            improvement_type='knowledge',
                            description=f"Could benefit from {domain} domain knowledge",
                            expected_impact=f'Expand capabilities in {domain} area',
                            priority=2,
                            evidence={
                                'current_score': specs.get(domain, 0),
                                'available_knowledge': True
                            },
                            estimated_effort='low'
                        ))

            # Sort by priority
            improvements.sort(key=lambda x: x.priority, reverse=True)

            self.logger.info(f"Proposed {len(improvements)} agent improvements")
            return improvements[:20]  # Top 20 improvements

        except Exception as e:
            self.logger.error(f"Error proposing improvements: {e}")
            return []

    # =========================================================================
    # REAL-TIME COLLABORATION MONITORING
    # =========================================================================

    def get_collaboration_monitor(self) -> CollaborationMonitor:
        """
        Get real-time collaboration monitoring data.

        Returns current state of agent collaborations including
        active sessions, performance metrics, and health status.
        """
        try:
            from core.models_unified_system import CollaborationSession

            # Count active and pending
            active = CollaborationSession.objects.filter(
                status='active'
            ).count()

            pending = CollaborationSession.objects.filter(
                status='pending'
            ).count()

            # Get currently collaborating agents
            active_sessions = CollaborationSession.objects.filter(
                status__in=['active', 'pending']
            ).values_list('participating_agents', flat=True)

            collaborating_agents = set()
            for agents_list in active_sessions:
                if agents_list:
                    collaborating_agents.update(agents_list)

            # Recent completions (last hour)
            recent = CollaborationSession.objects.filter(
                status='completed',
                completed_at__gte=timezone.now() - timedelta(hours=1)
            ).order_by('-completed_at')[:10]

            recent_completions = [{
                'id': str(r.id),
                'requester': r.requester_agent,
                'type': r.collaboration_type,
                'quality_score': r.quality_score,
                'completed_at': r.completed_at.isoformat() if r.completed_at else None
            } for r in recent]

            # Calculate 24h success rate
            last_24h = CollaborationSession.objects.filter(
                created_at__gte=timezone.now() - timedelta(hours=24)
            )
            total_24h = last_24h.count()
            completed_24h = last_24h.filter(status='completed').count()
            success_rate = completed_24h / total_24h if total_24h > 0 else 1.0

            # Calculate average response time
            completed_recent = CollaborationSession.objects.filter(
                status='completed',
                completed_at__isnull=False
            ).order_by('-completed_at')[:50]

            response_times = []
            for session in completed_recent:
                if session.completed_at and session.created_at:
                    delta = (session.completed_at - session.created_at).total_seconds() * 1000
                    response_times.append(delta)

            avg_response = sum(response_times) / len(response_times) if response_times else 0

            # Determine health status
            if active + pending > 50 or success_rate < 0.5:
                health = 'critical'
            elif active + pending > 20 or success_rate < 0.7:
                health = 'degraded'
            else:
                health = 'healthy'

            return CollaborationMonitor(
                active_collaborations=active,
                pending_collaborations=pending,
                agents_collaborating=list(collaborating_agents),
                recent_completions=recent_completions,
                collaboration_health=health,
                avg_response_time_ms=avg_response,
                success_rate_24h=success_rate
            )

        except Exception as e:
            self.logger.error(f"Error getting collaboration monitor: {e}")
            return CollaborationMonitor(
                active_collaborations=0,
                pending_collaborations=0,
                agents_collaborating=[],
                recent_completions=[],
                collaboration_health='unknown',
                avg_response_time_ms=0,
                success_rate_24h=0
            )

    # =========================================================================
    # MULTI-AGENT ORCHESTRATION
    # =========================================================================

    def orchestrate_multi_agent_task(
        self,
        task_description: str,
        required_capabilities: List[str] = None,
        max_agents: int = 5,
        timeout_seconds: int = 300
    ) -> Dict[str, Any]:
        """
        Orchestrate a complex task across multiple agents.

        Automatically selects best agents, coordinates their work,
        and aggregates results.
        """
        import uuid

        try:
            from agents.registry import get_agent_registry
            from core.models_unified_system import CollaborationSession

            orchestration_id = str(uuid.uuid4())
            start_time = timezone.now()

            # 1. Select agents for the task
            registry = get_agent_registry()
            all_agents = registry.list_agents()

            # Score agents based on task requirements
            scored_agents = []
            for agent in all_agents:
                score = 0

                # Capability matching
                if required_capabilities:
                    agent_caps = agent.get('capabilities', [])
                    matches = len(set(required_capabilities) & set(agent_caps))
                    score += matches * 10

                # Keyword matching
                keywords = agent.get('routing_keywords', [])
                task_lower = task_description.lower()
                for kw in keywords:
                    if kw.lower() in task_lower:
                        score += 5

                # Performance bonus
                metrics = agent.get('performance_metrics', {})
                score += metrics.get('success_rate', 0.5) * 10

                if score > 0:
                    scored_agents.append((agent, score))

            # Select top agents
            scored_agents.sort(key=lambda x: x[1], reverse=True)
            selected_agents = [a[0] for a in scored_agents[:max_agents]]

            if not selected_agents:
                return {
                    'orchestration_id': orchestration_id,
                    'status': 'failed',
                    'error': 'No suitable agents found for task',
                    'selected_agents': [],
                    'results': []
                }

            # 2. Create parallel collaboration sessions
            agent_names = [a['name'] for a in selected_agents]

            session = CollaborationSession.objects.create(
                requester_agent='collective_intelligence',
                collaboration_type='parallel',
                task_description=task_description,
                input_data={
                    'required_capabilities': required_capabilities or [],
                    'timeout_seconds': timeout_seconds
                },
                participating_agents=agent_names,
                status='active',
                user=self.user
            )

            # 3. Return orchestration info (actual execution would be async)
            return {
                'orchestration_id': orchestration_id,
                'session_id': str(session.id),
                'status': 'initiated',
                'selected_agents': agent_names,
                'agent_count': len(selected_agents),
                'task_description': task_description,
                'timeout_seconds': timeout_seconds,
                'started_at': start_time.isoformat()
            }

        except Exception as e:
            self.logger.error(f"Error orchestrating multi-agent task: {e}")
            return {
                'orchestration_id': str(uuid.uuid4()),
                'status': 'failed',
                'error': str(e),
                'selected_agents': [],
                'results': []
            }

    # =========================================================================
    # COLLABORATION NETWORK ANALYSIS
    # =========================================================================

    def get_collaboration_network(self) -> Dict[str, Any]:
        """
        Get collaboration network data for visualization.

        Returns nodes (agents) and edges (collaborations) for
        network graph visualization.
        """
        try:
            from core.models_unified_system import (
                CollaborationSession,
                InterAgentMessage,
                AgentPerformanceMetric
            )

            # Build nodes from agent metrics
            nodes = []
            metrics = AgentPerformanceMetric.objects.all()

            for metric in metrics:
                nodes.append({
                    'id': metric.agent_name,
                    'label': metric.agent_name.replace('_', ' ').title(),
                    'size': min(50, 10 + metric.total_executions),  # Size based on activity
                    'color': self._get_agent_color(metric.quality_score),
                    'metrics': {
                        'executions': metric.total_executions,
                        'collaborations': metric.successful_collaborations,
                        'quality_score': metric.quality_score
                    }
                })

            # Build edges from collaboration history
            edges = []
            edge_weights = defaultdict(int)

            # From collaboration sessions
            sessions = CollaborationSession.objects.filter(
                status='completed'
            ).values('requester_agent', 'participating_agents')

            for session in sessions:
                requester = session['requester_agent']
                for participant in session['participating_agents'] or []:
                    if participant != requester:
                        key = tuple(sorted([requester, participant]))
                        edge_weights[key] += 1

            # From inter-agent messages
            messages = InterAgentMessage.objects.values(
                'sender_agent', 'receiver_agent'
            ).annotate(count=Count('id'))

            for msg in messages:
                key = tuple(sorted([msg['sender_agent'], msg['receiver_agent']]))
                edge_weights[key] += msg['count']

            # Create edge list
            for (agent1, agent2), weight in edge_weights.items():
                edges.append({
                    'source': agent1,
                    'target': agent2,
                    'weight': weight,
                    'width': min(10, 1 + weight // 5)  # Visual width
                })

            return {
                'nodes': nodes,
                'edges': edges,
                'stats': {
                    'total_nodes': len(nodes),
                    'total_edges': len(edges),
                    'total_collaborations': sum(edge_weights.values())
                },
                'generated_at': timezone.now().isoformat()
            }

        except Exception as e:
            self.logger.error(f"Error getting collaboration network: {e}")
            return {'nodes': [], 'edges': [], 'stats': {}, 'error': str(e)}

    def _get_agent_color(self, quality_score: float) -> str:
        """Get color based on quality score"""
        if quality_score >= 80:
            return '#22c55e'  # Green
        elif quality_score >= 60:
            return '#eab308'  # Yellow
        elif quality_score >= 40:
            return '#f97316'  # Orange
        else:
            return '#ef4444'  # Red

    # =========================================================================
    # STATISTICS AND ANALYTICS
    # =========================================================================

    def get_collective_stats(self) -> Dict[str, Any]:
        """Get comprehensive collective intelligence statistics"""
        try:
            from core.models_unified_system import (
                CollaborationSession,
                SharedKnowledge,
                AgentPerformanceMetric,
                InterAgentMessage,
                Agent,
                AgentKnowledgeSource,
                AgentSpiderConnection,
                AgentLearningConnection  # Session 243
            )

            # Collaboration stats
            total_collabs = CollaborationSession.objects.count()
            completed_collabs = CollaborationSession.objects.filter(status='completed').count()

            # Knowledge stats - use AgentKnowledgeSource if available, fallback to SharedKnowledge
            knowledge_source_count = AgentKnowledgeSource.objects.filter(is_active=True).count()
            total_knowledge = knowledge_source_count if knowledge_source_count > 0 else SharedKnowledge.objects.count()
            avg_effectiveness = SharedKnowledge.objects.aggregate(
                avg=Avg('effectiveness_score')
            )['avg'] or 0

            # Agent stats - use core.Agent model (the real 20 agents) with fallback
            real_agent_count = Agent.objects.filter(is_active=True).count()
            total_agents = real_agent_count if real_agent_count > 0 else AgentPerformanceMetric.objects.count()
            avg_quality = AgentPerformanceMetric.objects.aggregate(
                avg=Avg('quality_score')
            )['avg'] or 0

            # Spider connection stats (Session 242)
            spider_connections = AgentSpiderConnection.objects.count()

            # Learning connections (Session 243)
            learning_connections = AgentLearningConnection.objects.filter(is_active=True).count()

            # Message stats
            total_messages = InterAgentMessage.objects.count()

            # Top domains
            domain_stats = SharedKnowledge.objects.values('domain').annotate(
                count=Count('id')
            ).order_by('-count')[:5]

            # Top collaborating agents
            top_collaborators = AgentPerformanceMetric.objects.order_by(
                '-successful_collaborations'
            ).values('agent_name', 'successful_collaborations')[:5]

            return {
                'collaboration': {
                    'total': total_collabs,
                    'completed': completed_collabs,
                    'success_rate': completed_collabs / total_collabs if total_collabs > 0 else 0
                },
                'knowledge': {
                    'total_items': total_knowledge,
                    'avg_effectiveness': avg_effectiveness
                },
                'agents': {
                    'total': total_agents,
                    'avg_quality_score': avg_quality,
                    'spider_connections': spider_connections,  # Session 242
                    'learning_connections': learning_connections  # Session 243
                },
                'messages': {
                    'total': total_messages
                },
                'top_domains': list(domain_stats),
                'top_collaborators': list(top_collaborators),
                'generated_at': timezone.now().isoformat()
            }

        except Exception as e:
            self.logger.error(f"Error getting collective stats: {e}")
            return {'error': str(e)}


# =============================================================================
# FACTORY FUNCTION
# =============================================================================

def get_collective_intelligence_service(user=None) -> CollectiveIntelligenceService:
    """Get a CollectiveIntelligenceService instance"""
    return CollectiveIntelligenceService(user=user)
