"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables
load_dotenv(BASE_DIR / '.env')

# SECURITY ENHANCEMENT: Load secrets from secure vault in production
try:
    # Only load from secure vault if not in development/testing
    if not os.environ.get('DEBUG', 'False') == 'True':
        secrets_loader_path = BASE_DIR / 'secrets' / 'loader.py'
        if secrets_loader_path.exists():
            sys.path.insert(0, str(BASE_DIR / 'secrets'))
            import loader  # This auto-loads secrets from vault
            print("✅ Loaded secrets from secure vault")
    else:
        print("🔧 Development mode: Using .env file for configuration")
except Exception as e:
    print(f"⚠️  Could not load secrets from vault: {e}")
    print("   Falling back to environment variables")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from django.core.management.utils import get_random_secret_key
SECRET_KEY = os.environ.get('SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Unified Platform Core
    "core",
    
    # Agent System
    "agents",
    
    # Sports Analytics
    "sports.apps.SportsConfig",
    
    # Content Generation
    "content",
    
    # Self-Awareness & Intelligence
    "self_awareness",

    # Real-Time Intelligence Engine
    "intelligence.apps.IntelligenceConfig",

    # ML Intelligence Pipeline
    "ml_intelligence.apps.MlIntelligenceConfig",

    # Style Memory System
    "style_memory",

    # Data Persistence Infrastructure
    "persistence",
    
    # Dashboard
    "dashboard",
    
    # Mythology/Hallucination Detection
    "mythology",
    
    # Third-party packages
    "rest_framework",
    "rest_framework.authtoken",  # Add token authentication
    "django_filters",
    "channels",
    "corsheaders",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # "backend.middleware.UnifiedSecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # "backend.middleware.UnifiedAuthenticationMiddleware",
    # "backend.middleware.RequestLoggingMiddleware",
    # "backend.middleware.UnifiedRateLimitingMiddleware",  # Temporarily disabled due to cache issues
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "backend.middleware.UnifiedAPIResponseMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url

if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    # Fallback to SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# PostgreSQL specific configuration
if 'postgres' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {
        'application_name': 'unified_donkey_betz',
        'client_encoding': 'UTF8',
        'connect_timeout': 10,
    }
    DATABASES['default']['CONN_MAX_AGE'] = 600


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'core.UnifiedUser'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     'rest_framework.throttling.AnonRateThrottle',
    #     'rest_framework.throttling.UserRateThrottle',
    # ],
    # 'DEFAULT_THROTTLE_RATES': {
    #     'anon': '100/hour',
    #     'user': '1000/hour',
    #     'burst': '60/min',
    # },
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION': 'v1',
    'ALLOWED_VERSIONS': ['v1'],
    'VERSION_PARAM': 'version',
}

# API Documentation Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Unified Donkey Betz Platform API',
    'DESCRIPTION': 'Comprehensive sports betting analytics and agent orchestration platform with unified API versioning, authentication, and real-time capabilities',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1',
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Development server'},
        {'url': 'https://api.donkeybetz.com', 'description': 'Production server'},
    ],
    'TAGS': [
        {'name': 'agents', 'description': 'Agent orchestration and management'},
        {'name': 'sports', 'description': 'Sports analytics and betting'},
        {'name': 'content', 'description': 'Content generation and management'},
        {'name': 'self-awareness', 'description': 'System introspection and analysis'},
    ],
    'CONTACT': {
        'name': 'API Support',
        'email': 'support@donkeybetz.com',
    },
    'LICENSE': {
        'name': 'Proprietary License',
    },
}

# Channels Configuration (for WebSocket)
ASGI_APPLICATION = 'backend.asgi.application'

# Production-Grade Channels Layer Configuration
try:
    import channels_redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [os.environ.get('REDIS_CHANNELS_URL', 'redis://localhost:6379/3')],
                'capacity': 1000,  # Increased for production
                'expiry': 300,     # 5 minutes for production stability
            },
        },
    }
    print("✅ Production-grade Redis Channels Layer configured")
except ImportError:
    # Fallback to in-memory channel layer
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
    print("⚠️  Using in-memory channels (Redis not available)")

# CORS Configuration - SECURE IMPLEMENTATION
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000,http://127.0.0.1:3001,http://localhost:8080,http://localhost:8081,http://localhost:5173,http://127.0.0.1:5173').split(',')
CORS_ALLOW_CREDENTIALS = True
# Allow null origin for file:// protocol during development
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only in DEBUG mode

# Custom headers configuration
from corsheaders.defaults import default_headers

CORS_ALLOWED_HEADERS = [
    'accept',
    'accept-encoding', 
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-orchestrator',
    'x-orchestra-client',
    'x-dbao-client',
    'x-version',
    'x-client',
]

# Allow all headers in development (alternative method)
if DEBUG:
    from corsheaders.defaults import default_headers
    # Add custom headers to default headers (avoiding duplicates)
    CORS_ALLOW_HEADERS = list(default_headers) + [
        'x-orchestrator',
        'x-orchestra-client',
        'x-dbao-client',
        'x-version',
        'x-client',
    ]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000').split(',')
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'
CSRF_COOKIE_HTTPONLY = True

# Environment-specific Security Configuration
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')

# Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Production Security Settings
if ENVIRONMENT == 'production':
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
elif ENVIRONMENT == 'staging':
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:  # development
    SECURE_HSTS_SECONDS = 0
    SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'False') == 'True'
    CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False') == 'True'

# AI Configuration
AI_CONFIG = {
    'DEFAULT_LLM_MODEL': 'gpt-5-mini',
    # GPT-5 Reasoning Configuration
    'GPT5_REASONING_LEVELS': ['minimal', 'low', 'medium', 'high'],
    'DEFAULT_REASONING_LEVEL': 'medium',
    # Token Limits
    'MAX_INPUT_TOKENS': {
        'gpt-5': 272000,
        'gpt-5-mini': 272000,
        'gpt-5-nano': 272000,
        'gpt-4': 128000,
        'gpt-3.5-turbo': 16385
    },
    'MAX_OUTPUT_TOKENS': {
        'gpt-5': 128000,
        'gpt-5-mini': 128000,
        'gpt-5-nano': 128000,
        'gpt-4': 4096,
        'gpt-3.5-turbo': 4096
    },
    # Prompt Caching
    'ENABLE_PROMPT_CACHING': True,
    'PROMPT_CACHE_TTL': 300,
    'GPT5_FALLBACK_MODEL': 'gpt-4',
    'ENABLE_GPT5_MIGRATION': True,
}

# Agent System Configuration
AGENT_SYSTEM = {
    'MAX_CONCURRENT_EXECUTIONS': 10,
    'DEFAULT_EXECUTION_TIMEOUT': 300,  # 5 minutes
    'WEBSOCKET_HEARTBEAT_INTERVAL': 30,
    'REGISTRY_REBUILD_INTERVAL': 60,  # 1 minute
    'ENABLE_AGENT_LEARNING': True,
    'ENABLE_SELF_IMPROVEMENT': True,
    'DEFAULT_LLM_PROVIDER': 'openai',
    'DEFAULT_LLM_MODEL': 'gpt-5-mini',
}

# Sports Analytics Configuration
SPORTS_ANALYTICS = {
    'ODDS_INGESTION_INTERVAL': 30,  # seconds
    'LINE_MOVEMENT_THRESHOLD': 10,  # points for American odds
    'ARBITRAGE_MIN_PROFIT': 1.0,  # minimum profit percentage
    'KELLY_DEFAULT_MULTIPLIER': 0.25,  # fractional Kelly
    'MAX_BET_PERCENTAGE': 0.10,  # maximum 10% of bankroll
    'WEBSOCKET_ODDS_THROTTLE': 1,  # max 1 update per second
    'ENABLE_REAL_TIME_UPDATES': True,
    'CACHE_TIMEOUT': 300,  # 5 minutes
    'SUPPORTED_SPORTS': ['nfl', 'ncaaf', 'nba', 'ncaab', 'mlb', 'nhl'],
    'DEFAULT_SPORTSBOOKS': ['draftkings', 'fanduel', 'bet365', 'caesars'],
}

# External API Keys for Sports Data
THE_ODDS_API_KEY = os.environ.get('THE_ODDS_API_KEY', 'demo')  # Real API key from .env
ODDS_API_KEY = os.environ.get('THE_ODDS_API_KEY', 'demo')  # Alias for compatibility
SPORTRADAR_API_KEY = os.environ.get('SPORTRADAR_API_KEY', 'demo')  # Real SportRadar key from .env
SPORTSDB_API_KEY = os.environ.get('SPORTSDB_API_KEY', '1')  # Free tier key for TheSportsDB
WEATHER_API_KEY = os.environ.get('WEATHERAPI_KEY', '')  # Weather API key - matches .env variable name

# API Rate Limiting
API_RATE_LIMITS = {
    'espn': 100,  # requests per minute (no official limit)
    'odds_api': 500,  # requests per month for free tier
    'sportsdb': 100,  # requests per minute
}

# Redis Configuration
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '')

# Redis Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_CACHE_URL', 'redis://localhost:6379/1'),
        'KEY_PREFIX': 'unified_platform',
        'TIMEOUT': 300,
        'VERSION': 1,
    },
    'sessions': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.environ.get('REDIS_SESSION_URL', 'redis://localhost:6379/2'),
        'TIMEOUT': 86400,  # 24 hours
        'KEY_PREFIX': 'session',
    }
}

# Redis Key Naming Patterns
REDIS_KEY_PATTERNS = {
    'agents': 'unified_platform:agents:{identifier}',
    'sports': 'unified_platform:sports:{identifier}',
    'content': 'unified_platform:content:{identifier}',
    'auth': 'unified_platform:auth:{identifier}',
    'rate_limit': 'unified_platform:rate_limit:{type}:{identifier}',
    'sessions': 'unified_platform:sessions:{identifier}',
    'analytics': 'unified_platform:analytics:{identifier}',
}

# Celery Configuration (for async tasks)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_WORKER_CONCURRENCY = int(os.environ.get('CELERY_WORKER_CONCURRENCY', '4'))
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'
CELERY_TASK_ROUTES = {
    'agents.*': {'queue': 'agents'},
    'sports.*': {'queue': 'sports'},
    'content.*': {'queue': 'content'},
    'self_awareness.*': {'queue': 'self_awareness'},
}

# AI Provider Configuration with Secure Key Management
def validate_api_key(key_name, key_value):
    """Validate API key format and log warning if missing."""
    if not key_value:
        if not DEBUG:
            import logging
            logger = logging.getLogger('ai_providers')
            logger.warning(f"Missing API key: {key_name}")
        return None
    return key_value

AI_PROVIDERS = {
    'OPENAI_API_KEY': validate_api_key('OPENAI_API_KEY', os.environ.get('OPENAI_API_KEY', '')),
    'ANTHROPIC_API_KEY': validate_api_key('ANTHROPIC_API_KEY', os.environ.get('ANTHROPIC_API_KEY', '')),
    'GOOGLE_API_KEY': validate_api_key('GOOGLE_API_KEY', os.environ.get('GOOGLE_API_KEY', '')),
    'REPLICATE_API_KEY': validate_api_key('REPLICATE_API_KEY', os.environ.get('REPLICATE_API_KEY', '')),
    'MISTRAL_API_KEY': validate_api_key('MISTRAL_API_KEY', os.environ.get('MISTRAL_API_KEY', '')),
    'COHERE_API_KEY': validate_api_key('COHERE_API_KEY', os.environ.get('COHERE_API_KEY', '')),
    'GROQ_API_KEY': validate_api_key('GROQ_API_KEY', os.environ.get('GROQ_API_KEY', '')),
    'DEEPSEEK_API_KEY': validate_api_key('DEEPSEEK_API_KEY', os.environ.get('DEEPSEEK_API_KEY', '')),
    'STABILITY_API_KEY': validate_api_key('STABILITY_API_KEY', os.environ.get('STABILITY_API_KEY', '')),
}

# Additional API Keys for External Services
EXTERNAL_API_KEYS = {
    'STABILITY_API_KEY': validate_api_key('STABILITY_API_KEY', os.environ.get('STABILITY_API_KEY', '')),
    'ELEVENLABS_API_KEY': validate_api_key('ELEVENLABS_API_KEY', os.environ.get('ELEVENLABS_API_KEY', '')),
    'GIPHY_API_KEY': validate_api_key('GIPHY_API_KEY', os.environ.get('GIPHY_API_KEY', '')),
    'ALPHA_VANTAGE_API_KEY': validate_api_key('ALPHA_VANTAGE_API_KEY', os.environ.get('ALPHA_VANTAGE_API_KEY', '')),
    'POLYGON_API_KEY': validate_api_key('POLYGON_API_KEY', os.environ.get('POLYGON_API_KEY', '')),
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'unified_platform.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'agents': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'sports': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
