# Generated by Django 5.0.6 on 2025-10-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
        ("persistence", "0007_unifiedembedding_unified_embedding_hnsw_cosine"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarningRecord",
            fields=[],
            options={
                "verbose_name": "Earning Record",
                "verbose_name_plural": "Earning Records",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("persistence.revenuetracker",),
        ),
        migrations.CreateModel(
            name="RevenueMetrics",
            fields=[],
            options={
                "verbose_name": "Revenue Metrics",
                "verbose_name_plural": "Revenue Metrics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("persistence.revenuetracker",),
        ),
        migrations.CreateModel(
            name="SpiderIntelligenceNode",
            fields=[],
            options={
                "verbose_name": "Spider Intelligence Node",
                "verbose_name_plural": "Spider Intelligence Nodes",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("persistence.spiderdata",),
        ),
    ]
