from __future__ import annotations

import unittest

from scripts.verify_repo_guardrails import (
    classify_docs_index_autogen,
    classify_platform_inventory_freshness,
)


class PlatformInventoryFreshnessTests(unittest.TestCase):
    def test_passes_when_recorded_head_matches_current_head(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="abc1234",
            current_head="abc1234",
            current_commit_files=["docs/PLATFORM_INVENTORY.md"],
            parent_head="deadbeef",
        )

        self.assertTrue(ok)
        self.assertIn("matches repo head abc1234", message)

    def test_passes_for_inventory_only_commit_against_parent_head(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="deadbeef",
            current_head="abc1234",
            current_commit_files=["docs/PLATFORM_INVENTORY.md"],
            parent_head="deadbeef",
        )

        self.assertTrue(ok)
        self.assertIn("inventory reflects parent HEAD", message)
        self.assertIn("inventory-only", message)

    def test_fails_for_real_stale_inventory(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="deadbeef",
            current_head="abc1234",
            current_commit_files=["README.md"],
            parent_head="deadbeef",
        )

        self.assertFalse(ok)
        self.assertEqual(message, "inventory head deadbeef != repo head abc1234")


class DocsIndexAutogenMarkerTests(unittest.TestCase):
    def test_passes_with_canonical_marker(self) -> None:
        ok, message = classify_docs_index_autogen(
            "<!-- DOC-AUTOGEN: generated by `python manage.py build_docs_index`; "
            "do not hand-edit. -->"
        )

        self.assertTrue(ok)
        self.assertIn("DOC-AUTOGEN marker", message)

    def test_passes_with_minor_wording_drift(self) -> None:
        ok, _ = classify_docs_index_autogen(
            "<!-- DOC-AUTOGEN: regenerated via build_docs_index command -->"
        )

        self.assertTrue(ok)

    def test_fails_when_marker_missing(self) -> None:
        ok, message = classify_docs_index_autogen(
            "# Unified Donkey Betz - Documentation Index"
        )

        self.assertFalse(ok)
        self.assertIn("python manage.py build_docs_index", message)

    def test_fails_when_first_line_blank(self) -> None:
        ok, message = classify_docs_index_autogen("")

        self.assertFalse(ok)
        self.assertIn("DOC-AUTOGEN marker", message)


if __name__ == "__main__":
    unittest.main()
