from __future__ import annotations

import unittest

from scripts.verify_repo_guardrails import (
    classify_docs_index_autogen,
    classify_failures,
    classify_makefile_pg_application_name,
    classify_platform_inventory_freshness,
    classify_procfile_pg_application_name,
)


class PlatformInventoryFreshnessTests(unittest.TestCase):
    def test_passes_when_recorded_head_matches_current_head(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="abc1234",
            current_head="abc1234",
            current_commit_files=["docs/PLATFORM_INVENTORY.md"],
            parent_head="deadbeef",
        )

        self.assertTrue(ok)
        self.assertIn("matches repo head abc1234", message)

    def test_passes_for_inventory_only_commit_against_parent_head(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="deadbeef",
            current_head="abc1234",
            current_commit_files=["docs/PLATFORM_INVENTORY.md"],
            parent_head="deadbeef",
        )

        self.assertTrue(ok)
        self.assertIn("inventory reflects parent HEAD", message)
        self.assertIn("inventory-only", message)

    def test_fails_for_real_stale_inventory(self) -> None:
        ok, message = classify_platform_inventory_freshness(
            recorded_head="deadbeef",
            current_head="abc1234",
            current_commit_files=["README.md"],
            parent_head="deadbeef",
        )

        self.assertFalse(ok)
        self.assertEqual(message, "inventory head deadbeef != repo head abc1234")


class DocsIndexAutogenMarkerTests(unittest.TestCase):
    def test_passes_with_canonical_marker(self) -> None:
        ok, message = classify_docs_index_autogen(
            "<!-- DOC-AUTOGEN: generated by `python manage.py build_docs_index`; "
            "do not hand-edit. -->"
        )

        self.assertTrue(ok)
        self.assertIn("DOC-AUTOGEN marker", message)

    def test_passes_with_minor_wording_drift(self) -> None:
        ok, _ = classify_docs_index_autogen(
            "<!-- DOC-AUTOGEN: regenerated via build_docs_index command -->"
        )

        self.assertTrue(ok)

    def test_fails_when_marker_missing(self) -> None:
        ok, message = classify_docs_index_autogen(
            "# Unified Donkey Betz - Documentation Index"
        )

        self.assertFalse(ok)
        self.assertIn("python manage.py build_docs_index", message)

    def test_fails_when_first_line_blank(self) -> None:
        ok, message = classify_docs_index_autogen("")

        self.assertFalse(ok)
        self.assertIn("DOC-AUTOGEN marker", message)


class ProcfilePgApplicationNameTests(unittest.TestCase):
    """Session 1166: every Procfile entry must set PG_APPLICATION_NAME=dbz:<role>."""

    def test_passes_on_canonical_procfile_entry(self) -> None:
        ok, messages = classify_procfile_pg_application_name(
            ["web: PG_APPLICATION_NAME=dbz:web daphne -b 0.0.0.0 -p 8000\n"]
        )

        self.assertTrue(ok)
        self.assertIn("Procfile entry `web`: dbz:web", messages)

    def test_fails_when_entry_missing_tag(self) -> None:
        ok, messages = classify_procfile_pg_application_name(
            ["web: daphne -b 0.0.0.0 -p 8000\n"]
        )

        self.assertFalse(ok)
        self.assertTrue(
            any("missing PG_APPLICATION_NAME=dbz:<role>" in m for m in messages),
            messages,
        )

    def test_skips_comment_and_blank_lines(self) -> None:
        ok, messages = classify_procfile_pg_application_name(
            [
                "# top-of-file comment\n",
                "\n",
                "web: PG_APPLICATION_NAME=dbz:web daphne -b 0.0.0.0 -p 8000\n",
            ]
        )

        self.assertTrue(ok)
        self.assertEqual(
            [m for m in messages if "Procfile entry" in m],
            ["Procfile entry `web`: dbz:web"],
        )

    def test_rejects_tag_with_uppercase(self) -> None:
        ok, _ = classify_procfile_pg_application_name(
            ["web: PG_APPLICATION_NAME=dbz:WEB daphne -b 0.0.0.0 -p 8000\n"]
        )

        self.assertFalse(ok)

    def test_accepts_tag_with_digits_and_hyphens(self) -> None:
        ok, messages = classify_procfile_pg_application_name(
            [
                "celery-long-running-2: PG_APPLICATION_NAME=dbz:celery-long-running-2 "
                "celery -A core worker\n"
            ]
        )

        self.assertTrue(ok)
        self.assertIn(
            "Procfile entry `celery-long-running-2`: dbz:celery-long-running-2",
            messages,
        )

    def test_reports_empty_procfile(self) -> None:
        ok, messages = classify_procfile_pg_application_name(["# only a comment\n"])

        self.assertFalse(ok)
        self.assertIn("Procfile has no parseable entries", messages)


class MakefilePgApplicationNameTests(unittest.TestCase):
    """Session 1166: Makefile launches that lack PG_APPLICATION_NAME are advisory-flagged."""

    def test_passes_when_celery_launch_has_tag_inline(self) -> None:
        content = (
            "celery:\n"
            "\tPG_APPLICATION_NAME=dbz:celery-pa celery -A core worker --queues=pa\n"
        )
        ok, messages = classify_makefile_pg_application_name(content)

        self.assertTrue(ok)
        self.assertIn(
            "Makefile celery/daphne launches all set PG_APPLICATION_NAME", messages
        )

    def test_passes_when_tag_set_on_preceding_continuation_line(self) -> None:
        content = (
            "celery:\n"
            "\tPG_APPLICATION_NAME=dbz:celery-pa SKIP_NLP_MODELS=1 \\\n"
            "\tcelery -A core worker --queues=pa\n"
        )
        ok, _ = classify_makefile_pg_application_name(content)

        self.assertTrue(ok)

    def test_flags_celery_launch_without_tag(self) -> None:
        content = (
            "celery:\n"
            "\tcelery -A core worker --queues=pa\n"
        )
        ok, messages = classify_makefile_pg_application_name(content)

        self.assertFalse(ok)
        self.assertTrue(
            any("missing PG_APPLICATION_NAME" in m for m in messages), messages
        )

    def test_does_not_false_positive_on_pkill(self) -> None:
        content = (
            "celery-stop:\n"
            "\tpkill -9 -f celery 2>/dev/null || true\n"
        )
        ok, messages = classify_makefile_pg_application_name(content)

        # No celery/daphne launches matched at all; ok defaults to True.
        self.assertTrue(ok)
        self.assertIn(
            "Makefile has no daphne/celery launches matched by detector", messages
        )


class ClassifyFailuresStrictModeTests(unittest.TestCase):
    """Default strict mode: every blocker should produce a failure entry."""

    def _kwargs(self, **overrides):
        base = dict(
            strict=True,
            inventory_advisory=False,
            tracked_blocking=False,
            inventory_blocking=False,
            autogen_blocking=False,
            conflict_blocking=False,
            procfile_tag_blocking=False,
        )
        base.update(overrides)
        return base

    def test_no_blockers_returns_empty(self):
        self.assertEqual(classify_failures(**self._kwargs()), [])

    def test_strict_fails_on_stale_inventory(self):
        failures = classify_failures(**self._kwargs(inventory_blocking=True))
        self.assertEqual(failures, ["platform inventory is stale"])

    def test_strict_fails_on_tracked_paths(self):
        failures = classify_failures(**self._kwargs(tracked_blocking=True))
        self.assertEqual(failures, ["tracked generated paths are present"])

    def test_strict_fails_on_missing_autogen_marker(self):
        failures = classify_failures(**self._kwargs(autogen_blocking=True))
        self.assertEqual(
            failures,
            ["docs/INDEX.md is missing the DOC-AUTOGEN marker"],
        )

    def test_strict_fails_on_conflict_findings(self):
        failures = classify_failures(**self._kwargs(conflict_blocking=True))
        self.assertEqual(failures, ["context-kit has CONFLICT findings"])

    def test_strict_fails_on_procfile_tag_gap(self):
        failures = classify_failures(**self._kwargs(procfile_tag_blocking=True))
        self.assertEqual(
            failures,
            [
                "one or more Procfile entries are missing "
                "PG_APPLICATION_NAME=dbz:<role>"
            ],
        )

    def test_strict_aggregates_multiple_blockers(self):
        failures = classify_failures(
            **self._kwargs(
                tracked_blocking=True,
                inventory_blocking=True,
                autogen_blocking=True,
                conflict_blocking=True,
                procfile_tag_blocking=True,
            )
        )
        self.assertIn("tracked generated paths are present", failures)
        self.assertIn("platform inventory is stale", failures)
        self.assertIn("docs/INDEX.md is missing the DOC-AUTOGEN marker", failures)
        self.assertIn("context-kit has CONFLICT findings", failures)
        self.assertIn(
            "one or more Procfile entries are missing "
            "PG_APPLICATION_NAME=dbz:<role>",
            failures,
        )
        self.assertEqual(len(failures), 5)


class ClassifyFailuresInventoryAdvisoryTests(unittest.TestCase):
    """``--inventory-advisory`` carves out only the freshness check.

    Every other strict gate continues to block. Intended for PR-time CI
    where ``generate_platform_inventory`` needs DB access the runner
    does not have.
    """

    def _kwargs(self, **overrides):
        base = dict(
            strict=True,
            inventory_advisory=True,
            tracked_blocking=False,
            inventory_blocking=False,
            autogen_blocking=False,
            conflict_blocking=False,
            procfile_tag_blocking=False,
        )
        base.update(overrides)
        return base

    def test_stale_inventory_does_not_block_with_advisory(self):
        failures = classify_failures(**self._kwargs(inventory_blocking=True))
        self.assertEqual(failures, [])

    def test_tracked_paths_still_block_under_advisory(self):
        failures = classify_failures(
            **self._kwargs(tracked_blocking=True, inventory_blocking=True)
        )
        self.assertEqual(failures, ["tracked generated paths are present"])

    def test_autogen_still_blocks_under_advisory(self):
        failures = classify_failures(
            **self._kwargs(autogen_blocking=True, inventory_blocking=True)
        )
        self.assertEqual(
            failures,
            ["docs/INDEX.md is missing the DOC-AUTOGEN marker"],
        )

    def test_conflict_still_blocks_under_advisory(self):
        failures = classify_failures(
            **self._kwargs(conflict_blocking=True, inventory_blocking=True)
        )
        self.assertEqual(failures, ["context-kit has CONFLICT findings"])

    def test_advisory_does_not_revive_no_strict(self):
        # --no-strict + --inventory-advisory: nothing blocks regardless,
        # because strict=False already suppresses every gate.
        failures = classify_failures(
            **self._kwargs(strict=False, inventory_blocking=True)
        )
        self.assertEqual(failures, [])


class ClassifyFailuresNoStrictTests(unittest.TestCase):
    """``--no-strict`` disables every gate; nothing should ever block."""

    def test_no_strict_never_blocks(self):
        failures = classify_failures(
            strict=False,
            inventory_advisory=False,
            tracked_blocking=True,
            inventory_blocking=True,
            autogen_blocking=True,
            conflict_blocking=True,
            procfile_tag_blocking=True,
        )
        self.assertEqual(failures, [])


if __name__ == "__main__":
    unittest.main()
