"""
Impact Event Model — records real downstream value generated by agents.

Session 1089: Autonomy #8 — Impact tracking for IQROI and PortfolioAllocator.

ImpactEvents capture measurable value produced by the system:
- Wager settled with profit → sports desk impact
- Deliverable saved/exported/action_taken → content desk impact
- Revenue confirmed → general impact
- User engagement → weighted content impact

Each event links back to the agent/desk that produced it, enabling
IQROI computation: (impact_value / cost_usd) × quality_weight.
"""

import uuid
from django.conf import settings
from django.db import models


class ImpactEvent(models.Model):
    """
    A single measurable impact event attributed to an agent or desk.

    Aggregated by PortfolioAllocator to compute IQROI per desk/pipeline
    and allocate budget + scheduling priority accordingly.
    """

    IMPACT_TYPES = [
        ('wager_profit', 'Wager Profit/Loss'),
        ('revenue_confirmed', 'Revenue Confirmed'),
        ('content_action', 'Content Action Taken'),
        ('content_save', 'Content Saved'),
        ('content_export', 'Content Exported'),
        ('content_share', 'Content Shared'),
        ('prediction_hit', 'ML Prediction Hit'),
    ]

    DESK_CHOICES = [
        ('sports', 'Sports Betting'),
        ('content', 'Content Pipeline'),
        ('research', 'Research & Analysis'),
        ('career', 'Career & Jobs'),
        ('trading', 'Trading & Finance'),
        ('general', 'General'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # What happened
    impact_type = models.CharField(max_length=30, choices=IMPACT_TYPES, db_index=True)
    desk = models.CharField(max_length=20, choices=DESK_CHOICES, db_index=True)

    # Value
    value_usd = models.DecimalField(
        max_digits=12, decimal_places=4, default=0,
        help_text="Dollar value (negative for losses, e.g. lost wager)",
    )
    impact_points = models.IntegerField(
        default=0,
        help_text="Non-monetary impact points (1=save, 2=export, 5=action_taken)",
    )

    # Attribution
    agent_name = models.CharField(max_length=100, blank=True, db_index=True)
    source_object_type = models.CharField(
        max_length=50, blank=True,
        help_text="Model name: Wager, Deliverable, Revenue, etc.",
    )
    source_object_id = models.UUIDField(null=True, blank=True)
    trace_id = models.UUIDField(
        null=True, blank=True, db_index=True,
        help_text="Orchestration trace_id for cost attribution",
    )

    # Cost attribution (denormalized for fast IQROI queries)
    attributed_cost_usd = models.DecimalField(
        max_digits=10, decimal_places=4, default=0,
        help_text="LLM cost attributed to this impact",
    )

    # Context
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
    )
    metadata = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        app_label = 'core'
        db_table = 'core_impact_events'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['desk', '-created_at']),
            models.Index(fields=['agent_name', '-created_at']),
            models.Index(fields=['impact_type', '-created_at']),
        ]

    def __str__(self):
        return (
            f"{self.impact_type} | {self.desk} | "
            f"${self.value_usd} | {self.agent_name}"
        )

    # ── Impact point weights ──────────────────────────────────────

    POINT_WEIGHTS = {
        'content_save': 1,
        'content_export': 2,
        'content_share': 3,
        'content_action': 5,
        'prediction_hit': 3,
    }

    @classmethod
    def points_for_type(cls, impact_type: str) -> int:
        return cls.POINT_WEIGHTS.get(impact_type, 0)
