"""
Autonomous Alert Models - Session 477

Models for Tier 1 Autonomous Situations:
1. Blockchain Security Monitoring
2. Stock Market Intelligence (extends existing MarketIntelligenceBrief)

These models enable:
- Persistent context (Property #1)
- Output tracking with consequences (Property #4)
- Self-renewal scheduling (Property #5)
"""

import uuid
from decimal import Decimal
from django.db import models
from django.utils import timezone


class BlockchainAlertSeverity(models.TextChoices):
    """Alert severity levels for blockchain security."""
    CRITICAL = 'critical', 'Critical - Active Exploit'
    HIGH = 'high', 'High - Immediate Attention'
    MEDIUM = 'medium', 'Medium - Monitor Closely'
    LOW = 'low', 'Low - Informational'


class BlockchainAlertType(models.TextChoices):
    """Types of blockchain security alerts."""
    WHALE_MOVEMENT = 'whale_movement', 'Whale Movement'
    SUSPICIOUS_TX = 'suspicious_tx', 'Suspicious Transaction'
    CONTRACT_EXPLOIT = 'contract_exploit', 'Contract Exploit'
    FLASH_LOAN = 'flash_loan', 'Flash Loan Attack'
    RUG_PULL = 'rug_pull', 'Rug Pull Warning'
    UNUSUAL_VOLUME = 'unusual_volume', 'Unusual Volume'
    LARGE_TRANSFER = 'large_transfer', 'Large Transfer'
    DEX_ARBITRAGE = 'dex_arbitrage', 'DEX Arbitrage'
    PRICE_MANIPULATION = 'price_manipulation', 'Price Manipulation'
    GOVERNANCE_ATTACK = 'governance_attack', 'Governance Attack'


class BlockchainSecurityAlert(models.Model):
    """
    Blockchain Security Alert - Tier 1 Autonomous Situation Output

    Generated by the Blockchain Audit Coordinator orchestrating:
    - SmartContractAuditorAgent
    - TransactionMonitorAgent
    - WhaleWatcherAgent
    - ExploitDetectorAgent

    Each alert represents a significant finding that warrants user attention.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Alert identification
    alert_type = models.CharField(
        max_length=50,
        choices=BlockchainAlertType.choices,
        db_index=True,
        help_text="Type of security alert"
    )
    severity = models.CharField(
        max_length=20,
        choices=BlockchainAlertSeverity.choices,
        db_index=True,
        help_text="Alert severity level"
    )

    # Target information
    chain = models.CharField(
        max_length=50,
        default='ethereum',
        help_text="Blockchain network (ethereum, polygon, etc.)"
    )
    address = models.CharField(
        max_length=100,
        blank=True,
        help_text="Contract or wallet address involved"
    )
    token_symbol = models.CharField(
        max_length=20,
        blank=True,
        help_text="Token symbol if applicable"
    )

    # Alert content
    title = models.CharField(
        max_length=200,
        help_text="Short alert title"
    )
    summary = models.TextField(
        help_text="Detailed summary of the security finding"
    )

    # Financial impact
    value_usd = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="USD value involved in the alert"
    )

    # Agent analysis
    detecting_agent = models.CharField(
        max_length=100,
        help_text="Which agent detected this alert"
    )
    confidence_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=Decimal('0.50'),
        help_text="Agent confidence in this alert (0-1)"
    )
    analysis_details = models.JSONField(
        default=dict,
        help_text="Detailed analysis from agents"
    )

    # Evidence and sources
    transaction_hash = models.CharField(
        max_length=100,
        blank=True,
        help_text="Transaction hash if applicable"
    )
    source_data = models.JSONField(
        default=dict,
        help_text="Raw source data from spiders"
    )
    evidence_links = models.JSONField(
        default=list,
        help_text="Links to etherscan, etc."
    )

    # Recommendations
    recommended_action = models.TextField(
        blank=True,
        help_text="What user should do"
    )
    risk_score = models.IntegerField(
        default=50,
        help_text="Risk score 0-100"
    )

    # Discord delivery
    discord_sent = models.BooleanField(
        default=False,
        help_text="Whether alert was sent to Discord"
    )
    discord_sent_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When alert was sent"
    )
    discord_message_id = models.CharField(
        max_length=100,
        blank=True,
        help_text="Discord message ID for tracking"
    )

    # User interaction
    acknowledged = models.BooleanField(
        default=False,
        help_text="Whether user acknowledged this alert"
    )
    acknowledged_at = models.DateTimeField(
        null=True,
        blank=True
    )
    user_action_taken = models.TextField(
        blank=True,
        help_text="What action user took in response"
    )

    # Timestamps
    detected_at = models.DateTimeField(
        default=timezone.now,
        db_index=True,
        help_text="When alert was detected"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'core'
        db_table = 'blockchain_security_alert'
        ordering = ['-detected_at']
        indexes = [
            models.Index(fields=['severity', '-detected_at']),
            models.Index(fields=['alert_type', '-detected_at']),
            models.Index(fields=['chain', '-detected_at']),
        ]

    def __str__(self):
        return f"[{self.severity.upper()}] {self.title}"


class BlockchainMonitoringSession(models.Model):
    """
    Tracks each autonomous monitoring cycle.

    This is the "self-renewal" property - each session schedules the next.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Session timing
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    next_session_scheduled = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When next monitoring session is scheduled"
    )

    # Data processed
    spider_data_processed = models.IntegerField(
        default=0,
        help_text="Number of spider data records processed"
    )
    transactions_analyzed = models.IntegerField(
        default=0,
        help_text="Number of transactions analyzed"
    )
    contracts_audited = models.IntegerField(
        default=0,
        help_text="Number of contracts audited"
    )

    # Alerts generated
    alerts_generated = models.IntegerField(
        default=0,
        help_text="Number of alerts generated this session"
    )
    critical_alerts = models.IntegerField(default=0)
    high_alerts = models.IntegerField(default=0)
    medium_alerts = models.IntegerField(default=0)
    low_alerts = models.IntegerField(default=0)

    # Session health
    status = models.CharField(
        max_length=20,
        default='running',
        choices=[
            ('running', 'Running'),
            ('completed', 'Completed'),
            ('failed', 'Failed'),
            ('partial', 'Partial (some errors)'),
        ]
    )
    error_message = models.TextField(
        blank=True,
        help_text="Error details if session failed"
    )

    # Discord summary
    discord_summary_sent = models.BooleanField(default=False)

    class Meta:
        app_label = 'core'
        db_table = 'blockchain_monitoring_session'
        ordering = ['-started_at']


class StockMarketAlert(models.Model):
    """
    Stock Market Alert - Tier 1 Autonomous Situation Output

    Generated by the Market Intelligence Coordinator from Bull vs Bear debates.
    Complements the MarketIntelligenceBrief with real-time alerts.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Alert classification
    alert_type = models.CharField(
        max_length=50,
        choices=[
            ('high_conviction_bull', 'High Conviction Bullish'),
            ('high_conviction_bear', 'High Conviction Bearish'),
            ('debate_zone', 'Debate Zone - Bull vs Bear'),
            ('risk_alert', 'Risk Alert'),
            ('momentum_shift', 'Momentum Shift'),
            ('institutional_activity', 'Institutional Activity'),
            ('anomaly_detected', 'Anomaly Detected'),
            ('earnings_alert', 'Earnings Alert'),
        ],
        db_index=True
    )

    # Stock information
    symbol = models.CharField(
        max_length=20,
        db_index=True,
        help_text="Stock ticker symbol"
    )
    company_name = models.CharField(
        max_length=200,
        blank=True
    )
    sector = models.CharField(
        max_length=100,
        blank=True
    )

    # Alert content
    title = models.CharField(max_length=200)
    summary = models.TextField()

    # Bull vs Bear analysis
    bull_case = models.TextField(
        blank=True,
        help_text="Bull case arguments"
    )
    bear_case = models.TextField(
        blank=True,
        help_text="Bear case arguments"
    )
    disagreement_level = models.CharField(
        max_length=20,
        choices=[
            ('consensus', 'Consensus'),
            ('mild', 'Mild Disagreement'),
            ('strong', 'Strong Disagreement'),
            ('extreme', 'Extreme Disagreement'),
        ],
        default='mild'
    )

    # Confidence and scores
    confidence_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=Decimal('0.50'),
        help_text="Overall confidence (0-1)"
    )
    bull_score = models.IntegerField(
        default=50,
        help_text="Bull strength 0-100"
    )
    bear_score = models.IntegerField(
        default=50,
        help_text="Bear strength 0-100"
    )

    # Price context
    current_price = models.DecimalField(
        max_digits=15,
        decimal_places=4,
        null=True,
        blank=True
    )
    price_change_24h = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
        help_text="24h price change %"
    )

    # Source data
    source_data = models.JSONField(
        default=dict,
        help_text="Spider data and analysis"
    )
    related_brief = models.ForeignKey(
        'core.MarketIntelligenceBrief',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='alerts',
        help_text="Related daily brief if any"
    )

    # Recommended action
    recommended_action = models.CharField(
        max_length=50,
        choices=[
            ('watch', 'Watch'),
            ('research', 'Research Further'),
            ('consider_buy', 'Consider Buying'),
            ('consider_sell', 'Consider Selling'),
            ('hedge', 'Consider Hedging'),
            ('avoid', 'Avoid'),
        ],
        default='watch'
    )

    # Discord delivery
    discord_sent = models.BooleanField(default=False)
    discord_sent_at = models.DateTimeField(null=True, blank=True)
    discord_message_id = models.CharField(max_length=100, blank=True)

    # User interaction
    viewed = models.BooleanField(default=False)
    bookmarked = models.BooleanField(default=False)
    user_notes = models.TextField(blank=True)

    # Timestamps
    detected_at = models.DateTimeField(default=timezone.now, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        app_label = 'core'
        db_table = 'stock_market_alert'
        ordering = ['-detected_at']
        indexes = [
            models.Index(fields=['symbol', '-detected_at']),
            models.Index(fields=['alert_type', '-detected_at']),
        ]

    def __str__(self):
        return f"[{self.alert_type}] {self.symbol}: {self.title}"


class MarketMonitoringSession(models.Model):
    """
    Tracks each stock market autonomous monitoring cycle.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Session timing
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    next_session_scheduled = models.DateTimeField(null=True, blank=True)

    # Data processed
    spider_data_processed = models.IntegerField(default=0)
    stocks_analyzed = models.IntegerField(default=0)

    # Agent activity
    bull_analyses = models.IntegerField(default=0)
    bear_analyses = models.IntegerField(default=0)
    debates_generated = models.IntegerField(default=0)

    # Alerts generated
    alerts_generated = models.IntegerField(default=0)
    high_conviction_count = models.IntegerField(default=0)
    debate_zone_count = models.IntegerField(default=0)
    risk_alerts_count = models.IntegerField(default=0)

    # Session health
    status = models.CharField(
        max_length=20,
        default='running',
        choices=[
            ('running', 'Running'),
            ('completed', 'Completed'),
            ('failed', 'Failed'),
            ('partial', 'Partial'),
        ]
    )
    error_message = models.TextField(blank=True)

    # Brief generated
    brief = models.ForeignKey(
        'core.MarketIntelligenceBrief',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='monitoring_sessions'
    )

    # Discord
    discord_summary_sent = models.BooleanField(default=False)

    class Meta:
        app_label = 'core'
        db_table = 'market_monitoring_session'
        ordering = ['-started_at']
