# Generated by Django 5.0.6 on 2025-12-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_businessresearchresult_project"),
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativepipelinerun",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project to attach outputs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_runs",
                to="core.partnershipproject",
            ),
        ),
    ]
