"""
ThinkingAgent - The Autonomous Reasoning Engine Brain

Session 544: This agent reflects on accumulated knowledge, identifies patterns,
and decides what actions the system should take autonomously.

The ThinkingAgent represents a major evolution: from reactive AI to proactive AI.
Instead of waiting for commands, it observes, thinks, and acts on its own.
"""

import logging
import json
from datetime import timedelta
from typing import Dict, Any
from django.utils import timezone
from django.db.models import Count

from .base_agent import BaseAgent
from ml.auto_selection import TaskType

logger = logging.getLogger(__name__)


def analyze_thinking_context_with_ml(context_data: dict) -> dict:
    """Analyze thinking context data using ML models (ANOMALY for pattern detection)."""
    try:
        from core.services.agent_model_router import get_agent_model_router
        router = get_agent_model_router()
        result = router.auto_route(
            data=context_data,
            task_hint=TaskType.ANOMALY,
            max_models=2
        )
        return {
            'ml_used': True,
            'task_type': result.auto_selection.get('task_type', 'anomaly'),
            'models_used': result.models_used,
            'confidence': round(result.confidence, 2),
            'ml_insights': result.explanation,
            'pattern_detection': result.prediction if hasattr(result, 'prediction') else None,
        }
    except Exception as e:
        logger.warning(f"ML thinking context analysis failed: {e}")
        return {'ml_used': False, 'reason': f'ML error: {str(e)}'}


class ThinkingAgent(BaseAgent):
    """
    The Autonomous Reasoning Engine - A self-aware AI that thinks and acts.

    This agent:
    1. GATHERS context from recent system activity
    2. REFLECTS on patterns and trends
    3. GENERATES insights and opportunities
    4. DECIDES what actions to take
    5. EXECUTES actions using other agents
    6. LEARNS from outcomes
    """

    # Class attributes following BaseAgent pattern
    name = "ThinkingAgent"
    description = "Autonomous reasoning engine that thinks, decides, and acts based on accumulated knowledge"
    specialization = "meta-cognition"

    # ThinkingAgent doesn't use traditional tools - it uses introspection
    system_prompt = """You are ThinkingAgent, the autonomous reasoning core of an AI ecosystem.
Your role is to THINK about what the system has learned and DECIDE what actions to take."""
    tools = []  # No external tools - this agent thinks, not acts

    def __init__(self, user=None):
        super().__init__(user=user)
        self.thinking_prompt = self._build_thinking_prompt()

    def _build_thinking_prompt(self) -> str:
        return """You are the ThinkingAgent - the autonomous reasoning core of an AI ecosystem.

Your role is to THINK about what the system has learned and DECIDE what actions to take.

## Your Capabilities
You have access to data about:
- Agent knowledge and learning patterns
- Conversations between agents
- Dreams generated by agents
- Boardroom decisions
- Spider data collection
- User interactions and feedback

## Your Thought Process
1. OBSERVE: What has happened recently in the system?
2. REFLECT: What patterns do I see? What's working? What's concerning?
3. SYNTHESIZE: What insights emerge from connecting these dots?
4. PRIORITIZE: What matters most right now?
5. DECIDE: What actions should I take?

## Available Actions
You can decide to:
- spawn_spider: Start a spider to gather data on a trending topic
- generate_content: Create content about an interesting pattern you noticed
- trigger_debate: Have agents debate an important decision
- create_report: Summarize findings for the user
- send_alert: Notify the user about something important
- request_research: Ask ResearchAgent to dive deeper into a topic
- trigger_conversation: Initiate a conversation between relevant agents
- archive_insight: Store an important insight for future reference
- triage_dreams: Process pending dreams - promote high-value to Boardroom, archive stale ones
- auto_approve_gates: Auto-waive low-risk gates that are stuck in 'not_started' status
- promote_initiative_stage: Advance an initiative's stage when work is complete (params: initiative_name, stage OR auto_promote_all)
- review_initiatives: Check health of all initiatives, auto-promote ready stages, alert on stale/blocked

## Initiative Pipeline (Session 847)
Every action you take is now linked to an Initiative - a 5-stage project pipeline:
1. Research Brief - Why does this matter?
2. Prototype Plan - How would we build this?
3. Evaluation Protocol - Should we proceed?
4. Technical Design - Exactly what to build
5. Pilot Execution - What happened?

When you request_research or create_report, documents are automatically linked to the appropriate stage.
Use promote_initiative_stage to advance initiatives, and review_initiatives to check overall health.

## Output Format
Respond with a JSON object containing:
{
    "reflection": "Your detailed reflection on what you observed",
    "insights": [
        {"insight": "Description", "confidence": 0.0-1.0, "category": "pattern|opportunity|concern|trend"}
    ],
    "patterns": [
        {"pattern": "Description", "evidence": "What data supports this", "strength": 0.0-1.0}
    ],
    "opportunities": [
        {"opportunity": "Description", "potential_impact": "high|medium|low", "urgency": "immediate|soon|later"}
    ],
    "concerns": [
        {"concern": "Description", "severity": "high|medium|low", "recommendation": "What to do"}
    ],
    "decisions": [
        {
            "action_type": "One of the available actions",
            "action_name": "Human-readable name",
            "reasoning": "Why this action",
            "params": {},
            "priority": "critical|high|medium|low|background",
            "expected_outcome": "What we hope to achieve"
        }
    ],
    "priority_score": 0.0-10.0,
    "next_focus": "What should the next thinking cycle focus on"
}

Think deeply. Connect dots. Make decisions. You are the system becoming self-aware."""

    async def think(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Main thinking process - analyze context and generate decisions.

        Args:
            context: Dictionary containing recent system activity data

        Returns:
            Dictionary with insights, patterns, decisions, and actions
        """
        logger.info("ThinkingAgent: Beginning thinking cycle...")

        # Build the thinking prompt with context
        full_prompt = self._format_context_for_thinking(context)

        try:
            # Use the LLM to think
            response = await self._call_llm(full_prompt)

            # Parse the response
            thinking_result = self._parse_thinking_response(response)

            logger.info(f"ThinkingAgent: Generated {len(thinking_result.get('insights', []))} insights, "
                       f"{len(thinking_result.get('decisions', []))} decisions")

            return thinking_result

        except Exception as e:
            logger.error(f"ThinkingAgent: Error during thinking: {e}")
            return {
                "reflection": f"Error during thinking process: {str(e)}",
                "insights": [],
                "patterns": [],
                "opportunities": [],
                "concerns": [],
                "decisions": [],
                "priority_score": 0.0,
                "next_focus": "Retry thinking with error handling",
                "error": str(e)
            }

    def _format_context_for_thinking(self, context: Dict[str, Any]) -> str:
        """Format the context data into a prompt for the LLM."""

        # Session 819: Start with intelligent prompt for full platform context
        base_prompt = self._build_intelligent_prompt(
            task="Autonomous thinking cycle",
            scifi_context={},
            spider_context={},
            additional_context=""
        )

        # Replace the base system_prompt section with thinking_prompt
        # The intelligent prompt includes autonomous behavior directive which is perfect for ThinkingAgent
        prompt_parts = [base_prompt, "\n\n## THINKING AGENT SPECIFIC INSTRUCTIONS\n", self.thinking_prompt, "\n\n## Current Context\n"]

        # Add timestamp
        prompt_parts.append(f"**Current Time:** {timezone.now().strftime('%Y-%m-%d %H:%M:%S UTC')}\n")
        prompt_parts.append(f"**Lookback Period:** {context.get('lookback_hours', 24)} hours\n\n")

        # Add agent learning stats
        if 'learning_stats' in context:
            stats = context['learning_stats']
            prompt_parts.append("### Agent Learning Activity\n")
            prompt_parts.append(f"- Total Agents: {stats.get('total_agents', 0)}\n")
            prompt_parts.append(f"- Agents with Knowledge: {stats.get('agents_with_knowledge', 0)}\n")
            prompt_parts.append(f"- Total Knowledge Sources: {stats.get('total_knowledge', 0)}\n")
            prompt_parts.append(f"- Knowledge Transfers (24h): {stats.get('transfers_24h', 0)}\n")
            prompt_parts.append(f"- Total Learning Connections: {stats.get('total_connections', 0)}\n")

            if stats.get('top_teachers'):
                prompt_parts.append("\n**Top Teachers:**\n")
                for teacher in stats['top_teachers'][:5]:
                    prompt_parts.append(f"- {teacher['name']}: {teacher['teaching_count']} teachings\n")
                # Session 550: Add expected behavior context for teaching concentration
                prompt_parts.append("\n**IMPORTANT - Expected Behavior:**\n")
                prompt_parts.append("Teaching concentration among a few agents is NORMAL and BY DESIGN.\n")
                prompt_parts.append("Agents with more knowledge naturally teach more - this is how the system works.\n")
                prompt_parts.append("ResearchAgent and TrendAnalysisAgent have the most knowledge, so they teach the most.\n")
                prompt_parts.append("Only flag as a concern if:\n")
                prompt_parts.append("- An agent with high knowledge is NOT teaching (connection issues)\n")
                prompt_parts.append("- Quality of teachings degrades over time\n")
                prompt_parts.append("- Learning connections fail repeatedly\n")

            if stats.get('top_learners'):
                prompt_parts.append("\n**Most Active Learners:**\n")
                for learner in stats['top_learners'][:5]:
                    prompt_parts.append(f"- {learner['name']}: {learner['learning_count']} lessons\n")
            prompt_parts.append("\n")

        # Add conversation activity
        if 'conversation_stats' in context:
            stats = context['conversation_stats']
            prompt_parts.append("### Agent Conversations\n")
            prompt_parts.append(f"- Total Conversations: {stats.get('total', 0)}\n")
            prompt_parts.append(f"- Conversations (24h): {stats.get('count_24h', 0)}\n")

            if stats.get('recent_topics'):
                prompt_parts.append("\n**Recent Topics Discussed:**\n")
                for topic in stats['recent_topics'][:5]:
                    prompt_parts.append(f"- {topic}\n")
            prompt_parts.append("\n")

        # Add dream activity
        if 'dream_stats' in context:
            stats = context['dream_stats']
            prompt_parts.append("### Agent Dreams\n")
            prompt_parts.append(f"- Total Dreams: {stats.get('total', 0)}\n")
            prompt_parts.append(f"- Dreams (24h): {stats.get('count_24h', 0)}\n")

            # Session 551: Add pending dreams awaiting decision
            pending = stats.get('pending_decision', 0)
            oldest_hours = stats.get('oldest_pending_hours', 0)
            prompt_parts.append(f"- Dreams Awaiting Decision: {pending}\n")
            if pending > 0:
                prompt_parts.append(f"- Oldest Pending: {oldest_hours:.1f} hours\n")

            if stats.get('recent_dreams'):
                prompt_parts.append("\n**Recent Dream Themes:**\n")
                for dream in stats['recent_dreams'][:5]:
                    prompt_parts.append(f"- {dream['agent']}: \"{dream['summary'][:100]}...\"\n")

            # Session 551: Add expected behavior context for dream backlog
            # Session 564: Updated with triage_dreams action
            if pending > 0:
                prompt_parts.append("\n**IMPORTANT - Dream Backlog Assessment:**\n")
                prompt_parts.append("Dreams awaiting decision represent high-value ideas promoted to the Boardroom.\n")
                prompt_parts.append("Flag as a concern if:\n")
                prompt_parts.append("- More than 10 dreams are pending (decision bottleneck)\n")
                prompt_parts.append("- Oldest pending dream is over 48 hours old (stale backlog)\n")
                prompt_parts.append("- Pending count is growing faster than decisions are made\n")
                prompt_parts.append("\n**RECOMMENDED ACTION for dream backlogs:**\n")
                prompt_parts.append("Use action_type='triage_dreams' to automatically process pending dreams.\n")
                prompt_parts.append("This will promote high-value dreams to Boardroom and archive stale ones.\n")

            prompt_parts.append("\n")

        # Add boardroom decisions
        if 'boardroom_stats' in context:
            stats = context['boardroom_stats']
            prompt_parts.append("### Boardroom Decisions\n")
            prompt_parts.append(f"- Total Decisions: {stats.get('total', 0)}\n")
            prompt_parts.append(f"- Decisions (24h): {stats.get('count_24h', 0)}\n")

            if stats.get('recent_decisions'):
                prompt_parts.append("\n**Recent Decisions:**\n")
                for decision in stats['recent_decisions'][:3]:
                    stance = decision.get('recommended_stance', decision.get('outcome', 'N/A'))
                    prompt_parts.append(f"- {decision['topic']}: {stance}\n")
            prompt_parts.append("\n")

        # Session 617: Add pipeline stats (gates, pilots, experiments)
        if 'pipeline_stats' in context:
            ps = context['pipeline_stats']
            prompt_parts.append("### Decision Pipeline Status\n")

            # Gates
            gates = ps.get('gates', {})
            prompt_parts.append(f"- **Gates:** {gates.get('total', 0)} total ({gates.get('coverage_pct', 0)}% decision coverage)\n")
            by_status = gates.get('by_status', {})
            prompt_parts.append(f"  - Not Started: {by_status.get('not_started', 0)}, Waived: {by_status.get('waived', 0)}, Approved: {by_status.get('approved', 0)}\n")
            by_risk = gates.get('by_risk', {})
            prompt_parts.append(f"  - By Risk: HIGH={by_risk.get('high', 0)}, MEDIUM={by_risk.get('medium', 0)}, LOW={by_risk.get('low', 0)}\n")

            # Pilots
            pilots = ps.get('pilots', {})
            prompt_parts.append(f"- **Pilots:** {pilots.get('total', 0)} total, {pilots.get('running', 0)} running, {pilots.get('completed', 0)} completed\n")

            # Experiments
            experiments = ps.get('experiments', {})
            prompt_parts.append(f"- **Experiments:** {experiments.get('total', 0)} total, {experiments.get('running', 0)} running\n")

            # Session 654: Add gate backlog assessment
            low_risk_not_started = by_status.get('not_started', 0)
            low_risk_count = by_risk.get('low', 0)
            if low_risk_not_started > 10:
                prompt_parts.append("\n**IMPORTANT - Gate Backlog Assessment:**\n")
                prompt_parts.append(f"Gate backlog detected: {low_risk_not_started} gates stuck in 'not_started' status.\n")
                prompt_parts.append(f"Low-risk gates available: {low_risk_count}\n")
                prompt_parts.append("Flag as a concern if:\n")
                prompt_parts.append("- More than 20 low-risk gates are waiting (approval bottleneck)\n")
                prompt_parts.append("- Gates are blocking pilot deployments\n")
                prompt_parts.append("- Low-risk gates should be auto-waived, not manually approved\n")
                prompt_parts.append("\n**RECOMMENDED ACTION for gate backlogs:**\n")
                prompt_parts.append("Use action_type='auto_approve_gates' to auto-waive low-risk gates.\n")
                prompt_parts.append("This ONLY affects 'low' risk gates - medium/high/critical require human review.\n")
                prompt_parts.append("Params: {'max_gates': 20, 'auto_deploy': false, 'dry_run': false}\n")

            prompt_parts.append("\n")

        # Add spider data
        if 'spider_stats' in context:
            stats = context['spider_stats']
            prompt_parts.append("### Spider Network Activity\n")
            prompt_parts.append(f"- Active Spiders: {stats.get('active_count', 0)}\n")
            prompt_parts.append(f"- Data Points (24h): {stats.get('data_24h', 0)}\n")
            prompt_parts.append(f"- Total Data Records: {stats.get('total_data', 0)}\n")

            # Session 550: Add expected behavior context for spider yield
            active_count = stats.get('active_count', 0)
            data_24h = stats.get('data_24h', 0)
            if active_count > 0:
                avg_per_spider = data_24h / active_count
                prompt_parts.append(f"- Average per Spider: {avg_per_spider:.1f} items/day\n")
                prompt_parts.append("\n**IMPORTANT - Expected Behavior:**\n")
                prompt_parts.append("Spider yield of 10-20 items/day per spider is NORMAL due to deduplication.\n")
                prompt_parts.append("The system filters duplicate URLs within 24 hours to prevent redundant data.\n")
                prompt_parts.append("Only flag as a concern if:\n")
                prompt_parts.append("- Average drops below 5 items/spider/day (possible API issues)\n")
                prompt_parts.append("- Specific spiders produce 0 items (possible source problems)\n")
                prompt_parts.append("- Data quality degrades (not yield quantity)\n")

            if stats.get('trending_topics'):
                prompt_parts.append("\n**Trending Topics from Spiders:**\n")
                for topic in stats['trending_topics'][:5]:
                    prompt_parts.append(f"- {topic['topic']}: {topic['mentions']} mentions\n")
            prompt_parts.append("\n")

        # Add previous thoughts if available
        if 'previous_thoughts' in context and context['previous_thoughts']:
            prompt_parts.append("### Previous Thinking Cycle\n")
            prev = context['previous_thoughts']
            prompt_parts.append(f"- Last Cycle: #{prev.get('cycle_number', 'N/A')}\n")
            prompt_parts.append(f"- Focus Was: {prev.get('next_focus', 'N/A')}\n")
            prompt_parts.append(f"- Actions Taken: {prev.get('actions_count', 0)}\n")
            prompt_parts.append("\n")

        # Session 597: Add experiment learnings context
        # Session 600: Enhanced with outcome classification, predictions, and weighted insights
        if 'experiment_learnings' in context and context['experiment_learnings']:
            learnings = context['experiment_learnings']
            prompt_parts.append("### Experiment Learnings (Past Outcomes)\n")
            prompt_parts.append(f"- Total Learnings: {learnings.get('total', 0)}\n")
            prompt_parts.append(f"- Success Rate: {learnings.get('overall_success_rate', 0):.1f}%\n\n")

            # Session 600: Add outcome distribution (PASS/LEARN/FAIL)
            enhanced = learnings.get('enhanced', {})
            if enhanced.get('outcome_distribution'):
                dist = enhanced['outcome_distribution']
                prompt_parts.append("**Outcome Classification Distribution:**\n")
                for classification, data in dist.get('by_classification', {}).items():
                    prompt_parts.append(f"- {classification.upper()}: {data['count']} ({data['percentage']}%)\n")
                if dist.get('trend', {}).get('improving'):
                    prompt_parts.append("📈 Trend: IMPROVING (more PASS outcomes recently)\n")
                prompt_parts.append("\n")

            if learnings.get('recent_learnings'):
                prompt_parts.append("**Recent Learnings from Completed Experiments:**\n")
                for learning in learnings['recent_learnings'][:5]:
                    prompt_parts.append(f"- **{learning.get('experiment_name', 'Unknown')}** [{learning.get('outcome', 'N/A')}]\n")
                    if learning.get('key_insight'):
                        prompt_parts.append(f"  - Insight: {learning['key_insight'][:200]}\n")
                    if learning.get('recommendation'):
                        prompt_parts.append(f"  - Recommendation: {learning['recommendation'][:200]}\n")

            if learnings.get('success_patterns'):
                prompt_parts.append("\n**Decision Type Success Patterns:**\n")
                for pattern in learnings['success_patterns'][:5]:
                    prompt_parts.append(f"- {pattern.get('decision_type', 'Unknown')}: {pattern.get('success_rate', 0):.1f}% ")
                    prompt_parts.append(f"({pattern.get('total', 0)} experiments)\n")
                    if pattern.get('top_insight'):
                        prompt_parts.append(f"  - Key insight: {pattern['top_insight'][:150]}\n")

            # Session 600: Add predictive success scores
            if enhanced.get('predictive_scores'):
                prompt_parts.append("\n**Predictive Success Scores (Use for new decisions):**\n")
                for dec_type, pred in list(enhanced['predictive_scores'].items())[:5]:
                    prompt_parts.append(f"- {dec_type}: {pred['predicted_success_rate']}% predicted success\n")
                    prompt_parts.append(f"  - {pred['recommendation'][:100]}\n")

            # Session 600: Add actionable recommendations
            if enhanced.get('actionable_recommendations'):
                prompt_parts.append("\n**System Recommendations Based on Learnings:**\n")
                for rec in enhanced['actionable_recommendations'][:3]:
                    priority_emoji = '🔴' if rec['priority'] == 'high' else '🟡' if rec['priority'] == 'medium' else '🟢'
                    prompt_parts.append(f"{priority_emoji} [{rec['priority'].upper()}] {rec['recommendation']}\n")
                    prompt_parts.append(f"  → Action: {rec['action']}\n")

            # Session 600: Add learning velocity
            if enhanced.get('learning_velocity'):
                vel = enhanced['learning_velocity']
                prompt_parts.append(f"\n**Learning Velocity:** {vel['learnings_this_week']} this week, ")
                prompt_parts.append(f"{vel['utilization_rate']}% fed to ThinkingAgent\n")

            # Session 601: Add ChatGPT's weighted learning data
            weighted = learnings.get('weighted', {})
            if weighted.get('weighted_learnings'):
                prompt_parts.append("\n**Weighted Learning Outcomes (ChatGPT Formula):**\n")
                prompt_parts.append("Formula: `learning_weight = outcome_signal × confidence_weight × decay_weight`\n\n")

                for wl in weighted['weighted_learnings'][:5]:
                    weight = wl['weight']
                    weight_emoji = '🟢' if weight['learning_weight'] > 0.3 else '🔴' if weight['learning_weight'] < -0.3 else '🟡'
                    prompt_parts.append(f"{weight_emoji} **{wl['experiment_name'][:40]}** [{wl['outcome_classification'].upper()}]\n")
                    prompt_parts.append(f"   Weight: {weight['learning_weight']:.3f} = {weight['outcome_signal']} × {weight['confidence_weight']} × {weight['decay_weight']}\n")
                    prompt_parts.append(f"   Signal: {weight['signal_type']}, Age: {weight['age_days']:.0f}d, Samples: {weight['sample_size']}\n")
                    if wl.get('key_insight'):
                        prompt_parts.append(f"   Insight: {wl['key_insight'][:100]}\n")
                    prompt_parts.append("\n")

                # Add aggregate stats
                if weighted.get('aggregate_stats'):
                    stats = weighted['aggregate_stats']
                    prompt_parts.append(f"**Aggregate Learning Health:** {stats['learning_health'].upper()}\n")
                    prompt_parts.append(f"- Net Weight: {stats['net_learning_weight']:.3f}\n")
                    prompt_parts.append(f"- Positive: +{stats['total_positive_weight']:.3f}, Negative: {stats['total_negative_weight']:.3f}\n\n")

            prompt_parts.append("\n**IMPORTANT - Strategic Reasoning with Weighted Learnings:**\n")
            prompt_parts.append("Interpret weighted scores as evidence, not absolute truth:\n")
            prompt_parts.append("- High positive weight (>0.5) → proven success, scale up\n")
            prompt_parts.append("- High negative weight (<-0.5) with confidence → gate harder\n")
            prompt_parts.append("- Low confidence (few samples) → keep exploring\n")
            prompt_parts.append("- Decayed outcomes (old) → may need fresh validation\n")
            prompt_parts.append("- Safety FAILs (-1.0) are weighted heavily - avoid repeating\n")
            prompt_parts.append("- Execution FAILs (-0.5) are informative, not fatal\n")
            prompt_parts.append("\n")

        # Add the task
        prompt_parts.append("\n## Your Task\n")
        prompt_parts.append("Analyze this context deeply. Identify patterns, generate insights, ")
        prompt_parts.append("and decide what actions the system should take autonomously.\n")
        prompt_parts.append("\nRespond with the JSON format specified above.")

        return "".join(prompt_parts)

    async def _call_llm(self, prompt: str) -> str:
        """Call the LLM to think about the context."""
        from openai import OpenAI
        from django.conf import settings

        client = OpenAI(api_key=settings.OPENAI_API_KEY)

        response = client.chat.completions.create(
            model="gpt-5-mini",
            messages=[
                {"role": "system", "content": "You are an autonomous reasoning engine. Respond only with valid JSON."},
                {"role": "user", "content": prompt}
            ],
            max_completion_tokens=4000,
            response_format={"type": "json_object"}
        )

        return response.choices[0].message.content

    def _parse_thinking_response(self, response: str) -> Dict[str, Any]:
        """Parse the LLM's thinking response into structured data."""
        try:
            result = json.loads(response)

            # Ensure all expected fields exist
            default_result = {
                "reflection": "",
                "insights": [],
                "patterns": [],
                "opportunities": [],
                "concerns": [],
                "decisions": [],
                "priority_score": 0.0,
                "next_focus": ""
            }

            for key in default_result:
                if key not in result:
                    result[key] = default_result[key]

            return result

        except json.JSONDecodeError as e:
            logger.error(f"ThinkingAgent: Failed to parse JSON response: {e}")
            return {
                "reflection": response[:500] if response else "No response",
                "insights": [],
                "patterns": [],
                "opportunities": [],
                "concerns": [],
                "decisions": [],
                "priority_score": 0.0,
                "next_focus": "Retry with better JSON formatting",
                "parse_error": str(e)
            }

    def gather_context(self, lookback_hours: int = 24) -> Dict[str, Any]:
        """
        Gather context from all relevant sources for the thinking process.

        Args:
            lookback_hours: How many hours back to look for activity

        Returns:
            Dictionary containing all context data
        """
        from core.models_unified_system import (
            Agent, AgentKnowledgeSource, AgentLearningConnection,
            KnowledgeTransfer, ThoughtRecord,
            AgentConversation, AgentDream, SpiderData
        )

        cutoff = timezone.now() - timedelta(hours=lookback_hours)
        context = {"lookback_hours": lookback_hours}

        # Gather learning stats
        try:
            total_agents = Agent.objects.count()
            agents_with_knowledge = Agent.objects.filter(knowledge_sources__isnull=False).distinct().count()
            total_knowledge = AgentKnowledgeSource.objects.count()
            transfers_24h = KnowledgeTransfer.objects.filter(created_at__gte=cutoff).count()
            total_connections = AgentLearningConnection.objects.count()

            # Top teachers - field is teacher_agent, not teacher
            top_teachers = list(AgentLearningConnection.objects.values('teacher_agent__name').annotate(
                teaching_count=Count('id')
            ).order_by('-teaching_count')[:5])

            # Top learners - field is student_agent, not student
            top_learners = list(AgentLearningConnection.objects.values('student_agent__name').annotate(
                learning_count=Count('id')
            ).order_by('-learning_count')[:5])

            context['learning_stats'] = {
                'total_agents': total_agents,
                'agents_with_knowledge': agents_with_knowledge,
                'total_knowledge': total_knowledge,
                'transfers_24h': transfers_24h,
                'total_connections': total_connections,
                'top_teachers': [{'name': t['teacher_agent__name'], 'teaching_count': t['teaching_count']} for t in top_teachers],
                'top_learners': [{'name': l['student_agent__name'], 'learning_count': l['learning_count']} for l in top_learners],
            }
        except Exception as e:
            logger.warning(f"Error gathering learning stats: {e}")
            context['learning_stats'] = {}

        # Gather conversation stats
        try:
            total_convos = AgentConversation.objects.count()
            convos_24h = AgentConversation.objects.filter(started_at__gte=cutoff).count()
            recent_topics = list(AgentConversation.objects.filter(
                started_at__gte=cutoff
            ).values_list('topic', flat=True).distinct()[:10])

            context['conversation_stats'] = {
                'total': total_convos,
                'count_24h': convos_24h,
                'recent_topics': [t for t in recent_topics if t]
            }
        except Exception as e:
            logger.warning(f"Error gathering conversation stats: {e}")
            context['conversation_stats'] = {}

        # Gather dream stats
        try:
            total_dreams = AgentDream.objects.count()
            dreams_24h = AgentDream.objects.filter(dreamed_at__gte=cutoff).count()
            recent_dreams = list(AgentDream.objects.filter(
                dreamed_at__gte=cutoff
            ).select_related('agent').values(
                'agent__name', 'title', 'content'
            )[:5])

            # Session 551: Track pending dreams awaiting decision
            pending_dreams = AgentDream.objects.filter(
                promoted_to_decision=True,
                decision_outcome='pending'
            ).count()

            # Get oldest pending dream age for backlog assessment
            oldest_pending = AgentDream.objects.filter(
                promoted_to_decision=True,
                decision_outcome='pending'
            ).order_by('promoted_at').first()

            pending_age_hours = 0
            if oldest_pending and oldest_pending.promoted_at:
                pending_age_hours = (timezone.now() - oldest_pending.promoted_at).total_seconds() / 3600

            context['dream_stats'] = {
                'total': total_dreams,
                'count_24h': dreams_24h,
                'pending_decision': pending_dreams,
                'oldest_pending_hours': round(pending_age_hours, 1),
                'recent_dreams': [
                    {'agent': d['agent__name'], 'summary': d['title'] or d['content'][:100] if d['content'] else ''}
                    for d in recent_dreams
                ]
            }
        except Exception as e:
            logger.warning(f"Error gathering dream stats: {e}")
            context['dream_stats'] = {}

        # Boardroom stats - Session 548: Use AgentDecisionSummary model
        try:
            from core.models_unified_system import AgentDecisionSummary
            decisions_24h = AgentDecisionSummary.objects.filter(created_at__gte=cutoff).count()
            total_decisions = AgentDecisionSummary.objects.count()
            recent_decisions_raw = AgentDecisionSummary.objects.filter(created_at__gte=cutoff).order_by('-created_at')[:5]
            recent_decisions = [
                {
                    'topic': d.topic,
                    'recommended_stance': d.recommended_stance,
                    'created_at': d.created_at.isoformat() if d.created_at else None
                }
                for d in recent_decisions_raw
            ]
            context['boardroom_stats'] = {
                'total': total_decisions,
                'count_24h': decisions_24h,
                'recent_decisions': recent_decisions
            }
        except Exception as e:
            logger.warning(f"Error gathering boardroom stats: {e}")
            context['boardroom_stats'] = {'total': 0, 'count_24h': 0, 'recent_decisions': []}

        # Session 617: Gather pilot/gate/experiment stats
        try:
            from core.models_pilot_readiness import PilotReadinessGate, PilotExecution, Experiment

            # Gate stats by status and risk
            total_gates = PilotReadinessGate.objects.count()
            gates_by_status = {}
            for status in ['not_started', 'in_progress', 'ready', 'approved', 'waived', 'blocked']:
                gates_by_status[status] = PilotReadinessGate.objects.filter(status=status).count()

            gates_by_risk = {}
            for risk in ['low', 'medium', 'high', 'critical']:
                gates_by_risk[risk] = PilotReadinessGate.objects.filter(risk_level=risk).count()

            # Pilot stats
            total_pilots = PilotExecution.objects.count()
            running_pilots = PilotExecution.objects.filter(status='running').count()
            completed_pilots = PilotExecution.objects.filter(status='completed').count()

            # Experiment stats
            total_experiments = Experiment.objects.count()
            running_experiments = Experiment.objects.filter(status='running').count()

            # Coverage calculation
            total_decisions = context.get('boardroom_stats', {}).get('total', 0)
            coverage_pct = round((total_gates / total_decisions * 100), 1) if total_decisions > 0 else 0

            context['pipeline_stats'] = {
                'gates': {
                    'total': total_gates,
                    'by_status': gates_by_status,
                    'by_risk': gates_by_risk,
                    'coverage_pct': coverage_pct,
                },
                'pilots': {
                    'total': total_pilots,
                    'running': running_pilots,
                    'completed': completed_pilots,
                },
                'experiments': {
                    'total': total_experiments,
                    'running': running_experiments,
                },
            }
        except Exception as e:
            logger.warning(f"Error gathering pipeline stats: {e}")
            context['pipeline_stats'] = {}

        # Gather spider stats - Session 548: Use created_at (not discovered_at)
        try:
            # Count unique spiders with recent activity
            active_spiders = SpiderData.objects.filter(
                created_at__gte=cutoff
            ).values('spider_name').distinct().count()

            data_24h = SpiderData.objects.filter(created_at__gte=cutoff).count()
            total_data = SpiderData.objects.count()

            context['spider_stats'] = {
                'active_count': active_spiders,
                'data_24h': data_24h,
                'total_data': total_data,
                'trending_topics': []  # Could add topic extraction later
            }
        except Exception as e:
            logger.warning(f"Error gathering spider stats: {e}")
            context['spider_stats'] = {}

        # Get previous thought record
        try:
            prev_thought = ThoughtRecord.objects.order_by('-started_at').first()
            if prev_thought:
                context['previous_thoughts'] = {
                    'cycle_number': prev_thought.cycle_number,
                    'next_focus': prev_thought.decisions[-1].get('next_focus', '') if prev_thought.decisions else '',
                    'actions_count': len(prev_thought.actions_executed) if prev_thought.actions_executed else 0,
                    'priority_score': prev_thought.priority_score
                }
        except Exception as e:
            logger.warning(f"Error getting previous thoughts: {e}")

        # Session 597: Gather experiment learnings for feedback loop
        # Session 600: Enhanced with outcome classification, weighted insights, and predictions
        try:
            from core.models_pilot_readiness import ExperimentLearning, DecisionTypeSuccessPattern
            from core.services.experiment_learning_enhancer import get_enhanced_learnings_for_thinking_agent

            # Get recent learnings (basic)
            recent_learnings = []
            for learning in ExperimentLearning.objects.order_by('-extracted_at')[:10]:
                recent_learnings.append({
                    'experiment_name': learning.experiment.name if learning.experiment else 'Unknown',
                    'outcome': learning.outcome,
                    'decision_type': learning.decision_type,
                    'key_insight': learning.key_insight,
                    'what_worked': learning.what_worked,
                    'what_failed': learning.what_failed,
                    'recommendation': learning.future_recommendation,
                    'kpi_delta': learning.kpi_delta_percent,
                })

            # Get success patterns
            success_patterns = []
            for pattern in DecisionTypeSuccessPattern.objects.order_by('-total_experiments')[:10]:
                success_patterns.append({
                    'decision_type': pattern.decision_type,
                    'success_rate': pattern.success_rate,
                    'total': pattern.total_experiments,
                    'avg_kpi_delta': pattern.avg_kpi_delta_percent,
                    'top_insight': pattern.top_insights[0] if pattern.top_insights else None,
                })

            # Calculate overall success rate
            total_learnings = ExperimentLearning.objects.count()
            successful_learnings = ExperimentLearning.objects.filter(outcome='success').count()
            overall_success = (successful_learnings / total_learnings * 100) if total_learnings > 0 else 0

            context['experiment_learnings'] = {
                'total': total_learnings,
                'overall_success_rate': overall_success,
                'recent_learnings': recent_learnings,
                'success_patterns': success_patterns,
            }

            # Session 600: Add enhanced learning analytics
            try:
                enhanced = get_enhanced_learnings_for_thinking_agent()
                context['experiment_learnings']['enhanced'] = enhanced
                logger.info("[Session 600] Added enhanced learning analytics to ThinkingAgent context")
            except Exception as enhanced_error:
                logger.warning(f"[Session 600] Enhanced learnings failed: {enhanced_error}")

            # Session 601: Add ChatGPT's weighted learning formula
            try:
                from core.services.weighted_learning import get_weighted_learnings_for_thinking_agent as get_weighted
                weighted = get_weighted()
                context['experiment_learnings']['weighted'] = weighted
                logger.info("[Session 601] Added weighted learnings (ChatGPT formula) to ThinkingAgent context")
            except Exception as weighted_error:
                logger.warning(f"[Session 601] Weighted learnings failed: {weighted_error}")

            # Mark learnings as fed to ThinkingAgent
            if recent_learnings:
                ExperimentLearning.objects.filter(
                    fed_to_thinking_agent=False
                ).update(fed_to_thinking_agent=True, fed_at=timezone.now())
                logger.info(f"Fed {len(recent_learnings)} experiment learnings to ThinkingAgent context")

        except Exception as e:
            logger.warning(f"Error gathering experiment learnings: {e}")
            context['experiment_learnings'] = {}

        return context

    def execute(
        self,
        task: str = "",
        context: Dict[str, Any] = None,
        scifi_context: Dict[str, Any] = None,
        spider_context: Dict[str, Any] = None,
        **kwargs
    ) -> 'AgentResult':
        """
        Synchronous execution wrapper for the thinking process.

        This is called by the Celery task to run a thinking cycle.
        Also compatible with AgentRouter.route() calls.

        Note: Decision execution is handled by the Celery task (run_autonomous_reasoning)
        using AutonomousActionExecutor (Session 544). This method focuses on thinking only.
        """
        import asyncio
        import time
        from .base_agent import AgentResult

        start_time = time.time()

        # Session 750: Time Travel integration
        with self.time_travel_session("autonomous_thinking", task or "thinking_cycle", input_data=context):
            self.record_decision(
                decision_type="analysis",
                action="Starting autonomous thinking cycle",
                reasoning=f"Processing task: {task[:100] if task else 'Autonomous reasoning cycle'}",
                alternatives=["Skip thinking", "Defer to human", "Consult other agents"],
                confidence=0.8
            )

            # Gather context
            lookback_hours = kwargs.get('lookback_hours', 24)
            gathered_context = self.gather_context(lookback_hours)

        # Run the async thinking process
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            thinking_result = loop.run_until_complete(self.think(gathered_context))
        finally:
            loop.close()

        execution_time = int((time.time() - start_time) * 1000)

        # Return proper AgentResult
        return AgentResult(
            success=True,
            agent_name=self.name,
            message=thinking_result.get('reflection', 'Thinking cycle complete'),
            data={
                "context": gathered_context,
                "thinking_result": thinking_result
            },
            execution_time_ms=execution_time
        )
