"""
Action Plan Formatter

Creates beautiful, professional action plans instead of raw JSON dumps
"""

from datetime import datetime
from typing import Dict, Any, List


class ActionPlanFormatter:
    """Format action plans into beautiful, actionable documents"""

    def format_complete_plan(self, plan_data: Dict[str, Any]) -> str:
        """Create a beautifully formatted complete action plan"""

        opportunity = plan_data.get('opportunity_title', 'Business Opportunity')
        plan_id = plan_data.get('id', 'unknown')
        steps = plan_data.get('steps', [])
        timeline = plan_data.get('timeline', '4 weeks')

        # Extract actual AI-generated content from steps
        step_contents = []
        for i, step in enumerate(steps, 1):
            step_data = plan_data.get(f'step_{i}_data', {})
            ai_content = step_data.get('ai_content', '')
            if ai_content:
                step_contents.append({
                    'number': i,
                    'title': step,
                    'content': ai_content
                })

        # Build the complete plan with ACTUAL AI-generated content
        formatted_plan = f"""# 🚀 {opportunity} - Complete Action Plan

## 📋 Executive Summary
Your personalized roadmap for {opportunity.lower()} success, powered by AI-generated insights and real market data.

**Timeline:** {timeline}
**Total Steps:** {len(steps)}
**Status:** Ready for Execution

---

## 📊 Action Steps Overview

"""
        # Add each step's title as overview
        for i, step in enumerate(steps, 1):
            formatted_plan += f"{i}. {step}\n"

        formatted_plan += "\n---\n\n## 🎯 Detailed Action Plan\n\n"

        # Now add the ACTUAL AI-generated content for each step
        for step_info in step_contents:
            formatted_plan += f"### Step {step_info['number']}: {step_info['title']}\n\n"
            formatted_plan += step_info['content']
            formatted_plan += "\n\n---\n\n"

        # Add platform tools and resources section
        formatted_plan += """## 🛠️ Platform Tools & Resources

### AI-Powered Tools Available
- **AI Content Studio** - Create visual assets and branding
- **Content-Creator Agent** - Generate high-quality written content
- **Research Agent** - Market analysis and competitor research
- **Revenue Engine** - Payment processing and invoicing
- **ML Analytics** - Performance tracking and optimization

### Quick Access Links
- 🎨 Launch AI Content Studio
- 🤖 Deploy Specialized Agents
- 💳 Configure Revenue Engine
- 📊 View Analytics Dashboard

---

## 💰 Revenue Potential

Based on market research and platform capabilities:
- **Week 1-2:** $0-$500 (Setup & First Clients)
- **Week 3-4:** $500-$2,000 (Growth Phase)
- **Month 2:** $2,000-$5,000 (Scaling)
- **Month 3+:** $5,000-$10,000+ (Optimized)

---

## ✅ Success Tips

1. **Leverage Platform Tools** - Use built-in AI capabilities instead of external services
2. **Start Small, Scale Fast** - Begin with 1-2 clients, then rapidly expand
3. **Automate Everything** - Use agents to handle repetitive tasks
4. **Track & Optimize** - Monitor metrics and continuously improve
5. **Build Relationships** - Focus on client satisfaction for referrals

---

*Generated by Income Builder AI System*
*Powered by Real Market Data & AI Analysis*
"""

        return formatted_plan

        return formatted_plan

    def format_step_content(self, step_data: Dict[str, Any], step_number: int) -> str:
        """Format individual step content"""

        step_title = step_data.get('title', f'Step {step_number}')
        ai_content = step_data.get('ai_content', '')
        real_data = step_data.get('real_data', {})

        # Extract useful data from real_data - handle both dict and list formats
        search_results_data = real_data.get('search_results', {})
        search_results = []

        # Handle different formats of search_results
        if isinstance(search_results_data, dict):
            search_results = search_results_data.get('results', [])
        elif isinstance(search_results_data, list):
            search_results = search_results_data

        market_insights = []

        for result in search_results[:3]:
            # Handle both dict and other formats
            if isinstance(result, dict) and result.get('snippet'):
                market_insights.append(f"• {result['snippet']}")

        formatted_step = f"""# Step {step_number}: {step_title}

## 🎯 Objective
{ai_content if ai_content and 'Error' not in ai_content else f'Complete {step_title.lower()} using platform tools'}

## 📊 Market Intelligence
{chr(10).join(market_insights) if market_insights else '• Leverage platform analytics for insights'}

## ✅ Action Items
1. Use AI Content Studio for visual assets
2. Deploy specialized agents for automation
3. Track progress with ML Analytics
4. Optimize based on real-time data

## 🛠️ Platform Tools
- **Primary:** AI Content Studio, Content-Creator Agent
- **Support:** ML Analytics, Revenue Engine
- **Advanced:** Agent Network, Distribution System

## 📈 Success Metrics
- Task completion: 100%
- Time saved: 75% vs manual
- Cost saved: $200+ vs external tools

---
*Powered by Platform AI*
"""

        return formatted_step

    def format_quickstart_guide(self, plan_data: Dict[str, Any]) -> str:
        """Create a quickstart guide"""

        opportunity = plan_data.get('opportunity_title', 'Business Opportunity')

        quickstart = f"""# ⚡ {opportunity} - Quick Start Guide

## 🚀 Start in 5 Minutes

### Step 1: Brand Creation (2 min)
```
1. Open AI Content Studio
2. Generate logo with prompt: "Professional logo for {opportunity.lower()}"
3. Save brand assets
```

### Step 2: Service Setup (2 min)
```
1. Deploy Content-Creator Agent
2. Generate service description
3. Create pricing tiers
```

### Step 3: Launch (1 min)
```
1. Activate Revenue Engine
2. Enable payment processing
3. Go live!
```

## 🎯 First 24 Hours Checklist

⏰ **Hour 1-2:** Setup
- [ ] Create brand identity
- [ ] Write service description
- [ ] Set pricing

⏰ **Hour 3-4:** Content
- [ ] Generate 5 marketing posts
- [ ] Create email templates
- [ ] Build FAQ

⏰ **Hour 5-8:** Outreach
- [ ] Find 20 prospects
- [ ] Send 10 proposals
- [ ] Schedule follow-ups

⏰ **Hour 9-24:** Optimize
- [ ] Track responses
- [ ] Adjust messaging
- [ ] Book first calls

## 💰 Quick Revenue Path

**Day 1:** Setup + First outreach = 0 clients
**Day 3:** Follow-ups + Calls = 1-2 clients
**Day 7:** Referrals + Growth = 3-5 clients
**Day 14:** Systems + Scale = 10+ clients
**Day 30:** Automation + Optimize = $3,000+ MRR

---

*No external tools needed - everything included in platform!*
"""

        return quickstart


# Global formatter instance
action_plan_formatter = ActionPlanFormatter()

def format_action_plan(plan_data: Dict[str, Any]) -> Dict[str, str]:
    """Format action plan data into beautiful documents"""

    formatter = ActionPlanFormatter()

    return {
        'complete_plan': formatter.format_complete_plan(plan_data),
        'quickstart': formatter.format_quickstart_guide(plan_data)
    }