/**
 * Session 971b: Data & Intel Tab — merged view of DataSources + Intelligence.
 *
 * B1: Adapter delegating to original tab components (double nav).
 * B3: Now passes controlledSubTab to suppress inner nav — single unified nav.
 */

import { useState } from 'react'
import {
  Globe,
  Rss,
  BookOpen,
  Brain,
  Shield,
  Users,
  TrendingUp,
  GraduationCap,
  Loader2,
} from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { cn } from '@/lib/cn'
import { DataSourcesTab } from './DataSourcesTab'
import { IntelligenceTab } from './IntelligenceTab'
import type { DataIntelSubTab } from '../types'

interface DataIntelTabProps {
  initialSubTab?: string
}

type DelegateView = 'data' | 'intel' | 'predictions' | 'skills'

const subTabs: Array<{
  id: DataIntelSubTab
  label: string
  icon: typeof Globe
  delegate: DelegateView
}> = [
  // From DataSources
  { id: 'spiders', label: 'Spiders', icon: Globe, delegate: 'data' },
  { id: 'feed', label: 'Feed', icon: Rss, delegate: 'data' },
  { id: 'learning', label: 'Learning', icon: BookOpen, delegate: 'data' },
  // From Intelligence
  { id: 'reasoning', label: 'Reasoning', icon: Brain, delegate: 'intel' },
  { id: 'safety', label: 'Safety', icon: Shield, delegate: 'intel' },
  { id: 'collective', label: 'Collective', icon: Users, delegate: 'intel' },
  // Surfaced orphan data
  { id: 'predictions', label: 'Viral Predictions', icon: TrendingUp, delegate: 'predictions' },
  { id: 'skills', label: 'Skill Gaps', icon: GraduationCap, delegate: 'skills' },
]

export function DataIntelTab({ initialSubTab }: DataIntelTabProps) {
  const initial = (initialSubTab && subTabs.some(t => t.id === initialSubTab)
    ? initialSubTab
    : 'spiders') as DataIntelSubTab

  const [activeSubTab, setActiveSubTab] = useState<DataIntelSubTab>(initial)

  const current = subTabs.find(t => t.id === activeSubTab)
  const delegate = current?.delegate ?? 'data'

  return (
    <div className="space-y-4">
      {/* Unified sub-tab nav */}
      <div className="flex gap-2 overflow-x-auto pb-2">
        {subTabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveSubTab(tab.id)}
            className={cn(
              'flex items-center gap-2 px-3 py-2 rounded-lg text-sm whitespace-nowrap transition-colors',
              activeSubTab === tab.id
                ? 'bg-primary-500/20 text-primary-400 border border-primary-500/30'
                : 'bg-gray-800/50 text-gray-400 hover:bg-gray-800 hover:text-white'
            )}
          >
            <tab.icon size={14} />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Session 971b B3: controlledSubTab suppresses inner nav — single nav level */}
      {delegate === 'data' && <DataSourcesTab controlledSubTab={activeSubTab} />}
      {delegate === 'intel' && <IntelligenceTab controlledSubTab={activeSubTab} />}
      {delegate === 'predictions' && <ViralPredictionsPanel />}
      {delegate === 'skills' && <SkillGapsPanel />}
    </div>
  )
}


function ViralPredictionsPanel() {
  const { data, isLoading } = useQuery({
    queryKey: ['viral-predictions'],
    queryFn: async () => {
      const r = await fetch('/api/autonomous/viral-predictions/?limit=50', { credentials: 'include' })
      if (!r.ok) return null
      return r.json()
    },
    staleTime: 60000,
  })

  const items = data?.items || []

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-gray-300 flex items-center gap-2">
          <TrendingUp size={14} className="text-primary-400" />
          Viral Content Predictions ({data?.total || 0})
        </h3>
        <span className="text-xs text-gray-500">Auto-generated by spider analysis</span>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-8"><Loader2 size={20} className="animate-spin text-primary-400" /></div>
      ) : items.length === 0 ? (
        <div className="card p-8 text-center text-gray-500">No viral predictions yet.</div>
      ) : (
        <div className="space-y-2">
          {items.map((item: Record<string, unknown>) => (
            <div key={item.id as string} className="card p-4 hover:border-primary-500/30 transition-colors">
              <div className="flex items-start justify-between mb-2">
                <div className="flex-1 min-w-0">
                  <h4 className="text-sm font-medium text-white truncate">{item.title as string}</h4>
                  <p className="text-xs text-gray-500 mt-0.5">{item.topic as string} &middot; {item.content_type as string}</p>
                </div>
                <div className="flex items-center gap-2 flex-shrink-0 ml-3">
                  <span className={cn(
                    'px-2 py-0.5 rounded text-xs font-bold',
                    (item.viral_score as number) >= 0.7 ? 'bg-green-500/20 text-green-400' :
                    (item.viral_score as number) >= 0.4 ? 'bg-yellow-500/20 text-yellow-400' :
                    'bg-gray-700 text-gray-400'
                  )}>
                    {((item.viral_score as number) * 100).toFixed(0)}% viral
                  </span>
                </div>
              </div>
              <div className="flex flex-wrap gap-3 text-xs text-gray-500">
                <span>Engagement: {((item.engagement_potential as number) * 100).toFixed(0)}%</span>
                <span>Shareability: {((item.shareability_score as number) * 100).toFixed(0)}%</span>
                <span>Timing: {((item.timing_score as number) * 100).toFixed(0)}%</span>
                {item.emotional_trigger && <span className="text-amber-400">{item.emotional_trigger as string}</span>}
              </div>
              {Array.isArray(item.recommended_platforms) && (item.recommended_platforms as string[]).length > 0 && (
                <div className="flex flex-wrap gap-1 mt-2">
                  {(item.recommended_platforms as string[]).map((p: string) => (
                    <span key={p} className="px-1.5 py-0.5 rounded bg-dark-border text-[10px] text-gray-400">{p}</span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}


function SkillGapsPanel() {
  const { data, isLoading } = useQuery({
    queryKey: ['skill-gaps'],
    queryFn: async () => {
      const r = await fetch('/api/autonomous/skill-gaps/?limit=50', { credentials: 'include' })
      if (!r.ok) return null
      return r.json()
    },
    staleTime: 60000,
  })

  const items = data?.items || []

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-sm font-medium text-gray-300 flex items-center gap-2">
          <GraduationCap size={14} className="text-primary-400" />
          Skill Gap Analysis ({data?.total || 0})
        </h3>
        <span className="text-xs text-gray-500">Market demand from spider intelligence</span>
      </div>

      {isLoading ? (
        <div className="flex justify-center py-8"><Loader2 size={20} className="animate-spin text-primary-400" /></div>
      ) : items.length === 0 ? (
        <div className="card p-8 text-center text-gray-500">No skill gap analyses yet.</div>
      ) : (
        <div className="card overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-gray-500 border-b border-dark-border">
                <th className="p-3">Skill</th>
                <th className="p-3">Category</th>
                <th className="p-3 text-right">Demand Score</th>
                <th className="p-3">Trend</th>
                <th className="p-3 text-right">Salary Premium</th>
                <th className="p-3">Sources</th>
              </tr>
            </thead>
            <tbody>
              {items.map((item: Record<string, unknown>) => (
                <tr key={item.id as string} className="border-b border-dark-border/50 hover:bg-dark-border/20">
                  <td className="p-3 text-white font-medium">{item.skill_name as string}</td>
                  <td className="p-3">
                    <span className="px-2 py-0.5 rounded bg-primary-500/20 text-primary-400 text-xs">
                      {item.category as string}
                    </span>
                  </td>
                  <td className="p-3 text-right">
                    <span className={cn(
                      'font-bold',
                      (item.demand_score as number) >= 1000 ? 'text-green-400' :
                      (item.demand_score as number) >= 500 ? 'text-yellow-400' : 'text-gray-400'
                    )}>
                      {(item.demand_score as number).toLocaleString()}
                    </span>
                  </td>
                  <td className="p-3">
                    <span className={cn(
                      'text-xs',
                      item.demand_trend === 'rising' ? 'text-green-400' :
                      item.demand_trend === 'stable' ? 'text-gray-400' : 'text-red-400'
                    )}>
                      {item.demand_trend as string}
                    </span>
                  </td>
                  <td className="p-3 text-right text-emerald-400">
                    {(item.avg_salary_premium as number) > 0 ? `+$${((item.avg_salary_premium as number) / 1000).toFixed(0)}K` : '—'}
                  </td>
                  <td className="p-3 text-gray-500 text-xs">
                    {Array.isArray(item.source_spiders) ? (item.source_spiders as string[]).join(', ') : '—'}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
