"""
Agent Execution and Output Views

This module handles actual agent execution and displays their generated outputs.
Now supports both demo mode (fast, pre-generated) and real mode (LLM-powered).
"""

# PARTIAL — Session 1113 review (Session 1111 PR-B/PR-E queue).
# Classification: built but not URL-mounted.
# Why: views are reached only via `agents/urls_deployment.py`, which is
# never included from any active URLConf. The module also lazy-imports
# `views_deployment_execute_improved.execute_agents_improved` (also
# partial, see that module). No active runtime caller.
# Decision pending: same as `agents/urls_deployment.py`.
# See: docs/handoffs/SESSION_1111_DEEPER_REVIEW_MAP.md

import os
from django.http import JsonResponse, FileResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods
from django.conf import settings

from core.models.agents_registry import AgentExecution
from core.models import GeneratedProject, GeneratedCode


@csrf_exempt
@require_http_methods(["POST"])
def execute_deployed_agents(request):
    """
    Actually execute the deployed agents and generate real output

    Now supports both demo mode (fast, pre-generated) and real mode (LLM-powered)
    """
    # Import the improved executor function
    from agents.views_deployment_execute_improved import execute_agents_improved

    # Delegate to improved executor with mode support
    return execute_agents_improved(request)


def _get_agent_task(agent_name: str, project_type: str, ml_features: list) -> str:
    """
    Generate appropriate task description for an agent based on project context
    """
    tasks = {
        "Business Agent": f"Develop business strategy for {project_type} project",
        "Market Research Specialist": f"Analyze market opportunities for {project_type}",
        "ML Recommendation Engine": f"Design ML system with features: {', '.join(ml_features)}",
        "Database Architect": f"Design database schema for {project_type} application",
        "Frontend Engineer": f"Create UI components for {project_type} interface",
        "API Developer": f"Build REST APIs for {project_type} backend",
        "Security Specialist": f"Implement security for {project_type} platform",
        "DevOps Engineer": f"Setup CI/CD pipeline for {project_type}",
        "Testing Automation": f"Create test suites for {project_type}",
        "Performance Optimizer": f"Optimize performance for {project_type} system"
    }
    return tasks.get(agent_name, f"Execute task for {project_type} project")


def _save_to_filesystem(project_name: str, filename: str, content: str):
    """
    Save generated code to filesystem
    """
    try:
        base_path = os.path.join(settings.BASE_DIR, 'ai_generated_projects', project_name)
        os.makedirs(base_path, exist_ok=True)

        file_path = os.path.join(base_path, filename)
        with open(file_path, 'w') as f:
            f.write(content)

        return file_path
    except Exception as e:
        print(f"Error saving to filesystem: {e}")
        return None


def download_generated_file(request, project_id, filename):
    """Download a specific generated file"""
    try:
        code_file = GeneratedCode.objects.filter(
            project_id=project_id,
            filename=filename,
            is_latest=True
        ).first()

        if not code_file:
            return JsonResponse({
                'success': False,
                'error': 'File not found'
            }, status=404)

        from django.http import HttpResponse
        response = HttpResponse(code_file.content, content_type='text/plain')
        response['Content-Disposition'] = f'attachment; filename="{filename}"'
        return response

    except Exception as e:
        return JsonResponse({
            'success': False,
            'error': str(e)
        }, status=500)


def get_live_output_stream(request):
    """Get live output stream for real-time updates"""
    # Build WebSocket URL dynamically from request
    ws_scheme = 'wss' if request.is_secure() else 'ws'
    ws_host = request.get_host()
    return JsonResponse({
        'success': True,
        'message': 'Use WebSocket connection for live updates',
        'ws_url': f'{ws_scheme}://{ws_host}/ws/ai-training/'
    })


@csrf_exempt
@require_http_methods(["GET"])
def get_agent_output(request, project_id, agent_name):
    """
    Get the output generated by a specific agent
    """
    try:
        # Get the latest code generated by this agent for this project
        code_file = GeneratedCode.objects.filter(
            project_id=project_id,
            agent_creator=agent_name,
            is_latest=True
        ).first()

        if not code_file:
            return JsonResponse({
                'success': False,
                'error': 'No output found for this agent'
            }, status=404)

        return JsonResponse({
            'success': True,
            'filename': code_file.filename,
            'content': code_file.content,
            'language': code_file.language,
            'created_at': code_file.created_at.isoformat(),
            'lines_of_code': len(code_file.content.splitlines()),
            'execution_status': code_file.execution_status
        })

    except Exception as e:
        return JsonResponse({
            'success': False,
            'error': str(e)
        }, status=500)


@csrf_exempt
@require_http_methods(["GET"])
def download_generated_code(request, project_id):
    """
    Download all generated code for a project as a zip file
    """
    try:
        import zipfile
        from io import BytesIO

        project = GeneratedProject.objects.get(id=project_id)
        code_files = GeneratedCode.objects.filter(project=project, is_latest=True)

        if not code_files:
            return JsonResponse({
                'success': False,
                'error': 'No code files found for this project'
            }, status=404)

        # Create a zip file in memory
        zip_buffer = BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for code_file in code_files:
                zip_file.writestr(code_file.filename, code_file.content)

        # Prepare the response
        zip_buffer.seek(0)
        response = FileResponse(
            zip_buffer,
            as_attachment=True,
            filename=f"{project.name.replace(' ', '_')}_code.zip"
        )

        return response

    except GeneratedProject.DoesNotExist:
        return JsonResponse({
            'success': False,
            'error': 'Project not found'
        }, status=404)
    except Exception as e:
        return JsonResponse({
            'success': False,
            'error': str(e)
        }, status=500)


@csrf_exempt
@require_http_methods(["GET"])
def list_agent_executions(request):
    """
    List recent agent executions with their results
    """
    try:
        limit = int(request.GET.get('limit', 10))

        executions = AgentExecution.objects.all().order_by('-started_at')[:limit]

        results = []
        for execution in executions:
            results.append({
                'id': str(execution.id),
                'agent_name': execution.agent_template.name if execution.agent_template else 'Unknown',
                'status': execution.status,
                'started_at': execution.started_at.isoformat() if execution.started_at else None,
                'completed_at': execution.completed_at.isoformat() if execution.completed_at else None,
                'result_summary': execution.result_summary,
                'error_message': execution.error_message
            })

        return JsonResponse({
            'success': True,
            'executions': results,
            'count': len(results)
        })

    except Exception as e:
        return JsonResponse({
            'success': False,
            'error': str(e)
        }, status=500)

# Alias for URL compatibility
get_agent_outputs = get_agent_output
