# Generated by Django 5.0.6 on 2025-09-30 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_core", "0002_alter_commandexecution_id_alter_databasechange_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AgentKnowledgeBase",
        ),
        migrations.RemoveField(
            model_name="agentlearningevent",
            name="related_events",
        ),
        migrations.RemoveField(
            model_name="learningdocument",
            name="source_events",
        ),
        migrations.RemoveField(
            model_name="learninginsight",
            name="source_events",
        ),
        migrations.RemoveField(
            model_name="learningembedding",
            name="learning_event",
        ),
        migrations.DeleteModel(
            name="AgentLearningSession",
        ),
        migrations.RemoveField(
            model_name="commandexecution",
            name="session",
        ),
        migrations.RemoveField(
            model_name="databasechange",
            name="session",
        ),
        migrations.RemoveField(
            model_name="filemodification",
            name="session",
        ),
        migrations.RemoveField(
            model_name="implementationevidence",
            name="session",
        ),
        migrations.RemoveField(
            model_name="learningembedding",
            name="document",
        ),
        migrations.AlterUniqueTogether(
            name="learningembedding",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="LearningInsight",
        ),
        migrations.DeleteModel(
            name="AgentLearningEvent",
        ),
        migrations.DeleteModel(
            name="CommandExecution",
        ),
        migrations.DeleteModel(
            name="DatabaseChange",
        ),
        migrations.DeleteModel(
            name="FileModification",
        ),
        migrations.DeleteModel(
            name="ImplementationEvidence",
        ),
        migrations.DeleteModel(
            name="ImplementationSession",
        ),
        migrations.DeleteModel(
            name="LearningDocument",
        ),
        migrations.DeleteModel(
            name="LearningEmbedding",
        ),
    ]
