# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(help_text="Name of the metric", max_length=100),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("histogram", "Histogram"),
                            ("rate", "Rate"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metric_value",
                    models.FloatField(help_text="Numeric value of the metric"),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, help_text="Additional context and dimensions"
                    ),
                ),
                (
                    "subsystem",
                    models.CharField(
                        choices=[
                            ("documents", "Document Processing"),
                            ("generation", "Content Generation"),
                            ("embeddings", "Vector Embeddings"),
                            ("knowledge_base", "Knowledge Base"),
                            ("workflows", "Workflow Execution"),
                            ("templates", "Template Usage"),
                            ("search", "Semantic Search"),
                            ("system", "System Performance"),
                        ],
                        max_length=100,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("instant", "Instant"),
                            ("minute", "Per Minute"),
                            ("hour", "Per Hour"),
                            ("day", "Per Day"),
                            ("week", "Per Week"),
                            ("month", "Per Month"),
                        ],
                        default="instant",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Analytics",
                "verbose_name_plural": "Content Analytics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ContentGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The prompt used for content generation"
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True, help_text="System prompt for this generation"
                    ),
                ),
                (
                    "generation_config",
                    models.JSONField(
                        default=dict, help_text="AI model configuration used"
                    ),
                ),
                (
                    "rag_context",
                    models.TextField(
                        blank=True, help_text="Retrieved context for RAG generation"
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(blank=True, help_text="The generated content"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Currently Processing"),
                            ("processed", "Successfully Processed"),
                            ("failed", "Processing Failed"),
                            ("archived", "Archived"),
                            ("deleted", "Soft Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "generation_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to generate content in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "token_usage",
                    models.JSONField(default=dict, help_text="Token usage statistics"),
                ),
                (
                    "generation_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Cost of content generation",
                        max_digits=10,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Automated quality assessment (0-1)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User satisfaction rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_feedback",
                    models.TextField(
                        blank=True, help_text="User feedback on generated content"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web Interface"),
                            ("api", "API Request"),
                            ("workflow", "Workflow System"),
                            ("agent", "Agent Generated"),
                            ("sports", "Sports Analysis"),
                            ("betting", "Betting System"),
                        ],
                        help_text="System that initiated this generation",
                        max_length=100,
                    ),
                ),
                (
                    "workflow_context",
                    models.JSONField(
                        default=dict,
                        help_text="Context from workflow or orchestration system",
                    ),
                ),
                (
                    "export_formats",
                    models.JSONField(
                        default=list,
                        help_text="Formats this content has been exported to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Generation",
                "verbose_name_plural": "Content Generations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template name", max_length=200, unique=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-friendly display name", max_length=250
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Template description and usage instructions"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("article", "Article/Blog Post"),
                            ("summary", "Content Summary"),
                            ("analysis", "Analysis Report"),
                            ("sports_report", "Sports Analysis Report"),
                            ("betting_guide", "Betting Strategy Guide"),
                            ("news_brief", "News Brief"),
                            ("social_post", "Social Media Post"),
                            ("email", "Email Content"),
                            ("documentation", "Technical Documentation"),
                            ("creative", "Creative Writing"),
                            ("translation", "Translation Template"),
                            ("qa", "Question & Answer"),
                        ],
                        help_text="Type of content this template generates",
                        max_length=100,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="System prompt that defines content generation behavior"
                    ),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        help_text="Template for user prompts with variable placeholders"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Template variables and their configuration",
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("json", "JSON Structure"),
                            ("structured", "Structured Data"),
                        ],
                        default="markdown",
                        help_text="Expected output format",
                        max_length=50,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google", "Google AI"),
                            ("local", "Local Model"),
                        ],
                        default="openai",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="gpt-5-mini",
                        help_text="Specific AI model to use",
                        max_length=100,
                    ),
                ),
                (
                    "generation_config",
                    models.JSONField(
                        default=dict, help_text="Model-specific generation parameters"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Tags for categorization and discovery"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Primary category", max_length=100
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_generation_time",
                    models.FloatField(
                        default=0.0, help_text="Average generation time in seconds"
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=1.0, help_text="Success rate for content generation"
                    ),
                ),
                (
                    "avg_user_rating",
                    models.FloatField(
                        default=0.0, help_text="Average user satisfaction rating"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether template is available to all users",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether template has been verified for quality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Template",
                "verbose_name_plural": "Content Templates",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContentWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("name", models.CharField(help_text="Workflow name", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Workflow description and purpose"),
                ),
                (
                    "workflow_steps",
                    models.JSONField(
                        help_text="Ordered list of workflow steps with configurations"
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        default=dict,
                        help_text="Default configuration for workflow execution",
                    ),
                ),
                ("execution_count", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=1.0)),
                (
                    "avg_execution_time",
                    models.FloatField(
                        default=0.0, help_text="Average execution time in seconds"
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("general", "General Content"),
                            ("sports", "Sports Content"),
                            ("betting", "Betting Analysis"),
                            ("news", "News and Updates"),
                            ("social", "Social Media"),
                            ("documentation", "Documentation"),
                            ("marketing", "Marketing Content"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                (
                    "integration_points",
                    models.JSONField(
                        default=dict,
                        help_text="Integration points with other platform systems",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Workflow",
                "verbose_name_plural": "Content Workflows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                ("title", models.CharField(help_text="Document title", max_length=500)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional document description"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("pdf", "PDF Document"),
                            ("docx", "Word Document"),
                            ("rtf", "Rich Text Format"),
                            ("json", "JSON Data"),
                            ("csv", "CSV Data"),
                            ("xml", "XML Data"),
                            ("yaml", "YAML Data"),
                            ("python", "Python Code"),
                            ("javascript", "JavaScript Code"),
                            ("typescript", "TypeScript Code"),
                            ("sql", "SQL Code"),
                            ("image", "Image File"),
                            ("audio", "Audio File"),
                            ("video", "Video File"),
                            ("sports_data", "Sports Analytics Data"),
                            ("betting_analysis", "Betting Analysis"),
                            ("agent_log", "Agent Execution Log"),
                            ("knowledge_extract", "Knowledge Base Extract"),
                        ],
                        help_text="Type of document",
                        max_length=50,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, help_text="Path to the stored file", max_length=1000
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Original filename when uploaded",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of the document",
                        max_length=200,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True, help_text="Raw extracted text content"
                    ),
                ),
                (
                    "processed_content",
                    models.TextField(
                        blank=True, help_text="Cleaned and processed text content"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Currently Processing"),
                            ("processed", "Successfully Processed"),
                            ("failed", "Processing Failed"),
                            ("archived", "Archived"),
                            ("deleted", "Soft Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("upload", "User Upload"),
                            ("generated", "AI Generated"),
                            ("imported", "Imported from External System"),
                            ("scraped", "Web Scraped"),
                            ("api", "API Integration"),
                            ("workflow", "Workflow Generated"),
                            ("sports_feed", "Sports Data Feed"),
                            ("betting_system", "Betting Analysis System"),
                        ],
                        default="upload",
                        max_length=50,
                    ),
                ),
                (
                    "processing_log",
                    models.JSONField(
                        default=list, help_text="Log of processing steps and results"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Detected language code (e.g., 'en', 'es')",
                        max_length=10,
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of words in the document",
                        null=True,
                    ),
                ),
                (
                    "readability_score",
                    models.FloatField(
                        blank=True,
                        help_text="Automated readability assessment",
                        null=True,
                    ),
                ),
                (
                    "extracted_metadata",
                    models.JSONField(
                        default=dict, help_text="Metadata extracted from document"
                    ),
                ),
                (
                    "key_phrases",
                    models.JSONField(
                        default=list, help_text="Extracted key phrases and topics"
                    ),
                ),
                (
                    "entities",
                    models.JSONField(
                        default=list, help_text="Named entities found in the document"
                    ),
                ),
                ("tags", models.JSONField(default=list, help_text="User-defined tags")),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="Document category", max_length=100
                    ),
                ),
                (
                    "collection",
                    models.CharField(
                        blank=True,
                        help_text="Collection or folder this document belongs to",
                        max_length=200,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether document is publicly accessible",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sports", "Sports Analytics"),
                            ("agents", "Agent System"),
                            ("betting", "Betting Analysis"),
                            ("manual", "Manual Upload"),
                            ("api", "API Integration"),
                        ],
                        help_text="System that created this document",
                        max_length=100,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID in source system",
                        max_length=500,
                    ),
                ),
                (
                    "cross_references",
                    models.JSONField(
                        default=dict,
                        help_text="References to related objects in other systems",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        choices=[
                            (
                                "openai_text_embedding_3_small",
                                "OpenAI text-embedding-3-small",
                            ),
                            (
                                "openai_text_embedding_3_large",
                                "OpenAI text-embedding-3-large",
                            ),
                            (
                                "openai_text_embedding_ada_002",
                                "OpenAI text-embedding-ada-002",
                            ),
                            ("sentence_transformer", "Sentence Transformer"),
                            ("cohere_embed_english", "Cohere Embed English"),
                            ("local_model", "Local Embedding Model"),
                        ],
                        help_text="Model used to generate embeddings",
                        max_length=100,
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Index of this chunk within the document"
                    ),
                ),
                (
                    "chunk_text",
                    models.TextField(help_text="Text content of this chunk"),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        help_text="Size of text chunk in characters"
                    ),
                ),
                (
                    "overlap_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Overlap with adjacent chunks in characters",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="The actual embedding vector as JSON array"
                    ),
                ),
                (
                    "embedding_dimension",
                    models.PositiveIntegerField(
                        help_text="Dimension of the embedding vector"
                    ),
                ),
                (
                    "context_before",
                    models.TextField(
                        blank=True, help_text="Context text before this chunk"
                    ),
                ),
                (
                    "context_after",
                    models.TextField(
                        blank=True, help_text="Context text after this chunk"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata for this chunk"
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to generate embedding in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "embedding_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Cost to generate this embedding",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Embedding",
                "verbose_name_plural": "Document Embeddings",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Content"),
                            ("image", "Image Content"),
                            ("video", "Video Content"),
                            ("blog", "Blog Post"),
                            ("social", "Social Media Post"),
                            ("ebook", "eBook Content"),
                            ("voice", "Voice Content"),
                            ("research", "Research Content"),
                        ],
                        help_text="Type of content being rated",
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.PositiveIntegerField(
                        help_text="ID of the content item being rated"
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        help_text="Overall rating from 1-5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "quality_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Quality rating from 1-5 stars",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "accuracy_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Accuracy rating from 1-5 stars",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "usefulness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Usefulness rating from 1-5 stars",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("quality", "Quality Issue"),
                            ("accuracy", "Accuracy Issue"),
                            ("usefulness", "Usefulness Issue"),
                            ("general", "General Feedback"),
                            ("suggestion", "Improvement Suggestion"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, help_text="Written feedback comments"),
                ),
                (
                    "suggestions",
                    models.TextField(
                        blank=True, help_text="Suggestions for improvement"
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True,
                        help_text="Would recommend this content to others",
                        null=True,
                    ),
                ),
                (
                    "met_expectations",
                    models.BooleanField(
                        blank=True, help_text="Content met user expectations", null=True
                    ),
                ),
                (
                    "saved_time",
                    models.BooleanField(
                        blank=True, help_text="Content saved user time", null=True
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags associated with this feedback",
                    ),
                ),
                (
                    "generation_params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters used to generate the rated content",
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, help_text="Admin response to user feedback"
                    ),
                ),
                (
                    "admin_response_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When admin responded to feedback",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Feedback",
                "verbose_name_plural": "User Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Knowledge base name", max_length=200, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the knowledge base"),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        choices=[
                            (
                                "openai_text_embedding_3_small",
                                "OpenAI text-embedding-3-small",
                            ),
                            (
                                "openai_text_embedding_3_large",
                                "OpenAI text-embedding-3-large",
                            ),
                            (
                                "openai_text_embedding_ada_002",
                                "OpenAI text-embedding-ada-002",
                            ),
                            ("sentence_transformer", "Sentence Transformer"),
                            ("cohere_embed_english", "Cohere Embed English"),
                            ("local_model", "Local Embedding Model"),
                        ],
                        default="openai_text_embedding_3_small",
                        help_text="Default embedding model for this knowledge base",
                        max_length=100,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Default chunk size for document processing",
                    ),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(
                        default=200, help_text="Default overlap between chunks"
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text="Available categories for documents in this KB",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="Available tags for documents in this KB",
                    ),
                ),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("total_chunks", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "last_indexed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the knowledge base was fully indexed",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this knowledge base is publicly searchable",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("general", "General Knowledge"),
                            ("sports", "Sports Analytics"),
                            ("betting", "Betting & Gambling"),
                            ("agents", "AI Agents & Automation"),
                            ("technical", "Technical Documentation"),
                            ("business", "Business Intelligence"),
                        ],
                        default="general",
                        help_text="Domain specialization of this knowledge base",
                        max_length=100,
                    ),
                ),
                (
                    "integration_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for cross-system integration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Knowledge Base",
                "verbose_name_plural": "Knowledge Bases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input data for workflow execution"
                    ),
                ),
                (
                    "execution_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration overrides for this execution",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("processing", "Currently Processing"),
                            ("processed", "Successfully Processed"),
                            ("failed", "Processing Failed"),
                            ("archived", "Archived"),
                            ("deleted", "Soft Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=0, help_text="Currently executing step index"
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "step_results",
                    models.JSONField(
                        default=list, help_text="Results from each completed step"
                    ),
                ),
                (
                    "final_output",
                    models.JSONField(
                        blank=True, help_text="Final workflow output", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("execution_time_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "error_step",
                    models.PositiveIntegerField(
                        blank=True, help_text="Step where error occurred", null=True
                    ),
                ),
                (
                    "agent_execution",
                    models.CharField(
                        blank=True,
                        help_text="Agent execution ID if triggered by agent",
                        max_length=200,
                    ),
                ),
                (
                    "websocket_channel",
                    models.CharField(
                        blank=True,
                        help_text="WebSocket channel for real-time updates",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "ordering": ["-created_at"],
            },
        ),
    ]
