# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentanalytics",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_generations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contenttemplate",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generations",
                to="content.contenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="contentanalytics",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="content.contenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="contentworkflow",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentworkflow",
            name="required_templates",
            field=models.ManyToManyField(
                blank=True,
                help_text="Templates required for this workflow",
                related_name="workflows",
                to="content.contenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users with explicit access to this document",
                related_name="accessible_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="parent_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent document if this is a section/chapter",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_documents",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="related_documents",
            field=models.ManyToManyField(
                blank=True, help_text="Related documents", to="content.document"
            ),
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="context_documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents used as context for RAG",
                related_name="content_generations",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="output_document",
            field=models.OneToOneField(
                blank=True,
                help_text="Document created from this generation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_source",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="contentanalytics",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="documentembedding",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embeddings",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can add/edit documents in this KB",
                related_name="contributed_knowledge_bases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_bases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contentworkflow",
            name="required_knowledge_bases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Knowledge bases required for this workflow",
                related_name="workflows",
                to="content.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="contentgeneration",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generations",
                to="content.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="contentanalytics",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="content.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="generated_content",
            field=models.ManyToManyField(
                blank=True,
                help_text="Content generations from this workflow",
                related_name="workflow_executions",
                to="content.contentgeneration",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="generated_documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents generated by this workflow",
                related_name="workflow_executions",
                to="content.document",
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workflowexecution",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="content.contentworkflow",
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["template_type"], name="content_con_templat_8d8f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["category"], name="content_con_categor_f7ffc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttemplate",
            index=models.Index(
                fields=["is_public", "is_active"], name="content_con_is_publ_440b87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type"], name="content_doc_documen_85431e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="content_doc_status_4c528f_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["category"], name="content_doc_categor_0b7c6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner"], name="content_doc_owner_i_013099_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["content_hash"], name="content_doc_content_a3ed25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["-created_at"], name="content_doc_created_b08e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentembedding",
            index=models.Index(
                fields=["document", "chunk_index"],
                name="content_doc_documen_bcc94c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentembedding",
            index=models.Index(
                fields=["embedding_model"], name="content_doc_embeddi_cca67f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentembedding",
            unique_together={("document", "chunk_index", "embedding_model")},
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="content_fee_content_6cd292_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["user", "-created_at"], name="content_fee_user_id_bd8d36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["overall_rating"], name="content_fee_overall_5b9f5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["feedback_type"], name="content_fee_feedbac_c2db9c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedback",
            unique_together={("user", "content_type", "content_id")},
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(fields=["domain"], name="content_kno_domain_e4a081_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["is_public", "is_active"], name="content_kno_is_publ_4caed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentworkflow",
            index=models.Index(fields=["domain"], name="content_con_domain_aa1adc_idx"),
        ),
        migrations.AddIndex(
            model_name="contentworkflow",
            index=models.Index(
                fields=["is_public", "is_active"], name="content_con_is_publ_a22898_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgeneration",
            index=models.Index(
                fields=["user", "-created_at"], name="content_con_user_id_6ee7e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgeneration",
            index=models.Index(
                fields=["template"], name="content_con_templat_33dc9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentgeneration",
            index=models.Index(fields=["status"], name="content_con_status_453c6e_idx"),
        ),
        migrations.AddIndex(
            model_name="contentgeneration",
            index=models.Index(
                fields=["source_system"], name="content_con_source__bd41f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["metric_name", "-timestamp"],
                name="content_con_metric__05b142_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["subsystem", "-timestamp"],
                name="content_con_subsyst_1302c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentanalytics",
            index=models.Index(
                fields=["user", "-timestamp"], name="content_con_user_id_8d0626_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "-created_at"],
                name="content_wor_workflo_c02ebd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["user", "-created_at"], name="content_wor_user_id_4363fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(fields=["status"], name="content_wor_status_baa596_idx"),
        ),
    ]
