# Generated by Django 5.0.6 on 2025-11-03 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Stored filename", max_length=255),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Full path to image file in storage", max_length=500
                    ),
                ),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True,
                        help_text="Path to thumbnail version",
                        max_length=500,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("generated", "AI Generated"),
                            ("erased", "Object Erased"),
                            ("inpainted", "Inpainted/Smart Fill"),
                            ("outpainted", "Outpainted/Extended"),
                            ("upscaled_fast", "Upscaled (Fast 4x)"),
                            ("upscaled_conservative", "Upscaled (Conservative 4K)"),
                            ("upscaled_creative", "Upscaled (Creative)"),
                            ("recolored", "Recolored"),
                            ("background_removed", "Background Removed"),
                            ("sketch_control", "Sketch to Image"),
                            ("structure_control", "Structure Transfer"),
                        ],
                        help_text="Type of operation that created this image",
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, help_text="Prompt used for generation or editing"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Complete parameters used (style, model, settings, etc.)",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("core", "Stability Core"),
                            ("sdxl", "Stability SDXL"),
                            ("sd3", "Stability SD3"),
                            ("ultra", "Stability Ultra"),
                        ],
                        help_text="AI model used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        help_text="Style preset used (e.g., Pixar, Photographic, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times viewed"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="User marked as favorite"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="User's personal notes about this image"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="User-defined tags for organization"
                    ),
                ),
                (
                    "parent_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent image if this is an edit of another image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_images",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created/edited this image",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Image History",
                "verbose_name_plural": "Image History",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="content_ima_user_id_d5c84d_idx",
                    ),
                    models.Index(
                        fields=["image_type"], name="content_ima_image_t_a62e76_idx"
                    ),
                    models.Index(
                        fields=["model_used"], name="content_ima_model_u_51998f_idx"
                    ),
                    models.Index(fields=["style"], name="content_ima_style_9f190a_idx"),
                    models.Index(
                        fields=["is_favorite"], name="content_ima_is_favo_c21df1_idx"
                    ),
                ],
            },
        ),
    ]
