# Generated by Django 5.0.6 on 2025-11-03 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_imagehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        blank=True, help_text="Runway ML task/video ID", max_length=255
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the generated video file",
                        max_length=1000,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, help_text="URL to video thumbnail", max_length=1000
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("text_to_video", "Text to Video"),
                            ("image_to_video", "Image to Video"),
                        ],
                        help_text="Type of video generation",
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(help_text="Prompt used for video generation"),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Complete parameters used (model, duration, ratio, etc.)",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        choices=[
                            ("veo3.1_fast", "Runway Veo 3.1 Fast"),
                            ("veo3.1", "Runway Veo 3.1"),
                            ("gen4_turbo", "Runway Gen-4 Turbo"),
                        ],
                        help_text="AI model used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                (
                    "ratio",
                    models.CharField(
                        blank=True,
                        help_text="Aspect ratio (e.g., 1920:1080)",
                        max_length=20,
                    ),
                ),
                (
                    "video_width",
                    models.PositiveIntegerField(
                        blank=True, help_text="Video width in pixels", null=True
                    ),
                ),
                (
                    "video_height",
                    models.PositiveIntegerField(
                        blank=True, help_text="Video height in pixels", null=True
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        help_text="Generation status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times viewed"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="User marked as favorite"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="User's personal notes about this video"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="User-defined tags for organization"
                    ),
                ),
                (
                    "generation_started",
                    models.DateTimeField(
                        blank=True, help_text="When video generation started", null=True
                    ),
                ),
                (
                    "generation_completed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When video generation completed",
                        null=True,
                    ),
                ),
                (
                    "generation_time_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total generation time in seconds",
                        null=True,
                    ),
                ),
                (
                    "source_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source image if this is image-to-video",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_videos",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this video",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Video History",
                "verbose_name_plural": "Video History",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="content_vid_user_id_893e73_idx",
                    ),
                    models.Index(
                        fields=["video_type"], name="content_vid_video_t_9b49f9_idx"
                    ),
                    models.Index(
                        fields=["model_used"], name="content_vid_model_u_d80bc2_idx"
                    ),
                    models.Index(
                        fields=["status"], name="content_vid_status_8344de_idx"
                    ),
                    models.Index(
                        fields=["is_favorite"], name="content_vid_is_favo_c2521c_idx"
                    ),
                ],
            },
        ),
    ]
