# Generated by Django 5.0.6 on 2025-11-06 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_fix_workflow_history_uuid_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreativeProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Project name (e.g., 'Brand Launch Campaign')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the project"
                    ),
                ),
                (
                    "goal",
                    models.TextField(help_text="What's the objective of this project?"),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, help_text="Project deadline", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="planning",
                        help_text="Current project status",
                        max_length=20,
                    ),
                ),
                (
                    "total_workflows",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of workflows in this project"
                    ),
                ),
                (
                    "completed_workflows",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completed workflows"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Project category (e.g., 'Branding', 'Marketing', 'Personal')",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Project tags for organization"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Whether project is shared with others"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creative_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Creative Project",
                "verbose_name_plural": "Creative Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order in project sequence (0-indexed)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about this workflow in the project context",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When workflow was added to project",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this workflow belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "workflow_history",
                    models.ForeignKey(
                        help_text="Workflow execution linked to this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="content.workflowhistory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Workflow",
                "verbose_name_plural": "Project Workflows",
                "ordering": ["order", "added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="creativeproject",
            index=models.Index(
                fields=["user", "-created_at"], name="content_cre_user_id_a79f6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creativeproject",
            index=models.Index(
                fields=["user", "status"], name="content_cre_user_id_747eef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="creativeproject",
            index=models.Index(
                fields=["deadline"], name="content_cre_deadlin_e50708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectworkflow",
            index=models.Index(
                fields=["project", "order"], name="content_pro_project_8de9a6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectworkflow",
            unique_together={("project", "workflow_history")},
        ),
    ]
