# Generated by Django 5.0.6 on 2025-11-06 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_add_project_to_workflow_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagehistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_images",
                to="content.creativeproject",
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this video belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_videos",
                to="content.creativeproject",
            ),
        ),
    ]
