# Generated by Django 5.0.6 on 2025-11-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_add_project_to_history_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativeproject",
            name="colors",
            field=models.CharField(
                blank=True,
                help_text="Color palette for this project (e.g., 'navy blue, gold, white')",
                max_length=200,
            ),
        ),
    ]
