# Generated by Django 5.0.6 on 2025-11-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_add_colors_field_to_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagehistory",
            name="file_path",
            field=models.TextField(
                help_text="Full path to image file in storage (can be data URI)"
            ),
        ),
    ]
