# Generated by Django 5.0.6 on 2025-11-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_change_file_path_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="videohistory",
            name="parent_video_url",
            field=models.URLField(
                blank=True,
                help_text="URL of parent video if this is an extension (for tracking 8s→18s→28s→38s chains)",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="videohistory",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("text_to_video", "Text to Video"),
                    ("image_to_video", "Image to Video"),
                    ("extend_video", "Video Extension"),
                ],
                help_text="Type of video generation",
                max_length=50,
            ),
        ),
    ]
