# Generated by Django 5.0.6 on 2025-11-13 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_charactermodel_charactertrainingimage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCreativePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_styles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred styles (photographic, digital-art, etc.) ordered by preference",
                    ),
                ),
                (
                    "preferred_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred AI models (sdxl, ultra, etc.) ordered by preference",
                    ),
                ),
                (
                    "color_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Color palette preferences (warm: 0.7, cool: 0.3, etc.)",
                    ),
                ),
                (
                    "composition_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Composition preferences (centered: 0.6, rule_of_thirds: 0.9, etc.)",
                    ),
                ),
                (
                    "total_choices",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of choices user has made (agent learning progress)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When user started using CreativeDirector",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time preferences were updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Creative Preference",
                "verbose_name_plural": "User Creative Preferences",
            },
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="generation_batch_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID linking related options generated together",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="option_number",
            field=models.IntegerField(
                blank=True,
                help_text="Option number in batch (1, 2, 3, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="seed",
            field=models.IntegerField(
                blank=True,
                help_text="Random seed used for generation (enables exact reproduction)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="selection_timestamp",
            field=models.DateTimeField(
                blank=True, help_text="When user selected this option", null=True
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="was_selected",
            field=models.BooleanField(
                default=False,
                help_text="Did user select this option? (agent learns from this!)",
            ),
        ),
        migrations.AddIndex(
            model_name="imagehistory",
            index=models.Index(
                fields=["generation_batch_id"], name="content_ima_generat_58b21a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="imagehistory",
            index=models.Index(
                fields=["user", "was_selected"], name="content_ima_user_id_24c8b9_idx"
            ),
        ),
        migrations.AddField(
            model_name="usercreativepreference",
            name="user",
            field=models.OneToOneField(
                help_text="User these preferences belong to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creative_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usercreativepreference",
            index=models.Index(fields=["user"], name="content_use_user_id_1d2d4d_idx"),
        ),
        migrations.AddIndex(
            model_name="usercreativepreference",
            index=models.Index(
                fields=["total_choices"], name="content_use_total_c_20a060_idx"
            ),
        ),
    ]
