# Generated by Django 5.0.6 on 2025-11-14 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_usercreativepreference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AISession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique session identifier for tracking",
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Session title (auto-generated or user-defined)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Brief description of what was created in this session",
                    ),
                ),
                (
                    "conversation_transcript",
                    models.JSONField(
                        default=list,
                        help_text="Complete conversation history (messages and responses)",
                    ),
                ),
                (
                    "first_prompt",
                    models.TextField(
                        blank=True,
                        help_text="The initial user prompt that started this session",
                    ),
                ),
                (
                    "auto_created_project",
                    models.BooleanField(
                        default=False,
                        help_text="Whether we auto-created a project from this session",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this session is currently active",
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the session was ended/closed",
                        null=True,
                    ),
                ),
                (
                    "total_images",
                    models.PositiveIntegerField(
                        default=0, help_text="Total images created in this session"
                    ),
                ),
                (
                    "total_videos",
                    models.PositiveIntegerField(
                        default=0, help_text="Total videos created in this session"
                    ),
                ),
                (
                    "total_audio",
                    models.PositiveIntegerField(
                        default=0, help_text="Total audio files created in this session"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Auto-generated and user-defined tags"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("branding", "Branding Package"),
                            ("logo_design", "Logo Design"),
                            ("video_creation", "Video Creation"),
                            ("content_package", "Complete Content Package"),
                            ("exploration", "Creative Exploration"),
                            ("refinement", "Content Refinement"),
                            ("general", "General Creation"),
                        ],
                        help_text="Type of creative work done in this session",
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project this session belongs to (can auto-create)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Session",
                "verbose_name_plural": "AI Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="AI session that created this image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_images",
                to="content.aisession",
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="AI session that created this video",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_videos",
                to="content.aisession",
            ),
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["user", "-created_at"], name="content_ais_user_id_61a9d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["session_id"], name="content_ais_session_e8d62d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["is_active"], name="content_ais_is_acti_4ba3ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aisession",
            index=models.Index(
                fields=["project"], name="content_ais_project_9b8c5f_idx"
            ),
        ),
    ]
