# Generated by Django 5.0.6 on 2025-11-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_add_session_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="creativeproject",
            name="is_quick_starts",
            field=models.BooleanField(
                default=False, help_text="Special project for ad-hoc/spontaneous work"
            ),
        ),
    ]
