# Generated by Django 5.0.6 on 2025-11-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_add_is_quick_starts_to_creative_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisession",
            name="action_items",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Action items from boardroom meeting",
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="agent_responses",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Individual agent responses in boardroom meetings",
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="decisions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Decisions made during boardroom meeting",
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="meeting_summary",
            field=models.TextField(
                blank=True, help_text="Summary of boardroom meeting discussion"
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="meeting_topic",
            field=models.TextField(
                blank=True, help_text="Topic/agenda for boardroom meetings"
            ),
        ),
        migrations.AddField(
            model_name="aisession",
            name="participants",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of agent names participating in boardroom meetings",
            ),
        ),
        migrations.AlterField(
            model_name="aisession",
            name="session_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Default Session"),
                    ("boardroom", "Executive Boardroom Meeting"),
                    ("branding", "Branding Package"),
                    ("logo_design", "Logo Design"),
                    ("video_creation", "Video Creation"),
                    ("content_package", "Complete Content Package"),
                    ("exploration", "Creative Exploration"),
                    ("refinement", "Content Refinement"),
                    ("general", "General Creation"),
                ],
                default="default",
                help_text="Type of session or creative work",
                max_length=50,
            ),
        ),
    ]
