# Generated by Django 5.0.6 on 2025-11-15 23:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_add_boardroom_meeting_fields"),
        ("pipelines", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MiniFigAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="User-friendly title for this mini-fig",
                        max_length=200,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("placeholder", "Placeholder (v1)"),
                            ("external_service", "External 3D Service (v2+)"),
                        ],
                        default="placeholder",
                        help_text="Provider used for 3D generation",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Generation status",
                        max_length=20,
                    ),
                ),
                (
                    "three_d_file",
                    models.URLField(
                        help_text="URL to 3D file (STL, OBJ, etc.) - v1: placeholder URL",
                        max_length=1000,
                    ),
                ),
                (
                    "preview_image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to preview/thumbnail image",
                        max_length=1000,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (style, scale, generation params, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times viewed"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="User marked as favorite"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True,
                        help_text="User's personal notes about this mini-fig",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="User-defined tags for organization"
                    ),
                ),
                (
                    "source_image_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source image used for mini-fig generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_minifigs",
                        to="content.imagehistory",
                    ),
                ),
                (
                    "source_pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pipeline run that created this mini-fig",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_minifigs",
                        to="pipelines.creativepipelinerun",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this mini-fig",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minifig_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MiniFig Asset",
                "verbose_name_plural": "MiniFig Assets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="content_min_user_id_27a5be_idx",
                    ),
                    models.Index(
                        fields=["status"], name="content_min_status_d0d458_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="content_min_provide_1da662_idx"
                    ),
                    models.Index(
                        fields=["is_favorite"], name="content_min_is_favo_64e34f_idx"
                    ),
                ],
            },
        ),
    ]
