# Generated by Django 5.0.6 on 2025-11-17 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0007_agentcontribution"),
        ("content", "0019_minifig_asset_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagehistory",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent that generated this image (if created by agent)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_images",
                to="agents.unifiedagenttemplate",
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent that generated this video (if created by agent)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_videos",
                to="agents.unifiedagenttemplate",
            ),
        ),
    ]
