# Generated by Django 5.0.6 on 2025-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_add_project_to_minifig"),
    ]

    operations = [
        migrations.AddField(
            model_name="minifigasset",
            name="glb_file",
            field=models.FileField(
                blank=True,
                help_text="Local GLB file (for viewing/rendering)",
                null=True,
                upload_to="3d_models/",
            ),
        ),
        migrations.AddField(
            model_name="minifigasset",
            name="stl_file",
            field=models.FileField(
                blank=True,
                help_text="Local STL file (for 3D printing with Cura, etc.)",
                null=True,
                upload_to="3d_models/",
            ),
        ),
    ]
