# Generated by Django 5.0.6 on 2025-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_add_project_to_minifigasset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aisession",
            name="last_response_id",
        ),
        migrations.RemoveField(
            model_name="imagehistory",
            name="cloud_url",
        ),
        migrations.RemoveField(
            model_name="minifigasset",
            name="stl_file",
        ),
        migrations.AddField(
            model_name="minifigasset",
            name="download_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether the CDN file has been downloaded to local storage",
            ),
        ),
        migrations.AddField(
            model_name="minifigasset",
            name="download_error",
            field=models.TextField(
                blank=True, help_text="Error message if file download failed"
            ),
        ),
        migrations.AddField(
            model_name="minifigasset",
            name="local_glb_path",
            field=models.CharField(
                blank=True,
                help_text="Path to local GLB file relative to MEDIA_ROOT",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="imagehistory",
            name="seed",
            field=models.BigIntegerField(
                blank=True,
                help_text="Random seed used for generation (enables exact reproduction)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="minifigasset",
            name="glb_file",
            field=models.FileField(
                blank=True,
                help_text="Local GLB file (permanent storage)",
                null=True,
                upload_to="3d_models/",
            ),
        ),
        migrations.AlterField(
            model_name="minifigasset",
            name="three_d_file",
            field=models.URLField(
                help_text="URL to 3D file (STL, OBJ, etc.) - CDN URL from Replicate (expires in 24-48hrs)",
                max_length=1000,
            ),
        ),
    ]
