# Generated by Django 5.0.6 on 2025-11-20 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0027_add_local_file_fields_to_minifigasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagehistory",
            name="seed",
            field=models.BigIntegerField(
                blank=True,
                help_text="Random seed used for generation (enables exact reproduction)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProjectShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        editable=False,
                        help_text="Unique token for share URL (auto-generated)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the share link is active"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed password for protected shares",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the share link expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times the shared project has been viewed",
                    ),
                ),
                (
                    "last_viewed",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the share link was last viewed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project being shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="content.creativeproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Share",
                "verbose_name_plural": "Project Shares",
                "db_table": "project_shares",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["share_token"], name="project_sha_share_t_94ee9a_idx"
                    ),
                    models.Index(
                        fields=["project", "is_active"],
                        name="project_sha_project_6c01b6_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="project_sha_expires_1dc870_idx"
                    ),
                ],
            },
        ),
    ]
