# Generated by Django 5.0.6 on 2025-11-24 20:27
# Session 452: Fixed - Made state-only since migration 0031 reverts this change anyway
# The AlterField from JSON to Vector fails on fresh databases because PostgreSQL
# cannot cast JSONB to Vector directly. Since 0031 reverts to JSON, this migration
# should only update state to keep migration history consistent.

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_alter_imagehistory_seed_projectshare"),
        ("persistence", "0003_enable_pgvector"),  # Requires pgvector extension
    ]

    operations = [
        # Session 452: Use SeparateDatabaseAndState since this AlterField cannot work
        # on fresh databases (cannot cast jsonb to vector), and migration 0031 reverts
        # this change back to JSONField anyway.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="documentembedding",
                    name="embedding_vector",
                    field=pgvector.django.vector.VectorField(
                        dimensions=3072,
                        help_text="The actual embedding vector using pgvector native type",
                    ),
                ),
                migrations.AddIndex(
                    model_name="documentembedding",
                    index=pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding_vector"],
                        m=16,
                        name="embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ),
            ],
            database_operations=[
                # No-op - cannot cast JSONB to Vector, and 0031 reverts this anyway
            ],
        ),
    ]
