# Generated by Django 5.0.6 on 2025-11-25 00:41
# Session 182: Add sequential_number field to ImageHistory

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_agentcontribution_minifig_asset"),
        ("content", "0029_upgrade_embedding_vector_to_pgvector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imagehistory",
            name="sequential_number",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Permanent sequential number per user (never changes, even if earlier images deleted)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="imagehistory",
            index=models.Index(
                fields=["user", "sequential_number"],
                name="content_ima_user_id_6eb9be_idx",
            ),
        ),
    ]
