# Generated by Django 5.0.6 on 2025-12-02 00:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_agentcontribution_minifig_asset"),
        ("content", "0032_add_project_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Stored filename", max_length=255),
                ),
                (
                    "file_path",
                    models.TextField(help_text="Full path to audio file in storage"),
                ),
                (
                    "audio_type",
                    models.CharField(
                        choices=[
                            ("tts", "Text to Speech"),
                            ("voice_clone", "Voice Clone"),
                            ("sfx", "Sound Effect"),
                            ("voice_design", "Voice Design"),
                            ("audio_isolation", "Audio Isolation"),
                        ],
                        help_text="Type of audio generation",
                        max_length=50,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True, help_text="Text/prompt used for generation"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="Complete parameters used (voice, model, settings, etc.)",
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True, help_text="ElevenLabs voice ID used", max_length=100
                    ),
                ),
                (
                    "voice_name",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable voice name",
                        max_length=100,
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("eleven_multilingual_v2", "ElevenLabs Multilingual v2"),
                            ("eleven_turbo_v2", "ElevenLabs Turbo v2"),
                            ("eleven_english_v1", "ElevenLabs English v1"),
                            ("eleven_monolingual_v1", "ElevenLabs Monolingual v1"),
                        ],
                        help_text="AI model used for generation",
                        max_length=50,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Audio duration in seconds", null=True
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "sample_rate",
                    models.PositiveIntegerField(
                        blank=True, help_text="Audio sample rate in Hz", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        help_text="Generation status",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "play_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times played"
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        default=False, help_text="User marked as favorite"
                    ),
                ),
                (
                    "user_notes",
                    models.TextField(
                        blank=True, help_text="User's personal notes about this audio"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="User-defined tags for organization"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent that generated this audio (if created by agent)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_audio",
                        to="agents.unifiedagenttemplate",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project this audio belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_audio",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI session that created this audio",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_audio",
                        to="content.aisession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this audio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio History",
                "verbose_name_plural": "Audio History",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="content_aud_user_id_35087e_idx",
                    ),
                    models.Index(
                        fields=["audio_type"], name="content_aud_audio_t_e1fe9f_idx"
                    ),
                    models.Index(
                        fields=["model_used"], name="content_aud_model_u_a08945_idx"
                    ),
                    models.Index(
                        fields=["status"], name="content_aud_status_480b26_idx"
                    ),
                    models.Index(
                        fields=["is_favorite"], name="content_aud_is_favo_d266fa_idx"
                    ),
                ],
            },
        ),
    ]
