# Generated by Django 5.0.6 on 2025-12-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0009_alter_agentcontribution_project"),
        ("coleadership", "0003_alter_coleadershipdecision_project"),
        ("content", "0033_audiohistory"),
        ("core", "0064_alter_businessresearchresult_project"),
        ("pipelines", "0002_alter_creativepipelinerun_project"),
        ("rendering", "0003_alter_renderjob_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagehistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_images",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="audiohistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this audio belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_audio",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="videohistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this video belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_videos",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="projectshare",
            name="project",
            field=models.ForeignKey(
                help_text="Project being shared",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="workflowhistory",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this workflow belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_executions",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="projectworkflow",
            name="project",
            field=models.ForeignKey(
                help_text="Project this workflow belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="minifigasset",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Creative project this 3D model belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="three_d_models",
                to="core.partnershipproject",
            ),
        ),
        migrations.AlterField(
            model_name="aisession",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project this session belongs to (can auto-create)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="core.partnershipproject",
            ),
        ),
        migrations.DeleteModel(
            name="CreativeProject",
        ),
    ]
