# Generated by Django 5.0.6 on 2025-12-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_alter_imagehistory_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="Original URL for web pages and YouTube videos",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain Text"),
                    ("markdown", "Markdown"),
                    ("html", "HTML"),
                    ("pdf", "PDF Document"),
                    ("docx", "Word Document"),
                    ("rtf", "Rich Text Format"),
                    ("json", "JSON Data"),
                    ("csv", "CSV Data"),
                    ("xml", "XML Data"),
                    ("yaml", "YAML Data"),
                    ("python", "Python Code"),
                    ("javascript", "JavaScript Code"),
                    ("typescript", "TypeScript Code"),
                    ("sql", "SQL Code"),
                    ("image", "Image File"),
                    ("audio", "Audio File"),
                    ("video", "Video File"),
                    ("sports_data", "Sports Analytics Data"),
                    ("betting_analysis", "Betting Analysis"),
                    ("agent_log", "Agent Execution Log"),
                    ("knowledge_extract", "Knowledge Base Extract"),
                    ("youtube", "YouTube Video Transcript"),
                    ("url", "Web Page Content"),
                ],
                help_text="Type of document",
                max_length=50,
            ),
        ),
    ]
