# Generated by Django 5.0.6 on 2025-12-15 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_session_402_document_ingestion"),
        ("core", "0094_session_451_user_upload_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="imagehistory",
            name="mime_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="Original uploaded file (for uploaded images)",
                null=True,
                upload_to="uploads/images/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="original_filename",
            field=models.CharField(
                blank=True, help_text="Original filename from upload", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("generated", "AI Generated"),
                    ("uploaded", "User Uploaded"),
                    ("imported", "External Import"),
                    ("edited", "Edited Version"),
                ],
                default="generated",
                help_text="How this content was created (generated, uploaded, imported, edited)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="codec",
            field=models.CharField(
                blank=True, help_text="Video codec (h264, hevc, etc.)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="fps",
            field=models.FloatField(
                blank=True, help_text="Frames per second", null=True
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="mime_type",
            field=models.CharField(
                blank=True, help_text="MIME type of the file", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="original_filename",
            field=models.CharField(
                blank=True, help_text="Original filename from upload", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("generated", "AI Generated"),
                    ("uploaded", "User Uploaded"),
                    ("imported", "External Import"),
                    ("edited", "Edited Version"),
                ],
                default="generated",
                help_text="How this content was created (generated, uploaded, imported, edited)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded video file (for user uploads)",
                null=True,
                upload_to="uploads/videos/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="imagehistory",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("generated", "AI Generated"),
                    ("erased", "Object Erased"),
                    ("inpainted", "Inpainted/Smart Fill"),
                    ("outpainted", "Outpainted/Extended"),
                    ("upscaled_fast", "Upscaled (Fast 4x)"),
                    ("upscaled_conservative", "Upscaled (Conservative 4K)"),
                    ("upscaled_creative", "Upscaled (Creative)"),
                    ("recolored", "Recolored"),
                    ("background_removed", "Background Removed"),
                    ("sketch_control", "Sketch to Image"),
                    ("structure_control", "Structure Transfer"),
                    ("uploaded", "User Uploaded"),
                ],
                help_text="Type of operation that created this image",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="videohistory",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("text_to_video", "Text to Video"),
                    ("image_to_video", "Image to Video"),
                    ("extend_video", "Video Extension"),
                    ("chained_video", "Chained Video"),
                    ("uploaded", "User Uploaded"),
                ],
                help_text="Type of video generation",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Total file size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        default="video",
                        help_text="Type of content being uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_size",
                    models.IntegerField(
                        default=5242880, help_text="Chunk size in bytes (default 5MB)"
                    ),
                ),
                (
                    "chunks_received",
                    models.IntegerField(
                        default=0, help_text="Number of chunks received"
                    ),
                ),
                (
                    "chunks_total",
                    models.IntegerField(help_text="Total number of chunks expected"),
                ),
                (
                    "bytes_received",
                    models.BigIntegerField(
                        default=0, help_text="Bytes received so far"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Upload status",
                        max_length=20,
                    ),
                ),
                (
                    "temp_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to temp directory for chunks",
                        max_length=500,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if upload failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Auto-cleanup incomplete uploads after this time"
                    ),
                ),
                (
                    "result_content_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of content created (image, video, audio)",
                        max_length=50,
                    ),
                ),
                (
                    "result_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the created ImageHistory, VideoHistory, or AudioHistory",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Project to associate uploaded content with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="upload_sessions",
                        to="core.partnershipproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Upload Session",
                "verbose_name_plural": "Upload Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="content_upl_user_id_ddb0ce_idx",
                    ),
                    models.Index(
                        fields=["status"], name="content_upl_status_709aea_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="content_upl_expires_96fa81_idx"
                    ),
                ],
            },
        ),
    ]
