# Generated by Django 5.0.6 on 2026-01-09 18:11

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0037_session_730_pgvector_documentembedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentembedding",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (pgvector)",
                null=True,
            ),
        ),
    ]
