# Generated by Django 5.0.6 on 2026-02-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0040_documentembedding_hnsw_index_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videohistory",
            name="model_used",
            field=models.CharField(
                choices=[
                    ("veo3.1_fast", "Runway Veo 3.1 Fast"),
                    ("veo3.1", "Runway Veo 3.1"),
                    ("gen4_turbo", "Runway Gen-4 Turbo"),
                    ("runway_gen4_turbo", "Runway Gen-4 Turbo (Pipeline)"),
                ],
                help_text="AI model used for generation",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="videohistory",
            name="video_type",
            field=models.CharField(
                choices=[
                    ("text_to_video", "Text to Video"),
                    ("image_to_video", "Image to Video"),
                    ("extend_video", "Video Extension"),
                    ("chained_video", "Chained Video"),
                    ("talking_character", "Talking Character"),
                    ("uploaded", "User Uploaded"),
                ],
                help_text="Type of video generation",
                max_length=50,
            ),
        ),
    ]
