# Generated by Django 5.0.6 on 2026-03-01 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0042_add_data_sensitivity_and_pinned_to_document"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["data_sensitivity", "-created_at"],
                name="content_doc_data_se_052aa2_idx",
            ),
        ),
    ]
