# Generated by Django 5.0.6 on 2026-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0043_document_content_doc_data_se_052aa2_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="promotion_status",
            field=models.CharField(
                choices=[
                    ("promoted", "Promoted"),
                    ("staged", "Staged"),
                    ("blocked", "Blocked"),
                ],
                db_index=True,
                default="promoted",
                help_text="Promotion gate: staged docs are not embedded or retrievable until promoted",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="documentembedding",
            name="ingested_via",
            field=models.CharField(
                choices=[
                    ("auto_research", "Auto Research"),
                    ("manual", "Manual Upload"),
                    ("spider_pipeline", "Spider Pipeline"),
                    ("sync_docs", "Docs Index Sync"),
                    ("backfill", "Backfill"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Pipeline that created this embedding",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documentembedding",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("web", "Web"),
                    ("spider", "Spider"),
                    ("user_upload", "User Upload"),
                    ("api", "API"),
                    ("unknown", "Unknown"),
                ],
                db_index=True,
                default="unknown",
                help_text="Origin of the source document (internal/web/spider/user_upload/api/unknown)",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="documentembedding",
            index=models.Index(
                fields=["source_type"], name="content_doc_source__0e17ad_idx"
            ),
        ),
    ]
