# Generated by Django 5.0.6 on 2026-03-02 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0044_provenance_and_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoTranscript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="whisper",
                        help_text="Transcription provider (whisper, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        help_text="Detected or requested language code (e.g. en)",
                        max_length=10,
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, help_text="Full transcript text"),
                ),
                (
                    "segments_json",
                    models.JSONField(
                        default=list,
                        help_text="Timestamped segments: [{start, end, text}, ...]",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Audio duration processed", null=True
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if transcription failed"
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        help_text="Source video",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to="content.videohistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["video", "-created_at"],
                        name="content_vid_video_i_2540bc_idx",
                    ),
                    models.Index(
                        fields=["status"], name="content_vid_status_054a12_idx"
                    ),
                ],
            },
        ),
    ]
