# Generated by Django 5.0.6 on 2026-04-05 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0045_video_transcript"),
        ("core", "0323_content_packets"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiohistory",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this audio belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audio",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="imagehistory",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this image belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="core.projectworkspace",
            ),
        ),
        migrations.AddField(
            model_name="videohistory",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                help_text="Workspace this video belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="core.projectworkspace",
            ),
        ),
    ]
