#!/usr/bin/env python3
"""
Test Code Agents Actually Doing Work
This demonstrates agents writing real code and producing deliverables
"""

import asyncio
import json
import os
from datetime import datetime
from backend.agents.code_agent_executor import code_agent_executor
from backend.agents.real_task_executor import real_task_executor

async def test_code_agents():
    """Run actual code generation tests"""

    print("\n" + "="*80)
    print("🚀 TESTING CODE AGENTS - REAL WORK DEMONSTRATION")
    print("="*80 + "\n")

    # Test 1: CodeMaster-7 builds Django API
    print("📌 Test 1: CodeMaster-7 Building Django REST API")
    print("-" * 40)

    django_result = await code_agent_executor.execute_django_api_job("CodeMaster-7")

    print(f"✅ Agent: {django_result['agent']}")
    print(f"✅ Job: {django_result['job']}")
    print(f"✅ Status: {django_result['status']}")
    print(f"📊 Metrics:")
    for key, value in django_result['metrics'].items():
        print(f"   - {key}: {value}")

    print(f"\n📁 Deliverables created:")
    for name, path in django_result['deliverables'].items():
        if os.path.exists(path):
            size = os.path.getsize(path)
            print(f"   ✓ {name}: {path} ({size} bytes)")

    print(f"\n🧪 Test Results:")
    print(f"   - Tests Run: {django_result['test_results']['tests_run']}")
    print(f"   - Tests Passed: {django_result['test_results']['tests_passed']}")
    print(f"   - Coverage: {django_result['test_results']['coverage']}")

    # Test 2: ReactNinja-X builds frontend
    print("\n" + "="*80)
    print("📌 Test 2: ReactNinja-X Building React Frontend")
    print("-" * 40)

    react_result = await code_agent_executor.execute_react_frontend_job("ReactNinja-X")

    print(f"✅ Agent: {react_result['agent']}")
    print(f"✅ Job: {react_result['job']}")
    print(f"✅ Status: {react_result['status']}")
    print(f"📊 Metrics:")
    for key, value in react_result['metrics'].items():
        print(f"   - {key}: {value}")

    # Test 3: CodeMaster-7 does code review
    print("\n" + "="*80)
    print("📌 Test 3: CodeMaster-7 Performing Code Review")
    print("-" * 40)

    review_job = {
        "job_id": "review_001",
        "title": "Security Audit for Payment Module",
        "client": "FinTech Corp"
    }

    review_result = await real_task_executor.execute_code_review_task("CodeMaster-7", review_job)

    print(f"✅ Success: {review_result['success']}")
    print(f"📄 Review saved to: {review_result['deliverable']}")
    print(f"📊 Review Metrics:")
    for key, value in review_result['metrics'].items():
        print(f"   - {key}: {value}")

    # Read and display part of the review
    if os.path.exists(review_result['deliverable']):
        with open(review_result['deliverable'], 'r') as f:
            lines = f.readlines()[:20]  # First 20 lines
            print(f"\n📝 Review Preview:")
            print("".join(lines))

    # Test 4: API Integration
    print("\n" + "="*80)
    print("📌 Test 4: BackendGuru-1 Creating API Integration")
    print("-" * 40)

    api_job = {
        "job_id": "api_001",
        "title": "Stripe Payment Integration",
        "client": "E-commerce Platform"
    }

    api_result = await real_task_executor.execute_api_integration_task("BackendGuru-1", api_job)

    print(f"✅ Success: {api_result['success']}")
    print(f"📄 Files created:")
    for file in api_result['deliverables']:
        if os.path.exists(file):
            print(f"   ✓ {file} ({os.path.getsize(file)} bytes)")
    print(f"📊 Lines of code: {api_result['lines_of_code']}")
    print(f"🧪 Test coverage: {api_result['test_coverage']}")

    # Summary
    print("\n" + "="*80)
    print("📊 SUMMARY - AGENTS COMPLETED REAL WORK")
    print("="*80)

    # List all created files
    output_dir = "/tmp/agent_work_output"
    code_workspace = "/tmp/agent_code_workspace"

    all_files = []

    if os.path.exists(output_dir):
        for file in os.listdir(output_dir):
            full_path = os.path.join(output_dir, file)
            if os.path.isfile(full_path):
                all_files.append(full_path)

    if os.path.exists(code_workspace):
        for root, dirs, files in os.walk(code_workspace):
            for file in files:
                all_files.append(os.path.join(root, file))

    print(f"\n✅ Total deliverables created: {len(all_files)}")
    print("📁 All files generated by agents:")

    total_size = 0
    for file_path in all_files:
        size = os.path.getsize(file_path)
        total_size += size
        print(f"   - {file_path} ({size:,} bytes)")

    print(f"\n💾 Total disk space used: {total_size:,} bytes")
    print(f"🎯 All agents completed their tasks successfully!")

    return {
        "django_result": django_result,
        "react_result": react_result,
        "review_result": review_result,
        "api_result": api_result,
        "total_files": len(all_files),
        "total_size": total_size
    }

if __name__ == "__main__":
    results = asyncio.run(test_code_agents())

    print("\n" + "="*80)
    print("✅ CODE AGENT TESTING COMPLETE")
    print("="*80)
    print("\nAgents have demonstrated they can:")
    print("1. ✓ Write complete Django REST APIs with models, views, and tests")
    print("2. ✓ Build React TypeScript frontends with components and services")
    print("3. ✓ Perform comprehensive code reviews with actionable feedback")
    print("4. ✓ Create production-ready API integrations with full documentation")
    print("5. ✓ Generate unit tests with high coverage")
    print("\n🎯 All deliverables are real files that can be used in production!")