# Generated by Django 5.0.6 on 2025-09-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sport_type",
                    models.CharField(
                        choices=[
                            ("nfl", "NFL"),
                            ("nba", "NBA"),
                            ("mlb", "MLB"),
                            ("nhl", "NHL"),
                        ],
                        help_text="Sport this model predicts",
                        max_length=10,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model identifier (e.g., 'nfl_predictor')",
                        max_length=100,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(help_text="Incremental version number"),
                ),
                (
                    "trained_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When model was trained"
                    ),
                ),
                (
                    "training_samples",
                    models.IntegerField(help_text="Number of games used for training"),
                ),
                (
                    "training_start_date",
                    models.DateField(help_text="Earliest game date in training data"),
                ),
                (
                    "training_end_date",
                    models.DateField(help_text="Latest game date in training data"),
                ),
                (
                    "validation_accuracy",
                    models.FloatField(
                        help_text="Accuracy on validation set (0.0 to 1.0)"
                    ),
                ),
                (
                    "test_accuracy",
                    models.FloatField(help_text="Accuracy on test set (0.0 to 1.0)"),
                ),
                (
                    "calibration_score",
                    models.FloatField(help_text="Calibration quality (log loss)"),
                ),
                (
                    "precision",
                    models.FloatField(
                        blank=True, help_text="Precision score (0.0 to 1.0)", null=True
                    ),
                ),
                (
                    "recall",
                    models.FloatField(
                        blank=True, help_text="Recall score (0.0 to 1.0)", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Is this the currently deployed model?"
                    ),
                ),
                (
                    "model_file_path",
                    models.CharField(
                        help_text="Path to saved model file", max_length=500
                    ),
                ),
                (
                    "training_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional training details (hyperparameters, etc.)",
                    ),
                ),
                (
                    "deployment_date",
                    models.DateTimeField(
                        blank=True, help_text="When model was activated", null=True
                    ),
                ),
                (
                    "retired_date",
                    models.DateTimeField(
                        blank=True, help_text="When model was deactivated", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Model Version",
                "verbose_name_plural": "ML Model Versions",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["sport_type", "is_active"],
                        name="ml_mlmodelv_sport_t_ea7b56_idx",
                    ),
                    models.Index(
                        fields=["sport_type", "-version"],
                        name="ml_mlmodelv_sport_t_322b6f_idx",
                    ),
                ],
                "unique_together": {("sport_type", "version")},
            },
        ),
    ]
