# Generated by Django 5.0.6 on 2025-09-17 16:41

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentKnowledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the agent that created this knowledge",
                        max_length=200,
                    ),
                ),
                (
                    "agent_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the specific agent execution instance",
                        null=True,
                    ),
                ),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("fact", "Factual Information"),
                            ("skill", "Learned Skill or Technique"),
                            ("pattern", "Identified Pattern"),
                            ("solution", "Problem Solution"),
                            ("experience", "Execution Experience"),
                            ("insight", "Strategic Insight"),
                            ("warning", "Warning or Caution"),
                            ("best_practice", "Best Practice"),
                            ("optimization", "Performance Optimization"),
                            ("integration", "System Integration Knowledge"),
                        ],
                        help_text="Type of knowledge being shared",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Clear, descriptive title for the knowledge",
                        max_length=255,
                    ),
                ),
                ("content", models.JSONField(help_text="Structured knowledge content")),
                (
                    "summary",
                    models.TextField(
                        help_text="Human-readable summary of the knowledge"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Context in which this knowledge is applicable",
                    ),
                ),
                (
                    "domain_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Domain tags (sports, content, agents, etc.)",
                        size=None,
                    ),
                ),
                (
                    "applicable_agents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Specific agents this knowledge applies to (empty = all agents)",
                        size=None,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this knowledge is available to all agents",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("read_write", "Read and Modify"),
                            ("restricted", "Restricted Access"),
                        ],
                        default="read",
                        help_text="Access level for other agents",
                        max_length=20,
                    ),
                ),
                (
                    "shared_with",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Specific agents this knowledge is shared with",
                        size=None,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence in the accuracy of this knowledge (0.0-1.0)",
                    ),
                ),
                (
                    "validation_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this knowledge has been validated",
                    ),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Success rate when this knowledge is applied",
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times applying this knowledge failed",
                    ),
                ),
                (
                    "accessed_by",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Agents that have accessed this knowledge",
                        size=None,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this knowledge has been used",
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this knowledge was used",
                        null=True,
                    ),
                ),
                (
                    "related_knowledge",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Related knowledge entries",
                        to="persistence.agentknowledge",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Knowledge entry that supersedes this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="persistence.agentknowledge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Knowledge",
                "verbose_name_plural": "Agent Knowledge",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentCollaborationSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "session_name",
                    models.CharField(
                        help_text="Name of the collaboration session", max_length=255
                    ),
                ),
                (
                    "participating_agents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        help_text="Agents participating in this session",
                        size=None,
                    ),
                ),
                (
                    "session_goal",
                    models.TextField(
                        help_text="Goal or objective of the collaboration"
                    ),
                ),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "shared_context",
                    models.JSONField(
                        default=dict, help_text="Shared context and data between agents"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        default=dict,
                        help_text="Results and outcomes of the collaboration",
                    ),
                ),
                (
                    "knowledge_generated",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Knowledge generated during this session",
                        related_name="collaboration_sessions",
                        to="persistence.agentknowledge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Collaboration Session",
                "verbose_name_plural": "Agent Collaboration Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataPersistenceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "metric_name",
                    models.CharField(help_text="Name of the metric", max_length=100),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("counter", "Counter"),
                            ("gauge", "Gauge"),
                            ("histogram", "Histogram"),
                            ("timer", "Timer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metric_value",
                    models.FloatField(help_text="Numeric value of the metric"),
                ),
                (
                    "subsystem",
                    models.CharField(
                        choices=[
                            ("embeddings", "Embedding System"),
                            ("agent_knowledge", "Agent Knowledge"),
                            ("spider_data", "Spider Data"),
                            ("search", "Search System"),
                            ("collaboration", "Agent Collaboration"),
                            ("routing", "Data Routing"),
                            ("performance", "System Performance"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metric metadata"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Data Persistence Metric",
                "verbose_name_plural": "Data Persistence Metrics",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_name", "-timestamp"],
                        name="persistence_metric__f813bb_idx",
                    ),
                    models.Index(
                        fields=["subsystem", "-timestamp"],
                        name="persistence_subsyst_d26d7c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RevenueTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "revenue_source",
                    models.CharField(
                        choices=[
                            ("spider_discovery", "Spider Discovery"),
                            ("agent_execution", "Agent Execution"),
                            ("content_generation", "Content Generation"),
                            ("betting_recommendation", "Betting Recommendation"),
                            ("workflow_automation", "Workflow Automation"),
                            ("user_subscription", "User Subscription"),
                            ("api_usage", "API Usage"),
                            ("affiliate_commission", "Affiliate Commission"),
                            ("consulting_service", "Consulting Service"),
                            ("data_licensing", "Data Licensing"),
                        ],
                        db_index=True,
                        help_text="Source system that generated this revenue",
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Revenue amount in USD",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the source object that generated this revenue",
                        null=True,
                    ),
                ),
                (
                    "source_agent",
                    models.CharField(
                        blank=True,
                        help_text="Agent that contributed to this revenue",
                        max_length=200,
                    ),
                ),
                (
                    "source_spider",
                    models.CharField(
                        blank=True,
                        help_text="Spider that discovered the opportunity",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of how this revenue was generated"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="External transaction ID (PayPal, Stripe, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("settled", "Settled"),
                        ],
                        default="pending",
                        help_text="Status of revenue verification",
                        max_length=20,
                    ),
                ),
                (
                    "opportunity_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Related opportunity that led to this revenue",
                        null=True,
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Conversion rate from opportunity to revenue",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "conversion_time",
                    models.DurationField(
                        blank=True,
                        help_text="Time from opportunity discovery to revenue conversion",
                        null=True,
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Return on investment percentage",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Confidence in revenue attribution (0.0-1.0)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "earned_at",
                    models.DateTimeField(
                        help_text="When the revenue was actually earned"
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the revenue was recorded in the system",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional revenue context and metadata",
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Tags for categorizing revenue",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Tracker",
                "verbose_name_plural": "Revenue Trackers",
                "ordering": ["-earned_at", "-amount"],
                "indexes": [
                    models.Index(
                        fields=["revenue_source", "-earned_at"],
                        name="persistence_revenue_1b2193_idx",
                    ),
                    models.Index(
                        fields=["-amount", "-earned_at"],
                        name="persistence_amount_fb3995_idx",
                    ),
                    models.Index(
                        fields=["verification_status", "-reported_at"],
                        name="persistence_verific_7104de_idx",
                    ),
                    models.Index(
                        fields=["source_agent", "-earned_at"],
                        name="persistence_source__59e9a5_idx",
                    ),
                    models.Index(
                        fields=["source_spider", "-earned_at"],
                        name="persistence_source__3bc381_idx",
                    ),
                    models.Index(
                        fields=["opportunity_id"], name="persistence_opportu_032074_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnifiedEmbedding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("agent_knowledge", "Agent Knowledge"),
                            ("spider_data", "Spider Discovered Data"),
                            ("document_chunk", "Document Chunk"),
                            ("code_snippet", "Code Snippet"),
                            ("conversation", "Agent Conversation"),
                            ("opportunity", "Revenue Opportunity"),
                            ("system_log", "System Log Entry"),
                            ("user_interaction", "User Interaction"),
                            ("workflow_result", "Workflow Result"),
                            ("research_finding", "Research Finding"),
                        ],
                        db_index=True,
                        help_text="Type of content this embedding represents",
                        max_length=50,
                    ),
                ),
                (
                    "content_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the content object this embedding represents",
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        help_text="The actual text content that was embedded"
                    ),
                ),
                (
                    "content_title",
                    models.CharField(
                        blank=True,
                        help_text="Title or summary of the content",
                        max_length=500,
                    ),
                ),
                (
                    "content_metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the content"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        choices=[
                            ("text-embedding-3-small", "OpenAI text-embedding-3-small"),
                            ("text-embedding-3-large", "OpenAI text-embedding-3-large"),
                            ("text-embedding-ada-002", "OpenAI text-embedding-ada-002"),
                            ("sentence-transformer", "Sentence Transformer"),
                            ("local-model", "Local Embedding Model"),
                        ],
                        default="text-embedding-3-small",
                        help_text="Model used to generate the embedding",
                        max_length=100,
                    ),
                ),
                (
                    "embedding",
                    models.JSONField(
                        help_text="Embedding vector (JSON fallback when pgvector unavailable)"
                    ),
                ),
                (
                    "embedding_dimension",
                    models.PositiveIntegerField(
                        default=1536, help_text="Dimension of the embedding vector"
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        choices=[
                            ("agents", "Agent System"),
                            ("spiders", "Spider Network"),
                            ("content", "Content System"),
                            ("intelligence", "Intelligence Layer"),
                            ("users", "User System"),
                            ("workflows", "Workflow Engine"),
                            ("self_awareness", "Self-Awareness System"),
                        ],
                        help_text="System that created this embedding",
                        max_length=100,
                    ),
                ),
                (
                    "creator_agent",
                    models.CharField(
                        blank=True,
                        help_text="Agent that created this embedding (if applicable)",
                        max_length=200,
                    ),
                ),
                (
                    "importance_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Importance score (0.0-1.0) for ranking results",
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.5, help_text="Domain relevance score (0.0-1.0)"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence in the content accuracy (0.0-1.0)",
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this embedding has been accessed",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this embedding was accessed",
                        null=True,
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this appeared in search results",
                    ),
                ),
                (
                    "generation_cost",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.000000"),
                        help_text="Cost to generate this embedding in USD",
                        max_digits=10,
                    ),
                ),
                (
                    "generation_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to generate embedding in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and filtering",
                        size=None,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Primary category classification",
                        max_length=100,
                    ),
                ),
                (
                    "content_timestamp",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the original content (if different from created_at)",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this embedding should be considered stale",
                        null=True,
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User that created this embedding (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_embeddings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified Embedding",
                "verbose_name_plural": "Unified Embeddings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SpiderData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "spider_name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the spider that discovered this data",
                        max_length=100,
                    ),
                ),
                (
                    "spider_version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Version of the spider",
                        max_length=20,
                    ),
                ),
                (
                    "spider_execution_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the spider execution instance",
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL where this data was discovered", max_length=2000
                    ),
                ),
                (
                    "source_platform",
                    models.CharField(
                        choices=[
                            ("reddit", "Reddit"),
                            ("upwork", "Upwork"),
                            ("fiverr", "Fiverr"),
                            ("freelancer", "Freelancer.com"),
                            ("linkedin", "LinkedIn"),
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("github", "GitHub"),
                            ("stackoverflow", "Stack Overflow"),
                            ("medium", "Medium"),
                            ("substack", "Substack"),
                            ("producthunt", "Product Hunt"),
                            ("craigslist", "Craigslist"),
                            ("indeed", "Indeed"),
                            ("glassdoor", "Glassdoor"),
                            ("angellist", "AngelList"),
                            ("other", "Other Platform"),
                        ],
                        help_text="Platform where this data was discovered",
                        max_length=50,
                    ),
                ),
                (
                    "source_metadata",
                    models.JSONField(
                        default=dict, help_text="Additional metadata about the source"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title or headline of the discovered content",
                        max_length=500,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Raw content text discovered by spider"),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        default=dict,
                        help_text="Structured data extracted from the content",
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(
                        blank=True, help_text="Raw HTML content (if applicable)"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("opportunity", "Revenue Opportunity"),
                            ("job_posting", "Job Posting"),
                            ("market_data", "Market Intelligence"),
                            ("competitor_info", "Competitor Information"),
                            ("trend_data", "Trend Data"),
                            ("user_feedback", "User Feedback"),
                            ("product_info", "Product Information"),
                            ("pricing_data", "Pricing Information"),
                            ("content_idea", "Content Creation Idea"),
                            ("collaboration", "Collaboration Opportunity"),
                            ("news", "News or Updates"),
                            ("research", "Research Material"),
                            ("tool_discovery", "Tool or Service Discovery"),
                            ("learning_resource", "Learning Resource"),
                        ],
                        help_text="Type of data discovered",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Specific category within the data type",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Tags for categorization and search",
                        size=None,
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Relevance score assigned by spider (0.0-1.0)",
                    ),
                ),
                (
                    "opportunity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Opportunity/revenue potential score (0.0-1.0)",
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0, help_text="Content quality score (0.0-1.0)"
                    ),
                ),
                (
                    "urgency_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Urgency score for time-sensitive opportunities (0.0-1.0)",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this data has been processed by agents",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When this data was processed", null=True
                    ),
                ),
                (
                    "processing_result",
                    models.JSONField(
                        default=dict, help_text="Results of processing by agents"
                    ),
                ),
                (
                    "routed_to_agents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        help_text="Agents this data has been routed to",
                        size=None,
                    ),
                ),
                (
                    "agent_responses",
                    models.JSONField(
                        default=list,
                        help_text="Responses from agents that processed this data",
                    ),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue generated from this discovery",
                        max_digits=10,
                    ),
                ),
                (
                    "revenue_potential",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated revenue potential",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "conversion_status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("analyzed", "Analyzed"),
                            ("pursued", "Being Pursued"),
                            ("converted", "Converted to Revenue"),
                            ("failed", "Failed to Convert"),
                            ("expired", "Opportunity Expired"),
                        ],
                        default="discovered",
                        max_length=20,
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash for duplicate detection",
                        max_length=64,
                    ),
                ),
                (
                    "discovered_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this data was first discovered",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this opportunity expires", null=True
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time this data was updated"
                    ),
                ),
                (
                    "similar_discoveries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Similar discoveries found by other spiders",
                        to="persistence.spiderdata",
                    ),
                ),
                (
                    "embedding",
                    models.OneToOneField(
                        blank=True,
                        help_text="Embedding for semantic search",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spider_data",
                        to="persistence.unifiedembedding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spider Data",
                "verbose_name_plural": "Spider Data",
                "ordering": ["-opportunity_score", "-discovered_at"],
            },
        ),
        migrations.AddField(
            model_name="agentknowledge",
            name="embedding",
            field=models.OneToOneField(
                blank=True,
                help_text="Embedding for semantic search",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_knowledge",
                to="persistence.unifiedembedding",
            ),
        ),
        migrations.CreateModel(
            name="SpiderDataRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universal unique identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible metadata storage for extensibility",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number for optimistic locking"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this record is active/enabled"
                    ),
                ),
                (
                    "target_agent",
                    models.CharField(
                        help_text="Agent this data was routed to", max_length=200
                    ),
                ),
                (
                    "routing_reason",
                    models.TextField(help_text="Reason for routing to this agent"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low Priority"),
                            ("normal", "Normal Priority"),
                            ("high", "High Priority"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "agent_response",
                    models.JSONField(
                        blank=True, help_text="Response from the agent", null=True
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "spider_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_records",
                        to="persistence.spiderdata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spider Data Route",
                "verbose_name_plural": "Spider Data Routes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_agent", "status"],
                        name="persistence_target__c2603f_idx",
                    ),
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="persistence_priorit_c367ee_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="persistence_content_208d5b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["source_system", "-created_at"],
                name="persistence_source__aed1a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["content_hash"], name="persistence_content_4bfb71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["-importance_score", "-created_at"],
                name="persistence_importa_902754_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["category", "content_type"],
                name="persistence_categor_424737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=models.Index(
                fields=["expires_at"], name="persistence_expires_c72e75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["spider_name", "-discovered_at"],
                name="persistence_spider__9a23a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["source_platform", "data_type"],
                name="persistence_source__a1d50b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["-opportunity_score", "-relevance_score"],
                name="persistence_opportu_95417c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["is_processed", "conversion_status"],
                name="persistence_is_proc_903d13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["content_hash"], name="persistence_content_260982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spiderdata",
            index=models.Index(
                fields=["expires_at"], name="persistence_expires_4c6c8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentknowledge",
            index=models.Index(
                fields=["agent_name", "-created_at"],
                name="persistence_agent_n_4359b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentknowledge",
            index=models.Index(
                fields=["knowledge_type", "is_public"],
                name="persistence_knowled_2979f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentknowledge",
            index=models.Index(
                fields=["-confidence_score", "-usage_count"],
                name="persistence_confide_046ac1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agentknowledge",
            index=models.Index(
                fields=["is_public", "is_active"], name="persistence_is_publ_8f5d8a_idx"
            ),
        ),
    ]
