# Generated by Django 5.0.6 on 2025-10-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unifiedembedding",
            name="creator_agent",
            field=models.CharField(
                blank=True,
                default="system",
                help_text="Agent that created this embedding (if applicable)",
                max_length=100,
                null=True,
            ),
        ),
    ]
