# Generated by Django 5.0.6 on 2025-10-05 04:28

import django.contrib.postgres.fields
import pgvector.django.vector
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0005_add_embedding_hnsw_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unifiedembedding",
            name="access_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="confidence_score",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="content_metadata",
            field=models.JSONField(default=dict, help_text="Additional metadata"),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="content_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="content_title",
            field=models.CharField(
                blank=True, help_text="Title/summary", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="embedding_dimension",
            field=models.PositiveIntegerField(
                default=1536, help_text="Vector dimension"
            ),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="generation_cost",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="generation_time_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="importance_score",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="relevance_score",
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="search_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="unifiedembedding",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
