# Generated by Django 5.0.6 on 2025-10-05 19:49

import pgvector.django.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persistence", "0007_unifiedembedding_unified_embedding_hnsw_cosine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="unifiedembedding",
            name="unified_embedding_hnsw_cosine",
        ),
        migrations.AddIndex(
            model_name="unifiedembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="unified_embedding_hnsw_cosine",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
