# Generated by Django 5.0.6 on 2025-11-15 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0006_add_tool_integrations"),
        ("content", "0018_add_boardroom_meeting_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoLeadershipDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary of the decision (e.g., 'Q1 AI roadmap')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Longer explanation or prompt that initiated this decision",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "frozen_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the human commits to a final decision",
                        null=True,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated this decision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional project context for this decision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coleadership_decisions",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usually a boardroom session where this decision was discussed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coleadership_decisions",
                        to="content.aisession",
                    ),
                ),
            ],
            options={
                "db_table": "coleadership_decision",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stance",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("concern", "Concern"),
                            ("objection", "Objection"),
                            ("alternative", "Alternative"),
                            ("neutral", "Neutral"),
                        ],
                        help_text="Agent's overall stance on this decision",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(help_text="Brief summary of agent's position"),
                ),
                (
                    "recommendation_text",
                    models.TextField(help_text="Full recommendation from the agent"),
                ),
                (
                    "risk_analysis",
                    models.TextField(
                        blank=True, help_text="Risks identified by this agent"
                    ),
                ),
                (
                    "alternative_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative approaches suggested by this agent",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Agent's confidence level (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                (
                    "time_horizon",
                    models.CharField(
                        blank=True,
                        help_text="Time horizon for this recommendation (short_term, long_term, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full raw response from agent for reference",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent_template",
                    models.ForeignKey(
                        help_text="Which agent provided this recommendation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agents.unifiedagenttemplate",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="coleadership.coleadershipdecision",
                    ),
                ),
            ],
            options={
                "db_table": "coleadership_agent_recommendation",
                "ordering": ["decision", "-confidence"],
            },
        ),
        migrations.CreateModel(
            name="DecisionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("mixed", "Mixed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "realized_at",
                    models.DateTimeField(
                        blank=True, help_text="When the outcome became clear", null=True
                    ),
                ),
                (
                    "outcome_summary",
                    models.TextField(blank=True, help_text="What actually happened"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quantitative metrics about the outcome",
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        choices=[
                            ("ai", "AI more correct"),
                            ("human", "Human more correct"),
                            ("both", "Both partly correct"),
                            ("unknown", "Unknown/unclear"),
                        ],
                        default="unknown",
                        help_text="Who was more correct: AI or Human?",
                        max_length=20,
                    ),
                ),
                (
                    "ai_confidence_snapshot",
                    models.FloatField(
                        blank=True,
                        help_text="AI's confidence at decision time",
                        null=True,
                    ),
                ),
                (
                    "human_confidence_snapshot",
                    models.FloatField(
                        blank=True,
                        help_text="Human's confidence at decision time",
                        null=True,
                    ),
                ),
                (
                    "told_you_so_triggered",
                    models.BooleanField(
                        default=False,
                        help_text="Did this outcome trigger an 'I told you so' moment?",
                    ),
                ),
                (
                    "told_you_so_message",
                    models.TextField(
                        blank=True,
                        help_text="The playful (but respectful) message generated",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome",
                        to="coleadership.coleadershipdecision",
                    ),
                ),
            ],
            options={
                "db_table": "coleadership_decision_outcome",
            },
        ),
        migrations.CreateModel(
            name="HumanDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosen_path_summary",
                    models.TextField(
                        help_text="Human's final decision in their own words"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="Why the human chose this path"
                    ),
                ),
                (
                    "is_override",
                    models.BooleanField(
                        default=False,
                        help_text="Did the human override the AI's top recommendation?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_decision",
                        to="coleadership.coleadershipdecision",
                    ),
                ),
                (
                    "overridden_agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which agent's recommendation was overridden (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.unifiedagenttemplate",
                    ),
                ),
            ],
            options={
                "db_table": "coleadership_human_decision",
            },
        ),
        migrations.AddIndex(
            model_name="coleadershipdecision",
            index=models.Index(
                fields=["-created_at"], name="coleadershi_created_680276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coleadershipdecision",
            index=models.Index(
                fields=["project", "-created_at"], name="coleadershi_project_b83d2e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coleadershipdecision",
            index=models.Index(
                fields=["session", "-created_at"], name="coleadershi_session_2eb715_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["decision", "stance"], name="coleadershi_decisio_aafd1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentrecommendation",
            index=models.Index(
                fields=["decision", "-confidence"],
                name="coleadershi_decisio_3abad6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentrecommendation",
            unique_together={("decision", "agent_template")},
        ),
    ]
