# Generated by Django 5.0.6 on 2025-11-15 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coleadership", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoLeadershipPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_told_you_so",
                    models.BooleanField(
                        default=False,
                        help_text="Allow playful 'I told you so' messages when outcomes favor AI",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("serious", "Serious - Professional and straightforward"),
                            ("playful", "Playful - Lighthearted and engaging"),
                        ],
                        default="serious",
                        help_text="Preferred tone for co-leadership interactions",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these preferences belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coleadership_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Co-Leadership Preferences",
                "verbose_name_plural": "Co-Leadership Preferences",
                "db_table": "coleadership_user_preferences",
            },
        ),
    ]
