# Generated by Django 5.0.6 on 2025-11-15 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0018_add_boardroom_meeting_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("dispatching", "Dispatching"),
                            ("rendering", "Rendering"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0, help_text="Render progress from 0.0 to 1.0"
                    ),
                ),
                (
                    "source_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data sent to Resolve Node (timeline name, media files, etc.)",
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Data received from Resolve Node (metadata, file info, etc.)",
                    ),
                ),
                (
                    "result_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to download rendered video",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if status == error"
                    ),
                ),
                (
                    "node_job_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Job ID from Resolve Node (may differ from our ID)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="render_jobs",
                        to="content.creativeproject",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="render_jobs",
                        to="content.aisession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Render Job",
                "verbose_name_plural": "Render Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="rendering_r_user_id_0e4a96_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="rendering_r_status_da61a6_idx",
                    ),
                ],
            },
        ),
    ]
