# Generated by Django 5.0.6 on 2025-11-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendering", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="renderjob",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly job title (auto-generated if empty)",
                max_length=255,
            ),
        ),
    ]
