# Generated by Django 5.0.6 on 2025-12-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_alter_businessresearchresult_project"),
        ("rendering", "0002_renderjob_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renderjob",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="render_jobs",
                to="core.partnershipproject",
            ),
        ),
    ]
